Repository cri-o/cri-o, pull requests merged in 2018-12, with the labels that each got.

#1943 lib/container_server: Deprecate implicit hook directories
  cmd/crio/config.go
  cmd/crio/main.go
  docs/crio.8.md
  docs/crio.conf.5.md
  lib/config.go
  lib/container_server.go
  lib/testdata/config.toml
  test/helpers.bash
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#1951 version: bump to v1.14.0-dev
  version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1952 release v1.13.0
  contrib/test/integration/main.yml
  version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1953 [release-1.11] Fix segfault on network failure
  lib/container_server.go
  server/sandbox_stop.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1954 [release-1.12] Fix segfault on network failure
  lib/container_server.go
  server/sandbox_stop_linux.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1955 container_server: fix a segfault when the sandbox is not found
  lib/container_server.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1959 [release-1.12] Fix another segfault
  lib/container_server.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1958 [release-1.11] container_server: fix a segfault when the sandbox is not found
  lib/container_server.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1947 Move container implementations from lib to oci package
  lib/container_server_linux.go
  lib/container_server_unsupported.go
  lib/kill.go
  lib/stats.go
  oci/attach.go
  oci/kill.go
  oci/oci.go
  oci/oci_linux.go
  oci/oci_unix.go
  oci/oci_windows.go
  oci/stats.go
  server/container_attach.go
  server/container_exec.go
  server/container_exec_unix.go
  server/container_exec_windows.go
  server/container_portforward.go
  server/container_reopen_log.go
  server/container_stats.go
  server/container_stats_list.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1967 test: Update to golang 1.10.6 and 1.11.3
  contrib/test/integration/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1968 config: Add missing comma after each hooks_dir item
  cmd/crio/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1960 [release-1.13] container_server: fix a segfault when the sandbox is not found
  lib/container_server.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1969 [1.13] config: Add missing comma after each hooks_dir item
  cmd/crio/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1957 fix some race conditions with short lived pods
  lib/sandbox/sandbox.go
  server/container_create.go
  server/sandbox_network.go
  server/sandbox_stop_linux.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1979 tutorial: Update CNI plugins install example
  tutorial.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1981 pkg/storage/image: set insecure only on docker transport
  pkg/storage/image.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1984 Add interface nil checks
  utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
