Repository cri-o/cri-o, pull requests merged in 2018-11, with the labels that each got.

#1889 [release-1.11] container_create: fix dev mounts and remove nodev from /dev mounts
  server/container_create.go
Labels: approved, cncf-cla: yes, size/M

#1888 [release-1.12] container_create: fix dev mounts and remove nodev from /dev mounts
  server/container_create.go
  server/container_create_linux.go
Labels: approved, cncf-cla: yes, size/M

#1887 docs: fix links to policy.json, registries.conf
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1892 Update OWNER file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1899 test: Networking setup for DNS tests
  contrib/test/integration/e2e.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1884 container_create: fix dev mounts and remove nodev from every mount
  server/container_create.go
  server/container_create_linux.go
  server/container_create_linux_test.go
Labels: approved, cncf-cla: yes, size/L

#1893 pkg/storage: force unmounts
  pkg/storage/runtime.go
Labels: approved, cncf-cla: yes, size/XS

#1880 conmon: report runtime errors when tty is used
  conmon/conmon.c
Labels: approved, cncf-cla: yes, size/XS

#1903 Cancell imageConfigDigest allong all other requests from ImageService
  pkg/storage/image.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XS

#1906 [1.12] Remove nodev from mounts
  server/container_create_linux.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1905 [release-1.11] Remove nodev from mounts
  server/container_create.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1907 Bump 1.11.9
  version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1909 Do not overflow local buffer
  conmon/conmon.c
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1913 [release-1.12] vendor: revendor c/storage to fix a devicemapper bug
  pkg/storage/runtime.go
  vendor.conf
  vendor/github.com/containers/storage/drivers/aufs/aufs.go
  vendor/github.com/containers/storage/drivers/overlay/overlay.go
  vendor/github.com/containers/storage/layers.go
  vendor/github.com/containers/storage/pkg/idtools/parser.go
  vendor/github.com/containers/storage/store.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1916 Remove nodev from mounts
  server/container_create_linux.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1915 [1.12] Do not overflow local buffer
  conmon/conmon.c
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1878 systemd: add support for a crio-metrics sysconfig file.
  contrib/sysconfig/crio
  contrib/systemd/crio.service
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#1919 runc: bump to 10d38b660a77168360df3522881e2dc2be5056bd
  Dockerfile
  contrib/test/integration/build/runc.yml
  vendor.conf
  vendor/github.com/opencontainers/runc/README.md
  vendor/github.com/opencontainers/runc/libcontainer/README.md
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/apply_raw.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/cpu.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/cpuset.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/kmem.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/kmem_disabled.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/memory.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/utils.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/intelrdt.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_syscall.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/validate/rootless.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/validate/validator.go
  vendor/github.com/opencontainers/runc/libcontainer/container_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/factory_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/init_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/intelrdt/intelrdt.go
  vendor/github.com/opencontainers/runc/libcontainer/intelrdt/stats.go
  vendor/github.com/opencontainers/runc/libcontainer/keys/keyctl.go
  vendor/github.com/opencontainers/runc/libcontainer/message_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/network_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/nsenter/README.md
  vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c
  vendor/github.com/opencontainers/runc/libcontainer/process_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/rootfs_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/setns_init_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/standard_init_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/sync.go
  vendor/github.com/opencontainers/runc/libcontainer/user/lookup_unix.go
  vendor/github.com/opencontainers/runc/libcontainer/utils/utils.go
  vendor/github.com/opencontainers/runc/vendor.conf
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1925 Return the correct host IP
  server/sandbox_network.go
  server/server.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1924 [1.12] Return the correct host IP
  server/sandbox_network.go
  server/server.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1928 man: Fix typo
  docs/crio.8.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1923 vendor: update selinux
  vendor.conf
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1930 Release 1.12.3
  version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1920 README.md: remove unsupported releases
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1936 vendor: Remove reference to github.com/juju/ratelimit
  vendor.conf
Labels: approved, cncf-cla: yes, lgtm, size/XS
