Repository cri-o/cri-o, pull requests merged in 2018-08, with the labels that each got.

#1716 sandbox_network: allow ipv6 addresses
  server/sandbox_network.go
Labels: cncf-cla: yes, size/XS

#1717 fix typo
  conmon/conmon.c
Labels: cncf-cla: yes, size/XS

#1723 [1.11] container_create: Set a minimum memory limit
  server/container_create.go
  test/testdata/container_config.json
  test/testdata/container_config_by_imageid.json
  test/testdata/container_config_hostport.json
  test/testdata/container_config_logging.json
  test/testdata/container_config_resolvconf.json
  test/testdata/container_config_resolvconf_ro.json
  test/testdata/container_config_seccomp.json
  test/testdata/container_config_sleep.json
  test/testdata/container_redis_default_mounts.json
  test/testdata/container_redis_device.json
  test/testdata/container_sleep.json
  test/testdata/template_container_config.json
Labels: cncf-cla: yes, size/M

#1720 Create LICENSE
  logo/LICENSE
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1724 conmon: fix segfault when --log-level is not specified
  conmon/conmon.c
Labels: cncf-cla: yes, size/XS

#1734 [1.11] test: Add a test for low memory configured
  test/ctr.bats
Labels: cncf-cla: yes, size/S

#1718 Fix AppArmor build
  pkg/apparmor/apparmor_supported.go
Labels: cncf-cla: yes, size/XS

#1735 Image Volumes should be bind mounted as private
  server/container_create.go
Labels: cncf-cla: yes, size/XS

#1722 container_create: Set a minimum memory limit
  server/container_create_linux.go
  test/testdata/container_config.json
  test/testdata/container_config_by_imageid.json
  test/testdata/container_config_hostport.json
  test/testdata/container_config_logging.json
  test/testdata/container_config_resolvconf.json
  test/testdata/container_config_resolvconf_ro.json
  test/testdata/container_config_seccomp.json
  test/testdata/container_config_sleep.json
  test/testdata/container_redis_default_mounts.json
  test/testdata/container_redis_device.json
  test/testdata/container_sleep.json
  test/testdata/template_container_config.json
Labels: cncf-cla: yes, size/M

#1736 Image Volumes should be bind mounted as private
  server/container_create.go
Labels: cncf-cla: yes, size/XS

#1738 cherry-pick commit 73b6901403 ("Fix AppArmor build")
  pkg/apparmor/apparmor_supported.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1741 test: Add a test for low memory configured
  test/ctr.bats
Labels: cncf-cla: yes, size/S

#1739 Begin shifting to use podman rather then docker
  .travis.yml
  Makefile
Labels: cncf-cla: yes, size/S

#1737 Image Volumes should be bind mounted as private
  server/container_create.go
Labels: cncf-cla: yes, size/XS

#1744 crio: revert 9699d24a09367e240bce3073435ef333a71f6da7
  lib/container_server.go
  server/container_create_linux.go
  server/sandbox_run_linux.go
Labels: cncf-cla: yes, size/S

#1745 [1.11] Revert "server: Don't make additional copy of config.json"
  lib/container_server.go
  server/container_create.go
  server/sandbox_run.go
Labels: cncf-cla: yes, size/S

#1746 Release v1.11.2
  version/version.go
Labels: cncf-cla: yes, size/XS

#1729 basic support for running in an user namespace
  cmd/crio/config.go
  lib/config.go
  lib/container_server.go
  oci/oci.go
  oci/oci_linux.go
  server/container_attach.go
  server/container_create_linux.go
  server/rootless.go
  server/sandbox_run_linux.go
  server/server.go
Labels: cncf-cla: yes, size/L

#1696 oci: Define a minimal timeout for WaitContainerStateStopped()
  cmd/crio/config.go
  lib/config.go
  lib/container_server.go
  lib/stop.go
  lib/testdata/config.toml
  oci/oci.go
  server/fixtures/crio.conf
  server/sandbox_remove.go
  server/sandbox_stop_linux.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#1755 Update runc to latest
  Dockerfile
  contrib/test/integration/build/runc.yml
  vendor.conf
  vendor/github.com/opencontainers/runc/README.md
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/apply_raw.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/validate/rootless.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/validate/validator.go
  vendor/github.com/opencontainers/runc/libcontainer/container_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/devices/devices.go
  vendor/github.com/opencontainers/runc/libcontainer/factory_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/init_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/message_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c
  vendor/github.com/opencontainers/runc/libcontainer/process.go
  vendor/github.com/opencontainers/runc/libcontainer/rootfs_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/standard_init_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/system/linux.go
  vendor/github.com/opencontainers/runc/libcontainer/system/unsupported.go
  vendor/github.com/opencontainers/runc/libcontainer/user/lookup_unix.go
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
Labels: cncf-cla: yes, size/XL

#1756 test: Switch to go 1.11
  contrib/test/integration/main.yml
Labels: cncf-cla: yes, size/XS

#1758 server: ignore server closed error
  server/server.go
Labels: cncf-cla: yes, size/XS

#1759 travis: Switch to go 1.11
  .travis.yml
  Dockerfile
  lib/container_server.go
Labels: cncf-cla: yes, size/S

#1762 [release-1.11] image_pull: remove redunant CanPull check
  pkg/storage/image.go
  server/image_pull.go
Labels: cncf-cla: yes, size/M

#1761 image_pull: remove redunant CanPull check
  pkg/storage/image.go
  server/image_pull.go
Labels: cncf-cla: yes, size/M

#1721 Add default_systcls option to crio.conf
  cmd/crio/config.go
  cmd/crio/main.go
  lib/config.go
  server/sandbox_run_linux.go
  server/utils.go
  server/utils_test.go
  test/helpers.bash
  test/pod.bats
Labels: cncf-cla: yes, size/L

#1579 CRI-O Integration testing with userns enabled
  contrib/test/integration/README.md
  contrib/test/integration/main.yml
  contrib/test/integration/test.yml
  contrib/test/integration/vars.yml
Labels: cncf-cla: yes, size/M

#1749 crio.conf(5): update manpage to the latest state
  cmd/crio/config.go
  docs/crio.conf.5.md
Labels: cncf-cla: yes, size/XL
