Repository cri-o/cri-o, pull requests merged in 2018-03, with the labels that each got.

#1390 execsync: Set terminal to true when we pass -t to conmon
  oci/oci.go
Labels: cncf-cla: yes, size/XS

#1391 vendor: update containers/storage to latest
  vendor.conf
  vendor/github.com/containers/storage/drivers/aufs/aufs.go
  vendor/github.com/containers/storage/drivers/driver.go
  vendor/github.com/containers/storage/drivers/fsdiff.go
  vendor/github.com/containers/storage/drivers/overlay/overlay.go
  vendor/github.com/containers/storage/drivers/windows/windows.go
  vendor/github.com/containers/storage/layers.go
  vendor/github.com/containers/storage/layers_ffjson.go
  vendor/github.com/containers/storage/pkg/truncindex/truncindex.go
Labels: cncf-cla: yes, size/L

#1371 conmon: Respect start-pipe read errors
  conmon/conmon.c
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1395 Change all references from kpod to podman
  lib/logs.go
  lib/testdata/config.toml
  test/helpers.bash
  transfer.md
Labels: cncf-cla: yes, size/M

#1394 system_containers: Update mounts
  contrib/system_containers/centos/config.json.template
  contrib/system_containers/centos/manifest.json
  contrib/system_containers/fedora/config.json.template
  contrib/system_containers/fedora/manifest.json
  contrib/system_containers/rhel/config.json.template
  contrib/system_containers/rhel/manifest.json
Labels: cncf-cla: yes, size/M

#1398 Release v1.9.8
  version/version.go
Labels: cncf-cla: yes, size/XS

#1345 Fsnotify hooks
  cmd/crio/main.go
  lib/container_server.go
  lib/hooks.go
  server/server.go
Labels: cncf-cla: yes, size/L

#1384 lib: abstract out sandbox for platforms
  lib/container_server.go
  lib/container_server_linux.go
  lib/container_server_unsupported.go
Labels: cncf-cla: yes, size/M

#1365 conmon: open+rename the log file instead of unlink+open
  conmon/conmon.c
Labels: cncf-cla: yes, size/S

#1405 server: prevent double channel close
  server/server.go
Labels: cncf-cla: yes, size/XS

#1403 vendor: _actually_ update containers/storage?
  vendor/github.com/containers/storage/lockfile.go
  vendor/github.com/containers/storage/lockfile_darwin.go
  vendor/github.com/containers/storage/lockfile_linux.go
  vendor/github.com/containers/storage/lockfile_unix.go
  vendor/github.com/containers/storage/lockfile_windows.go
  vendor/github.com/containers/storage/stat_mtim.go
  vendor/github.com/containers/storage/stat_mtimespec.go
Labels: cncf-cla: yes, size/L

#1355 hooks: Copy-edits for the Markdown docs (RFC 2119, etc.)
  hooks.md
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#1366 conmon: add new option to call cleanup program at exit
  conmon/conmon.c
Labels: cncf-cla: yes, size/M

#1406 Have make file create the oci/hooks.d directory
  Makefile
Labels: cncf-cla: yes, size/XS

#1377 Add context to net ns symlink removal errors
  lib/sandbox/sandbox.go
Labels: cncf-cla: yes, size/XS

#1334 crio: Ensure container state is stopped when calling StopContainer()
  lib/stop.go
  oci/oci.go
  server/sandbox_remove.go
  server/sandbox_stop.go
Labels: cncf-cla: yes, size/M

#1404 vendor: update runc to HEAD
  Dockerfile
  contrib/test/integration/build/runc.yml
  vendor.conf
  vendor/github.com/opencontainers/runc/README.md
  vendor/github.com/opencontainers/runc/libcontainer/capabilities_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go
  vendor/github.com/opencontainers/runc/libcontainer/container_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c
  vendor/github.com/opencontainers/runc/libcontainer/rootfs_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/standard_init_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/user/lookup.go
  vendor/github.com/opencontainers/runc/libcontainer/user/lookup_unix.go
  vendor/github.com/opencontainers/runc/libcontainer/user/lookup_windows.go
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/github.com/opencontainers/runc/vendor.conf
Labels: cncf-cla: yes, size/L

#1401 Fix create container failure due to wrong image reference
  pkg/storage/image.go
  server/container_create.go
Labels: cncf-cla: yes, size/S

#1122 pause: do not strip binary
  pause/Makefile
Labels: cncf-cla: yes, size/XS

#1383 lib: abstract out selinux call
  lib/config.go
  lib/config_linux.go
  lib/config_unsupported.go
Labels: cncf-cla: yes, size/S

#1412 Remove unneeded/repeated Travis steps
  .travis.yml
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#835 add dev vagrantfile
  Vagrantfile
Labels: cncf-cla: yes, size/L

#1416 Support src directory name other than cri-o
  Makefile
Labels: cncf-cla: yes, size/XS

#1417 small refactor: use imageService.getRef wherever possible
  pkg/storage/image.go
Labels: cncf-cla: yes, size/M

#1421 vendor: update runtime-tools to HEAD
  vendor.conf
  vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default.go
  vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default_linux.go
  vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default_unsupported.go
  vendor/github.com/opencontainers/runtime-tools/specerror/config.go
  vendor/github.com/opencontainers/runtime-tools/validate/validate.go
  vendor/github.com/opencontainers/runtime-tools/validate/validate_linux.go
  vendor/github.com/opencontainers/runtime-tools/validate/validate_unsupported.go
Labels: cncf-cla: yes, size/L

#1368 conmon: Distinguish pexit(s) from pexitf(fmt, ...) and similar
  conmon/cmsg.c
  conmon/conmon.c
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#1409 conmon: catch SIGTERM, SIGINT and SIGQUIT
  conmon/conmon.c
Labels: cncf-cla: yes, size/M

#1300 Setup LISTEN_PID to point to new child process
  conmon/conmon.c
Labels: cncf-cla: yes, size/S

#1425 sandbox_stop: Call CNI stop before stopping pod infra container
  server/sandbox_stop.go
Labels: cncf-cla: yes, size/S

#1410 lib: libcontainer references are linux only
  lib/container_server.go
  lib/container_server_linux.go
  lib/container_server_unsupported.go
  lib/stats.go
  lib/stats_linux.go
Labels: cncf-cla: yes, size/L

#1423 Update CNI config versions to 0.3.0
  contrib/cni/10-crio-bridge.conf
  contrib/cni/99-loopback.conf
Labels: cncf-cla: yes, size/XS

#1430 sandbox_stop: Call CNI stop before stopping pod infra container
  server/sandbox_stop.go
Labels: cncf-cla: yes, size/S

#1420 Fix two integration nits
  contrib/test/integration/README.md
  contrib/test/integration/system.yml
Labels: cncf-cla: yes, size/M

#1336 Add extra info to verbose requests to PodSandboxStatus
  .travis.yml
  server/config_test.go
  server/sandbox_status.go
  server/sandbox_status_test.go
  server/utils_test.go
Labels: cncf-cla: yes, size/L

#1431 Bump 1.9.9
  version/version.go
Labels: cncf-cla: yes, size/XS

#1426 Conmon reopen log file support
  conmon/conmon.c
Labels: cncf-cla: yes, size/M

#1428 .travis.yml: Add allowed-to-fail OS X compilation
  .travis.yml
  Makefile
  hack/seccomp_tag.sh
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#1385 lib/sandbox: clarify variable names
  lib/sandbox/sandbox.go
Labels: cncf-cla: yes, size/S

#1414 Make conmon and crio share the same constants
  .gitignore
  cmd/crio/main.go
  conmon/Makefile
  conmon/config.go
  conmon/conmon.c
  oci/oci.go
  server/container_attach.go
Labels: cncf-cla: yes, size/M

#1415 Image cache lock
  pkg/storage/image.go
Labels: cncf-cla: yes, size/L

#1399 test/testdata/container_redis.json: Set cpuset_cpus to 0
  test/ctr.bats
  test/testdata/container_redis.json
Labels: cncf-cla: yes, size/XS

#1438 conmon: Remove info logs
  cmd/crio/main.go
  conmon/conmon.c
  server/container_attach.go
Labels: cncf-cla: yes, size/XS

#1419 oci: Force kill the container process only if nothing else worked
  oci/oci.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#1411 utils: delete unused code
  utils/filesystem.go
Labels: cncf-cla: yes, size/M

#1435 vendor: update containers/image to HEAD
  vendor.conf
  vendor/github.com/containers/image/copy/copy.go
  vendor/github.com/containers/image/directory/directory_dest.go
  vendor/github.com/containers/image/directory/directory_src.go
  vendor/github.com/containers/image/directory/directory_transport.go
  vendor/github.com/containers/image/docker/archive/src.go
  vendor/github.com/containers/image/docker/daemon/daemon_src.go
  vendor/github.com/containers/image/docker/docker_image_src.go
  vendor/github.com/containers/image/image/memory.go
  vendor/github.com/containers/image/image/sourced.go
  vendor/github.com/containers/image/image/unparsed.go
  vendor/github.com/containers/image/oci/archive/oci_src.go
  vendor/github.com/containers/image/oci/layout/oci_src.go
  vendor/github.com/containers/image/openshift/openshift.go
  vendor/github.com/containers/image/ostree/ostree_dest.go
  vendor/github.com/containers/image/ostree/ostree_src.go
  vendor/github.com/containers/image/storage/storage_image.go
  vendor/github.com/containers/image/tarball/tarball_src.go
  vendor/github.com/containers/image/transports/alltransports/ostree.go
  vendor/github.com/containers/image/transports/alltransports/ostree_stub.go
  vendor/github.com/containers/image/types/types.go
Labels: cncf-cla: yes, size/L

#1444 container_exec: Fix terminal setting for exec
  oci/oci.go
Labels: cncf-cla: yes, size/XS

#1443 container_exec: Fix terminal setting for exec
  oci/oci.go
Labels: cncf-cla: yes, size/XS

#1447 conmon: Avoid strlen in logging path
  conmon/conmon.c
Labels: cncf-cla: yes, size/S

#1393 Add make install.tools to README.md and touch up tutorial
  README.md
  tutorial.md
Labels: cncf-cla: yes, size/S

#1446 Make network namespace lifecycle management optional
  lib/config.go
  lib/container_server.go
  lib/sandbox/sandbox.go
  server/sandbox_network.go
  server/sandbox_run.go
  server/sandbox_stop.go
  server/server.go
Labels: cncf-cla: yes, size/L

#1448 Release 1.9.10
  version/version.go
Labels: cncf-cla: yes, size/XS

#1427 conmon: add support to restore a container
  conmon/conmon.c
Labels: cncf-cla: yes, size/M

#1353 Using "/var/run/crio/crio.sock" as endpoint is deprecated.
  README.md
  contrib/test/integration/node-e2e.yml
  kubernetes.md
Labels: cncf-cla: yes, size/XS

#1449 conmon: Avoid strlen in logging path
  conmon/conmon.c
Labels: cncf-cla: yes, size/S

#1429 Tweak test timeouts to be readable + realistic
  contrib/test/integration/e2e.yml
  contrib/test/integration/node-e2e.yml
  contrib/test/integration/test.yml
Labels: cncf-cla: yes, size/XS

#1064 Add ability to enable/disable SELinux during tests
  contrib/test/integration/e2e.yml
  contrib/test/integration/node-e2e.yml
  contrib/test/integration/test.yml
  contrib/test/integration/vars.yml
Labels: cncf-cla: yes, size/M

#1451 Add support for partial IDs for exec and attach
  lib/container.go
  server/container_attach.go
  server/container_exec.go
  server/container_execsync.go
  server/container_start.go
  server/container_status.go
  server/container_update_resources.go
Labels: cncf-cla: yes, size/S

#1450 Reopen log file support
  Dockerfile
  contrib/test/integration/main.yml
  pkg/storage/image.go
  server/container_reopen_log.go
Labels: cncf-cla: yes, size/M

#1454 Return error for container exec
  server/container_exec.go
Labels: cncf-cla: yes, size/XS

#1437 run stop_crio inside cleanup_test
  test/helpers.bash
Labels: cncf-cla: yes, size/XS

#1456 v1.10 beta 1
  version/version.go
Labels: cncf-cla: yes, size/XS

#1455 Return error for container exec
  server/container_exec.go
Labels: cncf-cla: yes, size/XS

#1445 pkg/findprocess: Add a new package for portable process detection
  oci/oci.go
  pkg/findprocess/findprocess.go
  pkg/findprocess/findprocess_test.go
  pkg/findprocess/findprocess_unix.go
  pkg/findprocess/findprocess_windows.go
Labels: cncf-cla: yes, size/L

#1452 Fix accidental positive side-effect of RHEL 7.4- bug
  contrib/test/integration/system.yml
Labels: cncf-cla: yes, size/XS

#1356 travis: bump up go versions
  .travis.yml
Labels: cncf-cla: yes, size/XS

#1272 CONTRIBUTING: Link to Prow OWNERS
  CONTRIBUTING.md
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#701 Default to the storage defaults
  cmd/crio/config.go
  contrib/system_containers/centos/Dockerfile
  contrib/system_containers/fedora/Dockerfile
  contrib/system_containers/rhel/Dockerfile
  contrib/test/integration/build/cri-o.yml
  lib/config.go
  test/helpers.bash
Labels: cncf-cla: yes, size/M

#1458 Makefile: Avoid needless binary rebuilds
  Makefile
  conmon/Makefile
  pause/Makefile
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#1460 Use formatter for C code
  .clang-format
  Makefile
  conmon/cmsg.c
  conmon/conmon.c
  pause/pause.c
Labels: cncf-cla: yes, size/L

#1459 conmon/pause: Add order-only prereq for ../bin
  conmon/Makefile
  pause/Makefile
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#1465 Backport container and imageFs stats to release-1.9 branch
  lib/stats.go
  server/container_list.go
  server/container_stats.go
  server/container_stats_list.go
  server/image_fs_info.go
  utils/filesystem.go
Labels: cncf-cla: yes, size/L

#1464 conmon/pause: Allow user-specified CFLAGS
  conmon/Makefile
  conmon/cmsg.c
  conmon/conmon.c
  pause/Makefile
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#1463 *: Return err from AddHook and ok from RemoveHook
  lib/container_server.go
  lib/hooks.go
  server/server.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#1457 Update cri-tools commit to pick up latest tests and changes
  Dockerfile
  contrib/test/integration/build/cri-tools.yml
  contrib/test/integration/critest.yml
  contrib/test/integration/main.yml
Labels: cncf-cla: yes, size/S

#1461 Update cri-tools commit to pick up latest tests and changes
  Dockerfile
  contrib/test/integration/build/cri-tools.yml
  contrib/test/integration/critest.yml
  contrib/test/integration/main.yml
Labels: cncf-cla: yes, size/S

#1468 lib/hooks: Allow the same command in multiple hook files
  lib/hooks.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1467 CONTRIBUTING: Explain .github/CODEOWNERS
  CONTRIBUTING.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1466 CONTRIBUTING: Document test steps
  .travis.yml
  CONTRIBUTING.md
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#1471 Update cri-tools version
  Dockerfile
  contrib/test/integration/main.yml
Labels: cncf-cla: yes, size/XS

#1472 Fix crio man page bugs.
  docs/crio.8.md
Labels: cncf-cla: yes, size/S

#1469 conmon: new option --conmon-pidfile=
  conmon/conmon.c
Labels: cncf-cla: yes, size/S

#1329 Permanently disable swap prior to testing
  contrib/test/integration/disable_swap.yml
  contrib/test/integration/main.yml
  contrib/test/integration/system.yml
Labels: cncf-cla: yes, size/M

#1434 Add read-only flag
  cmd/crio/config.go
  cmd/crio/main.go
  docs/crio.8.md
  docs/crio.conf.5.md
  lib/config.go
  server/container_create.go
Labels: cncf-cla: yes, size/M

#1475 conmon: Add container id to syslog
  conmon/conmon.c
Labels: cncf-cla: yes, size/L
