Repository cri-o/cri-o, pull requests merged in 2018-07, with the labels that each got.

#1670 server: Don't make additional copy of config.json
  lib/container_server.go
  server/container_create.go
  server/sandbox_run.go
Labels: cncf-cla: yes, size/S

#1675 version: v1.12.0-dev
  version/version.go
Labels: cncf-cla: yes, size/XS

#1674 [1.11] server: Don't make additional copy of config.json
  lib/container_server.go
  server/container_create.go
  server/sandbox_run.go
Labels: cncf-cla: yes, size/S

#1676 vendor in new opencontainers/runtime-tools
  server/container_create.go
  server/sandbox_run.go
  vendor.conf
  vendor/github.com/opencontainers/runtime-tools/README.md
  vendor/github.com/opencontainers/runtime-tools/error/error.go
  vendor/github.com/opencontainers/runtime-tools/generate/config.go
  vendor/github.com/opencontainers/runtime-tools/generate/generate.go
  vendor/github.com/opencontainers/runtime-tools/generate/spec.go
  vendor/github.com/opencontainers/runtime-tools/specerror/error.go
  vendor/github.com/opencontainers/runtime-tools/validate/validate.go
  vendor/github.com/opencontainers/runtime-tools/validate/validate_linux.go
Labels: cncf-cla: yes, size/XXL

#1679 Block use of /proc/acpi from inside containers
  server/container_create.go
Labels: cncf-cla: yes, size/XS

#1677 tests: remove more sleeps from ctr.bats
  test/ctr.bats
  test/helpers.bash
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1682 server/container_create: Mask /proc/keys
  server/container_create.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1680 [release-1.11] tests: remove more sleeps from ctr.bats
  test/ctr.bats
  test/helpers.bash
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1684 [release-1.10] server/container_create: mask /proc/{acpi,keys}
  server/container_create.go
Labels: cncf-cla: yes, size/XS

#1672 4294967295 does not fit in an int on 32 bit systems
  server/inspect.go
Labels: cncf-cla: yes, size/XS

#1687 Bump 1.10.6
  version/version.go
Labels: cncf-cla: yes, size/XS

#1688 [1.11] 4294967295 does not fit in an int on 32 bit systems
  server/inspect.go
Labels: cncf-cla: yes, size/XS

#1686 Bump 1.11.1
  version/version.go
Labels: cncf-cla: yes, size/XS

#1689 server/container_create: mask /proc/{acpi,keys}
  server/container_create.go
Labels: cncf-cla: yes, size/XS

#1690 Release v1.9.14
  version/version.go
Labels: cncf-cla: yes, size/XS

#1681 [release-1.10] tests: remove more sleeps from ctr.bats
  .travis.yml
  lib/container_server.go
  server/container_create.go
  server/container_list.go
  server/container_stats_list.go
  server/sandbox_list.go
  server/server.go
  test/ctr.bats
  test/helpers.bash
Labels: cncf-cla: yes, size/S

#1697 [release 1.9] Fix tests for kata CI
  test/ctr.bats
  test/helpers.bash
Labels: cncf-cla: yes, size/M

#1655 server: cross-platform changes
  cmd/crio/main.go
  server/container_attach.go
  server/container_create.go
  server/container_create_generic.go
  server/container_create_linux.go
  server/container_create_unsupported.go
  server/label_linux.go
  server/label_unsupported.go
  server/listen_unix.go
  server/listen_windows.go
  server/sandbox_run.go
  server/sandbox_run_linux.go
  server/sandbox_run_unsupported.go
  server/sandbox_stop.go
  server/sandbox_stop_linux.go
  server/sandbox_stop_unsupported.go
  vendor/github.com/Microsoft/go-winio/file.go
  vendor/github.com/Microsoft/go-winio/pipe.go
  vendor/github.com/Microsoft/go-winio/zsyscall_windows.go
Labels: cncf-cla: yes, size/XXL

#1698 conmon: close extra files before exit
  conmon/conmon.c
Labels: cncf-cla: yes, size/S

#1699 Remove "--log-level debug" from service file
  tutorial.md
Labels: cncf-cla: yes, size/XS

#1701 oci: update privilege/trust handling
  oci/oci.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1703 oci: update privilege/trust handling
  oci/oci.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1708 [release-1.11] server/container_create: error out if capability is unknown
  server/container_create.go
Labels: cncf-cla: yes, size/XS

#1709 [release-1.10] server/container_create: error out if capability is unknown
  server/container_create.go
Labels: cncf-cla: yes, size/XS

#1707 server/container_create: error out if capability is unknown
  server/container_create.go
Labels: cncf-cla: yes, size/XS

#1705 tests: Add the possibility to change stream_port
  test/helpers.bash
Labels: cncf-cla: yes, size/XS

#1692 [1.10] Add log-level option to conmon and crio.conf
  cmd/crio/config.go
  cmd/crio/main.go
  conmon/conmon.c
  docs/crio.8.md
  docs/crio.conf.5.md
  lib/config.go
  oci/oci.go
  tutorial.md
Labels: cncf-cla: yes, size/L

#1714 server: serve streaming on localhost on a random port
  cmd/crio/main.go
  server/config.go
  server/server.go
Labels: cncf-cla: yes, size/XS
