Repository cri-o/cri-o, pull requests merged in 2018-09, with the labels that each got.

#1773 Fix manpage to correctly state default storage driver
  docs/crio.8.md
Labels: cncf-cla: yes, size/XS

#1774 [release-1.11] image_pull: fix variable shadowing
  pkg/storage/image.go
  server/image_pull.go
Labels: cncf-cla: yes, size/S

#1782 [release-1.11] server: don't wipe out the selinux mount label if privileged
  server/sandbox_run.go
Labels: cncf-cla: yes, size/S

#1785 Bump 1.11.3
  version/version.go
Labels: cncf-cla: yes, size/XS, ¯\_(ツ)_/¯

#1788 test: Add directory for kubernetes-sigs
  contrib/test/integration/golang.yml
Labels: approved, cncf-cla: yes, size/XS

#1786 test: Fixup kubernetes-incubator to kubernetes-sigs
  Dockerfile
  contrib/test/integration/build/cri-tools.yml
  contrib/test/integration/main.yml
  server/sandbox_status.go
  server/sandbox_status_test.go
Labels: approved, cncf-cla: yes, size/M

#1789 [release-1.11] use in memory created time
  Dockerfile
  contrib/test/integration/build/cri-tools.yml
  server/container_list.go
  server/container_status.go
  server/sandbox_list.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1792 Release 1.11.4
  version/version.go
Labels: approved, cncf-cla: yes, size/XS

#1772 contrib: test: run e2e in parallel
  Dockerfile
  contrib/test/integration/build/bats.yml
  contrib/test/integration/critest.yml
  contrib/test/integration/e2e.yml
  contrib/test/integration/golang.yml
  contrib/test/integration/main.yml
  pkg/storage/image.go
  server/container_list.go
  server/container_status.go
  server/image_pull.go
  server/sandbox_list.go
  server/sandbox_run.go
  test/README.md
  vendor/github.com/containers/libpod/README.md
  vendor/github.com/containers/libpod/pkg/hooks/0.1.0/hook.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1799 Pick up new tests for critest
  Dockerfile
  contrib/test/integration/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1801 [release-1.11] Fix create/list race
  lib/container_server.go
  lib/sandbox/history.go
  lib/sandbox/sandbox.go
  oci/container.go
  server/container_create.go
  server/container_list.go
  server/sandbox_list.go
  server/sandbox_run.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1795 [release-1.11] config: default file_locking to false
  lib/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1806 [release-1.11] test: Use crictl logs for parsing log file in tty test
  test/ctr.bats
Labels: approved, cncf-cla: yes, lgtm, size/S

#1803 Fix list/create race
  lib/container_server.go
  lib/sandbox/history.go
  lib/sandbox/sandbox.go
  oci/container.go
  server/container_create.go
  server/container_list.go
  server/sandbox_list.go
  server/sandbox_run_linux.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1807 test: Use crictl logs for parsing log file in tty test
  test/ctr.bats
Labels: approved, cncf-cla: yes, lgtm, size/S

#1808 Bump 1.11.5
  version/version.go
Labels: approved, cncf-cla: yes, size/XS

#1748 cni: Add CNI result JSON as an annotation
  pkg/annotations/annotations.go
  server/sandbox_network.go
  server/sandbox_run_linux.go
Labels: cncf-cla: yes, size/S

#1794 [release-1.11] test: Run e2e in parallel
  contrib/test/integration/e2e.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1754 container_status: Add debug info for container
  server/container_status.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1814 Vendor in latest containers/image and containers/storage
  pkg/storage/runtime.go
  vendor.conf
  vendor/github.com/containers/image/README.md
  vendor/github.com/containers/image/copy/copy.go
  vendor/github.com/containers/image/docker/docker_client.go
  vendor/github.com/containers/image/docker/docker_image.go
  vendor/github.com/containers/image/docker/docker_image_dest.go
  vendor/github.com/containers/image/docker/docker_image_src.go
  vendor/github.com/containers/image/manifest/docker_schema2.go
  vendor/github.com/containers/image/ostree/ostree_dest.go
  vendor/github.com/containers/image/pkg/tlsclientconfig/tlsclientconfig.go
  vendor/github.com/containers/image/storage/storage_image.go
  vendor/github.com/containers/storage/README.md
  vendor/github.com/containers/storage/containers.go
  vendor/github.com/containers/storage/containers_ffjson.go
  vendor/github.com/containers/storage/drivers/aufs/aufs.go
  vendor/github.com/containers/storage/drivers/btrfs/btrfs.go
  vendor/github.com/containers/storage/drivers/chown.go
  vendor/github.com/containers/storage/drivers/chown_unix.go
  vendor/github.com/containers/storage/drivers/devmapper/deviceset.go
  vendor/github.com/containers/storage/drivers/devmapper/driver.go
  vendor/github.com/containers/storage/drivers/driver.go
  vendor/github.com/containers/storage/drivers/fsdiff.go
  vendor/github.com/containers/storage/drivers/overlay/overlay.go
  vendor/github.com/containers/storage/drivers/vfs/driver.go
  vendor/github.com/containers/storage/drivers/windows/windows.go
  vendor/github.com/containers/storage/drivers/zfs/zfs.go
  vendor/github.com/containers/storage/images.go
  vendor/github.com/containers/storage/layers.go
  vendor/github.com/containers/storage/layers_ffjson.go
  vendor/github.com/containers/storage/lockfile.go
  vendor/github.com/containers/storage/lockfile_unix.go
  vendor/github.com/containers/storage/lockfile_windows.go
  vendor/github.com/containers/storage/pkg/idtools/idtools.go
  vendor/github.com/containers/storage/pkg/mount/flags.go
  vendor/github.com/containers/storage/pkg/mount/mount.go
  vendor/github.com/containers/storage/pkg/ostree/no_ostree.go
  vendor/github.com/containers/storage/pkg/ostree/ostree.go
  vendor/github.com/containers/storage/store.go
  vendor/github.com/containers/storage/vendor.conf
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XXL

#1817 runPodSandbox: clean up containers on error path
  server/sandbox_run_linux.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1818 [release-1.11] runPodSandbox: clean up containers on error path
  server/sandbox_run.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1819 Release 1.11.6
  version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
