Repository cri-o/cri-o, pull requests merged in 2018-06, with the labels that each got.

#1586 conmon: Remove unused CMD_SIZE and MAX_EVENTS
  conmon/conmon.c
Labels: cncf-cla: yes, size/XS

#1587 Fix syscontainer proxy export
  contrib/system_containers/centos/run.sh
  contrib/system_containers/fedora/run.sh
  contrib/system_containers/rhel/run.sh
Labels: cncf-cla: yes, size/XS

#1589 Makefile: Transition from 'make' to $(MAKE)
  Makefile
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1531 server/sandbox: clean up network even if networkStart() fails
  Dockerfile
  contrib/test/integration/build/plugins.yml
  server/sandbox_network.go
  test/cni_plugin_helper.bash
  test/helpers.bash
  test/network.bats
Labels: cncf-cla: yes, size/L

#1590 Makefile: Drop find-godeps.sh for bin/crio target and make it .PHONY
  Makefile
  hack/find-godeps.sh
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#1597 .travis.yml: One stage for integration tests (userns and otherwise)
  .travis.yml
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1598 Release 1.9.13
  version/version.go
Labels: cncf-cla: yes, size/XS

#1599 .travis.yml: Add missing $ to OSTree guard
  .travis.yml
Labels: cncf-cla: yes, size/XS

#1584 [1.10] server/sandbox: clean up network even if networkStart() fails
  Dockerfile
  contrib/test/integration/build/plugins.yml
  server/sandbox_network.go
  test/cni_plugin_helper.bash
  test/helpers.bash
  test/network.bats
Labels: cncf-cla: yes, size/L

#1541 [release-1.10] runtime_status: report correct network status
  oci/oci.go
  server/runtime_status.go
Labels: cncf-cla: yes, size/M

#1603 lib: config: use official kube pause image from gcr
  lib/config.go
Labels: cncf-cla: yes, size/XS

#1583 Add dynamic TLS Configuration for the streaming server
  cmd/crio/config.go
  server/config.go
  server/server.go
Labels: cncf-cla: yes, size/M

#1601 container_create: support CRI RunAsGroup
  server/container_create.go
Labels: cncf-cla: yes, size/XS

#1607 [release-1.10] conmon: fix incorrect log line on a log refresh
  conmon/conmon.c
Labels: cncf-cla: yes, size/XS

#1602 [release-1.10] container_create: support CRI RunAsGroup
  .travis.yml
  Dockerfile
  contrib/test/integration/main.yml
  server/container_create.go
  test/ctr.bats
  test/helpers.bash
  test/pod.bats
  test/restore.bats
Labels: cncf-cla: yes, size/M

#1609 contrib,test: bump cri-tools
  Dockerfile
  contrib/test/integration/main.yml
  test/ctr.bats
  test/helpers.bash
  test/pod.bats
  test/restore.bats
Labels: cncf-cla: yes, size/M

#1608 Release 1.10.2
  version/version.go
Labels: cncf-cla: yes, size/XS

#1612 container_create: fixes
  server/container_create.go
  server/container_portforward.go
Labels: cncf-cla: yes, size/S

#1613 Create fixes 1.10
  server/container_create.go
  server/container_portforward.go
Labels: cncf-cla: yes, size/S

#1611 [1.10] conmon: on a flush error discard the iov buffer
  conmon/conmon.c
Labels: cncf-cla: yes, size/XS

#1617 server: fix race between container create and cadvisor asking for info
  server/container_create.go
  server/sandbox_run.go
Labels: cncf-cla: yes, size/M

#1618 [release-1.9] server: fix race between container create and cadvisor asking for info
  .travis.yml
  server/container_create.go
  server/sandbox_run.go
Labels: cncf-cla: yes, size/M

#1615 [release-1.10] cmd: crio: suppress logging before flag.Parse
  cmd/crio/main.go
Labels: cncf-cla: yes, size/XS

#1621 container_create: correctly relabel mounts when asked
  server/container_create.go
Labels: cncf-cla: yes, size/XS

#1623 Make logging to syslog optional
  conmon/conmon.c
  oci/oci.go
Labels: cncf-cla: yes, size/S

#1620 [release-1.10] container_create: correctly relabel mounts when asked
  server/container_create.go
Labels: cncf-cla: yes, size/XS

#1616 [release-1.10] server: fix race between container create and cadvisor asking for info
  server/container_create.go
  server/sandbox_run.go
Labels: cncf-cla: yes, size/M

#1622 release 1.10.3
  version/version.go
Labels: cncf-cla: yes, size/XS

#1626 README.md: add 1.10 to version matrix
  README.md
Labels: cncf-cla: yes, size/S

#1629 [release-1.10] Port lvm_cleanup from master branch
  test/helpers.bash
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#1628 [release-1.10] Selinux relabel fixes for 1.10
  server/container_create.go
  server/sandbox_run.go
Labels: cncf-cla: yes, size/S

#1439 *: abstract out netns for multiple platforms
  client/client.go
  lib/container_server.go
  lib/logs.go
  lib/remove.go
  lib/rename.go
  lib/sandbox/sandbox.go
  lib/sandbox/sandbox_linux.go
  lib/sandbox/sandbox_unsupported.go
  lib/stop.go
  lib/wait.go
  oci/container.go
  oci/oci_windows.go
  pkg/storage/image.go
  server/container_create.go
  server/inspect_test.go
  server/sandbox_list.go
  server/sandbox_run.go
  server/sandbox_status_test.go
  server/server.go
Labels: cncf-cla: yes, size/L

#1631 apparmor: package not limited to server
  pkg/apparmor/aaparser.go
  pkg/apparmor/apparmor_common.go
  pkg/apparmor/apparmor_supported.go
  pkg/apparmor/apparmor_unsupported.go
  pkg/apparmor/template.go
  server/container_create.go
  server/server.go
Labels: cncf-cla: yes, size/XS

#1632 Vendor in latest go-selinux bindings
  vendor.conf
  vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux.go
Labels: cncf-cla: yes, size/L

#1633 server.Server: cleanup of public functions
  server/container_attach.go
  server/container_exec.go
  server/container_portforward.go
  server/sandbox_network.go
  server/sandbox_stop.go
  server/server.go
Labels: cncf-cla: yes, size/M

#1636 Fix Conmon timestamps with non-integer-hour offsets
  conmon/conmon.c
Labels: cncf-cla: yes, size/XS

#1638 Fix typo in crictl environment variable export
  tutorial.md
Labels: cncf-cla: yes, size/XS

#1640 [release 1.10] network: Fix manage NetworkNS lifecycle
  lib/container_server.go
  lib/sandbox/sandbox.go
  pkg/annotations/annotations.go
  server/sandbox_run.go
  server/sandbox_status_test.go
Labels: cncf-cla: yes, size/S

#1641 conmon: do not use an empty env when running the exit command
  conmon/conmon.c
Labels: cncf-cla: yes, size/XS

#1644 [1.11] Use kubernetes release-1.11 for tests
  contrib/test/integration/main.yml
  vendor.conf
  vendor/k8s.io/kubernetes/pkg/apis/autoscaling/types.go
  vendor/k8s.io/kubernetes/pkg/apis/autoscaling/zz_generated.deepcopy.go
Labels: cncf-cla: yes, size/XL

#1643 Update to latest ocicni
  server/sandbox_network.go
  vendor.conf
  vendor/github.com/cri-o/ocicni/pkg/ocicni/noop.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/types.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/types_unix.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/types_windows.go
Labels: cncf-cla: yes, size/L

#1646 system-containers: update maintainer for Fedora and CentOS to myself
  contrib/system_containers/centos/Dockerfile
  contrib/system_containers/fedora/Dockerfile
Labels: cncf-cla: yes, size/XS

#1506 cross platform compiles
  .travis.yml
  Makefile
Labels: cncf-cla: yes, size/S

#1642 [1.10] Update to latest ocicni
  server/sandbox_network.go
  vendor.conf
  vendor/github.com/cri-o/ocicni/pkg/ocicni/noop.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/types.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/types_unix.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/types_windows.go
Labels: cncf-cla: yes, size/L

#1647 release v1.10.4
  version/version.go
Labels: cncf-cla: yes, size/XS

#1650 [1.11] Update ocicni to latest
  server/sandbox_network.go
  vendor.conf
  vendor/github.com/cri-o/ocicni/pkg/ocicni/noop.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/types.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/types_unix.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/types_windows.go
Labels: cncf-cla: yes, size/L

#1645 system-container: change repo for CentOS
  contrib/system_containers/centos/Dockerfile
Labels: cncf-cla: yes, size/XS

#1652 [1.11] Reduce amount of logs being printed by default
  cmd/crio/selinux_unsupported.go
  conmon/conmon.c
  oci/oci.go
  oci/oci_linux.go
  pkg/storage/runtime.go
  server/container_attach.go
  server/container_create.go
  server/container_reopen_log.go
Labels: cncf-cla: yes, size/M

#1651 Reduce amount of logs being printed by default
  cmd/crio/selinux_unsupported.go
  conmon/conmon.c
  oci/oci.go
  oci/oci_linux.go
  pkg/storage/runtime.go
  server/container_attach.go
  server/container_create.go
  server/container_reopen_log.go
Labels: cncf-cla: yes, size/M

#1656 tests: Add timeout before stop container.
  test/ctr.bats
  test/helpers.bash
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#1634 platform specific default paths
  lib/config.go
  lib/config_unix.go
  lib/config_windows.go
  oci/oci.go
  oci/oci_unix.go
  oci/oci_windows.go
  server/config.go
  server/config_unix.go
  server/config_windows.go
  server/server.go
Labels: cncf-cla: yes, size/M

#1630 seccomp: package not limited to server
  pkg/seccomp/seccomp.go
  pkg/seccomp/seccomp_unsupported.go
  pkg/seccomp/types.go
  server/container_create.go
  server/server.go
Labels: cncf-cla: yes, size/XS

#1658 Release 1.11.0
  version/version.go
Labels: cncf-cla: yes, size/XS

#1659 [release-1.11] tests: Add timeout before remove container
  test/ctr.bats
  test/helpers.bash
Labels: cncf-cla: yes, size/M

#1657 [release-1.10] tests: Add timeout before stop container.
  test/ctr.bats
  test/helpers.bash
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#1660 vendor: update github.com/cri-o/ocicni
  vendor.conf
  vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/util.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/util_linux.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/util_unsupported.go
Labels: cncf-cla: yes, size/L

#1663 [1.11] cri-tools: Use release-1.11 branch
  Dockerfile
  contrib/test/integration/main.yml
Labels: cncf-cla: yes, size/XS

#1654 Makefile: Add .explicit_phony target for bin/crio.cross.%
  Makefile
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1649 Vendor in latest go-selinux so that it supports non linux builds
  lib/container_server.go
  server/container_create.go
  server/container_list.go
  server/container_stats_list.go
  server/sandbox_list.go
  server/server.go
  vendor.conf
  vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
  vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go
Labels: cncf-cla: yes, size/L

#1665 readme: Add 1.11 to compatibility matrix
  README.md
Labels: cncf-cla: yes, size/XS

#1666 Release v1.10.5
  version/version.go
Labels: cncf-cla: yes, size/XS
