Repository cri-o/cri-o, pull requests merged in 2018-04, with the labels that each got.

#1480 Drop libapparmor dependency from build docs
  .travis.yml
  Dockerfile
  README.md
  tutorial.md
Labels: cncf-cla: yes, size/S

#1476 Add documentation of files used by cri-o
  docs/crio.8.md
Labels: cncf-cla: yes, size/S

#1484 conmon: fix typo servier->server
  cmd/crio/main.go
Labels: cncf-cla: yes, size/XS

#1478 oci: avoid race on container stop
  oci/oci.go
Labels: cncf-cla: yes, size/S

#1487 oci: Replace ‘c.ID()’ with ‘c.id’
  oci/oci.go
Labels: cncf-cla: yes, size/S

#1486 findprocess: no new variables for :=
  pkg/findprocess/findprocess_windows.go
Labels: cncf-cla: yes, size/XS

#1489 test: Fix race condition in ctr.bats
  test/ctr.bats
Labels: cncf-cla: yes, size/M

#1497 Fix up config files description
  README.md
  docs/crio.8.md
Labels: cncf-cla: yes, size/XS

#1493 test: Fix race condition in ctr.bats
  test/ctr.bats
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#1495 test: Fix race condition in ctr.bats
  test/ctr.bats
Labels: cncf-cla: yes, size/M

#1494 server/sandbox_stop: Pass context through StopAllPodSandboxes
  cmd/crio/main.go
  server/sandbox_status_test.go
  server/sandbox_stop.go
  server/server.go
Labels: cherry-pick, cncf-cla: yes, size/M

#1503 conmon: Add container ID to syslog
  conmon/conmon.c
Labels: cncf-cla: yes, size/M

#1496 crio-shutdown.service was not working correctly
  contrib/systemd/crio-shutdown.service
Labels: cncf-cla: yes, size/XS

#1504 server: O_WRONLY is not unix only
  server/container_reopen_log.go
Labels: cncf-cla: yes, size/XS

#1499 Don't override registries.conf by default
  cmd/crio/config.go
  contrib/test/integration/build/cri-o.yml
  lib/config.go
  test/helpers.bash
  vendor.conf
  vendor/github.com/BurntSushi/toml/README.md
  vendor/github.com/BurntSushi/toml/decode.go
  vendor/github.com/BurntSushi/toml/decode_meta.go
  vendor/github.com/BurntSushi/toml/doc.go
  vendor/github.com/BurntSushi/toml/encode.go
  vendor/github.com/BurntSushi/toml/lex.go
  vendor/github.com/BurntSushi/toml/parse.go
  vendor/github.com/BurntSushi/toml/type_fields.go
  vendor/github.com/containers/image/pkg/sysregistries/system_registries.go
Labels: cncf-cla: yes, size/XL

#1508 [release 1.9] server/sandbox_stop: Pass context through StopAllPodSandboxes
  cmd/crio/main.go
  server/sandbox_stop.go
  server/server.go
Labels: cncf-cla: yes, size/S

#1501 [release-1.9] oci: avoid race on container stop
  oci/oci.go
  pkg/findprocess/findprocess.go
  pkg/findprocess/findprocess_test.go
  pkg/findprocess/findprocess_unix.go
  pkg/findprocess/findprocess_windows.go
Labels: cncf-cla: yes, size/L

#1500 [release-1.10] oci: avoid race on container stop
  oci/oci.go
  pkg/findprocess/findprocess.go
  pkg/findprocess/findprocess_test.go
  pkg/findprocess/findprocess_unix.go
  pkg/findprocess/findprocess_windows.go
Labels: cncf-cla: yes, size/L

#1483 Conmon multiple attach
  conmon/conmon.c
Labels: cncf-cla: yes, size/M

#1509 [release 1.10] server/sandbox_stop: Pass context through StopAllPodSandboxes
  cmd/crio/main.go
  server/sandbox_status_test.go
  server/sandbox_stop.go
  server/server.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#1505 main: a couple of platform depedent calls
  cmd/crio/daemon_unsupported.go
  cmd/crio/main.go
  pkg/signals/signal.go
  pkg/signals/signal_unix.go
  pkg/signals/signal_windows.go
Labels: cncf-cla: yes, size/M

#1485 cri-o: allow a prefix for all bind mounts
  cmd/crio/main.go
  docs/crio.8.md
  lib/config.go
  server/container_create.go
  server/secrets.go
Labels: cncf-cla: yes, size/M

#1507 Add mark comments near all lines added by Ansible
  contrib/test/integration/build/kubernetes.yml
  contrib/test/integration/e2e.yml
  contrib/test/integration/golang.yml
  contrib/test/integration/system.yml
  contrib/test/integration/test.yml
Labels: cncf-cla: yes, size/S

#1513 conmon: return the correct exit status
  conmon/conmon.c
Labels: cncf-cla: yes, size/S

#1511 lib/container_server: Allow the same command in multiple hook files
  lib/container_server.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1516 Release v1.9.11
  version/version.go
Labels: cncf-cla: yes, size/XS

#1407 oci: changes for cross-platform
  oci/finished.go
  oci/finished_32.go
  oci/finished_unsupported.go
  oci/oci.go
  oci/oci_linux.go
  oci/oci_unix.go
  oci/oci_unsupported.go
  oci/oci_windows.go
Labels: cncf-cla: yes, size/L

#1532 test: Skip image pull with signature
  test/image.bats
Labels: cncf-cla: yes, size/XS

#1525 Replace bool with gboolean
  conmon/conmon.c
Labels: cncf-cla: yes, size/S

#1533 Move cri-o test images to quay.io
  contrib/test/integration/build/cri-o.yml
  test/ctr.bats
  test/default_mounts.bats
  test/helpers.bash
  test/image.bats
  test/image_remove.bats
  test/image_volume.bats
  test/inspect.bats
  test/policy.json
  test/registries.conf
  test/testdata/container_config.json
  test/testdata/container_config_hostport.json
  test/testdata/container_config_logging.json
  test/testdata/container_config_resolvconf.json
  test/testdata/container_config_resolvconf_ro.json
  test/testdata/container_config_seccomp.json
  test/testdata/container_config_sleep.json
  test/testdata/container_exit_test.json
  test/testdata/container_redis.json
  test/testdata/container_redis_default_mounts.json
  test/testdata/container_redis_device.json
  test/testdata/container_redis_env_custom.json
Labels: cncf-cla: yes, size/L

#1528 runtime_status: report correct network status
  oci/oci.go
  server/runtime_status.go
Labels: cncf-cla: yes, size/M

#1524 network: Fix manage NetworkNS lifecycle
  lib/container_server.go
  lib/sandbox/sandbox.go
  pkg/annotations/annotations.go
  server/sandbox_run.go
  server/sandbox_status_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#1526 syscontainers: use --bind-mount-prefix
  contrib/system_containers/centos/config.json.template
  contrib/system_containers/centos/run.sh
  contrib/system_containers/fedora/config.json.template
  contrib/system_containers/fedora/run.sh
  contrib/system_containers/rhel/config.json.template
  contrib/system_containers/rhel/run.sh
Labels: cncf-cla: yes, size/L
