Repository cri-o/cri-o, pull requests merged in 2018-05, with the labels that each got.

#1537 Add FIPS mode secret and vendor in libpod/pkg/secret
  cmd/crio/config.go
  cmd/crio/main.go
  contrib/test/integration/build/cri-o.yml
  lib/config.go
  server/container_create.go
  test/default_mounts.bats
  test/helpers.bash
  vendor.conf
  vendor/github.com/projectatomic/libpod/pkg/secrets/secrets.go
  vendor/github.com/projectatomic/libpod/pkg/secrets/secrets_test.go
Labels: cncf-cla: yes, size/L

#1549 sandbox_run: Drop ambient capabilities for infra pod
  server/sandbox_run.go
Labels: cncf-cla: yes, size/XS

#1545 Fix handling of /dev/shm mounting inside of containers
  server/container_create.go
  server/sandbox_run.go
  test/shm.bats
  test/testdata/container_sleep.json
Labels: cncf-cla: yes, size/M

#1552 Fix handling of /dev/shm mounting inside of containers
  server/container_create.go
  server/sandbox_run.go
  test/image.bats
  test/shm.bats
  test/testdata/container_sleep.json
Labels: cncf-cla: yes, size/M

#1553 Add test to see if /dev/shm is working correctly
  test/image.bats
  test/shm.bats
  test/testdata/container_sleep.json
Labels: cncf-cla: yes, size/M

#1558 [1.9] Remove ambient capabilities
  server/container_create.go
  server/sandbox_run.go
  test/ctr.bats
Labels: cncf-cla: yes, size/M

#1542 Test for non root user capabilities
  test/ctr.bats
Labels: cncf-cla: yes, size/M

#1560 Release 1.9.12
  version/version.go
Labels: cncf-cla: yes, size/XS

#1559 Release 1.10.1
  version/version.go
Labels: cncf-cla: yes, size/XS

#1557 Updated tutorial.md
  tutorial.md
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#1564 version: v1.11.0-dev
  version/version.go
Labels: cncf-cla: yes, size/XS

#1540 [release-1.9] runtime_status: report correct network status
  oci/oci.go
  server/runtime_status.go
Labels: cncf-cla: yes, size/M

#1568 pkg: storage: provide an hint when pulling w/o registries configured
  pkg/storage/image.go
Labels: cncf-cla: yes, size/XS

#1567 server: platform specific tty handling
  server/container_exec.go
  server/container_exec_unix.go
  server/container_exec_windows.go
Labels: cncf-cla: yes, size/M

#1572 .travis.yml: install gpgme on osx
  .travis.yml
Labels: cncf-cla: yes, size/XS

#1573 Fix c compiler warning
  conmon/cmsg.c
Labels: cncf-cla: yes, size/XS

#1575 info: add information about ID mappings
  server/inspect.go
  test/ctr_userns.bats
  types/types.go
Labels: cncf-cla: yes, size/M

#1580 Add SECURITY_CONTACTS
  SECURITY_CONTACTS
Labels: cncf-cla: yes, size/S

#1581 .travis.yml: allow failures for go tip
  .travis.yml
Labels: cncf-cla: yes, size/XS

#1578 tests: enable integration tests with user namespaces
  .travis.yml
  Makefile
  server/container_create.go
  server/sandbox_run.go
  test/ctr.bats
  test/default_mounts.bats
  test/image_volume.bats
  test/pod.bats
  test/test_runner.sh
Labels: cncf-cla: yes, size/M

#1569 WIP: Fix missing ansible dependency
  contrib/test/integration/system.yml
Labels: cncf-cla: yes, size/XS
