Repository cri-o/cri-o, pull requests merged in 2019-07, with the labels that each got.

#2548 Remove unnecessary indirect dependency gopopulate
  go.mod
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2541 Discover runtimePath from $PATH environment
  cmd/crio/main.go
  lib/config/config.go
  lib/config/config_test.go
  lib/container_server.go
  oci/oci.go
  oci/oci_test.go
  server/config_test.go
  server/suite_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#2552 Remove invalid unit test to unblock master branch CI
  lib/container_server_test.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2550 Fix seccomp checks for integration tests
  .circleci/config.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2549 Remove unnecessary sudo from Makefile
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2551 Fix invalid CRIO_ROOT for integration tests
  test/helpers.bash
Labels: approved, dco-signoff: yes, lgtm, size/S

#2553 Release 1.15.0
  README.md
  contrib/test/integration/main.yml
  lib/container_server_test.go
  tutorials/setup.md
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#2558 Change default apparmor profile to actually contain the version
  docs/crio.8.md
  lib/config/config.go
  server/container_create_linux.go
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#2560 Update apparmor defaults to use them of Kubernetes
  server/container_create.go
  server/server.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/S

#2524 Search conmon executable in $PATH
  Makefile
  cmd/crio/config.go
  docs/crio.8.md
  docs/crio.conf.5.md
  lib/config/config.go
  lib/config/config_test.go
  lib/config/config_unix.go
  lib/config/config_windows.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#2559 [1.15] Change default apparmor profile to actually contain the version
  docs/crio.8.md
  lib/config/config.go
  server/container_create_linux.go
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#2561 Close temporary image in PullImage
  pkg/storage/image.go
  server/image_pull.go
  test/mocks/criostorage/criostorage.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2568 add rpm files in contrib/test/ci
  contrib/test/ci/cri-o.spec
  contrib/test/ci/crio-metrics.sysconfig
  contrib/test/ci/crio-network.sysconfig
  contrib/test/ci/crio-storage.sysconfig
  contrib/test/ci/crio.service
Labels: approved, dco-signoff: yes, lgtm, size/L

#2569 Add Dockerfile and update rpm spec for openshift e2e-aws tests
  contrib/test/ci/cri-o.spec
  hack/build-rpms.sh
  hack/lib/build/binaries.sh
  hack/lib/build/rpm.sh
  hack/lib/build/version.sh
  hack/lib/constants.sh
  hack/lib/init.sh
  hack/lib/log/output.sh
  hack/lib/log/stacktrace.sh
  hack/lib/log/system.sh
  hack/lib/util/ensure.sh
  hack/lib/util/environment.sh
  hack/lib/util/find.sh
  hack/lib/util/misc.sh
  hack/lib/util/text.sh
  hack/lib/util/trap.sh
  images/os/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#2565 Update libpod and containers/storage
  go.mod
  go.sum
  vendor/github.com/containers/libpod/libpod/container_api.go
  vendor/github.com/containers/libpod/libpod/container_attach_linux.go
  vendor/github.com/containers/libpod/libpod/container_attach_unsupported.go
  vendor/github.com/containers/libpod/libpod/image/image.go
  vendor/github.com/containers/libpod/libpod/runtime.go
  vendor/github.com/containers/libpod/libpod/runtime_ctr.go
  vendor/github.com/containers/libpod/libpod/runtime_pod_linux.go
  vendor/github.com/containers/libpod/libpod/stats.go
  vendor/github.com/containers/libpod/pkg/cgroups/cgroups.go
  vendor/github.com/containers/libpod/pkg/cgroups/cpu.go
  vendor/github.com/containers/libpod/pkg/rootless/rootless_linux.c
  vendor/github.com/containers/libpod/utils/utils.go
  vendor/github.com/containers/libpod/version/version.go
  vendor/github.com/containers/storage/VERSION
  vendor/github.com/containers/storage/drivers/quota/projectquota.go
  vendor/github.com/containers/storage/drivers/quota/projectquota_unsupported.go
  vendor/github.com/containers/storage/pkg/idtools/idtools.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#2570 Update codecov config to be less strict
  .codecov.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2571 Add short CLI flags to common configurations
  Makefile
  cmd/crio/main.go
  docs/crio.8.md
  test/command.bats
  test/helpers.bash
Labels: approved, dco-signoff: yes, lgtm, size/M

#2577 Remove unnecessary directory creation
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2576 Remove annotations in favor of libpod's
  lib/container_server.go
  lib/rename.go
  pkg/annotations/annotations.go
  server/container_create_linux.go
  server/sandbox_run_linux.go
  server/sandbox_run_test.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#2473 [1.14] Small crio wipe fix
  contrib/crio-wipe/crio-wipe.bash
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2483 Changes for the RHEL 8 distribution dependencies in the setup.md under the Tutorials folder
  tutorials/setup.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#2574 Allow building with go1.10
  cmd/crio/main.go
  internal/oci/runtime_vm.go
  tutorials/setup.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#2580 Add missing shortflags to bin2img and copyimg to fix integration tests
  test/bin2img/bin2img.go
  test/copyimg/copyimg.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#2578 Update tools make targets to be less verbose
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/S

#2585 Update codecov patch comparison to succeed
  .codecov.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2586 Add go 1.10 build to CircleCi
  .circleci/config.yml
Labels: approved, dco-signoff: yes, lgtm, size/M

#2587 conmon cgroups: don't create cgroupfs group for systemd
  internal/oci/oci_linux.go
Labels: approved, dco-signoff: yes, lgtm, needs-backport, size/S

#2581 Update git-vars target to check for executable as well
  Makefile.inc
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2589 [1.15] Update codecov config to be less strict
  .codecov.yml
Labels: approved, dco-signoff: yes, lgtm, size/S

#2583 Remove git-vars from conmon/config.h generation
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2590 [1.14] Update codecov config to be less strict
  .codecov.yml
Labels: approved, dco-signoff: yes, lgtm, size/S

#2591 [1.15] Remove git-vars from conmon/config.h generation
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2593 Fix git-vars target for shells which do not default to bash
  Makefile.inc
  conmon/Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2567 Fix AMI builds
  contrib/test/integration/build/plugins.yml
  contrib/test/integration/golang.yml
  contrib/test/integration/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/M

#2598 Do not print 'unknown' versions
  cmd/crio/main.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2594 Update docs to point to 1.15
  README.md
  internal/version/version.go
  tutorials/setup.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2596 version change from 0.7.4 to 0.8.1 released on June 6
  contrib/cni/README.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#2597 Add missing global-auth-file CLI flag
  cmd/crio/main.go
  docs/crio.8.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#2600 [1.14] run crio-wipe from /usr and add system-preset
  contrib/crio-wipe/50-crio-wipe.preset
  contrib/crio-wipe/crio-wipe.service
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, needs-forwardport, size/XS

#2572 Move server config into lib/config
  Makefile
  cmd/crio-config/config.go
  cmd/crio/config.go
  cmd/crio/main.go
  internal/lib/config/config.go
  internal/lib/config/config_test.go
  internal/lib/config/config_unix.go
  internal/lib/config/config_windows.go
  internal/lib/config/reload.go
  internal/lib/config/reload_test.go
  internal/lib/config/suite_test.go
  internal/oci/attach.go
  internal/oci/oci.go
  server/config.go
  server/config_test.go
  server/config_unix.go
  server/config_windows.go
  server/container_create_linux.go
  server/inspect.go
  server/inspect_test.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
  server/server.go
  server/server_test.go
  server/suite_test.go
  server/utils.go
  test/mocks/server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#2602 [1.15] Add release bundle target and documentation
  Makefile
  tutorials/setup.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#2603 Add release bundle target and documentation
  Makefile
  tutorials/setup.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#2599 Add missing config template values
  cmd/crio/config.go
  docs/crio.conf.5.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#2601 cgroupfs: don't leak conmon cgroups
  internal/lib/remove.go
  internal/oci/container.go
  internal/oci/oci_linux.go
  server/sandbox_remove.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#2605 [1.14] sandbox_run: Log a warning if we can't find a slice
  server/sandbox_run_linux.go
  test/helpers.bash
  test/network.bats
Labels: approved, dco-signoff: yes, size/M

#2611 [1.14] Fix 838 1.14
  lib/remove.go
  oci/container.go
  oci/oci_linux.go
  server/sandbox_remove.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#2609 [1.15] cgroupfs fixes
  lib/remove.go
  oci/container.go
  oci/oci_linux.go
  server/sandbox_remove.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#2610 Fix documentation between crio.conf.5.md and source
  cmd/crio/config.go
  cmd/crio/main.go
  docs/crio.conf.5.md
  internal/lib/config/config.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2608 [1.13] Fix integration tests for CNI update
  test/cni_plugin_helper.bash
  test/helpers.bash
  test/network.bats
Labels: approved, dco-signoff: yes, lgtm, size/M

#2615 [1.14] properly enable crio-wipe
  Makefile
  contrib/crio-wipe/50-crio-wipe.preset
  contrib/systemd/crio-wipe.service
  contrib/systemd/crio.service
  contrib/test/ci/cri-o.spec
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2616 [1.12] Fix integration tests for CNI update
  test/cni_plugin_helper.bash
  test/helpers.bash
  test/network.bats
Labels: approved, dco-signoff: yes, lgtm, size/M

#2618 Remove deprecated file-locking
  cmd/crio/config.go
  cmd/crio/main.go
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/lib/config/config.go
  internal/lib/config/config_unix.go
  internal/lib/config/config_windows.go
  internal/lib/config/testdata/config.toml
  internal/lib/container_server.go
  internal/lib/container_server_test.go
  internal/lib/suite_test.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#2622 [1.14] Return if error loading cgroup CleanupConmonCgroup
  oci/container.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2612 Fix documentation between crio.8.md and source
  docs/crio.8.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#2624 Release 1.14.9
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2595 server: support cgroupv2
  server/sandbox_run_linux.go
  utils/utils.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#2623 [1.15] Return if error loading cgroup CleanupConmonCgroup
  oci/container.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2556 Add context based logging facade and interceptors
  cmd/crio/main.go
  go.mod
  go.sum
  internal/pkg/log/interceptors.go
  internal/pkg/log/log.go
  server/container_attach.go
  server/container_create.go
  server/container_create_linux.go
  server/container_create_linux_test.go
  server/container_exec.go
  server/container_execsync.go
  server/container_list.go
  server/container_portforward.go
  server/container_remove.go
  server/container_reopen_log.go
  server/container_start.go
  server/container_stats_list.go
  server/container_status.go
  server/container_stop.go
  server/container_update_resources.go
  server/image_list.go
  server/image_pull.go
  server/image_remove.go
  server/image_status.go
  server/sandbox_list.go
  server/sandbox_network.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/sandbox_run_test.go
  server/sandbox_status.go
  server/sandbox_stop.go
  server/sandbox_stop_linux.go
  server/secrets.go
  vendor/github.com/google/uuid/go.mod
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/uuid.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/XL

#2621 Return if error loading cgroup CleanupConmonCgroup
  internal/oci/container.go
Labels: approved, dco-signoff: yes, lgtm, needs-backport, ok-to-test, size/XS

#2627 privileged: set mounts to rw
  server/container_create_linux.go
  test/ctr.bats
  test/testdata/container_config_privileged.json
Labels: approved, dco-signoff: yes, lgtm, needs-backport, size/L

#2630 [1.11] conmon: check it is a valid pid before killing it
  conmon/conmon.c
  test/helpers.bash
  test/network.bats
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, needs-forwardport, size/S

#2617 Add template and command line flags validation
  .circleci/config.yml
  Makefile
  cmd/crio/config.go
  internal/lib/config/template.go
  internal/lib/config/template_test.go
  test/docs-validation/main.go
Labels: approved, dco-signoff: yes, lgtm, size/XL

#2566 Bump cri-tools to v1.15.0
  .circleci/config.yml
  Dockerfile
  contrib/test/integration/main.yml
  test/pod.bats
Labels: approved, dco-signoff: yes, lgtm, size/S

#2629 Cgroup-hotfix in the Tutorials folder
  tutorials/setup.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#2626 Bump github.com/containers/buildah from 1.9.0 to 1.9.1
  go.mod
  go.sum
  vendor/github.com/containers/buildah/.cirrus.yml
  vendor/github.com/containers/buildah/.gitignore
  vendor/github.com/containers/buildah/.golangci.yml
  vendor/github.com/containers/buildah/.travis.yml
  vendor/github.com/containers/buildah/CONTRIBUTING.md
  vendor/github.com/containers/buildah/Makefile
  vendor/github.com/containers/buildah/add.go
  vendor/github.com/containers/buildah/bind/util.go
  vendor/github.com/containers/buildah/buildah.go
  vendor/github.com/containers/buildah/changelog.txt
  vendor/github.com/containers/buildah/chroot/run.go
  vendor/github.com/containers/buildah/chroot/util.go
  vendor/github.com/containers/buildah/docker/types.go
  vendor/github.com/containers/buildah/go.mod
  vendor/github.com/containers/buildah/go.sum
  vendor/github.com/containers/buildah/imagebuildah/build.go
  vendor/github.com/containers/buildah/imagebuildah/chroot_symlink_linux.go
  vendor/github.com/containers/buildah/imagebuildah/executor.go
  vendor/github.com/containers/buildah/imagebuildah/stage_executor.go
  vendor/github.com/containers/buildah/imagebuildah/util.go
  vendor/github.com/containers/buildah/install.md
  vendor/github.com/containers/buildah/pkg/blobcache/blobcache.go
  vendor/github.com/containers/buildah/pkg/cli/common.go
  vendor/github.com/containers/buildah/pkg/unshare/unshare.go
  vendor/github.com/containers/buildah/pull.go
  vendor/github.com/containers/buildah/run_linux.go
  vendor/github.com/containers/buildah/troubleshooting.md
  vendor/github.com/containers/buildah/util.go
  vendor/github.com/containers/buildah/util/util.go
  vendor/github.com/containers/buildah/vendor.conf
  vendor/github.com/docker/libnetwork/resolvconf/resolvconf.go
  vendor/github.com/docker/libnetwork/types/types.go
  vendor/github.com/ishidawataru/sctp/.gitignore
  vendor/github.com/ishidawataru/sctp/.travis.yml
  vendor/github.com/ishidawataru/sctp/GO_LICENSE
  vendor/github.com/ishidawataru/sctp/ipsock_linux.go
  vendor/github.com/ishidawataru/sctp/sctp.go
  vendor/github.com/ishidawataru/sctp/sctp_linux.go
  vendor/github.com/ishidawataru/sctp/sctp_unsupported.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#2631 Remove CRICTL_COMMIT from Dockerfile
  Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2634 [1.15] privileged: set mounts to rw
  server/container_create_linux.go
  test/ctr.bats
  test/testdata/container_config_privileged.json
Labels: approved, dco-signoff: yes, lgtm, size/L

#2640 [1.13] conmon: check it is a valid pid before killing it
  conmon/conmon.c
Labels: approved, dco-signoff: yes, lgtm, size/S

#2637 [1.15] conmon: check it is a valid pid before killing it
  conmon/conmon.c
Labels: approved, dco-signoff: yes, lgtm, size/S

#2646 Add CNCF article to awesome list
  awesome.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2643 Allow to override build date with SOURCE_DATE_EPOCH
  Makefile
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#2647 Pin CircleCI base image and update builds
  .circleci/config.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2648 Update crio.conf man page
  docs/crio.conf.5.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2642 [1.15] crio-wipe fixes
  Makefile
  contrib/systemd/crio-wipe.service
  contrib/systemd/crio.service
  contrib/test/ci/cri-o.spec
Labels: approved, dco-signoff: yes, lgtm, size/S

#2638 [1.14] conmon: check it is a valid pid before killing it
  conmon/conmon.c
Labels: approved, dco-signoff: yes, lgtm, size/S

#2645 Add internal log unit tests
  internal/pkg/log/interceptors.go
  internal/pkg/log/log.go
  internal/pkg/log/log_test.go
  internal/pkg/log/suite_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#2644 Add filename log hook
  cmd/crio/main.go
  internal/pkg/log/hooks.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#2636 conmon: check it is a valid pid before killing it
  conmon/conmon.c
Labels: approved, dco-signoff: yes, lgtm, size/S

#2653 Update tutorial for building from source
  tutorials/setup.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2654 [1.13] Allow default route to not be present
  Dockerfile
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, needs-backport, needs-forwardport, size/M

#2651 fix make integration
  Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2657 [1.14] Fix container image used for integration tests
  Dockerfile
  test/ctr.bats
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2656 Readme: Fix broken CRI link
  README.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#2582 Make integration tests more reliable
  test/helpers.bash
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2668 [1.13] Fix parse of memory.limit_in_bytes on 32-bit machines
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#2663 [1.14] Allow default route to not be present
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2673 [1.15] container_status: Use cached value of image name
  server/container_status.go
  server/container_status_test.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2675 [1.13] container_status: Use cached value of image name
  server/container_status.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2676 [1.14] Fix parse of memory.limit_in_bytes on 32-bit machines
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/XS

#2639 [1.13] privileged: set mounts to rw
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2666 [1.15] Make integration tests more reliable
  test/helpers.bash
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2677 [1.15] Fix parse of memory.limit_in_bytes on 32-bit machines
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#2664 [1.15] Allow default route to not be present
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2635 [1.14] privileged: set mounts to rw
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2655 [1.14] container_status: Use cached value of image name
  server/container_status.go
Labels: approved, dco-signoff: yes, lgtm, needs-forwardport, size/XS

#2679 v1.13.10
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, size/XS
