Repository cri-o/cri-o, pull requests merged in 2019-08, with the labels that each got.

#2658 [1.15] Fix container image used for integration tests
  Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2693 [1.15] Allow building with go1.10
  cmd/crio/main.go
  oci/runtime_vm.go
  tutorials/setup.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2699 [1.14] pick c/storage #401
  vendor.conf
  vendor/github.com/containers/storage/layers.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2706 Release 1.14.10
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2710 allow custom go-md2man binary
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2705 crio-wipe: Fix int compare in lib.bash
  contrib/crio-wipe/lib.bash
Labels: approved, dco-signoff: yes, lgtm, needs-backport, ok-to-test, size/XS

#2690 Use only the first IP for host port allocation
  server/sandbox_network.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1765 Improve build and runtime customization
  Makefile
  contrib/systemd/crio.service
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#2641 Crio wipe fixes
  Makefile
  contrib/systemd/crio-wipe.service
  contrib/systemd/crio.service
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2649 Add crio-status client for convenient HTTP API access
  Makefile
  README.md
  cmd/crio-status/main.go
  completions/bash/crio-status
  completions/fish/crio-status.fish
  docs/crio-status.8.md
  internal/client/client.go
  server/inspect.go
  test/helpers.bash
  test/status.bats
Labels: approved, dco-signoff: yes, lgtm, size/L

#2686 Fix documentation for IP based sandbox methods
  internal/lib/sandbox/sandbox.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2628 Add apparmor profile content output on "trace" log level
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2703 main.go: flag help message error fix
  cmd/crio/main.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#2670 Fix parse of memory.limit_in_bytes on 32-bit machines
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#2711 allow custom go-md2man binary
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2652 Make image volumes writeable by the container user
  server/container_create.go
  server/container_create_linux.go
  test/image_volume.bats
  test/testdata/container_config.json
Labels: approved, dco-signoff: yes, lgtm, size/M

#2687 Make integration tests ready for IPv6
  .circleci/config.yml
  Makefile
  contrib/cni/10-crio-bridge.conf
  test/helpers.bash
  test/inspect.bats
Labels: approved, dco-signoff: yes, lgtm, size/L

#2697 Use HTTP2MatchHeaderFieldSendSettings for incoming gRPC connections
  cmd/crio/main.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2714 Update fedora installation instructions
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2674 container_status: Use cached value of image name
  server/container_status.go
  server/container_status_test.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2681 Add missing CLI flags
  cmd/crio/main.go
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/lib/config/template.go
  test/docs-validation/main.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#2682 Remove go module disabling and stick to `-mod=vendor`
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/S

#2423 Added EnvVar to cri-o cli flags
  cmd/crio/main.go
  test/cgroups.bats
  test/ctr.bats
  test/ctr_seccomp.bats
  test/ctr_userns.bats
  test/default_mounts.bats
  test/helpers.bash
  test/image_volume.bats
  test/inspect.bats
  test/pod.bats
  test/restore.bats
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/L

#2667 Round 2 of integration test fixes
  test/apparmor.bats
  test/cgroups.bats
  test/critest.bats
  test/ctr.bats
  test/ctr_seccomp.bats
  test/ctr_userns.bats
  test/default_mounts.bats
  test/helpers.bash
  test/hooks.bats
  test/image.bats
  test/image_remove.bats
  test/image_volume.bats
  test/inspect.bats
  test/namespaces.bats
  test/network.bats
  test/pod.bats
  test/reload.bats
  test/restore.bats
  test/runtimeversion.bats
  test/selinux.bats
  test/shm.bats
  test/status.bats
Labels: approved, dco-signoff: yes, lgtm, needs-backport, size/XL

#2720 fix 32 bit builds
  go.mod
  go.sum
  vendor/github.com/containers/buildah/CHANGELOG.md
  vendor/github.com/containers/buildah/Makefile
  vendor/github.com/containers/buildah/buildah.go
  vendor/github.com/containers/buildah/changelog.txt
  vendor/github.com/containers/buildah/config.go
  vendor/github.com/containers/buildah/go.mod
  vendor/github.com/containers/buildah/go.sum
  vendor/github.com/containers/buildah/pkg/parse/parse.go
  vendor/github.com/containers/buildah/pkg/parse/parse_unix.go
  vendor/github.com/containers/buildah/pkg/parse/parse_unsupported.go
  vendor/github.com/containers/buildah/troubleshooting.md
  vendor/github.com/containers/libpod/cmd/podman/cliconfig/config.go
  vendor/github.com/containers/libpod/libpod/container.go
  vendor/github.com/containers/libpod/libpod/container_api.go
  vendor/github.com/containers/libpod/libpod/container_commit.go
  vendor/github.com/containers/libpod/libpod/container_inspect.go
  vendor/github.com/containers/libpod/libpod/container_internal.go
  vendor/github.com/containers/libpod/libpod/container_internal_linux.go
  vendor/github.com/containers/libpod/libpod/define/errors.go
  vendor/github.com/containers/libpod/libpod/define/exec_codes.go
  vendor/github.com/containers/libpod/libpod/events/config.go
  vendor/github.com/containers/libpod/libpod/events/events.go
  vendor/github.com/containers/libpod/libpod/events/events_linux.go
  vendor/github.com/containers/libpod/libpod/events/journal_linux.go
  vendor/github.com/containers/libpod/libpod/events/logfile.go
  vendor/github.com/containers/libpod/libpod/events/nullout.go
  vendor/github.com/containers/libpod/libpod/image/image.go
  vendor/github.com/containers/libpod/libpod/image/search.go
  vendor/github.com/containers/libpod/libpod/info.go
  vendor/github.com/containers/libpod/libpod/kube.go
  vendor/github.com/containers/libpod/libpod/oci.go
  vendor/github.com/containers/libpod/libpod/oci_attach_linux.go
  vendor/github.com/containers/libpod/libpod/oci_internal_linux.go
  vendor/github.com/containers/libpod/libpod/options.go
  vendor/github.com/containers/libpod/libpod/runtime.go
  vendor/github.com/containers/libpod/libpod/runtime_ctr.go
  vendor/github.com/containers/libpod/libpod/runtime_img.go
  vendor/github.com/containers/libpod/libpod/runtime_volume.go
  vendor/github.com/containers/libpod/libpod/stats.go
  vendor/github.com/containers/libpod/pkg/ctime/ctime_linux.go
  vendor/github.com/containers/libpod/pkg/hooks/hooks.go
  vendor/github.com/containers/libpod/pkg/hooks/monitor.go
  vendor/github.com/containers/libpod/pkg/hooks/read.go
  vendor/github.com/containers/libpod/pkg/namespaces/namespaces.go
  vendor/github.com/containers/libpod/pkg/spec/createconfig.go
  vendor/github.com/containers/libpod/pkg/spec/spec.go
  vendor/github.com/containers/libpod/pkg/spec/storage.go
  vendor/github.com/containers/libpod/pkg/util/utils.go
  vendor/github.com/containers/libpod/pkg/util/utils_linux.go
  vendor/github.com/containers/libpod/pkg/util/utils_supported.go
  vendor/github.com/containers/libpod/pkg/util/utils_windows.go
  vendor/github.com/containers/libpod/version/version.go
  vendor/github.com/containers/storage/VERSION
  vendor/github.com/containers/storage/drivers/btrfs/btrfs.go
  vendor/github.com/containers/storage/drivers/windows/windows.go
  vendor/github.com/vishvananda/netns/README.md
  vendor/github.com/vishvananda/netns/netns_linux.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#2743 set kube_ssh_user for e2e tests
  contrib/test/integration/e2e-base.yml
  contrib/test/integration/e2e.yml
  contrib/test/integration/vars.yml
Labels: dco-signoff: yes, lgtm, size/S

#2751 Allow usage of short container ID in ContainerStats()
  server/container_stats.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS
