Repository cri-o/cri-o, pull requests merged in 2019-09, with the labels that each got.

#2762 Makefile: Fixed go build command
  Makefile
Labels: approved, dco-signoff: yes, ok-to-test, size/XS

#2765 [1.14] Download kubetest manually
  contrib/test/integration/build/kubernetes.yml
  contrib/test/integration/build/kubetest.yml
  contrib/test/integration/e2e-features.yml
  contrib/test/integration/e2e.yml
  contrib/test/integration/golang.yml
  contrib/test/integration/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/M

#2758 [1.15] download kubetest manually
  contrib/test/integration/build/kubernetes.yml
  contrib/test/integration/build/kubetest.yml
  contrib/test/integration/e2e-features.yml
  contrib/test/integration/e2e.yml
  contrib/test/integration/golang.yml
  contrib/test/integration/main.yml
Labels: approved, dco-signoff: yes, size/M

#2759 download kubetest manually
  contrib/cni/10-crio-bridge.conf
  contrib/test/integration/build/kubernetes.yml
  contrib/test/integration/build/kubetest.yml
  contrib/test/integration/e2e-features.yml
  contrib/test/integration/e2e.yml
  contrib/test/integration/golang.yml
  contrib/test/integration/main.yml
Labels: approved, dco-signoff: yes, release-1.16, size/M

#2772 [1.15] e2e: clean kubernetes before making
  cmd/crio/main.go
  contrib/test/integration/build/kubernetes.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2780 Version 1.15.2
  version/version.go
Labels: approved, dco-signoff: yes, size/XS

#2753 Add `log_dir`/`--log-dir` validation to be absolute
  internal/lib/config/config.go
  internal/lib/config/config_test.go
  server/suite_test.go
Labels: approved, dco-signoff: yes, lgtm, release-1.16, size/S

#2749 Add config `runtime_type` validation
  internal/lib/config/config.go
  internal/lib/config/config_test.go
  internal/oci/oci.go
  internal/oci/runtime_vm.go
Labels: approved, dco-signoff: yes, lgtm, release-1.16, size/L

#2717 Add HUP reload feature for SystemRegistries
  cmd/crio/main.go
  docs/crio.conf.5.md
  server/server.go
  server/server_test.go
  server/suite_test.go
  test/helpers.bash
  test/reload_config.bats
  test/reload_system.bats
Labels: approved, dco-signoff: yes, lgtm, release-1.16, size/L

#2662 Allow default route to not be present
  server/server.go
  server/utils.go
Labels: approved, dco-signoff: yes, lgtm, needs-backport, size/M

#2784 fix selinux label on volume mount directory creation
  server/container_create.go
Labels: approved, dco-signoff: yes, lgtm, needs-backport, release-1.16, size/XS

#2766 use GOPROXY to speed up dependency management
  Makefile
  go.mod
  go.sum
  vendor/github.com/OpenPeeDeeP/depguard/README.md
  vendor/github.com/OpenPeeDeeP/depguard/depguard.go
  vendor/github.com/OpenPeeDeeP/depguard/rootchecker.go
  vendor/github.com/golangci/go-tools/lint/lint.go
  vendor/github.com/golangci/go-tools/stylecheck/lint.go
  vendor/github.com/golangci/golangci-lint/pkg/commands/completion.go
  vendor/github.com/golangci/golangci-lint/pkg/commands/executor.go
  vendor/github.com/golangci/golangci-lint/pkg/commands/run.go
  vendor/github.com/golangci/golangci-lint/pkg/config/config.go
  vendor/github.com/golangci/golangci-lint/pkg/fsutils/filecache.go
  vendor/github.com/golangci/golangci-lint/pkg/fsutils/linecache.go
  vendor/github.com/golangci/golangci-lint/pkg/golinters/depguard.go
  vendor/github.com/golangci/golangci-lint/pkg/golinters/funlen.go
  vendor/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/linter.go
  vendor/github.com/golangci/golangci-lint/pkg/golinters/gochecknoglobals.go
  vendor/github.com/golangci/golangci-lint/pkg/golinters/megacheck.go
  vendor/github.com/golangci/golangci-lint/pkg/golinters/misspell.go
  vendor/github.com/golangci/golangci-lint/pkg/lint/linter/context.go
  vendor/github.com/golangci/golangci-lint/pkg/lint/lintersdb/manager.go
  vendor/github.com/golangci/golangci-lint/pkg/lint/load.go
  vendor/github.com/golangci/golangci-lint/pkg/lint/runner.go
  vendor/github.com/golangci/golangci-lint/pkg/printers/junitxml.go
  vendor/github.com/timakin/bodyclose/passes/bodyclose/bodyclose.go
  vendor/github.com/ultraware/funlen/LICENSE
  vendor/github.com/ultraware/funlen/README.md
  vendor/github.com/ultraware/funlen/main.go
  vendor/golang.org/x/tools/go/analysis/analysis.go
  vendor/golang.org/x/tools/go/analysis/diagnostic.go
  vendor/golang.org/x/tools/go/analysis/diagnostic_experimental.go
  vendor/golang.org/x/tools/go/analysis/passes/cgocall/cgocall.go
  vendor/golang.org/x/tools/go/analysis/passes/ctrlflow/ctrlflow.go
  vendor/golang.org/x/tools/go/analysis/passes/printf/printf.go
  vendor/golang.org/x/tools/go/analysis/passes/printf/types.go
  vendor/golang.org/x/tools/go/analysis/passes/structtag/structtag.go
  vendor/golang.org/x/tools/go/analysis/validate.go
  vendor/golang.org/x/tools/go/cfg/builder.go
  vendor/golang.org/x/tools/go/internal/gcimporter/bimport.go
  vendor/golang.org/x/tools/go/internal/packagesdriver/sizes.go
  vendor/golang.org/x/tools/go/loader/loader.go
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/golang.org/x/tools/internal/imports/sortimports.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-1.16, size/XXL

#2791 Add additional documentation to runtime configurations
  internal/lib/config/template.go
Labels: approved, dco-signoff: yes, lgtm, release-1.16, size/M

#2728 Remove unnecessary store nil unit test
  internal/lib/container_server_test.go
Labels: approved, dco-signoff: yes, lgtm, release-1.16, size/S

#2738 Check inotify events read return code
  conmon/conmon.c
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#2807 Fallback to 127.0.0.1 if host IP is unavailable
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2811 Vendor in updated c/storage cri-o-release-1.14 branch
  vendor.conf
  vendor/github.com/containers/storage/layers.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#2816 Vendor c/storage v1.13.3
  go.mod
  go.sum
  vendor/github.com/containers/storage/Makefile
  vendor/github.com/containers/storage/VERSION
  vendor/github.com/containers/storage/images.go
  vendor/github.com/containers/storage/layers.go
  vendor/github.com/containers/storage/store.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#2815 [1.15] Vendor c/storage v1.13.3
  go.mod
  go.sum
  vendor/github.com/containers/storage/Makefile
  vendor/github.com/containers/storage/VERSION
  vendor/github.com/containers/storage/images.go
  vendor/github.com/containers/storage/layers.go
  vendor/github.com/containers/storage/store.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#2814 makeRepoDigests(): add all manifest digests to RepoDigests
  internal/pkg/storage/image.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2822 Vendor c/image cri-o-release-1.14
  vendor.conf
  vendor/github.com/containers/image/docker/docker_client.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2436 Move conmon to remote repo
  .circleci/config.yml
  .golangci.yml
  CONTRIBUTING.md
  Dockerfile
  Makefile
  cmd/crio-config/config.go
  conmon/Makefile
  conmon/cmsg.c
  conmon/cmsg.h
  conmon/conmon.c
  conmon/ctr_logging.c
  conmon/ctr_logging.h
  conmon/utils.c
  conmon/utils.h
  contrib/test/integration/build/conmon.yml
  contrib/test/integration/main.yml
  go.mod
  go.sum
  internal/lib/config/config.go
  internal/oci/attach.go
  nix/default.nix
  test/command.bats
  test/helpers.bash
  test/network.bats
  tutorials/setup.md
  vendor/github.com/containers/conmon/LICENSE
  vendor/github.com/containers/conmon/runner/config/config.go
  vendor/github.com/containers/conmon/runner/config/config_unix.go
  vendor/github.com/containers/conmon/runner/config/config_windows.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-1.16, size/XXL

#2825 [1.16] e2e: turn on force_clone for kubetest
  contrib/test/integration/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2800 Update vendor code for cni and ocicni and libpod
  server/sandbox_network.go
  server/utils.go
  test/cni_plugin_helper.bash
  test/testdata/labeled_container_redis.json
  vendor.conf
  vendor/github.com/containernetworking/cni/README.md
  vendor/github.com/containernetworking/cni/libcni/api.go
  vendor/github.com/containernetworking/cni/libcni/conf.go
  vendor/github.com/containernetworking/cni/pkg/invoke/args.go
  vendor/github.com/containernetworking/cni/pkg/invoke/delegate.go
  vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go
  vendor/github.com/containernetworking/cni/pkg/types/args.go
  vendor/github.com/containernetworking/cni/pkg/types/types.go
  vendor/github.com/containernetworking/cni/pkg/utils/utils.go
  vendor/github.com/containers/libpod/libpod/image/image.go
  vendor/github.com/containers/libpod/libpod/networking_linux.go
  vendor/github.com/containers/libpod/vendor.conf
  vendor/github.com/cri-o/ocicni/go.mod
  vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/types.go
  vendor/github.com/cri-o/ocicni/vendor.conf
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#2824 [1.16] use containers/conmon
  .circleci/config.yml
  .golangci.yml
  CONTRIBUTING.md
  Dockerfile
  Makefile
  cmd/crio-config/config.go
  conmon/Makefile
  conmon/cmsg.c
  conmon/cmsg.h
  conmon/conmon.c
  conmon/ctr_logging.c
  conmon/ctr_logging.h
  conmon/utils.c
  conmon/utils.h
  contrib/test/integration/build/conmon.yml
  contrib/test/integration/main.yml
  go.mod
  go.sum
  internal/lib/config/config.go
  internal/oci/attach.go
  nix/default.nix
  test/command.bats
  test/helpers.bash
  test/network.bats
  tutorials/setup.md
  vendor/github.com/containers/conmon/LICENSE
  vendor/github.com/containers/conmon/runner/config/config.go
  vendor/github.com/containers/conmon/runner/config/config_unix.go
  vendor/github.com/containers/conmon/runner/config/config_windows.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#2834 Burst for bandwidth can be only 4GB
  server/utils.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#2835 Add shell completion support
  Makefile
  bundle/Makefile
  bundle/build
  cmd/crio-status/main.go
  cmd/crio/main.go
  completions/bash/crio
  completions/bash/crio-status
  completions/fish/crio-status.fish
  completions/fish/crio.fish
  completions/zsh/_crio
  completions/zsh/_crio-status
  docs/crio-status.8.md
  docs/crio.8.md
  internal/pkg/completion/completion.go
Labels: approved, dco-signoff: yes, lgtm, size/XL

#2808 Add metrics to configuration file
  cmd/crio/main.go
  docs/crio.conf.5.md
  internal/lib/config/config.go
  internal/lib/config/template.go
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#2831 [1.14] e2e: turn on force_clone for kubetest
  Makefile
  contrib/test/integration/main.yml
  hack/install-golangci-lint.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#2844 missing 'https://' in the clone from the conmon setup part
  tutorials/setup.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#2838 Generate crio-status man page during build
  .circleci/config.yml
  Makefile
  cmd/crio-status/main.go
  completions/bash/crio-status
  completions/fish/crio-status.fish
  completions/zsh/_crio-status
  docs/crio-status.8.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#2856 [1.14] e2e: regenerate api before making k8s
  contrib/test/integration/build/kubernetes.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2857 [1.13] e2e: regenerate api before making k8s
  contrib/test/integration/build/kubernetes.yml
  contrib/test/integration/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/S

#2854 [1.14] sandbox_remove: Ensure that the pod infra container exit file is removed
  server/sandbox_remove.go
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#2855 [1.13] sandbox_remove: Ensure that the pod infra container exit file is removed
  server/sandbox_remove.go
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#2862 [1.16] Move e2e tests to k8s release-1.16 branch
  contrib/test/integration/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2860 [1.16] Remove pod infra exit file
  server/sandbox_remove.go
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/M
