Repository cri-o/cri-o, pull requests merged in 2019-04, with the labels that each got.

#2192 [1.10] Pick up correct gid
  server/container_create.go
  test/ctr.bats
  test/testdata/container_redis_user.json
Labels: cncf-cla: yes, lgtm, size/L

#2199 Remove timeout flag from kubernetes.yml
  contrib/test/integration/build/kubernetes.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2203 test: Increase number of inotify user watches
  contrib/test/integration/e2e.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2181 config: export manage_network_ns_lifecycle
  cmd/crio/config.go
  contrib/test/integration/build/cri-o.yml
  contrib/test/integration/vars.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2204 readme: Update support matrix for 1.14
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2202 Fix parallel make build failure
  Makefile
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#2220 Tagging v1.11.13
  version/version.go
Labels: lgtm, size/XS

#2223 test: Fix oom test
  test/ctr.bats
Labels: approved, lgtm, size/XS

#2215 rootless: fix rootless mode
  oci/oci_linux.go
  oci/runtime_oci.go
  utils/utils.go
Labels: approved, lgtm, size/M

#2216 conmon: do not leak fd when creating oom file
  conmon/conmon.c
Labels: approved, lgtm, size/XS

#2201 Fix parallel make build failure
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2226 utils: add license headers for pulled files
  utils/errdefs/errors.go
  utils/errdefs/grpc.go
  utils/fifo/fifo.go
  utils/fifo/handle.go
  utils/io/container_io.go
  utils/io/exec_io.go
  utils/io/helpers.go
  utils/io/logger.go
  utils/ioutil/read_closer.go
  utils/ioutil/write_closer.go
  utils/ioutil/writer_group.go
  utils/typeurl/types.go
Labels: approved, lgtm, ok-to-test, size/L

#2225 Refactor: use idtools.ParseIDMap instead of bundling own version
  server/server.go
Labels: approved, lgtm, ok-to-test, size/M

#2197 userns: drop intermediate mount namespace
  lib/sandbox/sandbox.go
  lib/sandbox/sandbox_test.go
  oci/container.go
  oci/container_test.go
  server/container_create_linux.go
  server/sandbox_run.go
  server/sandbox_run_linux.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2222 netns can be nil which can cause a segfault
  lib/sandbox/sandbox_linux.go
Labels: approved, lgtm, size/XS

#2227 test: Switch to go 1.12.2
  contrib/test/integration/main.yml
Labels: approved, size/XS

#2228 travis: Switch to go 1.12.x
  .travis.yml
Labels: approved, lgtm, size/S

#2238 [1.13] Revert containers/storage to older version
  .travis.yml
  vendor.conf
  vendor/github.com/containers/storage/containers.go
  vendor/github.com/containers/storage/containers_ffjson.go
  vendor/github.com/containers/storage/drivers/overlay/overlay.go
  vendor/github.com/containers/storage/errors.go
  vendor/github.com/containers/storage/images.go
  vendor/github.com/containers/storage/layers.go
  vendor/github.com/containers/storage/layers_ffjson.go
  vendor/github.com/containers/storage/lockfile.go
  vendor/github.com/containers/storage/lockfile_unix.go
  vendor/github.com/containers/storage/lockfile_windows.go
  vendor/github.com/containers/storage/pkg/archive/archive_ffjson.go
  vendor/github.com/containers/storage/store.go
  version/version.go
Labels: approved, size/XL

#2237 Add config interface nil check
  lib/container_server.go
  lib/container_server_test.go
Labels: approved, lgtm, size/S

#2240 Add stylecheck, unused and gosimple linters
  .golangci.yml
Labels: approved, lgtm, size/XS

#2249 Re-sync github.com/containers/image
  vendor/github.com/containers/image/copy/copy.go
  vendor/github.com/containers/image/docker/docker_client.go
  vendor/github.com/containers/image/docker/docker_image.go
  vendor/github.com/containers/image/docker/docker_image_dest.go
  vendor/github.com/containers/image/docker/docker_image_src.go
  vendor/github.com/containers/image/docker/tarfile/src.go
  vendor/github.com/containers/image/ostree/ostree_src.go
  vendor/github.com/containers/image/pkg/sysregistriesv2/system_registries_v2.go
  vendor/github.com/containers/image/storage/storage_image.go
  vendor/github.com/containers/image/storage/storage_reference.go
  vendor/github.com/containers/image/storage/storage_transport.go
  vendor/github.com/containers/image/version/version.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#2242 [1.11] Oom backport
  conmon/conmon.c
Labels: approved, lgtm, size/S

#2244 [1.13] Various oom backports
  conmon/conmon.c
Labels: lgtm, size/M

#2245 [1.14] various oom backports
  conmon/conmon.c
Labels: approved, lgtm, size/S

#2230 Use libpod registrar instead of pkg/registrar
  lib/container.go
  lib/container_server.go
  pkg/registrar/registrar.go
  pkg/registrar/registrar_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#2243 [1.12] Various oom backports
  conmon/conmon.c
Labels: approved, dco-signoff: yes, lgtm, size/M

#2241 conmon: use sd_journal_sendv
  conmon/conmon.c
  conmon/ctr_logging.c
Labels: approved, dco-signoff: yes, lgtm, size/M

#2200 Do not crash when netns is not set up
  lib/sandbox/sandbox_linux.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#2251 Fix travis build
  go.mod
  go.sum
  vendor/github.com/docker/distribution/.gitignore
  vendor/github.com/docker/distribution/.gometalinter.json
  vendor/github.com/docker/distribution/.mailmap
  vendor/github.com/docker/distribution/.travis.yml
  vendor/github.com/docker/distribution/AUTHORS
  vendor/github.com/docker/distribution/BUILDING.md
  vendor/github.com/docker/distribution/CHANGELOG.md
  vendor/github.com/docker/distribution/CONTRIBUTING.md
  vendor/github.com/docker/distribution/Dockerfile
  vendor/github.com/docker/distribution/MAINTAINERS
  vendor/github.com/docker/distribution/Makefile
  vendor/github.com/docker/distribution/RELEASE-CHECKLIST.md
  vendor/github.com/docker/distribution/blobs.go
  vendor/github.com/docker/distribution/circle.yml
  vendor/github.com/docker/distribution/coverpkg.sh
  vendor/github.com/docker/distribution/errors.go
  vendor/github.com/docker/distribution/metrics/prometheus.go
  vendor/github.com/docker/distribution/registry.go
  vendor/github.com/docker/distribution/registry/api/errcode/handler.go
  vendor/github.com/docker/distribution/registry/api/v2/routes.go
  vendor/github.com/docker/distribution/registry/client/auth/challenge/authchallenge.go
  vendor/github.com/docker/distribution/registry/client/repository.go
  vendor/github.com/docker/distribution/registry/client/transport/http_reader.go
  vendor/github.com/docker/distribution/registry/storage/cache/cachedblobdescriptorstore.go
  vendor/github.com/docker/distribution/vendor.conf
  vendor/github.com/docker/go-metrics/CONTRIBUTING.md
  vendor/github.com/docker/go-metrics/LICENSE
  vendor/github.com/docker/go-metrics/LICENSE.docs
  vendor/github.com/docker/go-metrics/NOTICE
  vendor/github.com/docker/go-metrics/README.md
  vendor/github.com/docker/go-metrics/counter.go
  vendor/github.com/docker/go-metrics/docs.go
  vendor/github.com/docker/go-metrics/gauge.go
  vendor/github.com/docker/go-metrics/handler.go
  vendor/github.com/docker/go-metrics/helpers.go
  vendor/github.com/docker/go-metrics/namespace.go
  vendor/github.com/docker/go-metrics/register.go
  vendor/github.com/docker/go-metrics/timer.go
  vendor/github.com/docker/go-metrics/unit.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#2232 [1.14] netns can be nil which can cause a segfault
  lib/sandbox/sandbox_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2175 Add RuntimeHandler.RuntimeRoot
  cmd/crio/config.go
  cmd/crio/main.go
  lib/config.go
  oci/oci.go
  oci/oci_linux.go
  oci/oci_test.go
  oci/runtime_oci.go
  test/helpers.bash
Labels: approved, dco-signoff: yes, lgtm, size/M

#2253 [1.14] Do not crash when netns is not set up
  lib/sandbox/sandbox_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2252 Fix Makefile targets for sudo
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2257 fix broken link to policy.json(5) in readme
  README.md
Labels: dco-signoff: yes, needs-ok-to-test, size/XS

#2262 runtime: fix a regression introduced by 296d80b6ac61b427583e1cfe06e74da73e7e875b
  oci/runtime_oci.go
  test/ctr_userns.bats
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2254 tests: added metrics test to ctr.bats and command.bats
  test/command.bats
  test/ctr.bats
  test/helpers.bash
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/L

#2231 Move ContainerAttachSocketDir/containerExitsDir to lib
  cmd/crio-config/config.go
  lib/config.go
  lib/config_unix.go
  lib/config_windows.go
  oci/oci_unix.go
  oci/oci_windows.go
  oci/runtime_oci.go
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#2263 [1.13] Add min memory limit check to sandbox_run_linux.go
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2096 Allow containers/storage to manage SELinux labels
  Dockerfile
  contrib/test/integration/main.yml
  pkg/storage/runtime.go
  pkg/storage/runtime_test.go
  server/container_create_linux.go
  server/sandbox_run.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
  test/ctr.bats
  test/ctr_seccomp.bats
  test/image_volume.bats
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/L

#2260 Remove unnecessary nolints
  lib/kill.go
  lib/sandbox/suite_test.go
  lib/suite_test.go
  lib/wait.go
  oci/suite_test.go
  pkg/findprocess/findprocess_test.go
  pkg/seccomp/seccomp_test.go
  pkg/storage/suite_test.go
  utils/suite_test.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2264 Tag v1.13.6
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2259 Fix travis badge URL
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2269 Add nil check for image status size
  server/image_status.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2266 Add min memory limit check to sandbox_run_linux.go
  server/sandbox_run_linux.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/M

#2224 Documentation fixes
  README.md
  contrib/cni/README.md
  releases/README.md
  tutorial.md
  tutorials/crictl.md
  tutorials/kubeadm.md
  tutorials/kubernetes.md
  tutorials/setup.md
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#2268 Add infra container check for pod sandbox
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2127 Update error handling paths for sandbox add and removal
  lib/container_server.go
  lib/container_server_linux.go
  lib/container_server_test.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/secrets.go
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#2265 [1.14] Add min memory limit check to sandbox_run_linux.go
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2272 Fix coverity scan problem
  conmon/conmon.c
Labels: approved, conmon, dco-signoff: yes, lgtm, size/XS

#2278 Remove ostree dependency
  .travis.yml
  Dockerfile
  Makefile
  contrib/test/integration/system.yml
  hack/ostree_tag.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#2277 Remove gofmt Makefile target
  Makefile
  contrib/test/integration/golang.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2182 [1.9] Fix possible out of bounds access during log parsing
  oci/oci.go
Labels: size/XS

#2258 Add default text to flags
  cmd/crio/main.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#2279 Fix testunit-bin Makefile target
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2191 Update bats tests to run in parallel
  Dockerfile
  contrib/test/integration/build/parallel.yml
  contrib/test/integration/build/plugins.yml
  contrib/test/integration/main.yml
  test/cni_plugin_helper.bash
  test/ctr_seccomp.bats
  test/helpers.bash
  test/hooks.bats
  test/hooks/checkhook.sh
  test/network.bats
  test/restore.bats
  test/test_runner.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#2274 Vendor update for runtime-tools
  go.mod
  go.sum
  vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
  vendor/github.com/opencontainers/runtime-tools/generate/config.go
  vendor/github.com/opencontainers/runtime-tools/generate/generate.go
  vendor/github.com/opencontainers/runtime-tools/validate/validate_linux.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#2283 Remove `go build -i` flag
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/S

#2282 Add openpgp_tag.sh as fallback if no gpgme is available
  Makefile
  hack/openpgp_tag.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2284 Update PluginDir to be created if not existing
  lib/config.go
  lib/config_test.go
  server/config_test.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2276 round 2 of documentation fixes
  tutorials/setup.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#2281 Update unit tests to use empty CNI hooks dir per default
  lib/container_server_test.go
  lib/suite_test.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2286 Add unit test inject files
  Makefile
  lib/container_server.go
  lib/container_server_test_inject.go
  oci/container.go
  oci/container_test_inject.go
  server/server_test_inject.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#2289 [1.13] Fix integration tests for missing cni_plugin_helper.bash
  test/test_runner.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2292 [1.13] Vendor in containers/storage release-1.13
  vendor.conf
  vendor/github.com/containers/storage/drivers/overlay/overlay.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#2290 Add server config interface
  Makefile
  server/config.go
  server/server.go
  test/mocks/server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#2270 Add static crio binary build for x86-64 (glibc and musl)
  .gitignore
  .travis.yml
  Dockerfile-nix
  Makefile
  nix/default.nix
  nix/derivation.nix
  nix/nixpkgs.nix
  test/command.bats
  test/helpers.bash
Labels: approved, dco-signoff: yes, lgtm, size/L

#2287 Vendor containers/storage v1.12.4
  CONTRIBUTING.md
  go.mod
  go.sum
  test/mocks/containerstorage/containerstorage.go
  vendor/github.com/containers/storage/VERSION
  vendor/github.com/containers/storage/containers_ffjson.go
  vendor/github.com/containers/storage/drivers/copy/copy_linux.go
  vendor/github.com/containers/storage/drivers/copy/copy_unsupported.go
  vendor/github.com/containers/storage/drivers/devmapper/device_setup.go
  vendor/github.com/containers/storage/drivers/overlay/overlay.go
  vendor/github.com/containers/storage/images_ffjson.go
  vendor/github.com/containers/storage/lockfile.go
  vendor/github.com/containers/storage/lockfile_unix.go
  vendor/github.com/containers/storage/lockfile_windows.go
  vendor/github.com/containers/storage/pkg/idtools/parser.go
  vendor/github.com/containers/storage/store.go
  vendor/github.com/containers/storage/utils.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#2288 Add documentation about static builds
  README.md
  tutorials/setup.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#2300 Fix hack/openpgp_tag.sh on older distributions
  hack/openpgp_tag.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2198 Improve LogDir configuration
  cmd/crio/config.go
  cmd/crio/main.go
  docs/crio.8.md
  docs/crio.conf.5.md
  lib/config.go
  lib/config_test.go
  server/config.go
  server/config_test.go
  test/helpers.bash
Labels: approved, dco-signoff: yes, lgtm, size/L

#2298 [1.12] Fix integration tests
  test/test_runner.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2302 [1.13] Containers run as a USER should have UID in /etc/passwd
  server/container_create.go
  server/container_create_linux.go
  utils/utils.go
  vendor/github.com/containers/libpod/pkg/lookup/lookup.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#2301 [1.14] Fix `make vendor` on travis and integration tests
  test/test_runner.sh
  vendor/github.com/fsouza/go-dockerclient/go.mod
  vendor/github.com/lithammer/dedent/go.mod
  vendor/github.com/onsi/gomega/go.mod
  vendor/golang.org/x/sys/go.mod
  vendor/golang.org/x/text/go.mod
  vendor/gopkg.in/yaml.v2/go.mod
Labels: approved, dco-signoff: yes, lgtm, size/M

#2305 Add CircleCI support
  .circleci/config.yml
  Dockerfile-circleci
  Makefile
  lib/sandbox/suite_test.go
  lib/suite_test.go
  oci/suite_test.go
  pkg/findprocess/findprocess_test.go
  pkg/seccomp/seccomp_test.go
  pkg/storage/suite_test.go
  test/framework/framework.go
  test/test_runner.sh
  utils/suite_test.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#2297 [1.11] Fix integration tests
  test/test_runner.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2293 Add server test suite and initial cases
  Makefile
  server/container_attach.go
  server/container_exec.go
  server/container_portforward.go
  server/server.go
  server/server_test.go
  server/server_test_inject.go
  server/suite_test.go
  test/mocks/containers/image/types.go
  test/mocks/criostorage/criostorage.go
  test/mocks/ocicni/types.go
  test/testdata/cert.pem
  test/testdata/key.pem
  vendor/github.com/onsi/ginkgo/extensions/table/table.go
  vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#2307 [1.13] sandbox_run: Log a warning if we can't find a slice
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2285 [1.13] Fix logic of server.restore()
  lib/container_server.go
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, needs-forwardport, size/M

#2310 Migrate server config test to ginkgo
  server/config_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#2311 [1.13] Vendor containers/storage
  vendor/github.com/containers/storage/drivers/overlay/overlay.go
Labels: approved, dco-signoff: yes, lgtm, needs-forwardport, size/S

#2312 Release v1.13.7
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, size/XS
