Repository cri-o/cri-o, pull requests merged in 2019-12, with the labels that each got.

#3009 version 1.13.11
  version/version.go
Labels: dco-signoff: yes, size/XS

#3012 Fix CLI double default prints
  completions/fish/crio.fish
  docs/crio.8.md
  internal/pkg/criocli/criocli.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3005 Update dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/.travis.yml
  vendor/google.golang.org/grpc/backoff.go
  vendor/google.golang.org/grpc/backoff/backoff.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer_conn_wrappers.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/credentials.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/encoding/encoding.go
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/go.sum
  vendor/google.golang.org/grpc/grpclog/grpclog.go
  vendor/google.golang.org/grpc/internal/backoff/backoff.go
  vendor/google.golang.org/grpc/internal/binarylog/binarylog.go
  vendor/google.golang.org/grpc/internal/binarylog/env_config.go
  vendor/google.golang.org/grpc/internal/binarylog/sink.go
  vendor/google.golang.org/grpc/internal/buffer/unbounded.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/internal/resolver/passthrough/passthrough.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_conn_wrapper.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/serviceconfig/serviceconfig.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#3017 Vendor Kubernetes 1.17.0-rc.2
  go.mod
  go.sum
  vendor/k8s.io/client-go/tools/cache/mutation_detector.go
  vendor/k8s.io/component-base/metrics/metric.go
  vendor/k8s.io/component-base/metrics/registry.go
  vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#3019 [1.16] Use vendored go modules when running unit tests
  Makefile
  internal/lib/sandbox/sandbox_test.go
  pkg/config/suite_test.go
  server/sandbox_run_test.go
  server/secrets_test.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3016 add default hooks dir to crio.conf
  completions/fish/crio.fish
  docs/crio.8.md
  pkg/config/config.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3024 Fix unit tests for master branch
  pkg/config/config_test.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3018 [1.16] Deflake network integration tests
  test/network.bats
  test/network_ping.bats
Labels: approved, dco-signoff: yes, lgtm, size/M

#3001 [1.16]: Add disk usage for ListContainerStats
  server/container_stats.go
  server/container_stats_list.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#2997 [1.16] add rw mount of cgroup
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3015 [1.16] add default hooks dir to crio.conf
  completions/fish/crio.fish
  pkg/config/config.go
  pkg/config/config_test.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2998 add rw mount of cgroup
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3025 Add network setup metrics
  server/sandbox_network.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3028 Vendor kubernetes v1.17.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/M

#3036 add error to reservation printed error
  internal/lib/container_server.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3035 [1.16] add error to reservation printed error
  internal/lib/container_server.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3037 [1.16] Update conmon to v2.0.5
  .circleci/config.yml
  Dockerfile
  Makefile
  contrib/test/integration/build/conmon.yml
  go.mod
  go.sum
  scripts/build-test-image
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, needs-forwardport, size/S

#3029 Add metrics documentation
  README.md
  tutorials/metrics.md
Labels: approved, dco-signoff: yes, release-1.17, size/M

#3042 [1.16] add conmonmon
  go.mod
  go.sum
  internal/lib/conmonmon.go
  internal/lib/container_server.go
  internal/oci/oci.go
  internal/oci/runtime_oci.go
  server/container_create.go
  server/container_remove.go
  server/container_start.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/server.go
  test/conmonmon.bats
  vendor/github.com/containers/psgo/README.md
  vendor/github.com/containers/psgo/internal/process/process.go
  vendor/github.com/containers/psgo/psgo.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/XL

#3041 [1.16] Persist exit status
  internal/lib/container_server.go
  internal/lib/wait.go
  internal/oci/container.go
  internal/oci/memory_store_test.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_vm.go
  server/container_status.go
  server/container_status_test.go
  utils/utils.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3022 add conmonmon
  go.mod
  go.sum
  internal/lib/conmonmon.go
  internal/lib/container_server.go
  internal/oci/oci.go
  internal/oci/runtime_oci.go
  server/container_create.go
  server/container_remove.go
  server/container_start.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/server.go
  test/conmonmon.bats
  vendor/github.com/containers/psgo/README.md
  vendor/github.com/containers/psgo/internal/process/process.go
  vendor/github.com/containers/psgo/psgo.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/XL

#3046 [1.16] fix concurrent merge compile error
  internal/oci/runtime_oci.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3027 Fix make will always rebuild issue.
  Makefile
  Makefile.inc
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#3049 Release v1.16.2
  internal/version/version.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3031 [1.16] bump containers storage to 1.13.6
  go.mod
  go.sum
  vendor/github.com/containers/storage/VERSION
  vendor/github.com/containers/storage/pkg/tarlog/tarlogger.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/S

#3043 bump conmon to 2.0.8
  .circleci/config.yml
  contrib/test/integration/build/conmon.yml
  go.mod
  go.sum
  scripts/build-test-image
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/XL

#3039 bump c/storage to 1.15.3
  go.mod
  go.sum
  vendor/github.com/containers/storage/VERSION
  vendor/github.com/containers/storage/drivers/overlay/overlay.go
  vendor/github.com/containers/storage/layers.go
  vendor/github.com/containers/storage/pkg/tarlog/tarlogger.go
  vendor/github.com/containers/storage/store.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/M

#3051 updating vendor packages
  vendor/github.com/urfave/cli/.gitignore
  vendor/github.com/urfave/cli/.travis.yml
  vendor/github.com/urfave/cli/CHANGELOG.md
  vendor/github.com/urfave/cli/CODE_OF_CONDUCT.md
  vendor/github.com/urfave/cli/CONTRIBUTING.md
  vendor/github.com/urfave/cli/README.md
  vendor/github.com/urfave/cli/app.go
  vendor/github.com/urfave/cli/appveyor.yml
  vendor/github.com/urfave/cli/category.go
  vendor/github.com/urfave/cli/cli.go
  vendor/github.com/urfave/cli/command.go
  vendor/github.com/urfave/cli/context.go
  vendor/github.com/urfave/cli/docs.go
  vendor/github.com/urfave/cli/fish.go
  vendor/github.com/urfave/cli/flag-types.json
  vendor/github.com/urfave/cli/flag.go
  vendor/github.com/urfave/cli/flag_bool.go
  vendor/github.com/urfave/cli/flag_bool_t.go
  vendor/github.com/urfave/cli/flag_duration.go
  vendor/github.com/urfave/cli/flag_float64.go
  vendor/github.com/urfave/cli/flag_generated.go
  vendor/github.com/urfave/cli/flag_generic.go
  vendor/github.com/urfave/cli/flag_int.go
  vendor/github.com/urfave/cli/flag_int64.go
  vendor/github.com/urfave/cli/flag_int64_slice.go
  vendor/github.com/urfave/cli/flag_int_slice.go
  vendor/github.com/urfave/cli/flag_string.go
  vendor/github.com/urfave/cli/flag_string_slice.go
  vendor/github.com/urfave/cli/flag_uint.go
  vendor/github.com/urfave/cli/flag_uint64.go
  vendor/github.com/urfave/cli/funcs.go
  vendor/github.com/urfave/cli/generate-flag-types
  vendor/github.com/urfave/cli/go.mod
  vendor/github.com/urfave/cli/go.sum
  vendor/github.com/urfave/cli/help.go
  vendor/github.com/urfave/cli/parse.go
  vendor/github.com/urfave/cli/runtests
  vendor/github.com/urfave/cli/sort.go
  vendor/github.com/urfave/cli/template.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XXL

#3040 [1.16] bump conmon to 2.0.8
  .circleci/config.yml
  Dockerfile
  Dockerfile-nix
  contrib/test/integration/build/conmon.yml
  go.mod
  go.sum
  scripts/build-test-image
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#2813 Image decryption support for CRIO
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  go.mod
  internal/pkg/criocli/criocli.go
  pkg/config/config.go
  pkg/config/template.go
  server/image_pull.go
  server/server.go
  server/utils.go
  server/utils_test.go
  test/mocks/containers/image/v5/types.go
  tutorial.md
  tutorials/decryption.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/L

#3052 Use vendored go modules when running unit tests
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3055 Deflake RHEL layer removal integration test
  go.mod
  go.sum
  vendor/github.com/containers/storage/Makefile
  vendor/github.com/containers/storage/VERSION
  vendor/github.com/containers/storage/pkg/system/rm.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/S

#3057 test: use dnf instead of package with loop
  contrib/test/integration/system-packages.yml
Labels: approved, dco-signoff: yes, lgtm, size/L

#3053 Add stats integration test
  .circleci/config.yml
  Makefile
  contrib/test/integration/build/jq.yml
  contrib/test/integration/main.yml
  scripts/build-test-image
  test/stats.bats
Labels: approved, dco-signoff: yes, lgtm, size/M

#3054 test: use cri stats instead of cadvisor
  contrib/test/integration/build/kubernetes.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3048 Allow CRI-O to manage net, IPC and UTS namespaces using pinns
  .circleci/config.yml
  Makefile
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  contrib/test/integration/build/cri-o.yml
  contrib/test/integration/vars.yml
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/lib/container_server.go
  internal/lib/container_server_test.go
  internal/lib/sandbox/namespaces.go
  internal/lib/sandbox/namespaces_linux.go
  internal/lib/sandbox/namespaces_test.go
  internal/lib/sandbox/sandbox.go
  internal/lib/sandbox/sandbox_linux.go
  internal/lib/sandbox/sandbox_test.go
  internal/lib/sandbox/sandbox_unsupported.go
  internal/lib/sandbox/suite_test.go
  internal/lib/suite_test.go
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/suite_test.go
  internal/pkg/criocli/criocli.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/template.go
  server/container_create_linux.go
  server/inspect_test.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
  server/suite_test.go
  test/ctr_userns.bats
  test/docs-validation/main.go
  test/mocks/sandbox/sandbox.go
Labels: approved, dco-signoff: yes, lgtm, release-1.17, size/XXL

#3030 Update libcontainer stats to use cgroups stats
  go.mod
  internal/oci/oci.go
  internal/oci/oci_linux.go
  internal/oci/oci_unix.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_vm.go
  internal/oci/stats.go
  server/container_stats.go
  server/container_stats_list.go
  server/container_stats_test.go
  vendor/github.com/mrunalp/fileutils/.gitignore
  vendor/github.com/mrunalp/fileutils/LICENSE
  vendor/github.com/mrunalp/fileutils/MAINTAINERS
  vendor/github.com/mrunalp/fileutils/README.md
  vendor/github.com/mrunalp/fileutils/fileutils.go
  vendor/github.com/mrunalp/fileutils/idtools.go
  vendor/github.com/opencontainers/runc/libcontainer/README.md
  vendor/github.com/opencontainers/runc/libcontainer/SPEC.md
  vendor/github.com/opencontainers/runc/libcontainer/capabilities_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/validate/rootless.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/validate/validator.go
  vendor/github.com/opencontainers/runc/libcontainer/console_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/container.go
  vendor/github.com/opencontainers/runc/libcontainer/container_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/criu_opts_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/error.go
  vendor/github.com/opencontainers/runc/libcontainer/factory.go
  vendor/github.com/opencontainers/runc/libcontainer/factory_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/generic_error.go
  vendor/github.com/opencontainers/runc/libcontainer/init_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/intelrdt/intelrdt.go
  vendor/github.com/opencontainers/runc/libcontainer/intelrdt/stats.go
  vendor/github.com/opencontainers/runc/libcontainer/keys/keyctl.go
  vendor/github.com/opencontainers/runc/libcontainer/logs/logs.go
  vendor/github.com/opencontainers/runc/libcontainer/message_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/mount/mount.go
  vendor/github.com/opencontainers/runc/libcontainer/mount/mount_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/mount/mountinfo.go
  vendor/github.com/opencontainers/runc/libcontainer/network_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/notify_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/process.go
  vendor/github.com/opencontainers/runc/libcontainer/process_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/restored_process.go
  vendor/github.com/opencontainers/runc/libcontainer/rootfs_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/seccomp/config.go
  vendor/github.com/opencontainers/runc/libcontainer/seccomp/seccomp_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/seccomp/seccomp_unsupported.go
  vendor/github.com/opencontainers/runc/libcontainer/setns_init_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/stacktrace/capture.go
  vendor/github.com/opencontainers/runc/libcontainer/stacktrace/frame.go
  vendor/github.com/opencontainers/runc/libcontainer/stacktrace/stacktrace.go
  vendor/github.com/opencontainers/runc/libcontainer/standard_init_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/state_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/stats.go
  vendor/github.com/opencontainers/runc/libcontainer/stats_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/sync.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-1.17, size/XXL

#3058 managed namespaces: batch infra.State() calls
  internal/lib/sandbox/namespaces.go
  internal/lib/sandbox/namespaces_test.go
  internal/lib/sandbox/sandbox_test.go
  server/container_create_linux.go
  server/sandbox_run_linux.go
  test/mocks/oci/oci.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#3059 Fixed cni setup link in crictl.md
  tutorials/crictl.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#3061 Fix pinns-path CLI flag and pass to integration test
  internal/pkg/criocli/criocli.go
  test/helpers.bash
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS
