Repository cri-o/cri-o, pull requests merged in 2019-02, with the labels that each got.

#2042 Fix apparmor related integration tests
  Dockerfile
  test/apparmor.bats
  test/testdata/container_redis_apparmor.json
  test/testdata/sandbox_config_apparmor.json
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#2049 Add disk usage for ListContainerStats
  server/container_stats.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2047 [1.12] Move config structs to pkg/config
  cmd/crio/main.go
  lib/config.go
  pkg/config/config.go
  server/config.go
  server/config_test.go
  server/container_create.go
  server/inspect_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1992 Add pkg unit tests and mock dependencies
  .gitignore
  Makefile
  pkg/findprocess/findprocess.go
  pkg/findprocess/findprocess_test.go
  pkg/findprocess/findprocess_unix.go
  pkg/registrar/registrar_test.go
  pkg/seccomp/seccomp.go
  pkg/seccomp/seccomp_test.go
  pkg/storage/image_test.go
  pkg/storage/runtime_test.go
  pkg/storage/suite_test.go
  test/framework/framework.go
  test/mocks/containerstorage/containerstorage.go
  test/mocks/criostorage/criostorage.go
  test/testdata/image.tar
  vendor.conf
  vendor/github.com/golang/mock/AUTHORS
  vendor/github.com/golang/mock/CONTRIBUTORS
  vendor/github.com/golang/mock/LICENSE
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/github.com/golang/mock/mockgen/mockgen.go
  vendor/github.com/golang/mock/mockgen/model/model.go
  vendor/github.com/golang/mock/mockgen/parse.go
  vendor/github.com/golang/mock/mockgen/reflect.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/README.md
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/README.md
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/requirements.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#2050 Add disk usage for ListContainerStats
  server/container_stats.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#1993 Add utils unit tests
  utils/filesystem_test.go
  utils/suite_test.go
  utils/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2052 Update image-test to be system independent
  pkg/storage/image_test.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#2066 bump github.com/containers/storage and github.com/containers/image
  contrib/system_containers/centos/Dockerfile
  contrib/system_containers/rhel/Dockerfile
  contrib/test/integration/build/cri-o.yml
  contrib/test/integration/vars.yml
  server/config_test.go
  server/fixtures/crio.conf
  vendor.conf
  vendor/github.com/containers/image/copy/copy.go
  vendor/github.com/containers/image/docker/docker_client.go
  vendor/github.com/containers/image/docker/docker_image.go
  vendor/github.com/containers/image/docker/docker_image_dest.go
  vendor/github.com/containers/image/docker/docker_image_src.go
  vendor/github.com/containers/image/docker/tarfile/src.go
  vendor/github.com/containers/image/ostree/ostree_src.go
  vendor/github.com/containers/image/pkg/sysregistriesv2/system_registries_v2.go
  vendor/github.com/containers/image/storage/storage_image.go
  vendor/github.com/containers/image/storage/storage_reference.go
  vendor/github.com/containers/image/storage/storage_transport.go
  vendor/github.com/containers/image/version/version.go
  vendor/github.com/containers/storage/containers_ffjson.go
  vendor/github.com/containers/storage/drivers/aufs/aufs.go
  vendor/github.com/containers/storage/drivers/btrfs/btrfs.go
  vendor/github.com/containers/storage/drivers/devmapper/driver.go
  vendor/github.com/containers/storage/drivers/driver.go
  vendor/github.com/containers/storage/drivers/overlay/check.go
  vendor/github.com/containers/storage/drivers/overlay/overlay.go
  vendor/github.com/containers/storage/drivers/template.go
  vendor/github.com/containers/storage/drivers/vfs/driver.go
  vendor/github.com/containers/storage/drivers/windows/windows.go
  vendor/github.com/containers/storage/drivers/zfs/zfs.go
  vendor/github.com/containers/storage/drivers/zfs/zfs_freebsd.go
  vendor/github.com/containers/storage/drivers/zfs/zfs_linux.go
  vendor/github.com/containers/storage/drivers/zfs/zfs_solaris.go
  vendor/github.com/containers/storage/drivers/zfs/zfs_unsupported.go
  vendor/github.com/containers/storage/images.go
  vendor/github.com/containers/storage/layers.go
  vendor/github.com/containers/storage/layers_ffjson.go
  vendor/github.com/containers/storage/pkg/archive/archive.go
  vendor/github.com/containers/storage/pkg/chrootarchive/archive.go
  vendor/github.com/containers/storage/pkg/config/config.go
  vendor/github.com/containers/storage/store.go
  vendor/github.com/containers/storage/vendor.conf
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#2067 Release 1.12.5
  version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2061 Backport hooks fix to release-1.12
  cmd/crio/config.go
  cmd/crio/main.go
  docs/crio.8.md
  docs/crio.conf.5.md
  lib/config.go
  lib/container_server.go
  lib/testdata/config.toml
  pkg/config/config.go
  server/sandbox_status_test.go
  test/helpers.bash
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2057 Added traces to CRI API pertaining to containers and sandboxes
  server/container_create.go
  server/container_execsync.go
  server/container_remove.go
  server/container_start.go
  server/container_stop.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
  server/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2070 Added traces to CRI API pertaining to containers and sandboxes
  oci/container.go
  server/container_create.go
  server/container_execsync.go
  server/container_remove.go
  server/container_start.go
  server/container_stop.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
  server/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2071 bump(github.com/containers/storage,github.com/containers/image)
  contrib/system_containers/centos/Dockerfile
  contrib/system_containers/rhel/Dockerfile
  contrib/test/integration/build/cri-o.yml
  contrib/test/integration/vars.yml
  server/config_test.go
  server/fixtures/crio.conf
  vendor.conf
  vendor/github.com/containers/storage/containers_ffjson.go
  vendor/github.com/containers/storage/drivers/aufs/aufs.go
  vendor/github.com/containers/storage/drivers/btrfs/btrfs.go
  vendor/github.com/containers/storage/drivers/devmapper/driver.go
  vendor/github.com/containers/storage/drivers/driver.go
  vendor/github.com/containers/storage/drivers/overlay/check.go
  vendor/github.com/containers/storage/drivers/overlay/overlay.go
  vendor/github.com/containers/storage/drivers/template.go
  vendor/github.com/containers/storage/drivers/vfs/driver.go
  vendor/github.com/containers/storage/drivers/windows/windows.go
  vendor/github.com/containers/storage/drivers/zfs/zfs.go
  vendor/github.com/containers/storage/drivers/zfs/zfs_freebsd.go
  vendor/github.com/containers/storage/drivers/zfs/zfs_linux.go
  vendor/github.com/containers/storage/drivers/zfs/zfs_solaris.go
  vendor/github.com/containers/storage/drivers/zfs/zfs_unsupported.go
  vendor/github.com/containers/storage/images.go
  vendor/github.com/containers/storage/layers.go
  vendor/github.com/containers/storage/layers_ffjson.go
  vendor/github.com/containers/storage/pkg/archive/archive.go
  vendor/github.com/containers/storage/pkg/chrootarchive/archive.go
  vendor/github.com/containers/storage/pkg/config/config.go
  vendor/github.com/containers/storage/store.go
  vendor/github.com/containers/storage/vendor.conf
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#2074 pkg/storage/image: wire in blocking registries feature
  pkg/storage/image.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#2073 pkg/storage/image: wire in blocking registries feature
  pkg/storage/image.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#2075 Disable broken tests
  contrib/test/integration/e2e.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2064 Vendor in latest c/storage and c/image
  contrib/system_containers/centos/Dockerfile
  contrib/system_containers/rhel/Dockerfile
  contrib/test/integration/build/cri-o.yml
  contrib/test/integration/vars.yml
  server/config_test.go
  server/fixtures/crio.conf
  vendor.conf
  vendor/github.com/containers/image/copy/copy.go
  vendor/github.com/containers/image/docker/docker_client.go
  vendor/github.com/containers/image/docker/docker_image.go
  vendor/github.com/containers/image/docker/docker_image_dest.go
  vendor/github.com/containers/image/docker/docker_image_src.go
  vendor/github.com/containers/image/docker/tarfile/src.go
  vendor/github.com/containers/image/ostree/ostree_src.go
  vendor/github.com/containers/image/pkg/sysregistriesv2/system_registries_v2.go
  vendor/github.com/containers/image/storage/storage_image.go
  vendor/github.com/containers/image/storage/storage_reference.go
  vendor/github.com/containers/image/storage/storage_transport.go
  vendor/github.com/containers/image/version/version.go
  vendor/github.com/containers/storage/containers_ffjson.go
  vendor/github.com/containers/storage/drivers/aufs/aufs.go
  vendor/github.com/containers/storage/drivers/btrfs/btrfs.go
  vendor/github.com/containers/storage/drivers/devmapper/driver.go
  vendor/github.com/containers/storage/drivers/driver.go
  vendor/github.com/containers/storage/drivers/overlay/check.go
  vendor/github.com/containers/storage/drivers/overlay/overlay.go
  vendor/github.com/containers/storage/drivers/template.go
  vendor/github.com/containers/storage/drivers/vfs/driver.go
  vendor/github.com/containers/storage/drivers/windows/windows.go
  vendor/github.com/containers/storage/drivers/zfs/zfs.go
  vendor/github.com/containers/storage/drivers/zfs/zfs_freebsd.go
  vendor/github.com/containers/storage/drivers/zfs/zfs_linux.go
  vendor/github.com/containers/storage/drivers/zfs/zfs_solaris.go
  vendor/github.com/containers/storage/drivers/zfs/zfs_unsupported.go
  vendor/github.com/containers/storage/images.go
  vendor/github.com/containers/storage/layers.go
  vendor/github.com/containers/storage/layers_ffjson.go
  vendor/github.com/containers/storage/pkg/archive/archive.go
  vendor/github.com/containers/storage/pkg/chrootarchive/archive.go
  vendor/github.com/containers/storage/pkg/config/config.go
  vendor/github.com/containers/storage/store.go
  vendor/github.com/containers/storage/vendor.conf
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#2069 Added traces to CRI API pertaining to containers and sandboxes
  oci/container.go
  server/container_create.go
  server/container_execsync.go
  server/container_remove.go
  server/container_start.go
  server/container_stop.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
  server/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2079 Drop the external git repo
  contrib/test/integration/e2e-base.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2080 Release v1.12.6
  contrib/test/integration/e2e.yml
  version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2082 [1.11] Drop the external git repo
  contrib/test/integration/e2e.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2081 [1.13] Drop the external git repo
  contrib/test/integration/e2e-base.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2059 Blocking
  pkg/storage/image.go
  test/helpers.bash
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2085 Release 1.13.1
  version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2062 conmon: allow to specify additional arguments to the OCI runtime
  conmon/conmon.c
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2083 server: delete the container if it cannot be restored
  server/server.go
  test/restore.bats
Labels: approved, cncf-cla: yes, lgtm, size/M

#2091 [1.12] Backport of user related fixes
  server/container_create.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2090 Always set gid if returned from container user files
  server/container_create.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2093 server: delete the container if it cannot be restored
  server/server.go
  test/restore.bats
Labels: approved, cncf-cla: yes, lgtm, size/M

#2092 Bump github.com/containers/storage to v1.11
  vendor.conf
  vendor/github.com/containers/storage/containers.go
  vendor/github.com/containers/storage/containers_ffjson.go
  vendor/github.com/containers/storage/drivers/overlay/overlay.go
  vendor/github.com/containers/storage/errors.go
  vendor/github.com/containers/storage/images.go
  vendor/github.com/containers/storage/layers.go
  vendor/github.com/containers/storage/layers_ffjson.go
  vendor/github.com/containers/storage/lockfile.go
  vendor/github.com/containers/storage/lockfile_unix.go
  vendor/github.com/containers/storage/lockfile_windows.go
  vendor/github.com/containers/storage/pkg/archive/archive_ffjson.go
  vendor/github.com/containers/storage/store.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#2077 Increase max grpc message size
  cmd/crio/main.go
  contrib/test/integration/golang.yml
Labels: approved, cncf-cla: yes, size/XS
