Repository cri-o/cri-o, pull requests merged in 2020-06, with the labels that each got.

#3812 oci: Don't return early for non-tty attach if there is no stdin
  internal/oci/runtime_oci.go
Labels: approved, dco-signoff: yes, lgtm

#3816 [1.18] misc test fixes
  contrib/test/integration/e2e.yml
  internal/oci/runtime_oci.go
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm

#3817 Fixed cidr standard net in documentation
  tutorials/kubeadm.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, ok-to-test

#3819 Add sandbox verbose info
  internal/lib/container_server.go
  server/sandbox_run_linux.go
  server/sandbox_status.go
  test/pod.bats
Labels: approved, dco-signoff: yes, kind/feature, lgtm

#3751 Add metrics exporter and documentation
  Makefile
  contrib/metrics-exporter/Containerfile
  contrib/metrics-exporter/cluster.yaml
  contrib/metrics-exporter/dashboard.gif
  contrib/metrics-exporter/dashboard.json
  contrib/metrics-exporter/main.go
  tutorials/metrics.md
Labels: approved, dco-signoff: yes, kind/feature, lgtm

#3777 Add `privileged` indicator to container status
  internal/storage/runtime.go
  internal/storage/runtime_test.go
  server/container_create_linux.go
  server/container_status.go
  server/container_status_test.go
  server/sandbox_run_linux.go
  server/sandbox_run_test.go
  test/ctr.bats
  test/mocks/criostorage/criostorage.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm

#3809 Add image pull success and failure metrics
  go.mod
  server/image_pull.go
  server/metrics/metrics.go
  tutorials/metrics.md
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/feature, lgtm

#3825 Use one deferred func to execute cleanup func's
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3790 vendor: update seccomp/containers-golang to v0.4.1
  go.mod
  go.sum
  vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
  vendor/github.com/seccomp/containers-golang/go.mod
  vendor/github.com/seccomp/containers-golang/go.sum
  vendor/github.com/seccomp/containers-golang/seccomp_default_linux.go
  vendor/github.com/seccomp/containers-golang/seccomp_linux.go
  vendor/github.com/seccomp/containers-golang/seccomp_unsupported.go
  vendor/github.com/seccomp/containers-golang/types.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm

#3829 [1.18] sandbox iface: don't fail if uid is not specified
  pkg/sandbox/sandbox.go
  pkg/sandbox/sandbox_setnameandid_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3833 Check whether seccomp is enabled before making assertion
  internal/config/seccomp/seccomp_test.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3824 Use correct format for logPath removal log
  server/container_create.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3834 Cleanup default info logs
  internal/oci/runtime_oci.go
  server/container_create.go
  server/container_remove.go
  server/container_start.go
  server/container_stop.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3830 Close the done channel when there is watcher error
  server/server.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3826 Add test for sandbox status verbose mode
  server/sandbox_status.go
  server/sandbox_status_test.go
  server/suite_test.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3838 Add crun to config template
  pkg/config/template.go
Labels: approved, dco-signoff: yes, kind/documentation, lgtm

#3836 Add sandbox IPs if there is no error in IP retrieval
  server/server.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3832 [1.19] Add logic for running openshift e2e-aws tests
  Makefile
  contrib/test/ci/cri-o.spec
  contrib/test/ci/crio-metrics.sysconfig
  contrib/test/ci/crio-network.sysconfig
  contrib/test/ci/crio-storage.sysconfig
  contrib/test/ci/crio.service
  hack/build-rpms.sh
  hack/lib/build/binaries.sh
  hack/lib/build/rpm.sh
  hack/lib/build/version.sh
  hack/lib/constants.sh
  hack/lib/init.sh
  hack/lib/log/output.sh
  hack/lib/log/stacktrace.sh
  hack/lib/log/system.sh
  hack/lib/util/ensure.sh
  hack/lib/util/environment.sh
  hack/lib/util/find.sh
  hack/lib/util/misc.sh
  hack/lib/util/text.sh
  hack/lib/util/trap.sh
  images/os/Dockerfile
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm

#3843 Add info logs for image pull and status CRI calls
  server/image_pull.go
  server/image_status.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3839 managed_ns: deflake tests
  internal/lib/sandbox/namespaces.go
  internal/lib/sandbox/namespaces_test.go
  test/mocks/containerstorage/containerstorage.go
  test/mocks/oci/oci.go
Labels: approved, dco-signoff: yes, kind/flake, lgtm

#3842 server: store container privilege bool in pkg/container
  pkg/container/container.go
  pkg/container/container_privileged_test.go
  pkg/container/container_setconfig_test.go
  pkg/container/container_setnameandid_test.go
  server/container_create.go
  server/container_create_linux.go
  server/container_create_unsupported.go
Labels: approved, dco-signoff: yes, kind/design, lgtm

#3841 oci: check container status before stop atomically
  internal/lib/stop.go
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_vm.go
Labels: approved, dco-signoff: yes, kind/flake, lgtm, needs-backport

#3848 Container should only be added once after passing filter
  internal/lib/container_server.go
  internal/lib/container_server_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3850 logs: fix some problems
  internal/oci/runtime_oci.go
  server/container_execsync.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3797 [1.18] bump containers image to 5.4.4
  go.mod
  go.sum
  vendor/github.com/containers/image/v5/copy/copy.go
  vendor/github.com/containers/image/v5/docker/docker_client.go
  vendor/github.com/containers/image/v5/docker/docker_image.go
  vendor/github.com/containers/image/v5/docker/docker_image_dest.go
  vendor/github.com/containers/image/v5/docker/docker_image_src.go
  vendor/github.com/containers/image/v5/internal/pkg/platform/platform_matcher.go
  vendor/github.com/containers/image/v5/internal/uploadreader/upload_reader.go
  vendor/github.com/containers/image/v5/manifest/common.go
  vendor/github.com/containers/image/v5/manifest/docker_schema2.go
  vendor/github.com/containers/image/v5/manifest/docker_schema2_list.go
  vendor/github.com/containers/image/v5/manifest/list.go
  vendor/github.com/containers/image/v5/manifest/manifest.go
  vendor/github.com/containers/image/v5/manifest/oci.go
  vendor/github.com/containers/image/v5/manifest/oci_index.go
  vendor/github.com/containers/image/v5/version/version.go
  vendor/github.com/vbauerster/mpb/v5/bar.go
  vendor/github.com/vbauerster/mpb/v5/bar_filler.go
  vendor/github.com/vbauerster/mpb/v5/go.mod
  vendor/github.com/vbauerster/mpb/v5/go.sum
  vendor/github.com/vbauerster/mpb/v5/internal/percentage.go
  vendor/golang.org/x/crypto/chacha20/chacha_generic.go
  vendor/golang.org/x/crypto/chacha20/xor.go
  vendor/golang.org/x/crypto/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/poly1305/poly1305.go
  vendor/golang.org/x/crypto/poly1305/sum_amd64.go
  vendor/golang.org/x/crypto/poly1305/sum_generic.go
  vendor/golang.org/x/crypto/poly1305/sum_noasm.go
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.go
  vendor/golang.org/x/crypto/ssh/agent/client.go
  vendor/golang.org/x/crypto/ssh/cipher.go
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm

#3854 Send only single error to stdinDone
  internal/oci/runtime_oci.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3855 config: add ulimits package
  internal/config/ulimits/suite_test.go
  internal/config/ulimits/ulimits.go
  internal/config/ulimits/ulimits_test.go
  pkg/config/config.go
  server/container_create_linux.go
  server/sandbox_run_linux.go
  server/utils.go
Labels: approved, dco-signoff: yes, kind/design, lgtm

#3837 Add crun to static binary bundle
  contrib/bundle/Makefile
  contrib/bundle/build
  scripts/versions
Labels: approved, dco-signoff: yes, kind/feature, lgtm

#3857 Close the done channel in waitContainerStop
  internal/oci/runtime_oci.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3859 use inactive-or-failed CollectMode if appropriate
  internal/config/node/node.go
  internal/config/node/systemd.go
  server/container_create_linux.go
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3874 Remove the protocol filter from the portMappings constructor
  server/sandbox_run.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, ok-to-test

#3870 StringSliceTrySplit: return a copy of the underlying slice
  cmd/crio/main.go
  internal/criocli/criocli.go
  internal/criocli/criocli_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test

#3875 [1.17] oci: check state before stop atomically
  internal/lib/stop.go
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_vm.go
Labels: approved, dco-signoff: yes, kind/flake, lgtm

#3798 [1.17] test: refactor some of main.yml
  contrib/test/integration/main.yml
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm

#3849 pkg/container: handle logPath
  pkg/container/container.go
  pkg/container/container_log_path_test.go
  pkg/container/container_setnameandid_test.go
  server/container_create.go
  server/container_create_linux.go
  server/sandbox_run_linux.go
  test/ctr_seccomp.bats
  utils/utils.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3880 [1.18] StringSliceTrySplit: return a copy of the underlying slice
  cmd/crio/main.go
  internal/criocli/criocli.go
  internal/criocli/criocli_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test

#3532 [1.11] oci: handle timeouts correctly for probes
  oci/oci.go
  test/ctr.bats
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3878 Select disabled e2e features manually and enable SCTP/Seccomp tests
  contrib/test/integration/e2e-features.yml
  internal/criocli/criocli_test.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm

#3881 [1.11] server/ContainerStatus: don't lock
  server/container_status.go
Labels: approved, dco-signoff: yes, lgtm

#3885 [1.18] Bump version to v1.18.2
  internal/version/version.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm

#3896 [1.19] Revert "Add logic for running openshift e2e-aws tests"
  Makefile
  contrib/test/ci/cri-o.spec
  contrib/test/ci/crio-metrics.sysconfig
  contrib/test/ci/crio-network.sysconfig
  contrib/test/ci/crio-storage.sysconfig
  contrib/test/ci/crio.service
  hack/build-rpms.sh
  hack/lib/build/binaries.sh
  hack/lib/build/rpm.sh
  hack/lib/build/version.sh
  hack/lib/constants.sh
  hack/lib/init.sh
  hack/lib/log/output.sh
  hack/lib/log/stacktrace.sh
  hack/lib/log/system.sh
  hack/lib/util/ensure.sh
  hack/lib/util/environment.sh
  hack/lib/util/find.sh
  hack/lib/util/misc.sh
  hack/lib/util/text.sh
  hack/lib/util/trap.sh
  images/os/Dockerfile
Labels: approved, dco-signoff: yes

#3893 [1.18] Fix lint issue in criocli_test.go
  internal/criocli/criocli_test.go
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm

#3887 server: re-add gocyclo skip
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, lgtm

#3897 Add logic for running openshift e2e-aws tests
  Makefile
  contrib/test/ci/cri-o.spec
  contrib/test/ci/crio-metrics.sysconfig
  contrib/test/ci/crio-network.sysconfig
  contrib/test/ci/crio-storage.sysconfig
  contrib/test/ci/crio.service
  hack/build-rpms.sh
  hack/lib/build/binaries.sh
  hack/lib/build/rpm.sh
  hack/lib/build/version.sh
  hack/lib/constants.sh
  hack/lib/init.sh
  hack/lib/log/output.sh
  hack/lib/log/stacktrace.sh
  hack/lib/log/system.sh
  hack/lib/util/ensure.sh
  hack/lib/util/environment.sh
  hack/lib/util/find.sh
  hack/lib/util/misc.sh
  hack/lib/util/text.sh
  hack/lib/util/trap.sh
  images/os/Dockerfile
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm

#3900 test: use node readiness as an indicator to run kubetest
  contrib/test/integration/e2e-base.yml
Labels: approved, dco-signoff: yes, lgtm

#3889 runtime_vm: Apply the correct label before the sandbox is created
  server/container_create_linux.go
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test

#3903 Add runtime_type as an option of "--runtimes"
  completions/fish/crio.fish
  docs/crio.8.md
  internal/criocli/criocli.go
  test/helpers.bash
Labels: approved, dco-signoff: yes, lgtm, ok-to-test

#3902 [1.18] logs: drop print on execsyncs
  server/container_execsync.go
Labels: approved, dco-signoff: yes, lgtm

#3905 test: bump go version to 1.14.4
  contrib/test/integration/main.yml
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm

#3886 Restore version output from crio --version
  Makefile
  cmd/crio/main.go
  internal/version/version.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test
