Repository cri-o/cri-o, pull requests merged in 2020-09, with the labels that each got.

#4065 Update nix pin with `make nixpkgs`
  .circleci/config.yml
  nix/default.nix
  nix/nixpkgs.json
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note

#4142 Revert "runtime_vm: Cleanup process when the Container is Stopped"
  internal/oci/runtime_vm.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4137 Fix pinns compilation for TEMP_FAILURE_RETRY
  pinns/utils.h
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4145 [release-1.17] Revert "runtime_vm: Cleanup process when the Container is Stopped"
  internal/oci/runtime_vm.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4141 test: reduce flakes
  internal/lib/sandbox/sandbox.go
  test/stats.bats
Labels: approved, dco-signoff: yes, kind/flake, lgtm, release-note-none

#4148 Fix pinns error diagnostics, cleanup, and return
  internal/lib/sandbox/namespaces_linux.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4152 sandbox config: Improve validation error message
  pkg/sandbox/sandbox.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, ok-to-test, release-note-none

#4139 oci: improve error message for verifyPid()
  internal/oci/container.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4149 oci: return IsAlive error instead of logging
  internal/oci/container.go
  internal/oci/container_test.go
  server/container_execsync.go
Labels: approved, dco-signoff: yes, lgtm

#4153 [1.19] fix stats test and fix Unmount error
  internal/lib/sandbox/sandbox.go
  test/stats.bats
Labels: approved, dco-signoff: yes, kind/flake, lgtm, release-note-none

#4121 Code clean up in containers_create_linux.go
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4008 [1.19] Point to k8s release-1.19 branch for tests
  contrib/test/integration/main.yml
  install.md
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note-none

#4125 [release-1.18] Backport "Use the container_kvm_t label when using kata as the runtime" (and follow-ups)
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note-none

#4119 Remove git-validation in favor of prow/golangci-lint
  .circleci/config.yml
  Makefile
  go.mod
  internal/tools/tools.go
  vendor/github.com/hashicorp/go-version/.travis.yml
  vendor/github.com/hashicorp/go-version/LICENSE
  vendor/github.com/hashicorp/go-version/README.md
  vendor/github.com/hashicorp/go-version/constraint.go
  vendor/github.com/hashicorp/go-version/go.mod
  vendor/github.com/hashicorp/go-version/version.go
  vendor/github.com/hashicorp/go-version/version_collection.go
  vendor/github.com/vbatts/git-validation/.gitignore
  vendor/github.com/vbatts/git-validation/.travis.yml
  vendor/github.com/vbatts/git-validation/LICENSE
  vendor/github.com/vbatts/git-validation/README.md
  vendor/github.com/vbatts/git-validation/git/commits.go
  vendor/github.com/vbatts/git-validation/go.mod
  vendor/github.com/vbatts/git-validation/go.sum
  vendor/github.com/vbatts/git-validation/main.go
  vendor/github.com/vbatts/git-validation/rules/danglingwhitespace/rule.go
  vendor/github.com/vbatts/git-validation/rules/dco/dco.go
  vendor/github.com/vbatts/git-validation/rules/messageregexp/rule.go
  vendor/github.com/vbatts/git-validation/rules/shortsubject/shortsubject.go
  vendor/github.com/vbatts/git-validation/validate/rules.go
  vendor/github.com/vbatts/git-validation/validate/runner.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note-none

#4131 config: set internal RootConfig to default storage if not specified
  pkg/config/config.go
  pkg/config/config_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4150 Bump cri-tools to v1.19.0, CNI plugins and golang
  .circleci/config.yml
  Makefile
  contrib/test/integration/main.yml
  scripts/versions
  test/apparmor.bats
  test/helpers.bash
  test/network_ping.bats
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note-none

#4159 Add image layer reuse docs to metrics.md
  tutorials/metrics.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note

#4160 [1.19] managed ns: ignore `PID not initialized` on sandbox creation
  internal/lib/sandbox/namespaces.go
  internal/oci/container.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4098 Switch to Kubernetes AppArmor unconfined const
  internal/config/apparmor/apparmor.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4126 [1.19] managed ns: report namespace cleanup failure by default
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4146 oci: parse stat file instead of using ctime
  internal/oci/container.go
  internal/oci/container_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4168 test: remove generated file
  test/testdata/labeled_container_redis.json
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4166 [1.19] oci: parse stat file instead of using ctime
  internal/oci/container.go
  internal/oci/container_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4135 Updating documentation of kubeadm with offline configurations.
  tutorials/kubeadm.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, ok-to-test, release-note

#4162 Update crictl.yaml to reflect cri-tools v1.19.0 configs
  crictl.yaml
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note

#4143 [release-1.19] Revert "runtime_vm: Cleanup process when the Container is Stopped"
  internal/oci/runtime_vm.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-1.19, release-note-none

#4186 [1.19] Add option to drop infra container
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  internal/lib/container_server.go
  internal/lib/sandbox/namespaces.go
  internal/lib/sandbox/namespaces_linux.go
  internal/lib/sandbox/namespaces_test.go
  internal/lib/sandbox/sandbox.go
  internal/lib/sandbox/sandbox_test.go
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/oci.go
  internal/oci/oci_linux.go
  internal/oci/runtime_oci.go
  pinns/Makefile
  pinns/src/pinns.c
  pinns/src/sysctl.c
  pinns/src/sysctl.h
  pinns/src/utils.h
  pkg/annotations/annotations.go
  pkg/config/config.go
  pkg/config/template.go
  server/container_portforward.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/sandbox_status.go
  server/sandbox_stop_linux.go
  test/cgroups.bats
  test/ctr_userns.bats
  test/drop_infra.bats
  test/helpers.bash
  test/network.bats
  test/pod.bats
  test/restore.bats
Labels: approved, dco-signoff: yes, lgtm, release-1.19, release-note

#4165 Add option to drop infra container
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  internal/lib/container_server.go
  internal/lib/sandbox/namespaces.go
  internal/lib/sandbox/namespaces_linux.go
  internal/lib/sandbox/namespaces_test.go
  internal/lib/sandbox/sandbox.go
  internal/lib/sandbox/sandbox_test.go
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/oci.go
  internal/oci/oci_linux.go
  internal/oci/runtime_oci.go
  pinns/Makefile
  pinns/src/pinns.c
  pinns/src/sysctl.c
  pinns/src/sysctl.h
  pinns/src/utils.h
  pkg/annotations/annotations.go
  pkg/config/config.go
  pkg/config/template.go
  server/container_portforward.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/sandbox_status.go
  server/sandbox_stop_linux.go
  test/cgroups.bats
  test/ctr_userns.bats
  test/drop_infra.bats
  test/helpers.bash
  test/network.bats
  test/pod.bats
  test/restore.bats
Labels: approved, dco-signoff: yes, lgtm, release-note

#4188 bump to v1.19.0
  internal/version/version.go
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none

#4190 Bump GRPC to v1.27.0
  go.mod
  go.sum
  vendor/google.golang.org/grpc/.travis.yml
  vendor/google.golang.org/grpc/Makefile
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/credentials.go
  vendor/google.golang.org/grpc/credentials/tls.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_conn_wrapper.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/trace.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#4144 [release-1.18] Revert "runtime_vm: Cleanup process when the Container is Stopped"
  internal/oci/runtime_vm.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4192 Switch to updated version of creack/pty
  go.mod
  go.sum
  vendor/github.com/creack/pty/run.go
  vendor/github.com/creack/pty/test_crosscompile.sh
  vendor/github.com/creack/pty/ztypes_freebsd_arm64.go
  vendor/github.com/creack/pty/ztypes_openbsd_32bit_int.go
  vendor/github.com/creack/pty/ztypes_openbsd_amd64.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4201 [1.19] server: cleanup container in runtime after failed creation
  server/container_create.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4202 test: skip MetricsGrabber tests
  contrib/test/integration/e2e.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none

#4207 [1.17] server: cleanup container in runtime after failed creation
  server/container_create.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4191 Bump GRPC to v1.27.0
  go.mod
  go.sum
  vendor/google.golang.org/grpc/.travis.yml
  vendor/google.golang.org/grpc/Makefile
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/credentials.go
  vendor/google.golang.org/grpc/credentials/tls.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_conn_wrapper.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/trace.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#4195 Enable debug logs for release notes generation
  scripts/release-notes/release_notes.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4209 deprecate manage_ns_lifecycle option
  completions/fish/crio.fish
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  pkg/config/config.go
  pkg/config/template.go
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note

#4158 Print seccomp profile JSON only on trace log level
  internal/config/seccomp/seccomp.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note

#4213 test/config: fix "config dir should fail with invalid option"
  test/config.bats
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4211 cni: fix ipv4 configuration file
  contrib/cni/11-crio-ipv4-bridge.conf
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none

#4174 Rebase of "support setting the size of /dev/shm"
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  pkg/annotations/annotations.go
  pkg/config/config.go
  pkg/config/template.go
  server/sandbox_run_linux.go
  test/shm_size.bats
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none

#4216 test: drop infra container
  contrib/test/integration/build/cri-o.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none

#3960 container refactor
  pkg/container/container.go
  pkg/container/container_setnameandid_test.go
  pkg/container/container_test.go
  pkg/container/suite_test.go
  server/container_create.go
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, ok-to-test, release-note-none

#4218 tests: use crun 0.15
  contrib/test/integration/build/crun.yml
  test/ctr.bats
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4184 Update nix pin with `make nixpkgs`
  nix/nixpkgs.json
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note

#4204 runtime: parse oom file for VM type runtimes
  internal/oci/runtime_vm.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none

#4178 [1.17] config: set internal RootConfig to default storage if not specified
  pkg/config/config.go
  pkg/config/config_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4217 Fix bogus CI test failures
  contrib/test/integration/main.yml
  internal/config/node/node.go
  internal/config/node/sysctl.go
  test/sanity_checks.bats
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#4208 Fix make vendor
  CONTRIBUTING.md
  Makefile
  contrib/test/ci/cri-o.spec
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4225 runtime_vm: set Pid and InitPid for VM runtimes
  internal/oci/runtime_vm.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none

#4231 [1.17] Fix bogus CI test failures on RHEL7
  contrib/test/integration/main.yml
  test/sanity_checks.bats
Labels: approved, dco-signoff: yes, kind/flake, lgtm, release-note-none

#4229 [1.18] test/config: fix "config dir should fail with invalid option"
  test/config.bats
Labels: approved, dco-signoff: yes, kind/flake, lgtm, release-note-none

#4226 Bump logrus to v1.7.0
  go.mod
  go.sum
  vendor/github.com/konsorten/go-windows-terminal-sequences/LICENSE
  vendor/github.com/konsorten/go-windows-terminal-sequences/README.md
  vendor/github.com/konsorten/go-windows-terminal-sequences/go.mod
  vendor/github.com/konsorten/go-windows-terminal-sequences/sequences.go
  vendor/github.com/konsorten/go-windows-terminal-sequences/sequences_dummy.go
  vendor/github.com/sirupsen/logrus/.gitignore
  vendor/github.com/sirupsen/logrus/buffer_pool.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/go.mod
  vendor/github.com/sirupsen/logrus/go.sum
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/terminal_check_windows.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note-none

#4193 Verify Cgroup Memory - cgroupfs
  internal/config/cgmgr/cgmgr.go
  internal/config/cgmgr/cgroupfs.go
  internal/config/cgmgr/systemd.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none

#4179 update link for podman
  transfer.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note

#4180 broken link
  install.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note
