Repository cri-o/cri-o, pull requests merged in 2020-12, with the labels that each got.

#4361 Portmap support for dual-stack
  .gitignore
  go.mod
  internal/hostport/HostPort.jpg
  internal/hostport/README.md
  internal/hostport/fake_iptables.go
  internal/hostport/fake_iptables_test.go
  internal/hostport/hostport.go
  internal/hostport/hostport_manager.go
  internal/hostport/hostport_manager_test.go
  internal/hostport/hostport_test.go
  internal/hostport/meta_hostport_manager.go
  internal/hostport/meta_hostport_manager_test.go
  internal/lib/container_server.go
  internal/lib/sandbox/history_test.go
  internal/lib/sandbox/sandbox.go
  internal/lib/sandbox/sandbox_test.go
  internal/lib/sandbox/suite_test.go
  internal/lib/suite_test.go
  pkg/container/container_test.go
  server/sandbox_network.go
  server/sandbox_run.go
  server/server.go
  server/suite_test.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/gopkg.in/yaml.v3/.travis.yml
  vendor/gopkg.in/yaml.v3/LICENSE
  vendor/gopkg.in/yaml.v3/NOTICE
  vendor/gopkg.in/yaml.v3/README.md
  vendor/gopkg.in/yaml.v3/apic.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/emitterc.go
  vendor/gopkg.in/yaml.v3/encode.go
  vendor/gopkg.in/yaml.v3/go.mod
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/gopkg.in/yaml.v3/readerc.go
  vendor/gopkg.in/yaml.v3/resolve.go
  vendor/gopkg.in/yaml.v3/scannerc.go
  vendor/gopkg.in/yaml.v3/sorter.go
  vendor/gopkg.in/yaml.v3/writerc.go
  vendor/gopkg.in/yaml.v3/yaml.go
  vendor/gopkg.in/yaml.v3/yamlh.go
  vendor/gopkg.in/yaml.v3/yamlprivateh.go
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/network/hostport/BUILD
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/bug, kind/dependency-change, lgtm, ok-to-test, release-note

#4389 Provide a better value for features specific annotations
  internal/oci/oci.go
  internal/oci/oci_test.go
  internal/runtimehandlerhooks/high_performance_hooks.go
  internal/runtimehandlerhooks/runtime_handler_hooks.go
  pkg/annotations/annotations.go
  server/container_start.go
  server/container_stop.go
  server/sandbox_stop_linux.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test, release-note

#4390 Add clean v1alpha2 CRI API interface
  server/cri/v1alpha2/api.go
  server/cri/v1alpha2/rpc_attach.go
  server/cri/v1alpha2/rpc_container_stats.go
  server/cri/v1alpha2/rpc_container_status.go
  server/cri/v1alpha2/rpc_create_container.go
  server/cri/v1alpha2/rpc_exec.go
  server/cri/v1alpha2/rpc_exec_sync.go
  server/cri/v1alpha2/rpc_image_fs_info.go
  server/cri/v1alpha2/rpc_image_status.go
  server/cri/v1alpha2/rpc_list_container_stats.go
  server/cri/v1alpha2/rpc_list_containers.go
  server/cri/v1alpha2/rpc_list_images.go
  server/cri/v1alpha2/rpc_list_pod_sandbox.go
  server/cri/v1alpha2/rpc_pod_sandbox_status.go
  server/cri/v1alpha2/rpc_port_forward.go
  server/cri/v1alpha2/rpc_pull_image.go
  server/cri/v1alpha2/rpc_remove_container.go
  server/cri/v1alpha2/rpc_remove_image.go
  server/cri/v1alpha2/rpc_remove_pod_sandbox.go
  server/cri/v1alpha2/rpc_reopen_container_log.go
  server/cri/v1alpha2/rpc_run_pod_sandbox.go
  server/cri/v1alpha2/rpc_start_container.go
  server/cri/v1alpha2/rpc_status.go
  server/cri/v1alpha2/rpc_stop_container.go
  server/cri/v1alpha2/rpc_stop_pod_sandbox.go
  server/cri/v1alpha2/rpc_update_container_resources.go
  server/cri/v1alpha2/rpc_update_runtime_config.go
  server/cri/v1alpha2/rpc_version.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none

#4396 Fix make vendor GOSUMDB
  Makefile
Labels: approved, dco-signoff: yes, kind/ci, release-note-none

#4241 server: refactor handling of cleanup funcs
  server/container_create.go
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4401 Add CRI glue types for v1alpha2 and v1 usage
  server/cri/types/types.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note-none

#4387 Use own metadata types
  internal/lib/container_server.go
  internal/lib/container_server_test.go
  internal/lib/rename.go
  internal/lib/sandbox/history_test.go
  internal/lib/sandbox/namespaces_test.go
  internal/lib/sandbox/sandbox.go
  internal/lib/sandbox/sandbox_test.go
  internal/lib/sandbox/suite_test.go
  internal/lib/suite_test.go
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/suite_test.go
  internal/runtimehandlerhooks/high_performance_hooks_test.go
  pkg/container/container_test.go
  server/container_create_linux.go
  server/container_list.go
  server/container_stats.go
  server/container_status.go
  server/inspect_test.go
  server/sandbox_list.go
  server/sandbox_run_linux.go
  server/sandbox_status.go
  server/suite_test.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4399 Portmap support for dual-stack
  go.mod
  internal/hostport/HostPort.jpg
  internal/hostport/README.md
  internal/hostport/fake_iptables.go
  internal/hostport/fake_iptables_test.go
  internal/hostport/hostport.go
  internal/hostport/hostport_manager.go
  internal/hostport/hostport_manager_test.go
  internal/hostport/hostport_test.go
  internal/hostport/meta_hostport_manager.go
  internal/hostport/meta_hostport_manager_test.go
  internal/lib/container_server.go
  internal/lib/sandbox/history_test.go
  internal/lib/sandbox/sandbox.go
  internal/lib/sandbox/sandbox_test.go
  internal/lib/sandbox/suite_test.go
  internal/lib/suite_test.go
  server/sandbox_network.go
  server/sandbox_run.go
  server/server.go
  server/suite_test.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/gopkg.in/yaml.v3/.travis.yml
  vendor/gopkg.in/yaml.v3/LICENSE
  vendor/gopkg.in/yaml.v3/NOTICE
  vendor/gopkg.in/yaml.v3/README.md
  vendor/gopkg.in/yaml.v3/apic.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/emitterc.go
  vendor/gopkg.in/yaml.v3/encode.go
  vendor/gopkg.in/yaml.v3/go.mod
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/gopkg.in/yaml.v3/readerc.go
  vendor/gopkg.in/yaml.v3/resolve.go
  vendor/gopkg.in/yaml.v3/scannerc.go
  vendor/gopkg.in/yaml.v3/sorter.go
  vendor/gopkg.in/yaml.v3/writerc.go
  vendor/gopkg.in/yaml.v3/yaml.go
  vendor/gopkg.in/yaml.v3/yamlh.go
  vendor/gopkg.in/yaml.v3/yamlprivateh.go
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/network/hostport/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/network/hostport/hostport_syncer.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note

#4405 test/*bats: don't overuse run, switch to jq for editing json
  test/apparmor.bats
  test/cgroups.bats
  test/ctr_seccomp.bats
  test/ctr_userns.bats
  test/drop_infra.bats
  test/image.bats
  test/image_volume.bats
  test/inspect.bats
  test/stats.bats
  test/testdata/container_redis_apparmor.json
  test/testdata/sandbox_config_apparmor.json
Labels: approved, dco-signoff: yes, kind/ci, release-note-none

#4138 Preserve sandbox annotations for handling OCI hooks
  pkg/container/container.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4407 test/*bats: simplify, fix, improve, and enable shellcheck
  Makefile
  test/ctr.bats
  test/ctr_seccomp.bats
  test/ctr_userns.bats
  test/devices.bats
  test/image.bats
  test/inspect.bats
  test/network.bats
  test/pod.bats
  test/runtimeversion.bats
  test/selinux.bats
  test/testdata/container_config_by_imageid.json
  test/testdata/container_config_seccomp.json
  test/testdata/container_config_sleep.json
  test/testdata/sandbox_config_selinux.json
  test/testdata/sandbox_config_sysctl.json
Labels: approved, dco-signoff: yes, kind/ci, lgtm, release-note-none

#3890 make: fix link to cri-o.service
  contrib/test/ci/cri-o.spec
Labels: approved, dco-signoff: yes, lgtm

#4410 [1.20] Point to k8s release-1.20 branch for tests
  contrib/test/integration/main.yml
Labels: approved, dco-signoff: yes, kind/other, lgtm, release-note-none

#4369 test/devices.bats: nits
  test/devices.bats
Labels: approved, dco-signoff: yes, kind/ci, kind/cleanup, lgtm, release-note-none

#4411 test/ctr.bats: fix a "ctr execsync" flake
  test/ctr.bats
Labels: approved, dco-signoff: yes, kind/ci, kind/flake, release-note-none

#4409 Fix the functions' name in completions
  completions/bash/crio
  completions/bash/crio-status
  completions/zsh/_crio
  completions/zsh/_crio-status
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none

#4412 image pull: close progress chan
  server/image_pull.go
Labels: approved, dco-signoff: yes, lgtm, needs-backport, release-note

#4402 convert shmsize annotation to handler_allowed
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  internal/oci/oci.go
  pkg/config/config.go
  pkg/config/template.go
  server/sandbox_run_linux.go
  test/shm_size.bats
Labels: approved, dco-signoff: yes, kind/feature, lgtm, ok-to-test, release-note

#4394 Improve timeout handling
  internal/resourcestore/resourcestore.go
  internal/resourcestore/resourcestore_test.go
  internal/resourcestore/suite_test.go
  server/container_create.go
  server/sandbox_network.go
  server/sandbox_run_linux.go
  server/server.go
  server/utils.go
  test/drop_infra.bats
  test/helpers.bash
  test/timeout.bats
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4377 test: add no-pull-on-run; fix no pull on create
  crictl.yaml
  test/ctr.bats
  test/helpers.bash
Labels: approved, dco-signoff: yes, kind/ci, kind/flake, lgtm, release-note-none

#4416 [1.20] Bump version to v1.20.0-rc.1
  internal/version/version.go
Labels: approved, dco-signoff: yes, kind/other, lgtm, release-note

#4420 test/*bats: nits
  test/helpers.bash
  test/image.bats
Labels: approved, dco-signoff: yes, kind/ci, lgtm, release-note-none

#4426 [1.20] release-notes: fix flags
  scripts/release-notes/release_notes.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4422 test/timeout.bats: fix flakes
  internal/resourcestore/resourcestore.go
  test/timeout.bats
Labels: approved, dco-signoff: yes, kind/ci, kind/flake, release-note-none

#4430 [1.20] improve timeout handling and fix flakes
  docs/crio.8.md
  internal/resourcestore/resourcestore.go
  internal/resourcestore/resourcestore_test.go
  internal/resourcestore/suite_test.go
  server/container_create.go
  server/sandbox_network.go
  server/sandbox_run_linux.go
  server/server.go
  server/utils.go
  test/drop_infra.bats
  test/helpers.bash
  test/timeout.bats
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4428 drop support for ManageNSLifecycle
  completions/bash/crio
  completions/bash/crio-status
  completions/fish/crio.fish
  completions/zsh/_crio
  completions/zsh/_crio-status
  docs/crio.8.md
  internal/criocli/criocli.go
  internal/lib/container_server.go
  pkg/config/config.go
  pkg/config/template.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/sandbox_run_test.go
  server/server_test_inject.go
Labels: approved, dco-signoff: yes, kind/deprecation, lgtm, release-note

#4433 bump to v1.20.0
  internal/version/version.go
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none

#4442 pinns: make binary not always static
  pinns/Makefile
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4447 modify the error url of podctl
  awesome.md
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test, release-note-none

#4448 bump to v1.19.1
  internal/version/version.go
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none
