Repository cri-o/cri-o, pull requests merged in 2020-07, with the labels that each got.

#3941 [1.18] test: build off of release-1.18 and with golang 1.14.4
  contrib/test/integration/main.yml
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#3943 test: use cgroupfs to fix tests temporarily
  contrib/test/integration/build/kubernetes.yml
  contrib/test/integration/e2e-base.yml
  contrib/test/integration/e2e.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none

#3460 Make release notes generator capable of handling tags
  scripts/release-notes/release_notes.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm

#3947 test: drop cgroupfs override
  contrib/test/integration/build/kubernetes.yml
  contrib/test/integration/e2e-base.yml
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#3939 [1.18] oci: add debug logs for runtime state calls
  internal/oci/runtime_oci.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3942 config: fix systemd version parsing
  internal/config/node/systemd.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test, release-note-none

#3931 Streamline how done channel is closed in Runtime#WaitContainerStateStopped
  internal/oci/oci.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test

#3940 Validate cgroupfs conmon cgroup on start
  pkg/config/config.go
  pkg/config/config_test.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm

#3948 oci: add debug logs for runtime state calls
  internal/oci/runtime_oci.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#3858 contrib, cgroup v2: use kubernetes master
  contrib/test/integration/build/kubernetes.yml
  contrib/test/integration/e2e.yml
  contrib/test/integration/main.yml
  server/container_create_linux.go
  server/sandbox_run_linux.go
  server/server.go
  test/pod.bats
Labels: approved, dco-signoff: yes, lgtm

#3930 Return empty DecryptConfig when no keys to force decryption
  server/utils.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test

#3789 test: add circle job that runs with cgroupfs
  .circleci/config.yml
  scripts/circle-setup-cgroup_manager
  test/cgroups.bats
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm

#3924 runtime_vm: Ignore ttrpc.ErrClosed when shutting the container down
  internal/oci/runtime_vm.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test

#3952 internal/oci/runtime_vm: lock around map access
  internal/oci/runtime_vm.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#3912 [1.18] keep conmons created by execsyncs as direct children
  Makefile
  contrib/test/integration/build/conmon.yml
  internal/config/conmonmgr/conmonmgr.go
  internal/config/conmonmgr/conmonmgr_test.go
  internal/config/conmonmgr/suite_test.go
  internal/oci/oci_unix.go
  internal/oci/runtime_oci.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/suite_test.go
  test/mocks/cmdrunner/cmdrunner.go
  utils/cmdrunner/cmdrunner.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#3950 [1.18] change variable name err to retErr for deferred comparisons
  internal/oci/oci.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_vm.go
  server/container_create.go
  server/container_create_linux.go
  server/sandbox_network.go
  server/sandbox_run_linux.go
  utils/io/helpers.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-1.16, release-1.17, release-note

#3955 Bump testimage versions including golang
  .circleci/config.yml
  Makefile
  scripts/versions
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note-none

#3957 Close the done channel in runtimeOCI#ReopenContainerLog
  internal/oci/runtime_oci.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#3958 bump to version 1.18.3
  internal/version/version.go
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none

#3956 runtimeVM: Improve CreateContainer cleanup in case of failures
  internal/oci/runtime_vm.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test, release-note-none

#3929 Managed NS: update default configuration values
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  internal/lib/suite_test.go
  pkg/config/config.go
  pkg/config/template.go
  server/sandbox_run_test.go
  server/sandbox_stop_linux.go
  server/server_test_inject.go
  server/suite_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm

#3928 Update golangci lint to v1.28.3
  .golangci.yml
  Makefile
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note-none

#3972 [1.18] Revert "container_server: disable fdatasync() for atomic writes"
  cmd/crio/main.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#3964 change variable name err to retErr for deferred comparisons
  internal/oci/oci.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_vm.go
  server/container_create.go
  server/container_create_linux.go
  server/sandbox_network.go
  server/sandbox_run_linux.go
  utils/io/helpers.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#3969 Fix static binary mode retrieval for musl toolchains
  internal/version/version.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#3971 Use /usr/bin/env bash in crio-shutdown.service
  contrib/systemd/crio-shutdown.service
  contrib/systemd/crio-wipe.service
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#3932 Enable more feature tests
  contrib/test/integration/e2e-features.yml
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm

#3982 Remove resolvPath when Relabel fails
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test, release-note-none

#3980 Perform log directory validation early in Server#runPodSandbox
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#3898 container: move some relatively low hanging options
  pkg/container/container.go
  pkg/container/container_test.go
  server/container_create_linux.go
  server/sandbox_run.go
  server/sandbox_run_linux.go
  utils/utils.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3981 remove all cases of returning an error named err
  cmd/crio/wipe.go
  internal/config/cgmgr/cgroupfs.go
  internal/config/cgmgr/systemd.go
  internal/findprocess/findprocess.go
  internal/findprocess/findprocess_unix.go
  internal/findprocess/findprocess_windows.go
  internal/log/hook_filter.go
  internal/oci/oci_linux.go
  internal/oci/oci_unsupported.go
  internal/oci/runtime_oci.go
  pkg/config/sysctl.go
  server/container_attach.go
  server/container_create.go
  server/container_exec.go
  server/container_execsync.go
  server/container_list.go
  server/container_portforward.go
  server/container_remove.go
  server/container_reopen_log.go
  server/container_start.go
  server/container_stats.go
  server/container_stats_list.go
  server/container_status.go
  server/container_stop.go
  server/container_update_resources.go
  server/container_updateruntimeconfig.go
  server/image_fs_info.go
  server/image_list.go
  server/image_pull.go
  server/image_remove.go
  server/image_status.go
  server/naming.go
  server/runtime_status.go
  server/sandbox_list.go
  server/sandbox_network.go
  server/sandbox_remove.go
  server/sandbox_run.go
  server/sandbox_run_linux.go
  server/sandbox_run_unsupported.go
  server/sandbox_status.go
  server/sandbox_stop.go
  server/sandbox_stop_linux.go
  server/sandbox_stop_unsupported.go
  server/secrets.go
  server/version.go
  utils/fifo/fifo.go
  utils/filesystem.go
  utils/io/container_io.go
  utils/utils.go
  utils/utils_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none

#3989 Copy spec to not touch original spec on exec(sync)
  internal/oci/runtime_oci.go
  test/ctr.bats
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#3985 Add volume mount option for SELinux labeling
  Makefile
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test, release-note-none

#3978 Update the container resources under the spec
  internal/lib/container_server.go
  server/container_update_resources.go
  server/container_update_resources_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test, release-note

#3804 Cleanup and update nix derivation for static builds
  .circleci/config.yml
  Makefile
  contrib/test/integration/build/crun.yml
  nix/default.nix
  nix/nixpkgs.json
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note

#3990 Make integration-cgroupfs tests depdent on results
  .circleci/config.yml
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#3936 Provide functionality to disable and enable back the CPU load balancing
  go.sum
  internal/runtimehandlerhooks/high_performance_hooks.go
  internal/runtimehandlerhooks/high_performance_hooks_test.go
  internal/runtimehandlerhooks/runtime_handler_hooks.go
  server/container_start.go
  server/container_start_test.go
  server/container_stop.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpuset/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpuset/OWNERS
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpuset/cpuset.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/feature, lgtm, ok-to-test, release-note-none

#4001 Restore CPU load balancing just when an error appears
  server/container_start.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test, release-note-none

#3986 Add gofumpt linter and apply lint fixes
  .golangci.yml
  cmd/crio/main.go
  internal/config/seccomp/seccomp_test.go
  internal/criocli/criocli_test.go
  internal/lib/container_server.go
  internal/lib/logs_test.go
  internal/lib/rename.go
  internal/lib/sandbox/sandbox_test.go
  internal/lib/sandbox/suite_test.go
  internal/lib/suite_test.go
  internal/log/hook_test.go
  internal/log/interceptors.go
  internal/log/log.go
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/finished_unsupported.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_vm.go
  internal/storage/image_test.go
  internal/storage/runtime_test.go
  internal/version/version.go
  internal/version/version_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/config_windows.go
  pkg/config/reload_test.go
  scripts/dependencies/dependencies.go
  scripts/release-notes/release_notes.go
  server/container_create.go
  server/container_create_linux.go
  server/container_create_test.go
  server/container_list_test.go
  server/container_stop_test.go
  server/container_update_resources_test.go
  server/image_fs_info.go
  server/image_fs_info_test.go
  server/image_list_test.go
  server/image_pull_test.go
  server/image_status_test.go
  server/inspect_ginkgo_test.go
  server/metrics/metrics_test.go
  server/rootless.go
  server/sandbox_list_test.go
  server/sandbox_run_linux.go
  server/sandbox_run_test.go
  server/secrets.go
  server/server.go
  server/server_test.go
  server/suite_test.go
  server/useragent/suite_test.go
  server/useragent/useragent_test.go
  server/useragent/version_info_test.go
  server/utils_test.go
  utils/fifo/handle.go
  utils/io/helpers.go
  utils/utils.go
  utils/utils_test.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4007 Fix gofumpt lints
  internal/runtimehandlerhooks/high_performance_hooks.go
  internal/runtimehandlerhooks/high_performance_hooks_test.go
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#4006 Restore Sandbox createdAt timestamp on cri-o restart
  internal/lib/container_server.go
  internal/lib/sandbox/history_test.go
  internal/lib/sandbox/sandbox.go
  internal/lib/sandbox/sandbox_test.go
  internal/lib/sandbox/suite_test.go
  internal/lib/suite_test.go
  server/sandbox_run_linux.go
  server/suite_test.go
  test/restore.bats
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test, release-note

#4011 Bring back pprof
  cmd/crio/main.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4015 Fix unit-tests and regenerate mocks
  internal/lib/container_server_test.go
  test/mocks/containerstorage/containerstorage.go
  test/mocks/oci/oci.go
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#4013 [1.18] Regenerate mocks to fix the CI
  test/mocks/containerstorage/containerstorage.go
  test/mocks/oci/oci.go
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#4020 Remove unnecessary err assignment
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#3470 [1.17] port error: check for error
  internal/oci/runtime_oci.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3995 [1.11] Copy spec to not touch original spec on exec(sync)
  oci/oci.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none

#3987 runtime_vm: Avoid possible deadlock on UpdateContainerStatus()
  internal/oci/runtime_vm.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#3974 [1.17] replaces checks in defers from err to retErr
  internal/lib/sandbox/namespaces.go
  internal/oci/oci.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_vm.go
  internal/pkg/storage/runtime.go
  server/container_create.go
  server/container_create_linux.go
  server/sandbox_network.go
  server/sandbox_run_linux.go
  utils/io/helpers.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#3998 runtimeVM: Cleanup a "Completed" container
  internal/oci/runtime_vm.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#3772 Do not remove existing runtime handler
  pkg/config/config.go
  pkg/config/config_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test

#4002 name is reserved: give more informative error
  server/container_create.go
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4012 Speedup static build by utilizing CI cache on `/nix` folder
  .circleci/config.yml
  Dockerfile-nix
  Makefile
  nix/nixpkgs.json
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none

#4023 docs: fix cni documentation
  contrib/cni/11-crio-ipv4-bridge.conf
  contrib/cni/README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none

#4021 runtime_vm: set container creation time
  internal/oci/runtime_vm.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test, release-note-none

#4024 crio: use json-iterator/go instead of encoding/json
  cmd/crio/wipe.go
  go.mod
  internal/client/client.go
  internal/config/seccomp/seccomp.go
  internal/lib/container_server.go
  internal/lib/rename.go
  internal/oci/container.go
  internal/oci/runtime_oci.go
  internal/storage/runtime.go
  internal/version/version.go
  server/container_create_linux.go
  server/container_status.go
  server/image_status.go
  server/inspect.go
  server/sandbox_run_linux.go
  server/sandbox_status.go
  test/restore.bats
  utils/typeurl/types.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4031 exec sync: be more careful about temp files
  internal/oci/runtime_oci.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#3933 Improves container memory usage stats
  internal/config/cgmgr/cgmgr.go
  internal/config/cgmgr/cgmgr_test.go
  internal/config/cgmgr/cgroupfs.go
  internal/config/cgmgr/systemd.go
  internal/oci/oci_linux.go
  test/stats.bats
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test, release-note
