Repository cri-o/cri-o, pull requests merged in 2020-03, with the labels that each got.

#3318 Move pkg/config/seccomp package to internal/config/seccomp
  internal/config/seccomp/seccomp.go
  internal/config/seccomp/seccomp_test.go
  internal/config/seccomp/suite_test.go
  pkg/config/config.go
Labels: approved, dco-signoff: yes, kind/cleanup, size/XS

#3341 man page for crio.conf.d
  bundle/Makefile
  bundle/build
  completions/fish/crio.fish
  docs/crio-status.8.md
  docs/crio.8.md
  docs/crio.conf.5.md
  docs/crio.conf.d.5.md
  internal/pkg/criocli/criocli.go
  internal/pkg/criocli/documentation.go
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, ok-to-test, size/M

#3347 skip failing storage test
  contrib/test/integration/e2e.yml
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#3346 Fix 32bit build by vendoring latest go-selinux
  go.mod
  go.sum
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#3361 [1.17] bump to conmon 2.0.11
  .circleci/config.yml
  contrib/test/integration/build/conmon.yml
  go.mod
  go.sum
  scripts/build-test-image
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#3321 Add DEFAULTS_PATH to Makefile
  Makefile
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XS

#3328 CreateContainer: pass TerminationGracePeriod
  contrib/test/integration/build/crun.yml
  contrib/test/integration/build/runc.yml
  server/container_create_linux.go
  test/pod.bats
  test/testdata/container_config_sleep.json
Labels: approved, dco-signoff: yes, lgtm, needs-backport, ok-to-test, size/M

#3367 Let CRI-O start when `runc` is not in $PATH and not configured
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/testdata/config.toml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#3354 [1.16] Check for context erroring before returning from longer requests
  contrib/test/integration/golang.yml
  server/container_create.go
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#3350 test/conmonmon: fix getting conmon pid
  test/conmonmon.bats
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test, size/XS

#3359 [1.18] bump to conmon v2.0.11
  .circleci/config.yml
  contrib/test/integration/build/conmon.yml
  go.mod
  go.sum
  scripts/versions
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XL

#3264 [1.15] klog: don't write to /tmp
  cmd/crio/main.go
  go.mod
  go.sum
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#3331 Upload every successful built bundle to the GCS bucket
  .circleci/config.yml
  Makefile
  README.md
  scripts/build-test-image
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/M

#3364 [1.16] bump to conmon 2.0.11
  .circleci/config.yml
  contrib/test/integration/build/conmon.yml
  go.mod
  go.sum
  scripts/build-test-image
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#3332 [1.14] Use containers/conmon
  Dockerfile
  Makefile
  cmd/crio-config/config.go
  conmon/Makefile
  conmon/cmsg.c
  conmon/cmsg.h
  conmon/conmon.c
  conmon/ctr_logging.c
  conmon/ctr_logging.h
  conmon/utils.c
  conmon/utils.h
  contrib/test/ci/cri-o.spec
  contrib/test/integration/build/conmon.yml
  contrib/test/integration/main.yml
  go.mod
  go.sum
  lib/config.go
  oci/attach.go
  test/command.bats
  test/helpers.bash
  test/network.bats
  tutorial.md
  vendor/github.com/containers/conmon/LICENSE
  vendor/github.com/containers/conmon/runner/config/config.go
  vendor/github.com/containers/conmon/runner/config/config_unix.go
  vendor/github.com/containers/conmon/runner/config/config_windows.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#3343 Update golangci-lint to v1.23.8
  .circleci/config.yml
  Makefile
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#3275 [1.16] klog: don't write to /tmp
  cmd/crio/main.go
  go.mod
Labels: approved, dco-signoff: yes, lgtm, size/S

#3344 Use `Value` field in CLI for non-default values
  completions/fish/crio.fish
  docs/crio.8.md
  hack/validate/.validate
  internal/criocli/criocli.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/L

#3265 [1.14] klog: don't write to /tmp
  cmd/crio/main.go
  go.mod
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/S

#3357 Use static runc binary in CircleCI
  scripts/circle-setup
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#3335 Update Makefile targets and docs to crio.conf.d
  .circleci/config.yml
  Makefile
  bundle/Makefile
  bundle/build
  bundle/test
  contrib/cni/README.md
  contrib/test/integration/build/cri-o.yml
  contrib/test/integration/e2e-base.yml
  test/helpers.bash
  tutorials/decryption.md
  tutorials/kubeadm.md
  tutorials/metrics.md
  tutorials/setup.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/L

#3273 [1.13] port forward: drain the stream on error
  server/container_portforward.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3377 Restore sandbox selinux labels directly from config.json
  internal/lib/container_server.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#3378 [1.14] conmon: bump to 2.0.11
  Dockerfile
  contrib/test/integration/build/conmon.yml
  go.mod
  go.sum
  vendor/github.com/containers/conmon/runner/config/config.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#3060 Support pulling image specified by tag and digest.
  internal/storage/image.go
  internal/storage/image_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#3261 Add high level Sandbox and Container interface
  pkg/container/container.go
  pkg/sandbox/add_container.go
  pkg/sandbox/create.go
  pkg/sandbox/delete.go
  pkg/sandbox/remove_container.go
  pkg/sandbox/sandbox.go
  pkg/sandbox/start.go
  pkg/sandbox/stop.go
Labels: approved, dco-signoff: yes, kind/design, lgtm, size/M

#3383 Add gRPC method name to logs
  internal/log/interceptors.go
  internal/log/log.go
  internal/log/log_test.go
  server/image_status.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/M

#3363 [1.17] drop conmonmon
  go.mod
  internal/lib/conmonmon.go
  internal/lib/container_server.go
  server/container_create.go
  server/container_remove.go
  server/container_start.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/server.go
  test/conmonmon.bats
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-1.16, release-1.18, size/L

#3333 integration tests: switch to systemd cgroups
  README.md
  bundle/test
  contrib/test/integration/build/cri-o.yml
  contrib/test/integration/vars.yml
  internal/oci/oci_linux.go
  test/cgroups.bats
  test/helpers.bash
  test/pod.bats
  test/testdata/sandbox1_config.json
  test/testdata/sandbox2_config.json
  test/testdata/sandbox3_config.json
  test/testdata/sandbox_config.json
  test/testdata/sandbox_config_apparmor.json
  test/testdata/sandbox_config_hostnet.json
  test/testdata/sandbox_config_hostport.json
  test/testdata/sandbox_config_privileged.json
  test/testdata/sandbox_config_seccomp.json
  test/testdata/sandbox_config_selinux.json
  test/testdata/sandbox_config_sysctl.json
  test/testdata/sandbox_pidnamespacemode_config.json
  test/testdata/template_sandbox_config.json
Labels: approved, dco-signoff: yes, lgtm, size/M

#3384 Add target release version to generated notes
  Makefile
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#3355 bump to conmon 2.0.11
  .circleci/config.yml
  contrib/test/integration/build/conmon.yml
  go.mod
  go.sum
  scripts/versions
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/L

#3387 Add container config (set/get) to Container interface
  pkg/container/container.go
  pkg/container/container_test.go
  pkg/container/suite_test.go
  server/container_create.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/L

#3309 Take localhost/ images into account during pull
  server/image_pull.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/S

#3391 docs: add TOC to setup.md
  tutorials/setup.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#3390 Skip release notes generation for forks
  .circleci/config.yml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#3394 Remove Update() method
  internal/lib/container_server.go
  internal/lib/container_server_test.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/L, ¯\_(ツ)_/¯

#3345 Add runc, conmon, crictl and CNI plugins to bundle
  .circleci/config.yml
  bundle/Makefile
  bundle/README.md
  bundle/build
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/L

#3376 contrib: use crun 0.13
  contrib/test/integration/build/crun.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3405 [1.17] version: bump to 1.17.1
  completions/fish/crio.fish
  contrib/test/ci/cri-o.spec
  docs/crio-status.8.md
  docs/crio.8.md
  internal/version/version.go
Labels: dco-signoff: yes, kind/cleanup

#3402 Update golangci-lint to v1.24.0
  Makefile
  internal/storage/runtime.go
  pkg/config/config.go
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3408 Add initial gh-pages layout
  .circleci/config.yml
  README.md
  _config.yml
  _layouts/default.html
Labels: dco-signoff: yes, kind/documentation

#3411 bump conmon to 2.0.12
  .circleci/config.yml
  Makefile
  bundle/build
  contrib/test/integration/build/conmon.yml
  go.mod
  go.sum
  scripts/versions
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3404 build: make uninstall improvements
  Makefile
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3419 Mention starting cri-o for running with kubernetes
  README.md
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test

#3416 Remove utils.ExecCmdWithStdStreams in favor of utils.ExecCmd
  internal/oci/runtime_oci.go
  utils/utils.go
  utils/utils_test.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3414 Add PodSandboxConfig (get/set) to Sandbox interface
  Makefile
  pkg/sandbox/sandbox.go
  pkg/sandbox/sandbox_test.go
  pkg/sandbox/suite_test.go
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, ok-to-test

#3415 Simplify container log path handling
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3403 Move bundle to contrib and reuse version vars
  .circleci/config.yml
  .gitignore
  Makefile
  bundle/build
  contrib/bundle/Makefile
  contrib/bundle/README.md
  contrib/bundle/build
  contrib/bundle/test
  contrib/bundle/vars
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3381 test: move readonly_rootfs and privileged to correct place
  test/testdata/container_config.json
  test/testdata/container_config_by_imageid.json
  test/testdata/container_config_hostport.json
  test/testdata/container_config_logging.json
  test/testdata/container_config_privileged.json
  test/testdata/container_config_resolvconf.json
  test/testdata/container_config_seccomp.json
  test/testdata/container_config_sleep.json
  test/testdata/container_exit_test.json
  test/testdata/container_redis.json
  test/testdata/container_redis_apparmor.json
  test/testdata/container_redis_default_mounts.json
  test/testdata/container_redis_device.json
  test/testdata/container_redis_env_custom.json
  test/testdata/container_redis_namespace.json
  test/testdata/container_sleep.json
  test/testdata/template_container_config.json
Labels: approved, dco-signoff: yes, lgtm, size/M

#3388 [1.18] drop conmonmon
  go.mod
  internal/lib/conmonmon.go
  internal/lib/container_server.go
  server/container_create.go
  server/container_remove.go
  server/container_start.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/server.go
  test/conmonmon.bats
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/L

#3425 stats: prevent a segfault
  server/container_stats.go
  server/container_stats_list.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3421 Add further kinds to pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, area/dependency, dco-signoff: yes, kind/documentation

#3426 Switch back to machine executor for CI lint stage
  .circleci/config.yml
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3409 avoid parallel pulls of the same image
  server/image_pull.go
  server/server.go
Labels: approved, dco-signoff: yes, lgtm

#3412 server: Return grpc code NotFound when we can't find a container or pod
  server/container_attach.go
  server/container_exec.go
  server/container_execsync.go
  server/container_remove.go
  server/container_start.go
  server/container_status.go
  server/container_stop.go
  server/sandbox_status.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3434 Add kind/dependency-change label
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm

#3432 [1.13] use containers/conmon
  Dockerfile
  Makefile
  cmd/crio-config/config.go
  conmon/Makefile
  conmon/cmsg.c
  conmon/cmsg.h
  conmon/conmon.c
  contrib/test/ci/cri-o.spec
  contrib/test/integration/build/conmon.yml
  contrib/test/integration/main.yml
  lib/config.go
  test/command.bats
  test/helpers.bash
  test/network.bats
  tutorial.md
  vendor/github.com/containers/conmon/LICENSE
  vendor/github.com/containers/conmon/runner/config/config.go
  vendor/github.com/containers/conmon/runner/config/config_unix.go
  vendor/github.com/containers/conmon/runner/config/config_windows.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3439 [1.13] bump conmon to 2.0.12
  Dockerfile
  contrib/test/integration/build/conmon.yml
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm

#3398 [1.18] stats: fix stats when systemd cgroups are used
  internal/oci/oci_linux.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3407 Publish release notes on gh-pages branch
  .circleci/config.yml
  Makefile
  go.sum
  scripts/latest-version/latest_version.go
  scripts/release-notes/release_notes.go
Labels: approved, dco-signoff: yes, kind/documentation, lgtm

#3435 tree_status: show the git diff
  hack/tree_status.sh
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3290 [1.17] port forward: drain the stream on error
  internal/oci/runtime_oci.go
  server/container_portforward.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3340 Add release-branch-forward script
  scripts/release-branch-forward/release-branch-forward.go
Labels: approved, dco-signoff: yes, kind/design, lgtm, size/L

#3451 Add OWNERS to gh-pages branch
  OWNERS
Labels: dco-signoff: yes, kind/cleanup

#3393 Add SetNameAndID to Container interface
  pkg/container/container.go
  pkg/container/container_setconfig_test.go
  pkg/container/container_setnameandid_test.go
  pkg/container/container_test.go
  server/container_create.go
  server/naming.go
  server/naming_test.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/L

#3449 [release-1.17] avoid parallel pulls of the same image
  server/image_pull.go
  server/server.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm

#3446 Fix gh-pages content width
  assets/css/style.scss
Labels: approved, dco-signoff: yes, kind/documentation, lgtm

#3433 stats: fix some style nits
  internal/oci/oci_linux.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3399 [1.18] use master circle images
  .circleci/config.yml
  Makefile
  contrib/test/integration/golang.yml
  contrib/test/integration/main.yml
  go.mod
  go.sum
  vendor/github.com/Microsoft/hcsshim/mksyscall_windows.go
  vendor/github.com/containers/storage/pkg/archive/example_changes.go
  vendor/github.com/creack/pty/types.go
  vendor/github.com/creack/pty/types_dragonfly.go
  vendor/github.com/creack/pty/types_freebsd.go
  vendor/github.com/creack/pty/types_openbsd.go
  vendor/github.com/docker/docker/pkg/archive/example_changes.go
  vendor/github.com/klauspost/compress/flate/gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/github.com/urfave/cli/build.go
  vendor/github.com/urfave/cli/v2/build.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3448 [1.17] Fix docs generation
  docs/crio-status.8.md
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm

#3445 Fix gh-pages push for remote branch
  scripts/release-notes/release_notes.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3431 [1.17] stats fixes
  internal/oci/oci_linux.go
  server/container_stats.go
  server/container_stats_list.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3457 server/ContainerStatus: don't lock for c.State()
  server/container_status.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3456 version: Release 1.16.4
  internal/version/version.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm

#3450 Add linkmode to crio version output
  internal/version/version.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm

#3440 Added integration test to make sure annotations are passed through to…
  test/ctr.bats
Labels: approved, dco-signoff: yes, lgtm

#3458 [1.17] server/ContainerStatus: don't lock for c.State()
  server/container_status.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3462 Add shell format check and apply diff
  .circleci/config.yml
  Makefile
  go.mod
  go.sum
  hack/apparmor_tag.sh
  hack/btrfs_installed_tag.sh
  hack/btrfs_tag.sh
  hack/libdm_installed.sh
  hack/libdm_no_deferred_remove_tag.sh
  hack/seccomp_tag.sh
  hack/selinux_tag.sh
  hack/tree_status.sh
  internal/tools/tools.go
  test/cni_plugin_helper.bash
  test/helpers.bash
  test/hooks/checkhook.sh
  test/test_runner.sh
  vendor/github.com/pkg/diff/LICENSE
  vendor/github.com/pkg/diff/adapter.go
  vendor/github.com/pkg/diff/context.go
  vendor/github.com/pkg/diff/diff.go
  vendor/github.com/pkg/diff/doc.go
  vendor/github.com/pkg/diff/fuzz.go
  vendor/github.com/pkg/diff/go.mod
  vendor/github.com/pkg/diff/go.sum
  vendor/github.com/pkg/diff/myers.go
  vendor/github.com/pkg/diff/op_string.go
  vendor/github.com/pkg/diff/print.go
  vendor/github.com/pkg/diff/readme.md
  vendor/modules.txt
  vendor/mvdan.cc/editorconfig/.gitmodules
  vendor/mvdan.cc/editorconfig/CMakeLists.txt
  vendor/mvdan.cc/editorconfig/LICENSE
  vendor/mvdan.cc/editorconfig/README.md
  vendor/mvdan.cc/editorconfig/editorconfig.go
  vendor/mvdan.cc/editorconfig/go.mod
  vendor/mvdan.cc/editorconfig/go.sum
  vendor/mvdan.cc/editorconfig/pattern_bundle.go
  vendor/mvdan.cc/sh/v3/LICENSE
  vendor/mvdan.cc/sh/v3/cmd/shfmt/Dockerfile
  vendor/mvdan.cc/sh/v3/cmd/shfmt/json.go
  vendor/mvdan.cc/sh/v3/cmd/shfmt/main.go
  vendor/mvdan.cc/sh/v3/fileutil/file.go
  vendor/mvdan.cc/sh/v3/syntax/braces.go
  vendor/mvdan.cc/sh/v3/syntax/canonical.sh
  vendor/mvdan.cc/sh/v3/syntax/doc.go
  vendor/mvdan.cc/sh/v3/syntax/lexer.go
  vendor/mvdan.cc/sh/v3/syntax/nodes.go
  vendor/mvdan.cc/sh/v3/syntax/parser.go
  vendor/mvdan.cc/sh/v3/syntax/printer.go
  vendor/mvdan.cc/sh/v3/syntax/quotestate_string.go
  vendor/mvdan.cc/sh/v3/syntax/simplify.go
  vendor/mvdan.cc/sh/v3/syntax/token_string.go
  vendor/mvdan.cc/sh/v3/syntax/tokens.go
  vendor/mvdan.cc/sh/v3/syntax/walk.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm

#3459 Add hint to release notes on gh-pages to README.md
  .circleci/config.yml
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm

#3452 Add cni-default-network option
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  contrib/cni/10-crio-bridge.conf
  contrib/cni/README.md
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  pkg/config/config.go
  pkg/config/template.go
  server/server.go
  test/helpers.bash
  test/network.bats
  tutorials/kubernetes.md
Labels: approved, dco-signoff: yes, kind/feature, lgtm

#3119 remove NET_RAW and SYS_CHROOT capability by default
  Vagrantfile
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  contrib/test/integration/critest.yml
  contrib/test/integration/e2e-base.yml
  contrib/test/integration/e2e.yml
  contrib/test/integration/system-packages.yml
  contrib/test/integration/system.yml
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  pkg/config/config.go
  test/ctr.bats
  test/helpers.bash
  test/network_ping.bats
  test/pod.bats
  test/testdata/container_config_ping.json
  tutorials/setup.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/L

#3385 Fix unit tests for locally configured registries
  internal/storage/image_test.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/M

#3476 Do not Wrapf errors if no format is specified
  internal/log/hook_filter.go
  internal/oci/oci_linux.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_vm.go
  pkg/config/config.go
  scripts/release-notes/release_notes.go
  server/container_create.go
  server/container_create_linux.go
  server/sandbox_run_linux.go
  server/secrets.go
  server/server.go
  utils/errdefs/grpc.go
  utils/io/container_io.go
  utils/utils.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3423 drop conmonmon
  go.mod
  internal/lib/conmonmon.go
  internal/lib/container_server.go
  server/container_create.go
  server/container_remove.go
  server/container_start.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/server.go
  test/conmonmon.bats
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3479 [1.17] bump to 1.17.2
  completions/fish/crio.fish
  docs/crio.8.md
  internal/version/version.go
Labels: approved, dco-signoff: yes, kind/documentation, lgtm

#3477 Add description to magic test value
  test/ctr.bats
Labels: approved, dco-signoff: yes, kind/documentation, lgtm

#3483 test: set cri-o systemd restart policy to no
  contrib/test/integration/build/cri-o.yml
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm

#3373 contrib: Add kube-local tool
  contrib/kube-local/README.md
  contrib/kube-local/examples/script
  contrib/kube-local/kube-local
  contrib/kube-local/kube-local.profile
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XXL

#3480 build: Makefile - add shfmt target to help
  Makefile
Labels: approved, dco-signoff: yes, kind/documentation, lgtm

#3488 build: clean generated bin/ dir
  Makefile
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3485 Downgrade golangci-lint to v1.23.8
  .circleci/config.yml
  Makefile
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm

#3493 Use HEAD for runc built from source
  contrib/test/integration/build/runc.yml
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm

#3494 vendor: use directly github.com/creack/pty
  go.mod
  go.sum
  internal/oci/oci_unix.go
  vendor/github.com/creack/pty/Dockerfile.riscv
  vendor/github.com/creack/pty/go.mod
  vendor/github.com/kr/pty/.gitignore
  vendor/github.com/kr/pty/LICENSE
  vendor/github.com/kr/pty/README.md
  vendor/github.com/kr/pty/go.mod
  vendor/github.com/kr/pty/go.sum
  vendor/github.com/kr/pty/shim.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm
