Repository cri-o/cri-o, pull requests merged in 2020-02, with the labels that each got.

#3177 build: make install providing systemd and config
  Makefile
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#3131 [1.16] Update test grid
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3174 [1.17] Allow server to start without config
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/pkg/criocli/criocli.go
  pkg/config/config.go
  pkg/config/reload_test.go
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3163 [1.17] fail on network stop
  internal/lib/container_server.go
  internal/lib/sandbox/namespaces.go
  internal/lib/sandbox/namespaces_test.go
  internal/lib/sandbox/sandbox.go
  internal/lib/sandbox/sandbox_test.go
  server/container_create_test.go
  server/sandbox_network.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
  server/sandbox_stop_test.go
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#3182 sandbox: skip memory check if set to "max"
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3185 Add the container IDs that cri-o assigns to various logs
  server/container_create.go
  server/container_remove.go
  server/container_start.go
  server/container_stop.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3178 config: move default version file location to tmpfs
  completions/fish/crio.fish
  docs/crio.8.md
  docs/crio.conf.5.md
  pkg/config/config_unix.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3191 docs: improve setup.md
  tutorials/setup.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#3193 Setup container environment variables before user
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3192 [1.17] fix unit tests
  pkg/config/config_test.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3196 Update golangci-lint to v1.23.3
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3164 fail on network stop
  internal/lib/container_server.go
  internal/lib/sandbox/namespaces.go
  internal/lib/sandbox/namespaces_test.go
  internal/lib/sandbox/sandbox.go
  internal/lib/sandbox/sandbox_test.go
  server/container_create_test.go
  server/sandbox_network.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
  server/sandbox_stop_test.go
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#3184 [1.17] move default version file location a tmpfs
  completions/fish/crio.fish
  docs/crio.8.md
  docs/crio.conf.5.md
  pkg/config/config_unix.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3188 [1.16] Add the container IDs that cri-o assigns to various logs
  server/container_create.go
  server/container_remove.go
  server/container_start.go
  server/container_stop.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3166 Add `crio version` subcommand
  Makefile
  cmd/crio/main.go
  cmd/crio/version.go
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  internal/version/version.go
  test/version.bats
Labels: approved, dco-signoff: yes, lgtm, size/L

#3187 [1.17] Add the container IDs that cri-o assigns to various logs
  server/container_create.go
  server/container_remove.go
  server/container_start.go
  server/container_stop.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3207 [1.16] update github.com/containers/image
  go.mod
  go.sum
  vendor/github.com/containers/image/v5/docker/docker_client.go
  vendor/github.com/containers/image/v5/docker/docker_image_dest.go
  vendor/github.com/containers/image/v5/docker/docker_image_src.go
  vendor/github.com/containers/image/v5/docker/tarfile/dest.go
  vendor/github.com/containers/image/v5/docker/tarfile/src.go
  vendor/github.com/containers/image/v5/image/docker_schema2.go
  vendor/github.com/containers/image/v5/image/oci.go
  vendor/github.com/containers/image/v5/internal/iolimits/iolimits.go
  vendor/github.com/containers/image/v5/openshift/openshift.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#3201 contrib: 10-crio-bridge.conf change subnet
  contrib/cni/10-crio-bridge.conf
Labels: approved, dco-signoff: yes, lgtm, ok-to-test

#3212 Unwrap errors from label.Relabel() before checking for ENOTSUP
  server/label_linux.go
  server/sandbox_run_linux.go
  server/secrets.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3183 [1.17] Revert "infra: remove unneeded uses of infra container"
  internal/lib/container_server.go
  internal/lib/sandbox/sandbox.go
  internal/oci/container.go
  server/container_create.go
  server/container_create_generic.go
  server/container_create_linux.go
  server/sandbox_list.go
  server/sandbox_list_test.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/sandbox_status.go
  server/sandbox_stop_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#3203 Skip invalid hooks directories by default
  completions/fish/crio.fish
  docs/crio.8.md
  internal/pkg/criocli/criocli.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/template.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3209 Fix reload behavior for unqualified search registries
  internal/pkg/storage/image.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3214 drop host_ip from crio.conf.5.md
  docs/crio.conf.5.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3206 [1.17] update github.com/containers/image
  go.mod
  go.sum
  vendor/github.com/containers/image/v5/docker/docker_client.go
  vendor/github.com/containers/image/v5/docker/docker_image_dest.go
  vendor/github.com/containers/image/v5/docker/docker_image_src.go
  vendor/github.com/containers/image/v5/docker/tarfile/dest.go
  vendor/github.com/containers/image/v5/docker/tarfile/src.go
  vendor/github.com/containers/image/v5/image/docker_schema2.go
  vendor/github.com/containers/image/v5/image/oci.go
  vendor/github.com/containers/image/v5/internal/iolimits/iolimits.go
  vendor/github.com/containers/image/v5/openshift/openshift.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#3208 [1.15] update github.com/containers/image
  go.mod
  go.sum
  lib/container_server_test.go
  test/image.bats
  vendor/github.com/containers/image/v5/docker/docker_client.go
  vendor/github.com/containers/image/v5/docker/docker_image_dest.go
  vendor/github.com/containers/image/v5/docker/docker_image_src.go
  vendor/github.com/containers/image/v5/docker/tarfile/dest.go
  vendor/github.com/containers/image/v5/docker/tarfile/src.go
  vendor/github.com/containers/image/v5/image/docker_schema2.go
  vendor/github.com/containers/image/v5/image/oci.go
  vendor/github.com/containers/image/v5/internal/iolimits/iolimits.go
  vendor/github.com/containers/image/v5/openshift/openshift.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#3217 [1.16] Vendor latest opencontainers/runtime-tools
  go.mod
  go.sum
  vendor/github.com/opencontainers/runtime-tools/generate/generate.go
  vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/M

#3210 [1.14] update github.com/containers/image
  go.mod
  go.sum
  test/image.bats
  vendor/github.com/containers/image/v5/docker/docker_client.go
  vendor/github.com/containers/image/v5/docker/docker_image_dest.go
  vendor/github.com/containers/image/v5/docker/docker_image_src.go
  vendor/github.com/containers/image/v5/docker/tarfile/dest.go
  vendor/github.com/containers/image/v5/docker/tarfile/src.go
  vendor/github.com/containers/image/v5/image/docker_schema2.go
  vendor/github.com/containers/image/v5/image/oci.go
  vendor/github.com/containers/image/v5/internal/iolimits/iolimits.go
  vendor/github.com/containers/image/v5/openshift/openshift.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#3215 [1.17] drop host_ip
  completions/fish/crio.fish
  docs/crio.8.md
  docs/crio.conf.5.md
  go.mod
  go.sum
  internal/pkg/criocli/criocli.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/template.go
  server/server.go
  vendor/github.com/urfave/cli/v2/.gitignore
  vendor/github.com/urfave/cli/v2/.travis.yml
  vendor/github.com/urfave/cli/v2/README.md
  vendor/github.com/urfave/cli/v2/app.go
  vendor/github.com/urfave/cli/v2/appveyor.yml
  vendor/github.com/urfave/cli/v2/category.go
  vendor/github.com/urfave/cli/v2/command.go
  vendor/github.com/urfave/cli/v2/context.go
  vendor/github.com/urfave/cli/v2/docs.go
  vendor/github.com/urfave/cli/v2/errors.go
  vendor/github.com/urfave/cli/v2/flag_float64.go
  vendor/github.com/urfave/cli/v2/flag_path.go
  vendor/github.com/urfave/cli/v2/flag_timestamp.go
  vendor/github.com/urfave/cli/v2/help.go
  vendor/github.com/urfave/cli/v2/parse.go
  vendor/github.com/urfave/cli/v2/template.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#3223 [1.14] Bump up version to 1.14.12
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3211 [1.13] update github.com/containers/image
  vendor/github.com/containers/image/docker/docker_client.go
  vendor/github.com/containers/image/docker/docker_image_dest.go
  vendor/github.com/containers/image/docker/docker_image_src.go
  vendor/github.com/containers/image/docker/tarfile/dest.go
  vendor/github.com/containers/image/docker/tarfile/src.go
  vendor/github.com/containers/image/image/docker_schema2.go
  vendor/github.com/containers/image/image/oci.go
  vendor/github.com/containers/image/internal/iolimits/iolimits.go
  vendor/github.com/containers/image/openshift/openshift.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#3225 [1.16] Bump up version to 1.16.3
  internal/version/version.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3082 [1.15] Set process label to privileged when host network is true
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3189 [1.14] Add the container IDs that cri-o assigns to various logs
  server/container_create.go
  server/container_remove.go
  server/container_start.go
  server/container_stop.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3228 fix server restore to not remove podman containers
  cmd/crio/wipe.go
  go.sum
  internal/lib/container_server.go
  internal/lib/container_server_test.go
  internal/pkg/storage/utils.go
  server/container_create_linux.go
  server/sandbox_run_linux.go
  server/server.go
  server/server_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#3227 [1.17] Fix server restore to not remove podman containers
  cmd/crio/wipe.go
  go.sum
  internal/lib/container_server.go
  internal/lib/container_server_test.go
  internal/pkg/storage/utils.go
  server/container_create_linux.go
  server/sandbox_run_linux.go
  server/server.go
  server/server_test.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3226 bump to v1.17.0
  completions/fish/crio.fish
  docs/crio.8.md
  internal/version/version.go
Labels: approved, dco-signoff: yes, size/XS

#3222 [1.13] Bump version to 1.13.12
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3224 [1.15] Bump version to 1.15.3
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3230 [1.17] oci: handle timeouts correctly for probes
  .circleci/config.yml
  go.mod
  go.sum
  internal/oci/runtime_oci.go
  scripts/build-test-image
  vendor/github.com/containers/conmon/runner/config/config.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/M

#3231 oci: Handle timeouts correctly for probes
  internal/oci/runtime_oci.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3190 [1.13] Add the container IDs that cri-o assigns to various logs
  server/container_create.go
  server/container_remove.go
  server/container_start.go
  server/container_stop.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3219 [1.13] Vendor latest opencontainers/runtime-tools
  vendor.conf
  vendor/github.com/opencontainers/runtime-spec/README.md
  vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
  vendor/github.com/opencontainers/runtime-tools/README.md
  vendor/github.com/opencontainers/runtime-tools/generate/config.go
  vendor/github.com/opencontainers/runtime-tools/generate/generate.go
  vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default.go
  vendor/github.com/opencontainers/runtime-tools/validate/validate_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/XL

#3202 Bump containers storage to v1.15.8
  go.sum
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3216 [1.14] Vendor latest opencontainers/runtime-tools
  go.mod
  go.sum
  vendor/github.com/opencontainers/runtime-tools/generate/generate.go
  vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/M

#3204 Add log context to container stats
  server/container_stats.go
  server/container_stats_list.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3235 contrib: use crun from the containers repository
  contrib/test/integration/build/crun.yml
Labels: approved, dco-signoff: yes, lgtm, size/S

#3218 [1.11] port forward: drain the stream on error
  Dockerfile
  Makefile
  build/bin/go-md2man
  contrib/test/integration/ansible.cfg
  contrib/test/integration/build/kubetest.yml
  contrib/test/integration/callback_plugins/default.py
  contrib/test/integration/disable_swap.yml
  contrib/test/integration/e2e.yml
  contrib/test/integration/golang.yml
  contrib/test/integration/main.yml
  server/container_create.go
  server/container_portforward.go
  test/helpers.bash
  vendor.conf
  vendor/github.com/containers/libpod/LICENSE
  vendor/github.com/containers/libpod/README.md
  vendor/github.com/containers/libpod/pkg/rootless/rootless_linux.c
  vendor/github.com/containers/libpod/pkg/rootless/rootless_linux.go
  vendor/github.com/containers/libpod/pkg/rootless/rootless_unsupported.go
  vendor/github.com/containers/libpod/pkg/secrets/secrets.go
  vendor/github.com/containers/libpod/vendor.conf
Labels: dco-signoff: yes, size/XXL

#3236 contrib: drop system containers
  contrib/system_containers/centos/Dockerfile
  contrib/system_containers/centos/README.md
  contrib/system_containers/centos/cccp.yml
  contrib/system_containers/centos/config.json.template
  contrib/system_containers/centos/manifest.json
  contrib/system_containers/centos/run.sh
  contrib/system_containers/centos/service.template
  contrib/system_containers/centos/set_mounts.sh
  contrib/system_containers/centos/tmpfiles.template
  contrib/system_containers/fedora/Dockerfile
  contrib/system_containers/fedora/README.md
  contrib/system_containers/fedora/config.json.template
  contrib/system_containers/fedora/manifest.json
  contrib/system_containers/fedora/run.sh
  contrib/system_containers/fedora/service.template
  contrib/system_containers/fedora/set_mounts.sh
  contrib/system_containers/fedora/tmpfiles.template
  contrib/system_containers/rhel/Dockerfile
  contrib/system_containers/rhel/config.json.template
  contrib/system_containers/rhel/help.md
  contrib/system_containers/rhel/manifest.json
  contrib/system_containers/rhel/run.sh
  contrib/system_containers/rhel/service.template
  contrib/system_containers/rhel/set_mounts.sh
  contrib/system_containers/rhel/tmpfiles.template
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#3237 Add pinns binary to static bundle
  bundle/Makefile
  bundle/build
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3238 [1.17] update installation info for debian and forks
  README.md
  tutorials/setup.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#3240 update installation info for debian and forks
  README.md
  tutorials/setup.md
Labels: approved, dco-signoff: yes, size/M

#3234 Remove trailing whitespaces from configuration template
  pkg/config/template.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3241 Make SIGHUP reload for drop-in config dir work
  cmd/crio/config.go
  cmd/crio/main.go
  cmd/crio/wipe.go
  internal/pkg/criocli/criocli.go
  pkg/config/config.go
  pkg/config/reload.go
  pkg/config/reload_test.go
  server/server.go
  server/server_test.go
  server/suite_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#3243 [1.17] exec: Close pipe fds to prevent hangs
  internal/oci/runtime_oci.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3244 Update nix package dependencies and cleanup default.nix
  .circleci/config.yml
  Makefile
  bundle/Makefile
  bundle/build
  nix/default.nix
  nix/nixpkgs.nix
Labels: approved, dco-signoff: yes, lgtm, size/M

#3249 Pass down the integer value of the stop signal
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/kill.go
  internal/oci/runtime_oci.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3255 [1.16] Pass down the integer value of the stop signal
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/kill.go
  internal/oci/runtime_oci.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3252 [1.14] exec: Close pipe fds to prevent hangs
  oci/runtime_oci.go
  test/testdata/labeled_container_redis.json
Labels: approved, dco-signoff: yes, lgtm, size/S

#3253 klog: don't write to /tmp
  cmd/crio/main.go
  go.mod
Labels: approved, dco-signoff: yes, lgtm, size/S

#3258 [1.15] Pass down the integer value of the stop signal
  oci/container.go
  oci/container_test.go
  oci/kill.go
  oci/runtime_oci.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3248 exec: Close pipe fds to prevent hangs
  internal/oci/runtime_oci.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3257 [1.13] Pass down the integer value of the stop signal
  lib/kill.go
  oci/container.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3256 [1.14] Pass down the integer value of the stop signal
  oci/container.go
  oci/container_test.go
  oci/kill.go
  oci/runtime_oci.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3044 [1.15] Add conmonmon
  go.mod
  go.sum
  lib/conmonmon.go
  lib/container_server.go
  oci/oci.go
  oci/runtime_oci.go
  server/container_create.go
  server/container_remove.go
  server/container_start.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/server.go
  test/conmonmon.bats
  vendor/github.com/containers/psgo/README.md
  vendor/github.com/containers/psgo/internal/process/process.go
  vendor/github.com/containers/psgo/psgo.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/XL

#3270 conmonmon: errorf when OOM killing
  internal/lib/conmonmon.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3032 [1.14] bump to containers storage 1.13.6
  go.mod
  go.sum
  vendor/github.com/containers/storage/VERSION
  vendor/github.com/containers/storage/pkg/tarlog/tarlogger.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/S

#3266 [1.13] klog: don't write to /tmp
  cmd/crio/main.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3281 Update pinns build and add small cleanups
  pinns/Makefile
  pinns/pinns.c
  pinns/utils.h
Labels: approved, dco-signoff: yes, lgtm, size/S

#3279 [1.14] Restore sandbox selinux labels directly from config.json
  lib/container_server.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3274 [1.14] port forward: drain the stream on error
  oci/runtime_oci.go
  server/container_portforward.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3288 [1.15] port forward: drain the stream on error
  oci/runtime_oci.go
  server/container_portforward.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3282 Add user-notice about minimal ctr_stop_timeout
  completions/fish/crio.fish
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/oci/oci.go
  internal/pkg/criocli/criocli.go
  pkg/config/config.go
  pkg/config/template.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3287 Remove version marker from AppArmor profile
  completions/fish/crio.fish
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/pkg/criocli/criocli.go
  pkg/config/config.go
  pkg/config/template.go
  test/helpers.bash
  test/testdata/fake_crio_default
Labels: approved, dco-signoff: yes, lgtm, size/S

#3246 Add live reload to DecryptionKeysPath
  pkg/config/config.go
  pkg/config/reload.go
  pkg/config/template.go
  server/image_pull.go
  server/server.go
  server/utils.go
  server/utils_test.go
  test/reload_config.bats
Labels: approved, dco-signoff: yes, lgtm, size/M

#3245 contrib: add tests for cgroup v2
  contrib/test/integration/build/cri-o.yml
  contrib/test/integration/build/crun.yml
  contrib/test/integration/main.yml
  contrib/test/integration/vars.yml
  server/container_create_linux.go
  test/ctr.bats
  test/ctr_userns.bats
  test/image_volume.bats
  test/restore.bats
Labels: approved, dco-signoff: yes, lgtm, size/L

#3299 [1.11] update containers/image
  vendor.conf
  vendor/github.com/containers/image/docker/docker_client.go
  vendor/github.com/containers/image/docker/docker_image_dest.go
  vendor/github.com/containers/image/docker/docker_image_src.go
  vendor/github.com/containers/image/docker/tarfile/dest.go
  vendor/github.com/containers/image/docker/tarfile/src.go
  vendor/github.com/containers/image/image/docker_schema2.go
  vendor/github.com/containers/image/image/oci.go
  vendor/github.com/containers/image/internal/iolimits/iolimits.go
  vendor/github.com/containers/image/openshift/openshift.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#3306 Fix Fedora based tests
  contrib/test/integration/main.yml
  contrib/test/integration/vars.yml
  test/helpers.bash
Labels: approved, dco-signoff: yes, lgtm, size/S

#3307 cgroups: parse cgroup.controllers once
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3271 Uppercase first log char per default
  internal/pkg/log/hook_filter.go
  internal/pkg/log/hook_filter_test.go
  test/helpers.bash
Labels: approved, dco-signoff: yes, lgtm, size/S

#3308 server, cgroupv2: do not create cgroupns
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3296 wipe: Add a force flag for skipping version check
  cmd/crio/wipe.go
  completions/fish/crio.fish
  docs/crio.8.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#3297 Add cgroup namespace unsharing to pinns
  .clang-format
  pinns/pinns.c
Labels: approved, dco-signoff: yes, lgtm, size/L

#3303 Automatically retrieve digest in test image builds
  .circleci/config.yml
  Makefile
  scripts/build-test-image
Labels: approved, dco-signoff: yes, lgtm, size/M

#3269 Change CircleCI config to build all jobs for all tags
  .circleci/config.yml
Labels: approved, dco-signoff: yes, lgtm, size/M

#3300 Add live configuration reload to seccomp profile
  pkg/config/config.go
  pkg/config/reload.go
  pkg/config/reload_test.go
  pkg/config/seccomp/seccomp.go
  pkg/config/seccomp/seccomp_test.go
  pkg/config/seccomp/suite_test.go
  pkg/config/template.go
  server/container_create.go
  server/sandbox_run_linux.go
  server/server.go
  server/server_test.go
  test/docs-validation/main.go
  test/reload_config.bats
Labels: approved, dco-signoff: yes, lgtm, size/L

#3312 Drop support for golang < v1.12
  .circleci/config.yml
  Makefile
  cmd/crio/main.go
  internal/oci/runtime_vm.go
  scripts/build-test-image
  scripts/circle-setup
  scripts/versions
  tutorials/setup.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#3316 Fix markdown for generated crio/crio-status docs
  docs/crio-status.8.md
  docs/crio.8.md
  internal/pkg/criocli/documentation.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#3314 Cleanup config default values
  pkg/config/config.go
Labels: approved, config change, dco-signoff: yes, lgtm, size/M

#3319 Make bin/pinns a PHONY target
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3323 Remove extra check for go modules in Makefile
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/S

#3320 Improve crio --version / version output
  Makefile
  cmd/crio-status/main.go
  cmd/crio/main.go
  internal/version/version.go
  internal/version/version_test.go
  server/useragent/useragent.go
  server/version.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3325 [1.18] Set k8s version to 1.18 for e2e and e2e-features tests
  contrib/test/integration/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3322 Rebuild bin/* targets on *.go file changes
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3313 Add live configuration reload to AppArmor profile
  internal/config/apparmor/apparmor.go
  internal/config/apparmor/apparmor_test.go
  internal/config/apparmor/suite_test.go
  pkg/config/config.go
  pkg/config/reload.go
  pkg/config/reload_test.go
  pkg/config/template.go
  server/container_create.go
  server/container_create_linux.go
  server/server.go
  test/reload_config.bats
Labels: approved, dco-signoff: yes, lgtm, size/L

#3329 Upgrade CI to use go 1.14
  .circleci/config.yml
  Makefile
  contrib/test/integration/golang.yml
  contrib/test/integration/main.yml
  go.mod
  go.sum
  scripts/build-test-image
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#3315 Apply Kubernetes PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#3324 Add CI bundle tests
  .circleci/config.yml
  Makefile
  bundle/build
  bundle/test
  bundle/vars
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/M
