Repository cri-o/cri-o, pull requests merged in 2020-01, with the labels that each got.

#3063 managed namespaces: manage user ns
  internal/lib/container_server.go
  internal/lib/sandbox/namespaces.go
  internal/lib/sandbox/namespaces_linux.go
  internal/lib/sandbox/namespaces_test.go
  internal/lib/sandbox/sandbox.go
  pinns/pinns.c
  server/container_create_linux.go
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#3064 InfraContainer(): drop some unneeded calls
  internal/lib/container_server.go
  internal/lib/sandbox/sandbox.go
  internal/oci/container.go
  server/container_create.go
  server/container_create_generic.go
  server/container_create_linux.go
  server/sandbox_list.go
  server/sandbox_list_test.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/sandbox_status.go
  server/sandbox_stop_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#3068 [1.16] Use golang 1.13
  contrib/test/integration/golang.yml
  contrib/test/integration/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3069 Bump golangci-lint to v1.22.2
  .golangci.yml
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3065 [1.16] oci: Handle timeouts correctly for probes
  .circleci/config.yml
  contrib/test/integration/build/conmon.yml
  go.mod
  go.sum
  internal/oci/runtime_oci.go
  scripts/build-test-image
  vendor/github.com/containers/conmon/runner/config/config.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/M

#3074 Fix possible segmentation fault in error handling
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, lgtm, release-1.17, size/XS

#3075 [1.17] Set k8s version to 1.17 for e2e and e2e-features tests
  contrib/test/integration/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3073 Cleanup sandbox shared memory before removing it
  internal/lib/sandbox/sandbox.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
Labels: approved, dco-signoff: yes, lgtm, release-1.17, size/M

#2878 [1.15] test: add changes required for fedora 30 AMI
  .circleci/config.yml
  contrib/test/integration/ansible.cfg
  contrib/test/integration/build/parallel.yml
  contrib/test/integration/callback_plugins/default.py
  contrib/test/integration/disable_swap.yml
  contrib/test/integration/e2e-base.yml
  contrib/test/integration/e2e.yml
  contrib/test/integration/golang.yml
  contrib/test/integration/main.yml
  contrib/test/integration/python3.yml
  contrib/test/integration/system-packages.yml
  contrib/test/integration/system.yml
  test/helpers.bash
Labels: approved, dco-signoff: yes, lgtm, size/L

#3077 Update to conmon v2.0.9
  .circleci/config.yml
  Makefile
  contrib/test/integration/build/conmon.yml
  go.mod
  go.sum
  scripts/build-test-image
  vendor/github.com/containers/conmon/runner/config/config.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/S

#3072 [1.14] skip test failing on mount eperm
  contrib/test/integration/e2e.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3083 Change AppArmor profile handling to fallback to the default
  server/container_create.go
  server/container_create_linux.go
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3080 [1.17] Add logic for running openshift e2e-aws tests
  contrib/test/ci/cri-o.spec
  contrib/test/ci/crio-metrics.sysconfig
  contrib/test/ci/crio-network.sysconfig
  contrib/test/ci/crio-storage.sysconfig
  contrib/test/ci/crio.service
  hack/build-rpms.sh
  hack/lib/build/binaries.sh
  hack/lib/build/rpm.sh
  hack/lib/build/version.sh
  hack/lib/constants.sh
  hack/lib/init.sh
  hack/lib/log/output.sh
  hack/lib/log/stacktrace.sh
  hack/lib/log/system.sh
  hack/lib/util/ensure.sh
  hack/lib/util/environment.sh
  hack/lib/util/find.sh
  hack/lib/util/misc.sh
  hack/lib/util/text.sh
  hack/lib/util/trap.sh
  images/os/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#3084 Fix possible segmentation fault in namespace removal
  internal/lib/sandbox/namespaces.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3088 Fix pinns path mismatch for install and uninstall
  Makefile
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#3000 [1.15]: Add disk usage for ListContainerStats
  server/container_stats.go
  server/container_stats_list.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#3092 Use UUID generator for namespace path
  internal/lib/sandbox/namespaces_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2999 [1.14]: Add disk usage for ListContainerStats
  server/container_stats.go
  server/container_stats_list.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#3091 Add new NSType for available namespaces
  internal/lib/sandbox/namespaces.go
  internal/lib/sandbox/namespaces_linux.go
  internal/lib/sandbox/namespaces_test.go
  server/sandbox_run_linux.go
  test/mocks/sandbox/sandbox.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3094 Update CNI plugins to v0.8.4
  .circleci/config.yml
  Makefile
  contrib/test/integration/build/plugins.yml
  go.mod
  go.sum
  scripts/build-test-image
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/S

#3096 Destroy the pod's network when it can't be restored
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3093 Add `namespaces{-_}dir` CLI and config option
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/lib/sandbox/namespaces.go
  internal/lib/sandbox/namespaces_linux.go
  internal/lib/sandbox/namespaces_test.go
  internal/pkg/criocli/criocli.go
  pkg/config/config.go
  pkg/config/template.go
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3098 server: create cgroupns when running on cgroup v2
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3097 [1.16] Don't check for closed namespaces
  internal/lib/container_server.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#3103 doc: improve setup.md
  tutorials/setup.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#3104 [1.17] Add `namespaces{-_}dir` CLI and config option
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/lib/sandbox/namespaces.go
  internal/lib/sandbox/namespaces_linux.go
  internal/lib/sandbox/namespaces_test.go
  internal/pkg/criocli/criocli.go
  pkg/config/config.go
  pkg/config/template.go
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3108 [1.17] Check for context erroring before returning from longer requests
  server/container_create.go
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3109 Bump version to 1.17.0-rc1
  internal/version/version.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3086 managed namespaces: remove ErrClosedNS
  internal/lib/container_server.go
  internal/lib/sandbox/namespaces.go
  internal/lib/sandbox/namespaces_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3105 [1.14] Destroy the pod's network when it can't be restored
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3110 [1.17] Fix generated docs for rc1 tag
  completions/fish/crio.fish
  docs/crio.8.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3114 update setup info for Debian, Raspbian and Ubuntu
  README.md
  tutorials/setup.md
Labels: approved, dco-signoff: yes, size/M

#3113 container_create_linux: refactor common code
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3116 Fix typos in test descriptions
  server/image_list_test.go
  server/image_pull_test.go
  server/runtime_status_test.go
  server/sandbox_remove_test.go
  server/server_test.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3117 Mention latest release branch in docs
  README.md
  tutorials/setup.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3120 docs: remove mention to RHEL-8 beta repo in setup.md
  tutorials/setup.md
Labels: dco-signoff: yes, ok-to-test, size/XS

#3118 [1.15] run the tests using the crun runtime
  contrib/test/integration/build/crun.yml
  contrib/test/integration/build/runc.yml
  contrib/test/integration/main.yml
  test/ctr.bats
Labels: approved, dco-signoff: yes, lgtm, size/M

#2912 Extend image pull metrics
  server/image_pull.go
  server/metrics/metrics.go
  tutorials/metrics.md
Labels: approved, dco-signoff: yes, lgtm, release-1.17, size/L

#3124 Fix generated docs formatting
  completions/fish/crio.fish
  docs/crio.8.md
  internal/pkg/criocli/criocli.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3115 Take total_inactive_file into consideration for memory usage
  internal/oci/oci_linux.go
  internal/oci/stats.go
  server/container_stats.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3112 Fix man page header
  docs/crio-status.8.md
  docs/crio.8.md
  internal/pkg/criocli/documentation.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3129 Update golangci-lint to v1.23.1
  .golangci.yml
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3133 Run integration tests natively in CircleCI
  .circleci/config.yml
  scripts/circle-setup
  test/cgroups.bats
  test/critest.bats
  test/ctr.bats
  test/network_ping.bats
Labels: approved, dco-signoff: yes, lgtm, size/L

#3137 Switch default cgroup manager to systemd
  completions/fish/crio.fish
  docs/crio.8.md
  docs/crio.conf.5.md
  pkg/config/config.go
  test/helpers.bash
Labels: approved, dco-signoff: yes, lgtm, size/S

#3138 [1.17] Revert net cleanup and ctx check
  server/container_create.go
  server/sandbox_run_linux.go
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3132 Fail to start when already listening on socket
  pkg/config/config.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3134 Fail to start when stream server port already allocated
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3135 Add documentation about stream_port="0"
  completions/fish/crio.fish
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/pkg/criocli/criocli.go
  pkg/config/template.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3141 [1.17] Run integration tests natively in CI
  .circleci/config.yml
  scripts/circle-setup
  test/cgroups.bats
  test/critest.bats
  test/ctr.bats
  test/network_ping.bats
Labels: approved, dco-signoff: yes, lgtm, size/L

#3140 [1.16] Run integration tests natively in CI
  .circleci/config.yml
  scripts/circle-setup
  test/cgroups.bats
  test/critest.bats
  test/ctr.bats
  test/network_ping.bats
Labels: approved, dco-signoff: yes, lgtm, size/L

#3146 Enable AppArmor tests in CircleCI
  nix/default.nix
  server/server.go
  test/apparmor.bats
  test/helpers.bash
  test/testdata/fake_crio_default
Labels: approved, dco-signoff: yes, lgtm, size/L

#3142 Log path location when using binaries discovered in $PATH
  pkg/config/config.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3143 [1.16] vendor storage 1.15.4
  go.mod
  go.sum
  vendor/github.com/containers/storage/Makefile
  vendor/github.com/containers/storage/VERSION
  vendor/github.com/containers/storage/pkg/system/rm.go
  vendor/github.com/containers/storage/store.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, size/M

#3145 Fix unit tests for rootless runs
  pkg/config/config_test.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3123 Add support for crio drop-in configuration files
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  internal/pkg/criocli/criocli.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/config_unix.go
  pkg/config/config_windows.go
  test/config.bats
  test/helpers.bash
Labels: approved, dco-signoff: yes, lgtm, size/L

#3139 server: allow an apparmor-unconfined container
  completions/fish/crio.fish
  docs/crio.8.md
  internal/pkg/criocli/criocli.go
  pkg/config/template.go
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#3126 Allow server to start without config
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/pkg/criocli/criocli.go
  pkg/config/config.go
  pkg/config/reload_test.go
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3150 Vendor in latest opencontainers/runtime-tools
  go.mod
  go.sum
  vendor/github.com/opencontainers/runtime-tools/generate/generate.go
  vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/M

#3144 Refactor sysctl handling and add unit tests
  internal/pkg/criocli/criocli.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/sysctl.go
  pkg/config/sysctl_test.go
  server/sandbox_run_linux.go
  server/utils.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#3147 Fix network ping integration test in CircleCI
  scripts/circle-setup
  test/network_ping.bats
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3151 [1.15] update c/storage to 1.13.7
  go.mod
  go.sum
  vendor/github.com/containers/storage/.cirrus.yml
  vendor/github.com/containers/storage/.golangci.yml
  vendor/github.com/containers/storage/Makefile
  vendor/github.com/containers/storage/VERSION
  vendor/github.com/containers/storage/drivers/overlay/overlay.go
  vendor/github.com/containers/storage/drivers/vfs/driver.go
  vendor/github.com/containers/storage/go.mod
  vendor/github.com/containers/storage/go.sum
  vendor/github.com/containers/storage/pkg/config/config.go
  vendor/github.com/containers/storage/pkg/lockfile/lockfile_unix.go
  vendor/github.com/containers/storage/pkg/ostree/no_ostree.go
  vendor/github.com/containers/storage/pkg/ostree/ostree.go
  vendor/github.com/containers/storage/pkg/system/rm.go
  vendor/github.com/containers/storage/pkg/tarlog/tarlogger.go
  vendor/github.com/containers/storage/storage.conf
  vendor/github.com/containers/storage/store.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#3127 [1.16] fail on network stop
  completions/fish/crio.fish
  internal/lib/container_server.go
  internal/lib/sandbox/sandbox.go
  internal/lib/sandbox/sandbox_test.go
  server/container_create_test.go
  server/sandbox_network.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
  server/sandbox_stop_test.go
  server/server.go
Labels: dco-signoff: yes, size/L

#3161 Fix integration tests by adjusting image digest
  pkg/config/config_test.go
  test/image.bats
Labels: approved, dco-signoff: yes, lgtm, size/M

#3165 stream server: Bind to all addresses
  server/server.go
  server/utils.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#3167 [1.17] fix integration tests
  test/image.bats
Labels: approved, dco-signoff: yes, lgtm, size/S

#3168 [1.16] fix integration tests
  test/image.bats
Labels: approved, dco-signoff: yes, lgtm, size/S

#3159 Use new containerd/release-tool path
  go.mod
  go.sum
  internal/tools/tools.go
  vendor/github.com/containerd/fifo/errors.go
  vendor/github.com/containerd/fifo/fifo.go
  vendor/github.com/containerd/fifo/raw.go
  vendor/github.com/containerd/go-runc/.travis.yml
  vendor/github.com/containerd/go-runc/README.md
  vendor/github.com/containerd/go-runc/command_linux.go
  vendor/github.com/containerd/go-runc/runc.go
  vendor/github.com/containerd/release-tool/.golangci.yml
  vendor/github.com/containerd/release-tool/.travis.yml
  vendor/github.com/containerd/release-tool/LICENSE
  vendor/github.com/containerd/release-tool/README.md
  vendor/github.com/containerd/release-tool/go.mod
  vendor/github.com/containerd/release-tool/go.sum
  vendor/github.com/containerd/release-tool/main.go
  vendor/github.com/containerd/release-tool/template.go
  vendor/github.com/containerd/release-tool/util.go
  vendor/github.com/containerd/release-tool/vendor.conf
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/XL

#3158 Update urfave/cli to latest version
  docs/crio.8.md
  go.mod
  go.sum
  vendor/github.com/urfave/cli/v2/.gitignore
  vendor/github.com/urfave/cli/v2/.travis.yml
  vendor/github.com/urfave/cli/v2/README.md
  vendor/github.com/urfave/cli/v2/app.go
  vendor/github.com/urfave/cli/v2/appveyor.yml
  vendor/github.com/urfave/cli/v2/category.go
  vendor/github.com/urfave/cli/v2/command.go
  vendor/github.com/urfave/cli/v2/context.go
  vendor/github.com/urfave/cli/v2/docs.go
  vendor/github.com/urfave/cli/v2/errors.go
  vendor/github.com/urfave/cli/v2/flag_float64.go
  vendor/github.com/urfave/cli/v2/flag_path.go
  vendor/github.com/urfave/cli/v2/flag_timestamp.go
  vendor/github.com/urfave/cli/v2/help.go
  vendor/github.com/urfave/cli/v2/parse.go
  vendor/github.com/urfave/cli/v2/template.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#3153 drop host_ip{,s}
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/pkg/criocli/criocli.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/template.go
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, release-1.17, size/M

#3170 [1.17] persist exit status
  internal/lib/container_server.go
  internal/lib/wait.go
  internal/oci/container.go
  internal/oci/memory_store_test.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_vm.go
  server/container_status.go
  server/container_status_test.go
  utils/utils.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3010 Move SystemContext from Server into Config
  cmd/crio/config.go
  cmd/crio/main.go
  internal/lib/container_server.go
  internal/lib/container_server_test.go
  internal/lib/suite_test.go
  internal/pkg/criocli/criocli.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/reload.go
  pkg/config/reload_test.go
  server/container_create_linux.go
  server/image_list.go
  server/image_pull.go
  server/image_remove.go
  server/image_status.go
  server/inspect.go
  server/sandbox_run_linux.go
  server/server.go
  server/server_test.go
  server/suite_test.go
  server/useragent/useragent.go
  server/useragent/useragent_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#3045 persist exit status
  internal/lib/container_server.go
  internal/lib/wait.go
  internal/oci/container.go
  internal/oci/memory_store_test.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_vm.go
  server/container_status.go
  server/container_status_test.go
  utils/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-1.17, size/M

#3173 [1.17] Add the context and network destroy commits back in
  server/container_create.go
  server/sandbox_run_linux.go
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3172 [1.17] Add support for crio drop-in config files
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  internal/pkg/criocli/criocli.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/config_unix.go
  pkg/config/config_windows.go
  test/config.bats
  test/helpers.bash
Labels: approved, dco-signoff: yes, lgtm, size/L
