Repository cri-o/cri-o, pull requests merged in 2020-08, with the labels that each got.

#3935 Implement big_files_temporary_dir on crio.image toml table
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  pkg/config/config.go
  pkg/config/template.go
  test/testdata/config/config-v1.17.0.toml
Labels: approved, dco-signoff: yes, kind/feature, lgtm, ok-to-test, release-note

#4034 Remove unused global vars in memory storer
  internal/lib/sandbox/memory_store.go
  internal/oci/memory_store.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4028 contrib: update the crun version to the last release
  contrib/test/integration/build/crun.yml
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4033 Make filter container list be able to filter short pod IDs
  server/container_list.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#4042 Fix lint pipeline by gofumpt'ing cgmgr_test.go
  internal/config/cgmgr/cgmgr_test.go
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#4040 Parameterize strip binary in pinns/Makefile for cross-compilation
  pinns/Makefile
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, ok-to-test, release-note-none

#4017 Add `make release` target
  Makefile
  scripts/release/release.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note-none

#3891 fix segfault with errors.Cause()
  cmd/crio/wipe.go
  internal/lib/container_server.go
  internal/oci/runtime_vm.go
  internal/storage/runtime.go
  server/label_linux.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
  server/secrets.go
  server/server.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3973 node: fix panic if /sys/fs/cgroup failed to stat
  internal/config/node/cgroups.go
  internal/config/node/node.go
Labels: approved, dco-signoff: yes, lgtm, release-note

#4041 [1.18] runtimeVM backports to release-1.18 branch
  internal/oci/runtime_vm.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#3482 stats: skipped stopped containers on container list stats
  server/container_stats_list.go
  server/container_stats_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4019 add crio --profile test
  test/ctr.bats
  test/helpers.bash
  test/profile.bats
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4026 Various nits
  internal/runtimehandlerhooks/high_performance_hooks.go
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#3901 docs: update installation instructions
  README.md
  install.md
  tutorial.md
  tutorials/install-distro.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none

#4054 Bump golangci-lint to v1.30.0
  .golangci.yml
  Makefile
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4052 config: create hooks dir if not present
  pkg/config/config.go
  pkg/config/config_test.go
Labels: approved, dco-signoff: yes, kind/design, lgtm, release-note

#4062 UPSTREAM: 80591: hostport: Don't masquerade localhost-to-localhost traffic
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/network/hostport/hostport.go
  vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/network/hostport/hostport_manager.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test, release-note

#4059 [1.17] backports related to the VM runtime type
  internal/oci/runtime_vm.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4061 test/ctr.bats: fix test check
  test/ctr.bats
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#3868 oci: check pid before using it
  internal/findprocess/findprocess.go
  internal/findprocess/findprocess_test.go
  internal/findprocess/findprocess_unix.go
  internal/findprocess/findprocess_windows.go
  internal/lib/sandbox/namespaces.go
  internal/lib/sandbox/namespaces_test.go
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/container_test_inject.go
  internal/oci/oci_linux.go
  internal/oci/runtime_oci.go
  server/container_create_linux.go
  server/container_execsync.go
  server/container_status_test.go
  server/inspect.go
  server/inspect_ginkgo_test.go
  server/sandbox_status_test.go
Labels: approved, dco-signoff: yes, lgtm, release-1.19

#4063 test/image_volume.bats: fixes
  test/image_volume.bats
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4067 Switch to go 1.15
  contrib/test/integration/main.yml
  go.mod
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note

#4058 Ensure CloseIO is called after Start for exec
  internal/oci/runtime_vm.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test, release-note-none

#4072 Add /sys/dev as a masked path
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4077 Reuse Kubernetes API consts for seccomp profiles
  server/container_create.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4070 Bump test images to go1.15
  .circleci/config.yml
  Makefile
  scripts/build-test-image
  scripts/versions
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note-none

#4082 runtimeVM: Store logs again, and store them in the correct format
  internal/oci/runtime_vm.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4068 oci_linux: fix working set calculation
  internal/oci/oci_linux.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4060 test/*bats: fix shellcheck SC2076
  test/apparmor.bats
  test/cgroups.bats
  test/command.bats
  test/config.bats
  test/crio-wipe.bats
  test/ctr.bats
  test/ctr_seccomp.bats
  test/ctr_userns.bats
  test/default_mounts.bats
  test/image.bats
  test/image_volume.bats
  test/inspect.bats
  test/network.bats
  test/pod.bats
  test/restore.bats
  test/status.bats
  test/version.bats
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4071 selinux: override only specified values
  pkg/container/container.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4092 Bump to v1.17.5
  completions/fish/crio.fish
  docs/crio.8.md
  internal/version/version.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note-none

#4093 Add fidencio to OWNERS file
  .github/CODEOWNERS
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none

#4090 Use Unmount w/o prior Mounted check
  internal/lib/sandbox/namespaces_linux.go
  internal/lib/sandbox/sandbox.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4086 Don't limit the size on /run for systemd based containers
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none

#4080 Fix container cgroup under cgroupfs
  internal/config/cgmgr/cgroupfs.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4066 Shellcheck misc
  test/apparmor.bats
  test/ctr.bats
  test/ctr_seccomp.bats
  test/helpers.bash
  test/image.bats
  test/network_ping.bats
  test/pod.bats
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#3908 keep conmons created by execsyncs as direct children
  Makefile
  internal/config/conmonmgr/conmonmgr.go
  internal/config/conmonmgr/conmonmgr_test.go
  internal/config/conmonmgr/suite_test.go
  internal/oci/oci_unix.go
  internal/oci/runtime_oci.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/suite_test.go
  test/mocks/cmdrunner/cmdrunner.go
  utils/cmdrunner/cmdrunner.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-1.19, release-note

#4079 Speed up mountinfo-related operations during container creation
  server/container_create.go
  server/container_create_linux.go
  server/utils.go
  server/utils_test.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4087 Assorted test fixes (might help CI flakes)
  test/critest.bats
  test/helpers.bash
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#4078 Remove duplicate check for enabled seccomp
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4104 oci: move channel close to writer goroutine
  internal/oci/oci.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4107 remove --runtime option
  completions/bash/crio
  completions/zsh/_crio
  internal/criocli/criocli.go
Labels: approved, dco-signoff: yes, lgtm, release-note

#4097 handle runc not present on the system
  pkg/config/config.go
  pkg/config/template.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note

#4111 Switch to updated version of creack/pty
  go.mod
  go.sum
  internal/oci/oci_unix.go
  vendor/github.com/creack/pty/run.go
  vendor/github.com/creack/pty/test_crosscompile.sh
  vendor/github.com/creack/pty/ztypes_freebsd_arm64.go
  vendor/github.com/creack/pty/ztypes_openbsd_32bit_int.go
  vendor/github.com/creack/pty/ztypes_openbsd_amd64.go
  vendor/github.com/kr/pty/.gitignore
  vendor/github.com/kr/pty/LICENSE
  vendor/github.com/kr/pty/README.md
  vendor/github.com/kr/pty/go.mod
  vendor/github.com/kr/pty/go.sum
  vendor/github.com/kr/pty/shim.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4096 fix high performance hook self-exit container issue
  server/sandbox_stop_linux.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test, release-note-none

#4091 test/*bats: fixes
  test/apparmor.bats
  test/cgroups.bats
  test/helpers.bash
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4064 test/stats.bats: fixes
  test/stats.bats
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4115 [1.11 backport] RunAsGroup fixes
  Makefile
  server/container_create.go
Labels: approved, dco-signoff: yes, lgtm, release-note

#4116 dual stack portmap support
  server/sandbox_network.go
  server/server.go
Labels: approved, dco-signoff: yes, kind/bug, kind/feature, lgtm, ok-to-test, release-note

#4108 Unset GOSUMDB when vendoring
  Makefile
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4102 managed ns: report namespace cleanup failure by default
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none

#4122 branch forward: stop on rc
  scripts/release-branch-forward/release_branch_forward.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4101 managed ns: ignore `PID not initialized` on sandbox creation
  internal/lib/sandbox/namespaces.go
  internal/oci/container.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4130 Revert "dual stack portmap support"
  server/sandbox_network.go
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none

#4022 added irq smp balance and cpu cfs quota control
  internal/runtimehandlerhooks/high_performance_hooks.go
  internal/runtimehandlerhooks/high_performance_hooks_test.go
  internal/runtimehandlerhooks/runtime_handler_hooks_suite_test.go
  internal/runtimehandlerhooks/utils.go
  internal/runtimehandlerhooks/utils_test.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, ok-to-test, release-note

#4140 [1.11] Release 1.11.16
  version/version.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none
