Repository cri-o/cri-o, pull requests merged in 2020-05, with the labels that each got.

#3709 [1.15] server/ContainerStatus: don't lock for c.State() and some friends
  oci/runtime_oci.go
  server/container_status.go
  test/ctr.bats
  test/image.bats
  version/version.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3706 Adds Ubuntu 20.04 to install instructions
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, ok-to-test

#3705 [1.18] oci: drop container level privileged flag
  internal/lib/container_server.go
  internal/lib/container_server_test.go
  internal/lib/sandbox/namespaces_test.go
  internal/lib/sandbox/sandbox_test.go
  internal/lib/suite_test.go
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/suite_test.go
  server/container_create_linux.go
  server/inspect_test.go
  server/sandbox_run_linux.go
  server/suite_test.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3658 Pass context from caller to ocicni methods
  go.mod
  go.sum
  server/sandbox_network.go
  server/sandbox_stop_test.go
  test/mocks/ocicni/types.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/types.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3710 Delete container Id from ctrIDIndex if podIDIndex.Add fails
  internal/lib/container_server.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3291 port forward: drain the stream on error
  go.mod
  internal/oci/runtime_oci.go
  server/container_portforward.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/S

#3713 version: small tweaks
  internal/version/version.go
Labels: approved, dco-signoff: yes, lgtm

#3714 Close done channel if the wait for ContainerStateStopped times out
  internal/oci/oci.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3715 Missing `cd ~/.ansible/roles` Before `git clone`
  tutorials/setup.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, ok-to-test

#3712 Delete container Id only when impl.DeleteContainer(c) passes
  internal/oci/oci.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3722 Cleanup go modules and vendor
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3721 [1.18] make lack of hugetlb support non-fatal for cgroupv1
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3723 Avoid unnecessary locking on runtimeImplMap
  internal/oci/oci.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test

#3731 removes the one minute network stop timeout
  server/sandbox_network.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test

#3728 Remove containerd/release-tool dependency
  Makefile
  go.mod
  go.sum
  internal/tools/tools.go
  vendor/github.com/containerd/release-tool/.golangci.yml
  vendor/github.com/containerd/release-tool/LICENSE
  vendor/github.com/containerd/release-tool/README.md
  vendor/github.com/containerd/release-tool/go.mod
  vendor/github.com/containerd/release-tool/go.sum
  vendor/github.com/containerd/release-tool/main.go
  vendor/github.com/containerd/release-tool/template.go
  vendor/github.com/containerd/release-tool/util.go
  vendor/github.com/urfave/cli/.flake8
  vendor/github.com/urfave/cli/.gitignore
  vendor/github.com/urfave/cli/.travis.yml
  vendor/github.com/urfave/cli/CHANGELOG.md
  vendor/github.com/urfave/cli/LICENSE
  vendor/github.com/urfave/cli/README.md
  vendor/github.com/urfave/cli/app.go
  vendor/github.com/urfave/cli/appveyor.yml
  vendor/github.com/urfave/cli/category.go
  vendor/github.com/urfave/cli/cli.go
  vendor/github.com/urfave/cli/command.go
  vendor/github.com/urfave/cli/context.go
  vendor/github.com/urfave/cli/errors.go
  vendor/github.com/urfave/cli/flag-types.json
  vendor/github.com/urfave/cli/flag.go
  vendor/github.com/urfave/cli/flag_generated.go
  vendor/github.com/urfave/cli/funcs.go
  vendor/github.com/urfave/cli/generate-flag-types
  vendor/github.com/urfave/cli/help.go
  vendor/github.com/urfave/cli/runtests
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm

#3727 Switch to logrus 1.6.0
  go.mod
  go.sum
  vendor/github.com/konsorten/go-windows-terminal-sequences/README.md
  vendor/github.com/konsorten/go-windows-terminal-sequences/sequences.go
  vendor/github.com/sirupsen/logrus/.golangci.yml
  vendor/github.com/sirupsen/logrus/.travis.yml
  vendor/github.com/sirupsen/logrus/CHANGELOG.md
  vendor/github.com/sirupsen/logrus/README.md
  vendor/github.com/sirupsen/logrus/appveyor.yml
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/go.mod
  vendor/github.com/sirupsen/logrus/go.sum
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_check_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_check_js.go
  vendor/github.com/sirupsen/logrus/terminal_check_unix.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/writer.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm

#3730 [1.17] Close image pull progress goroutine after completion
  server/image_pull.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test

#3639 Use correct upload URL for binary uploads
  scripts/upload-artifacts
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm

#3623 Makefile: allow customization of go commands
  Makefile
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3724 Add `--metrics-socket`/`metrics_socket` config option
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  pkg/config/config.go
  pkg/config/template.go
  server/server.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm

#3637 Update golangci lint to v1.26.0
  .golangci.yml
  Makefile
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm

#3642 Makefile: include -nobuild install targets
  Makefile
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm

#3609 [release-1.16] Stop container when there is error in createSandboxContainer
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test

#3734 [1.18] Fix linkmode for static binaries
  internal/version/version.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3746 [1.17] Use bats v1.2.0 release for CI
  .circleci/config.yml
  Makefile
  contrib/test/integration/build/bats.yml
  scripts/build-test-image
  scripts/circle-setup
  server/inspect_test.go
  server/suite_test.go
  test/crio-wipe.bats
Labels: approved, dco-signoff: yes, lgtm

#3648 crio wipe: add version-file-persist
  cmd/crio/main.go
  cmd/crio/wipe.go
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  internal/version/version.go
  pkg/config/config.go
  pkg/config/config_unix.go
  pkg/config/template.go
  test/crio-wipe.bats
  test/crio-wipe/crio-wipe.bats
  test/helpers.bash
  test/testdata/labeled_container_redis.json
Labels: approved, dco-signoff: yes, kind/feature, lgtm

#3741 [1.18] Makefile: include -nobuild install targets
  Makefile
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm

#3745 [1.18] Fix static binary integration tests
  test/crio-wipe.bats
  test/helpers.bash
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm

#3742 [1.17] Makefile: include -nobuild install targets
  Makefile
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm

#3754 Automatically label containers running systemd with the correct label
  server/container_create_linux.go
  vendor/github.com/containers/libpod/pkg/selinux/selinux.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/feature, lgtm

#3752 [1.18] Pin runc for CI
  contrib/test/integration/build/runc.yml
Labels: approved, dco-signoff: yes, kind/flake, lgtm

#3756 [1.18] fix naming test panic
  server/naming_test.go
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm

#3688 [1.18] version: small tweaks
  internal/version/version.go
Labels: approved, dco-signoff: yes, lgtm

#3763 crio wipe: log less
  cmd/crio/wipe.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3760 [1.18] bump to v1.18.1
  internal/version/version.go
Labels: approved, dco-signoff: yes, kind/documentation, lgtm

#3758 Update nix image and dependencies
  .circleci/config.yml
  .gitignore
  Makefile
  contrib/bundle/Makefile
  contrib/bundle/build
  nix/default.nix
  nix/nixpkgs.json
  test/version.bats
  tutorials/setup.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm

#3766 [1.18] Allow release notes for release branches
  scripts/release-notes/release_notes.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm

#3767 Allow release notes for release branches
  scripts/release-notes/release_notes.go
Labels: approved, dco-signoff: yes, kind/documentation, lgtm

#3765 [1.18] Automatically label containers running systemd with the correct label
  go.mod
  go.sum
  server/container_create_linux.go
  vendor/github.com/containers/libpod/cmd/podman/cliconfig/config.go
  vendor/github.com/containers/libpod/libpod/healthcheck.go
  vendor/github.com/containers/libpod/libpod/image/image.go
  vendor/github.com/containers/libpod/libpod/runtime.go
  vendor/github.com/containers/libpod/pkg/cgroups/cgroups.go
  vendor/github.com/containers/libpod/pkg/rootless/rootless_linux.c
  vendor/github.com/containers/libpod/pkg/rootless/rootless_linux.go
  vendor/github.com/containers/libpod/pkg/rootlessport/rootlessport_linux.go
  vendor/github.com/containers/libpod/pkg/selinux/selinux.go
  vendor/github.com/containers/libpod/pkg/spec/config_linux.go
  vendor/github.com/containers/libpod/pkg/spec/config_unsupported.go
  vendor/github.com/containers/libpod/pkg/spec/spec.go
  vendor/github.com/containers/libpod/version/version.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/feature, lgtm

#3762 [1.16] unmount network namespace on remove
  internal/lib/sandbox/sandbox_linux.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test

#3778 Exclude failing conntrack e2e test
  contrib/test/integration/e2e.yml
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm

#3775 Check that SecurityContext is not nil before dereferencing
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3774 sandbox iface: don't fail if uid is not specified
  pkg/sandbox/sandbox.go
  pkg/sandbox/sandbox_setnameandid_test.go
Labels: approved, dco-signoff: yes, lgtm

#3749 Remove socat runtime dependency
  internal/log/interceptors.go
  internal/oci/oci.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_vm.go
  server/container_portforward.go
  tutorials/setup.md
Labels: approved, dco-signoff: yes, kind/feature, lgtm

#3784 [1.11] conmon: make un-OOM-killable
  conmon/conmon.c
Labels: approved, dco-signoff: yes, kind/bug, lgtm

#3800 Fix the kubeadm command
  tutorials/kubeadm.md
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test
