Repository cri-o/cri-o, pull requests merged in 2021-03, with the labels that each got.

#4606 Fix GitHub actions workflow syntax
  .github/workflows/test.yml
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#4537 Bumps github.com/containers/ocicrypt from 1.0.3 to 1.1.0.
  go.mod
  go.sum
  vendor/github.com/containers/ocicrypt/.travis.yml
  vendor/github.com/containers/ocicrypt/Makefile
  vendor/github.com/containers/ocicrypt/README.md
  vendor/github.com/containers/ocicrypt/config/constructors.go
  vendor/github.com/containers/ocicrypt/config/keyprovider-config/config.go
  vendor/github.com/containers/ocicrypt/crypto/pkcs11/common.go
  vendor/github.com/containers/ocicrypt/crypto/pkcs11/pkcs11helpers.go
  vendor/github.com/containers/ocicrypt/crypto/pkcs11/pkcs11helpers_nocgo.go
  vendor/github.com/containers/ocicrypt/crypto/pkcs11/utils.go
  vendor/github.com/containers/ocicrypt/encryption.go
  vendor/github.com/containers/ocicrypt/go.mod
  vendor/github.com/containers/ocicrypt/go.sum
  vendor/github.com/containers/ocicrypt/gpg.go
  vendor/github.com/containers/ocicrypt/keywrap/keyprovider/keyprovider.go
  vendor/github.com/containers/ocicrypt/keywrap/pkcs11/keywrapper_pkcs11.go
  vendor/github.com/containers/ocicrypt/utils/ioutils.go
  vendor/github.com/containers/ocicrypt/utils/keyprovider/keyprovider.pb.go
  vendor/github.com/containers/ocicrypt/utils/keyprovider/keyprovider.proto
  vendor/github.com/containers/ocicrypt/utils/utils.go
  vendor/github.com/miekg/pkcs11/.gitignore
  vendor/github.com/miekg/pkcs11/.travis.yml
  vendor/github.com/miekg/pkcs11/LICENSE
  vendor/github.com/miekg/pkcs11/Makefile.release
  vendor/github.com/miekg/pkcs11/README.md
  vendor/github.com/miekg/pkcs11/const.go
  vendor/github.com/miekg/pkcs11/error.go
  vendor/github.com/miekg/pkcs11/go.mod
  vendor/github.com/miekg/pkcs11/hsm.db
  vendor/github.com/miekg/pkcs11/params.go
  vendor/github.com/miekg/pkcs11/pkcs11.go
  vendor/github.com/miekg/pkcs11/pkcs11.h
  vendor/github.com/miekg/pkcs11/pkcs11f.h
  vendor/github.com/miekg/pkcs11/pkcs11go.h
  vendor/github.com/miekg/pkcs11/pkcs11t.h
  vendor/github.com/miekg/pkcs11/release.go
  vendor/github.com/miekg/pkcs11/softhsm.conf
  vendor/github.com/miekg/pkcs11/softhsm2.conf
  vendor/github.com/miekg/pkcs11/types.go
  vendor/github.com/miekg/pkcs11/vendor.go
  vendor/github.com/stefanberger/go-pkcs11uri/.gitignore
  vendor/github.com/stefanberger/go-pkcs11uri/.travis.yml
  vendor/github.com/stefanberger/go-pkcs11uri/LICENSE
  vendor/github.com/stefanberger/go-pkcs11uri/Makefile
  vendor/github.com/stefanberger/go-pkcs11uri/README.md
  vendor/github.com/stefanberger/go-pkcs11uri/pkcs11uri.go
  vendor/gopkg.in/square/go-jose.v2/.gitignore
  vendor/gopkg.in/square/go-jose.v2/.travis.yml
  vendor/gopkg.in/square/go-jose.v2/asymmetric.go
  vendor/gopkg.in/square/go-jose.v2/cipher/ecdh_es.go
  vendor/gopkg.in/square/go-jose.v2/crypter.go
  vendor/gopkg.in/square/go-jose.v2/encoding.go
  vendor/gopkg.in/square/go-jose.v2/jwk.go
  vendor/gopkg.in/square/go-jose.v2/jws.go
  vendor/gopkg.in/square/go-jose.v2/opaque.go
  vendor/gopkg.in/square/go-jose.v2/shared.go
  vendor/gopkg.in/square/go-jose.v2/signing.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note

#4552 Add arm64 static build to GitHub actions and bundle
  .github/workflows/test.yml
  Makefile
  README.md
  contrib/bundle/10-crun.conf
  contrib/bundle/Makefile
  contrib/bundle/build
  contrib/bundle/test
  contrib/bundle/vars
  install.md
  nix/default-arm64.nix
  scripts/get
  scripts/release-notes/release_notes.go
  scripts/upload-artifacts
  scripts/versions
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#4602 Updates yq commnands for yq v4
  tutorials/kubeadm.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, ok-to-test, release-note-none

#4598 Add metric to grab latency of individual cri calls
  server/metrics/interceptors.go
  server/metrics/metrics.go
  server/sandbox_network.go
  tutorials/metrics.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note

#4615 test: correct the env variable for dropping the infra container
  test/timeout.bats
Labels: approved, dco-signoff: yes, kind/ci, lgtm, release-note-none

#4609 Fix `get` script commit SHA retrieval
  scripts/get
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4610 Make `get` script independent from `make`
  .github/workflows/verify.yml
  Makefile
  contrib/bundle/Makefile
  contrib/bundle/README.md
  contrib/bundle/build
  contrib/bundle/install
  contrib/bundle/install-paths
  contrib/bundle/test
  scripts/get
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4419 contrib/test/int: assorted minor cleanups
  contrib/test/integration/README.md
  contrib/test/integration/critest.yml
  contrib/test/integration/main.yml
  contrib/test/integration/node-e2e.yml
  contrib/test/integration/system.yml
  test/critest.bats
Labels: approved, dco-signoff: yes, kind/ci, lgtm, release-note-none

#4443 crio.service: Request to be run before kubelet.service
  contrib/systemd/crio.service
  contrib/test/ci/crio.service
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note

#4583 [1.18] server: mount cgroup with rslave
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, lgtm, release-note

#4573 sandbox: Initialize the infra container internally
  pkg/container/container.go
  pkg/container/container_setnameandid_test.go
  pkg/container/container_test.go
  pkg/container/suite_test.go
  pkg/sandbox/add_container.go
  pkg/sandbox/create.go
  pkg/sandbox/delete.go
  pkg/sandbox/infra.go
  pkg/sandbox/infra_test.go
  pkg/sandbox/remove_container.go
  pkg/sandbox/sandbox.go
  pkg/sandbox/start.go
  pkg/sandbox/stop.go
  pkg/sandbox/suite_test.go
  server/container_create.go
  server/container_create_linux.go
  server/sandbox_run_linux.go
  server/sandbox_run_test.go
Labels: approved, dco-signoff: yes, kind/design, lgtm, release-note-none

#4444 [1.19] improve timeout handling
  internal/lib/sandbox/sandbox.go
  internal/resourcestore/resourcestore.go
  internal/resourcestore/resourcestore_test.go
  internal/resourcestore/suite_test.go
  server/container_create.go
  server/sandbox_network.go
  server/sandbox_run_linux.go
  server/server.go
  server/utils.go
  test/drop_infra.bats
  test/helpers.bash
  test/timeout.bats
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4494 config: fix template to show infra_ctr_cpus option
  pkg/config/template.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4581 [1.19] server: mount cgroup with rslave
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, lgtm, release-note

#4502 Bump golangci-lint to v1.35.2
  .github/workflows/verify.yml
  .golangci.yml
  Makefile
  utils/utils_test.go
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note-none

#4619 fix: Don't set `image-endpoint` in crictl config
  crictl.yaml
Labels: approved, dco-signoff: yes, kind/other, lgtm, ok-to-test, release-note-none

#4600 oci: don't wait too long on a long stop
  internal/oci/container.go
  internal/oci/oci_unix.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4617 Add integration test for started/finished container time
  test/ctr.bats
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4458 [1.17] set inactive-or-failed CollectMode if appropriate
  internal/config/node/node.go
  internal/config/node/systemd.go
  pkg/config/config.go
  server/container_create_linux.go
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4100 test: reconfigure how runtimes are passed in
  test/README.md
  test/config.bats
  test/devices.bats
  test/drop_infra.bats
  test/helpers.bash
  test/restore.bats
  test/shm_size.bats
  test/timeout.bats
Labels: approved, dco-signoff: yes, lgtm, release-note-none

#4358 Support CRI seccomp security profiles
  internal/config/seccomp/seccomp.go
  internal/config/seccomp/seccomp_test.go
  server/container_create.go
  server/container_create_linux.go
  server/cri/types/types.go
  server/cri/v1/rpc_create_container.go
  server/cri/v1/rpc_pull_image.go
  server/cri/v1/rpc_run_pod_sandbox.go
  server/cri/v1alpha2/rpc_create_container.go
  server/cri/v1alpha2/rpc_pull_image.go
  server/cri/v1alpha2/rpc_run_pod_sandbox.go
  server/sandbox_run_linux.go
  test/ctr_seccomp.bats
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#4629 runtime_vm: Create the global fifo inside the runtime root path
  internal/oci/oci.go
  internal/oci/runtime_vm.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4595 feat: Add CLI option to set registries.conf.d path
  completions/bash/crio
  completions/zsh/_crio
  internal/criocli/criocli.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, ok-to-test, release-note

#4638 Fix GitHub actions cache key
  .github/workflows/integration.yml
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4438 Bug 1881694: Add pull source as info level log
  server/image_pull.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note

#4640 Revert "server: use IsAlive() more"
  internal/lib/container_server.go
  server/container_attach.go
  server/container_exec.go
  server/container_reopen_log.go
  server/container_update_resources.go
  server/container_update_resources_test.go
  server/sandbox_remove.go
  server/sandbox_stop_linux.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none

#4603 [1.20] update github actions to sync with main branch
  .circleci/config.yml
  .github/workflows/integration.yml
  .github/workflows/test.yml
  .github/workflows/verify.yml
  internal/lib/sandbox/namespaces_test.go
  pkg/config/config_test.go
  pkg/config/suite_test.go
  scripts/circle-setup-cgroup_manager
  scripts/github-actions-packages
  scripts/github-actions-setup
Labels: approved, dco-signoff: yes, kind/ci, lgtm, release-note-none

#4633 test: use latest conmon
  contrib/test/integration/build/conmon.yml
Labels: approved, dco-signoff: yes, kind/ci, lgtm, release-note-none

#4642 Add GitHub API pages support to `get` script
  scripts/get
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4641 add libbtrfs-dev to unit tests
  scripts/github-actions-packages
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none

#4652 [1.20] update github actions again
  .github/workflows/integration.yml
  .github/workflows/test.yml
  scripts/github-actions-packages
Labels: approved, dco-signoff: yes, kind/ci, lgtm, release-note-none

#4643 Fix lint GitHub action
  internal/oci/runtime_vm.go
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#4656 Backport irqbalance handling onto 1.20
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  internal/runtimehandlerhooks/high_performance_hooks.go
  internal/runtimehandlerhooks/high_performance_hooks_test.go
  internal/runtimehandlerhooks/runtime_handler_hooks.go
  internal/runtimehandlerhooks/utils.go
  pkg/config/config.go
  pkg/config/template.go
  server/container_start.go
  server/container_stop.go
  server/sandbox_stop_linux.go
  server/server.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test, release-note

#4651 install: drop support matrix and update instructions
  install.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none

#4659 Pin gocapability to v0.0.0-20180916011248-d98352740cb2
  go.mod
  go.sum
  vendor/github.com/syndtr/gocapability/capability/enum.go
  vendor/github.com/syndtr/gocapability/capability/enum_gen.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4650 do not create & store context in runtime vm
  cmd/crio/main.go
  internal/lib/container_server.go
  internal/lib/container_server_test.go
  internal/lib/kill.go
  internal/lib/kill_test.go
  internal/lib/pause.go
  internal/lib/pause_test.go
  internal/lib/remove.go
  internal/lib/stop.go
  internal/lib/wait.go
  internal/lib/wait_test.go
  internal/oci/oci.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_vm.go
  server/container_attach.go
  server/container_create.go
  server/container_create_generic.go
  server/container_create_linux.go
  server/container_exec.go
  server/container_execsync.go
  server/container_reopen_log.go
  server/container_start.go
  server/container_stats.go
  server/container_stats_list.go
  server/container_status.go
  server/container_update_resources.go
  server/sandbox_list_test.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
  server/server.go
  server/server_test.go
  server/streaming/streaming.go
  test/mocks/oci/oci.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none

#4639 use (sort of) happy-eyeballs for port-forwarding
  internal/oci/runtime_oci.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, ok-to-test, release-note

#4661 Update bats to v1.3.0
  contrib/test/integration/build/bats.yml
  scripts/versions
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, tide/merge-method-squash

#4647 Use and publish version marker for CRI-O
  scripts/get
  scripts/upload-artifacts
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note-none

#4665 Run GitHub actions on release branches
  .github/workflows/integration.yml
  .github/workflows/test.yml
  .github/workflows/verify.yml
Labels: approved, dco-signoff: yes, kind/ci, lgtm, release-note-none

#4666 [1.20] Run GitHub actions on release branches
  .github/workflows/integration.yml
  .github/workflows/test.yml
  .github/workflows/verify.yml
Labels: approved, dco-signoff: yes, kind/ci, lgtm, release-note-none

#4668 bump to v1.20.2
  contrib/test/integration/build/cri-tools.yml
  internal/version/version.go
  pkg/container/container.go
  pkg/container/container_test.go
  server/container_create_linux.go
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none

#4626 stats: fix log spam
  internal/oci/stats.go
  server/container_stats_list.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4670 Remove check for CI env variable for release-notes and dependencies
  scripts/dependencies/dependencies.go
  scripts/release-notes/release_notes.go
Labels: approved, dco-signoff: yes, kind/ci, lgtm, release-note-none

#4672 [1.20] Remove check for CI env variable for release-notes and dependencies
  scripts/dependencies/dependencies.go
  scripts/release-notes/release_notes.go
Labels: approved, dco-signoff: yes, kind/ci, lgtm, release-note-none

#4613 inspect: use first container when reporting pid of a pod with no infra
  internal/config/cgmgr/cgmgr.go
  internal/config/cgmgr/cgroupfs.go
  internal/config/cgmgr/systemd.go
  internal/lib/container_server.go
  internal/oci/container.go
  internal/oci/container_test.go
  server/inspect.go
  server/sandbox_run_linux.go
  test/inspect.bats
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4549 Log container stop timeout
  server/container_stop.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note

#4673 Do not return `<none>` placeholders for images any more
  README.md
  cri.md
  server/image_list.go
  server/image_list_test.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#4654 fix default dependencies on container scopes to fix graceful shutdowns
  pkg/container/container.go
Labels: approved, dco-signoff: yes, lgtm, release-note

#4631 config: Don't fail if the non default runtime doesn't pass validation
  pkg/config/config.go
  pkg/config/config_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4644 pkg/container: take process args
  pkg/container/container.go
  pkg/container/container_test.go
  server/container_create.go
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4590 runtimeVM: Fix shimv2 binary name construction
  internal/oci/oci.go
  internal/oci/oci_test.go
  internal/oci/runtime_vm.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: approved, area/vm, dco-signoff: yes, lgtm, release-note-none

#4686 [1.20] bump to latest c/storage 1.24 branch
  go.mod
  go.sum
  vendor/github.com/containers/storage/.cirrus.yml
  vendor/github.com/containers/storage/VERSION
  vendor/github.com/containers/storage/drivers/overlay/check.go
  vendor/github.com/containers/storage/drivers/overlay/overlay.go
  vendor/github.com/containers/storage/go.mod
  vendor/github.com/containers/storage/go.sum
  vendor/github.com/containers/storage/pkg/archive/archive.go
  vendor/github.com/containers/storage/pkg/homedir/homedir_others.go
  vendor/github.com/containers/storage/pkg/homedir/homedir_unix.go
  vendor/github.com/ulikunitz/xz/LICENSE
  vendor/github.com/ulikunitz/xz/TODO.md
  vendor/github.com/ulikunitz/xz/bits.go
  vendor/github.com/ulikunitz/xz/crc.go
  vendor/github.com/ulikunitz/xz/format.go
  vendor/github.com/ulikunitz/xz/internal/hash/cyclic_poly.go
  vendor/github.com/ulikunitz/xz/internal/hash/doc.go
  vendor/github.com/ulikunitz/xz/internal/hash/rabin_karp.go
  vendor/github.com/ulikunitz/xz/internal/hash/roller.go
  vendor/github.com/ulikunitz/xz/internal/xlog/xlog.go
  vendor/github.com/ulikunitz/xz/lzma/bintree.go
  vendor/github.com/ulikunitz/xz/lzma/bitops.go
  vendor/github.com/ulikunitz/xz/lzma/breader.go
  vendor/github.com/ulikunitz/xz/lzma/buffer.go
  vendor/github.com/ulikunitz/xz/lzma/bytewriter.go
  vendor/github.com/ulikunitz/xz/lzma/decoder.go
  vendor/github.com/ulikunitz/xz/lzma/decoderdict.go
  vendor/github.com/ulikunitz/xz/lzma/directcodec.go
  vendor/github.com/ulikunitz/xz/lzma/distcodec.go
  vendor/github.com/ulikunitz/xz/lzma/encoder.go
  vendor/github.com/ulikunitz/xz/lzma/encoderdict.go
  vendor/github.com/ulikunitz/xz/lzma/hashtable.go
  vendor/github.com/ulikunitz/xz/lzma/header.go
  vendor/github.com/ulikunitz/xz/lzma/header2.go
  vendor/github.com/ulikunitz/xz/lzma/lengthcodec.go
  vendor/github.com/ulikunitz/xz/lzma/literalcodec.go
  vendor/github.com/ulikunitz/xz/lzma/matchalgorithm.go
  vendor/github.com/ulikunitz/xz/lzma/operation.go
  vendor/github.com/ulikunitz/xz/lzma/prob.go
  vendor/github.com/ulikunitz/xz/lzma/properties.go
  vendor/github.com/ulikunitz/xz/lzma/rangecodec.go
  vendor/github.com/ulikunitz/xz/lzma/reader.go
  vendor/github.com/ulikunitz/xz/lzma/reader2.go
  vendor/github.com/ulikunitz/xz/lzma/state.go
  vendor/github.com/ulikunitz/xz/lzma/treecodecs.go
  vendor/github.com/ulikunitz/xz/lzma/writer.go
  vendor/github.com/ulikunitz/xz/lzma/writer2.go
  vendor/github.com/ulikunitz/xz/lzmafilter.go
  vendor/github.com/ulikunitz/xz/none-check.go
  vendor/github.com/ulikunitz/xz/reader.go
  vendor/github.com/ulikunitz/xz/writer.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none

#4683 Bump static binary dependency versions
  contrib/bundle/build
  scripts/versions
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note-none

#4691 crio wipe: only completely wipe storage after a reboot
  cmd/crio/wipe.go
  test/crio-wipe.bats
  test/helpers.bash
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4321 Add dependabot config file
  .github/dependabot.yml
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4697 crio-wipe: only clear storage if CleanShutdownFile is supported
  cmd/crio/main.go
  cmd/crio/wipe.go
  pkg/config/config.go
  test/crio-wipe.bats
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4694 Reload the main config file when reloading configs
  pkg/config/config.go
  pkg/config/reload.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4550 update pause image to 3.5（3.4.1 for multi-arch support and 3.5 for non-root）
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/config/migrate/from_1_17.go
  pkg/config/config.go
  test/helpers.bash
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, ok-to-test, release-note
