Repository cri-o/cri-o, pull requests merged in 2021-04, with the labels that each got.

#4678 remove dead code
  go.mod
  internal/lib/container.go
  internal/lib/container_server.go
  internal/lib/container_server_test.go
  internal/lib/container_test.go
  internal/lib/kill.go
  internal/lib/kill_test.go
  internal/lib/logs.go
  internal/lib/logs_test.go
  internal/lib/pause.go
  internal/lib/pause_test.go
  internal/lib/rename.go
  internal/lib/rename_test.go
  internal/lib/sandbox/namespaces.go
  internal/lib/sandbox/sandbox.go
  internal/lib/sandbox/sandbox_test.go
  internal/lib/wait.go
  internal/lib/wait_test.go
  internal/oci/runtime_oci.go
  pkg/config/config.go
  pkg/config/sysctl.go
  server/sandbox_run_linux.go
  server/server_test_inject.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4687 Add static bundle node e2e tests to GitHub actions
  .github/workflows/test.yml
  Makefile
  contrib/bundle/test-e2e
Labels: approved, dco-signoff: yes, kind/ci, lgtm, release-note-none

#4716 [1.20] bump c/common to 0.26.3
  go.mod
  go.sum
  vendor/github.com/containers/common/pkg/config/config.go
  vendor/github.com/containers/common/pkg/config/config_local.go
  vendor/github.com/containers/common/pkg/config/containers.conf
  vendor/github.com/containers/common/pkg/config/default.go
  vendor/github.com/containers/common/pkg/config/libpodConfig.go
  vendor/github.com/containers/common/pkg/seccomp/default_linux.go
  vendor/github.com/containers/common/pkg/seccomp/seccomp.json
  vendor/github.com/containers/common/version/version.go
  vendor/github.com/onsi/ginkgo/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/config/config.go
  vendor/github.com/onsi/ginkgo/ginkgo/generate_command.go
  vendor/github.com/onsi/ginkgo/ginkgo_dsl.go
  vendor/github.com/onsi/ginkgo/internal/testingtproxy/testing_t_proxy.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note

#4724 Add correct start time to initial log output
  cmd/crio/main.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note

#4722 resourcestore: introduce ResourceCleaner
  internal/resourcestore/resourcecleaner.go
  internal/resourcestore/resourcestore.go
  internal/resourcestore/resourcestore_test.go
  server/container_create.go
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4729 Fix unnecessary conversion lint report
  server/sandbox_status.go
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#4728 Clarify release cadence and version skew
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none

#4725 add support for customizing workloads (a second time!)
  internal/oci/oci.go
  internal/oci/oci_test.go
  internal/runtimehandlerhooks/runtime_handler_hooks.go
  pkg/annotations/annotations.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/template.go
  pkg/config/workloads.go
  server/container_create_linux.go
  server/container_start.go
  server/container_stop.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
  test/docs-validation/main.go
  test/workloads.bats
Labels: approved, dco-signoff: yes, kind/design, lgtm, release-note

#4714 Use internal logging when context available
  cmd/crio/main.go
  internal/lib/container_server.go
  internal/lib/stop.go
  internal/log/log.go
  internal/log/log_test.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_vm.go
  server/server.go
  test/copyimg/copyimg.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, ok-to-test, release-note-none

#4690 Add container out of memory metric
  internal/oci/runtime_oci.go
  internal/oci/runtime_vm.go
  server/metrics/metrics.go
  test/ctr.bats
  test/helpers.bash
  test/metrics.bats
  tutorials/metrics.md
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#4742 Bump cri-tools to v1.21.0
  scripts/versions
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note

#4730 Set short name mode to permissive
  internal/storage/image.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#4682 [CLI] "crio config" only prints the fields that are different than the default
  cmd/crio/config.go
  internal/criocli/criocli.go
  pkg/config/config.go
  pkg/config/template.go
  pkg/config/template_test.go
  test/config.bats
  test/config_migrate.bats
  test/crio-wipe.bats
  test/docs-validation/main.go
  test/helpers.bash
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note

#4747 Bump OpenShift CI cri-tools version and fix build path
  contrib/test/integration/build/cri-tools.yml
  contrib/test/integration/critest.yml
  contrib/test/integration/main.yml
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#4748 config: drop commented config lines
  contrib/bundle/test-e2e
  pkg/config/template.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4755 bump to v1.21.0
  contrib/test/integration/build/cri-tools.yml
  contrib/test/integration/main.yml
  internal/version/version.go
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none

#4757 Rebase release-notes job before pushing gh-pages
  .github/workflows/test.yml
  scripts/release-notes/release_notes.go
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#4762 Do not upload artifacts on dependabot branches
  .github/workflows/test.yml
Labels: approved, dco-signoff: yes, kind/ci, lgtm, release-note-none

#4761 Switch to `cri-o` bucket
  .github/workflows/test.yml
  README.md
  scripts/get
  scripts/release-notes/release_notes.go
  scripts/upload-artifacts
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note

#4764 Remove TODO in helpers.bash
  test/helpers.bash
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4470 Properly implement metrics for Kata Containers when using CRI stats.
  go.mod
  internal/oci/oci_linux.go
  internal/oci/runtime_vm.go
  utils/typeurl/types.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4766 Add After=crio.service dependency to containers and conmon
  internal/config/cgmgr/systemd.go
  pkg/container/container.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note

#4769 Fix bundle e2e test setup
  contrib/bundle/test-e2e
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#4726 Bug 1942608: do not list the image with error locating manifest
  internal/storage/image.go
  server/image_pull.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none

#4780 Bump crun to 0.19.1
  scripts/versions
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#4789 Fix RuntimeDefault seccomp behavior if disabled
  internal/config/seccomp/seccomp.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4758 nsmgr: fix some leaks with GetNamespace
  internal/config/nsmgr/nsmgr.go
  internal/config/nsmgr/types.go
  internal/lib/container_server.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4787 workloads: update how overrides are specified
  pkg/config/template.go
  pkg/config/workloads.go
  test/workloads.bats
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note

#4528 rootless: enable resource limit when cgroup v2 controllers are delegated
  server/rootless.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, ok-to-test, release-note

#4796 container server: fix silly typo
  internal/lib/container_server.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4797 Add HERE Technologies to ADOPTERS.md
  ADOPTERS.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, ok-to-test, release-note-none

#4804 main: still rely on logrus (rather than using the internal log)
  cmd/crio/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none

#4803 Use extra context for runtime VM
  internal/oci/runtime_vm.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4814 [1.19] bump containers/image to 5.5.3
  go.mod
  go.sum
  vendor/github.com/containers/image/v5/docker/docker_client.go
  vendor/github.com/containers/image/v5/docker/docker_image_src.go
  vendor/github.com/containers/image/v5/version/version.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4817 [1.20] server: use background context for network stop
  server/sandbox_network.go
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4809 [1.19] server: use background context for network stop
  server/sandbox_network.go
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4815 [1.20] bump containers/image to v5.10.6
  go.mod
  go.sum
  vendor/github.com/containers/image/v5/copy/copy.go
  vendor/github.com/containers/image/v5/docker/docker_client.go
  vendor/github.com/containers/image/v5/docker/docker_image.go
  vendor/github.com/containers/image/v5/docker/docker_image_src.go
  vendor/github.com/containers/image/v5/pkg/sysregistriesv2/shortnames.go
  vendor/github.com/containers/image/v5/storage/storage_image.go
  vendor/github.com/containers/image/v5/version/version.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4818 [1.20] test: replace critools image repo
  contrib/test/integration/build/cri-tools.yml
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#4824 Remove .gitattributes files from vendor directory
  .gitignore
  vendor/github.com/Microsoft/hcsshim/.gitattributes
  vendor/github.com/containerd/fifo/.gitattributes
  vendor/github.com/fsnotify/fsnotify/.gitattributes
  vendor/github.com/fsouza/go-dockerclient/.gitattributes
  vendor/github.com/go-task/slim-sprig/.gitattributes
  vendor/github.com/kevinburke/ssh_config/.gitattributes
  vendor/k8s.io/client-go/pkg/version/.gitattributes
  vendor/k8s.io/component-base/version/.gitattributes
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4826 Use HTML comment for /kind in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none

#4823 [1.21] Fix podman name in README
  README.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4827 config: fix type of privileged_without_host_devices
  pkg/config/template.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4828 Pin gocapability to v0.0.0-20180916011248-d98352740cb2
  go.mod
  go.sum
  vendor/github.com/syndtr/gocapability/capability/enum.go
  vendor/github.com/syndtr/gocapability/capability/enum_gen.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4822 [1.19] test: replace critools image repo
  contrib/test/integration/build/cri-tools.yml
  contrib/test/integration/main.yml
  test/network_ping.bats
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none
