Repository cri-o/cri-o, pull requests merged in 2021-08, with the labels that each got.

#5145 server: configure MountPoint for dropped infra containers
  server/sandbox_run_linux.go
  test/inspect.bats
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#5150 make `runtime_status_test` more accurate.
  server/runtime_status_test.go
Labels: approved, dco-signoff: yes, kind/other, lgtm, ok-to-test, release-note-none

#5162 [1.21] oci: fix a performance regression from execs
  go.mod
  go.sum
  internal/dirnotifier/dirnotifier.go
  internal/dirnotifier/dirnotifier_test.go
  internal/dirnotifier/suite_test.go
  internal/lib/container_server.go
  internal/lib/container_server_test.go
  internal/lib/suite_test.go
  internal/oci/oci.go
  internal/oci/oci_test.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  server/container_execsync.go
  vendor/github.com/rjeczalik/notify/.gitignore
  vendor/github.com/rjeczalik/notify/.travis.yml
  vendor/github.com/rjeczalik/notify/AUTHORS
  vendor/github.com/rjeczalik/notify/LICENSE
  vendor/github.com/rjeczalik/notify/README.md
  vendor/github.com/rjeczalik/notify/appveyor.yml
  vendor/github.com/rjeczalik/notify/debug.go
  vendor/github.com/rjeczalik/notify/debug_debug.go
  vendor/github.com/rjeczalik/notify/debug_nodebug.go
  vendor/github.com/rjeczalik/notify/doc.go
  vendor/github.com/rjeczalik/notify/event.go
  vendor/github.com/rjeczalik/notify/event_fen.go
  vendor/github.com/rjeczalik/notify/event_fsevents.go
  vendor/github.com/rjeczalik/notify/event_inotify.go
  vendor/github.com/rjeczalik/notify/event_kqueue.go
  vendor/github.com/rjeczalik/notify/event_readdcw.go
  vendor/github.com/rjeczalik/notify/event_stub.go
  vendor/github.com/rjeczalik/notify/event_trigger.go
  vendor/github.com/rjeczalik/notify/go.mod
  vendor/github.com/rjeczalik/notify/node.go
  vendor/github.com/rjeczalik/notify/notify.go
  vendor/github.com/rjeczalik/notify/tree.go
  vendor/github.com/rjeczalik/notify/tree_nonrecursive.go
  vendor/github.com/rjeczalik/notify/tree_recursive.go
  vendor/github.com/rjeczalik/notify/util.go
  vendor/github.com/rjeczalik/notify/watcher.go
  vendor/github.com/rjeczalik/notify/watcher_fen.go
  vendor/github.com/rjeczalik/notify/watcher_fen_cgo.go
  vendor/github.com/rjeczalik/notify/watcher_fsevents.go
  vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go
  vendor/github.com/rjeczalik/notify/watcher_inotify.go
  vendor/github.com/rjeczalik/notify/watcher_kqueue.go
  vendor/github.com/rjeczalik/notify/watcher_notimplemented.go
  vendor/github.com/rjeczalik/notify/watcher_readdcw.go
  vendor/github.com/rjeczalik/notify/watcher_stub.go
  vendor/github.com/rjeczalik/notify/watcher_trigger.go
  vendor/github.com/rjeczalik/notify/watchpoint.go
  vendor/github.com/rjeczalik/notify/watchpoint_other.go
  vendor/github.com/rjeczalik/notify/watchpoint_readdcw.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#5136 oci: fix a performance regression from execs
  go.mod
  go.sum
  internal/dirnotifier/dirnotifier.go
  internal/dirnotifier/dirnotifier_test.go
  internal/dirnotifier/suite_test.go
  internal/lib/container_server.go
  internal/lib/container_server_test.go
  internal/lib/suite_test.go
  internal/oci/oci.go
  internal/oci/oci_test.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  server/container_execsync.go
  vendor/github.com/rjeczalik/notify/.gitignore
  vendor/github.com/rjeczalik/notify/.travis.yml
  vendor/github.com/rjeczalik/notify/AUTHORS
  vendor/github.com/rjeczalik/notify/LICENSE
  vendor/github.com/rjeczalik/notify/README.md
  vendor/github.com/rjeczalik/notify/appveyor.yml
  vendor/github.com/rjeczalik/notify/debug.go
  vendor/github.com/rjeczalik/notify/debug_debug.go
  vendor/github.com/rjeczalik/notify/debug_nodebug.go
  vendor/github.com/rjeczalik/notify/doc.go
  vendor/github.com/rjeczalik/notify/event.go
  vendor/github.com/rjeczalik/notify/event_fen.go
  vendor/github.com/rjeczalik/notify/event_fsevents.go
  vendor/github.com/rjeczalik/notify/event_inotify.go
  vendor/github.com/rjeczalik/notify/event_kqueue.go
  vendor/github.com/rjeczalik/notify/event_readdcw.go
  vendor/github.com/rjeczalik/notify/event_stub.go
  vendor/github.com/rjeczalik/notify/event_trigger.go
  vendor/github.com/rjeczalik/notify/go.mod
  vendor/github.com/rjeczalik/notify/node.go
  vendor/github.com/rjeczalik/notify/notify.go
  vendor/github.com/rjeczalik/notify/tree.go
  vendor/github.com/rjeczalik/notify/tree_nonrecursive.go
  vendor/github.com/rjeczalik/notify/tree_recursive.go
  vendor/github.com/rjeczalik/notify/util.go
  vendor/github.com/rjeczalik/notify/watcher.go
  vendor/github.com/rjeczalik/notify/watcher_fen.go
  vendor/github.com/rjeczalik/notify/watcher_fen_cgo.go
  vendor/github.com/rjeczalik/notify/watcher_fsevents.go
  vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go
  vendor/github.com/rjeczalik/notify/watcher_inotify.go
  vendor/github.com/rjeczalik/notify/watcher_kqueue.go
  vendor/github.com/rjeczalik/notify/watcher_notimplemented.go
  vendor/github.com/rjeczalik/notify/watcher_readdcw.go
  vendor/github.com/rjeczalik/notify/watcher_stub.go
  vendor/github.com/rjeczalik/notify/watcher_trigger.go
  vendor/github.com/rjeczalik/notify/watchpoint.go
  vendor/github.com/rjeczalik/notify/watchpoint_other.go
  vendor/github.com/rjeczalik/notify/watchpoint_readdcw.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#5051 Bug 1868221: Add symlink /etc/mtab to container
  server/container_create_linux.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#5110 Bump nixpkgs
  Makefile
  nix/default-arm64.nix
  nix/default.nix
  nix/derivation.nix
  nix/nixpkgs.json
  nix/static.nix
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note-none

#5168 Fix linkmode retrieval for non en_US systems
  internal/version/version.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5164 [1.20] oci: fix a performance regression from execs
  go.mod
  go.sum
  internal/dirnotifier/dirnotifier.go
  internal/dirnotifier/dirnotifier_test.go
  internal/dirnotifier/suite_test.go
  internal/lib/container_server.go
  internal/lib/container_server_test.go
  internal/lib/suite_test.go
  internal/oci/oci.go
  internal/oci/oci_test.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  vendor/github.com/rjeczalik/notify/.gitignore
  vendor/github.com/rjeczalik/notify/.travis.yml
  vendor/github.com/rjeczalik/notify/AUTHORS
  vendor/github.com/rjeczalik/notify/LICENSE
  vendor/github.com/rjeczalik/notify/README.md
  vendor/github.com/rjeczalik/notify/appveyor.yml
  vendor/github.com/rjeczalik/notify/debug.go
  vendor/github.com/rjeczalik/notify/debug_debug.go
  vendor/github.com/rjeczalik/notify/debug_nodebug.go
  vendor/github.com/rjeczalik/notify/doc.go
  vendor/github.com/rjeczalik/notify/event.go
  vendor/github.com/rjeczalik/notify/event_fen.go
  vendor/github.com/rjeczalik/notify/event_fsevents.go
  vendor/github.com/rjeczalik/notify/event_inotify.go
  vendor/github.com/rjeczalik/notify/event_kqueue.go
  vendor/github.com/rjeczalik/notify/event_readdcw.go
  vendor/github.com/rjeczalik/notify/event_stub.go
  vendor/github.com/rjeczalik/notify/event_trigger.go
  vendor/github.com/rjeczalik/notify/go.mod
  vendor/github.com/rjeczalik/notify/node.go
  vendor/github.com/rjeczalik/notify/notify.go
  vendor/github.com/rjeczalik/notify/tree.go
  vendor/github.com/rjeczalik/notify/tree_nonrecursive.go
  vendor/github.com/rjeczalik/notify/tree_recursive.go
  vendor/github.com/rjeczalik/notify/util.go
  vendor/github.com/rjeczalik/notify/watcher.go
  vendor/github.com/rjeczalik/notify/watcher_fen.go
  vendor/github.com/rjeczalik/notify/watcher_fen_cgo.go
  vendor/github.com/rjeczalik/notify/watcher_fsevents.go
  vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go
  vendor/github.com/rjeczalik/notify/watcher_inotify.go
  vendor/github.com/rjeczalik/notify/watcher_kqueue.go
  vendor/github.com/rjeczalik/notify/watcher_notimplemented.go
  vendor/github.com/rjeczalik/notify/watcher_readdcw.go
  vendor/github.com/rjeczalik/notify/watcher_stub.go
  vendor/github.com/rjeczalik/notify/watcher_trigger.go
  vendor/github.com/rjeczalik/notify/watchpoint.go
  vendor/github.com/rjeczalik/notify/watchpoint_other.go
  vendor/github.com/rjeczalik/notify/watchpoint_readdcw.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5174 [1.19] oci: fix performance regression in execs
  go.mod
  go.sum
  internal/dirnotifier/dirnotifier.go
  internal/dirnotifier/dirnotifier_test.go
  internal/dirnotifier/suite_test.go
  internal/lib/container_server.go
  internal/lib/container_server_test.go
  internal/lib/suite_test.go
  internal/oci/oci.go
  internal/oci/oci_test.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  vendor/github.com/rjeczalik/notify/.gitignore
  vendor/github.com/rjeczalik/notify/.travis.yml
  vendor/github.com/rjeczalik/notify/AUTHORS
  vendor/github.com/rjeczalik/notify/LICENSE
  vendor/github.com/rjeczalik/notify/README.md
  vendor/github.com/rjeczalik/notify/appveyor.yml
  vendor/github.com/rjeczalik/notify/debug.go
  vendor/github.com/rjeczalik/notify/debug_debug.go
  vendor/github.com/rjeczalik/notify/debug_nodebug.go
  vendor/github.com/rjeczalik/notify/doc.go
  vendor/github.com/rjeczalik/notify/event.go
  vendor/github.com/rjeczalik/notify/event_fen.go
  vendor/github.com/rjeczalik/notify/event_fsevents.go
  vendor/github.com/rjeczalik/notify/event_inotify.go
  vendor/github.com/rjeczalik/notify/event_kqueue.go
  vendor/github.com/rjeczalik/notify/event_readdcw.go
  vendor/github.com/rjeczalik/notify/event_stub.go
  vendor/github.com/rjeczalik/notify/event_trigger.go
  vendor/github.com/rjeczalik/notify/go.mod
  vendor/github.com/rjeczalik/notify/node.go
  vendor/github.com/rjeczalik/notify/notify.go
  vendor/github.com/rjeczalik/notify/tree.go
  vendor/github.com/rjeczalik/notify/tree_nonrecursive.go
  vendor/github.com/rjeczalik/notify/tree_recursive.go
  vendor/github.com/rjeczalik/notify/util.go
  vendor/github.com/rjeczalik/notify/watcher.go
  vendor/github.com/rjeczalik/notify/watcher_fen.go
  vendor/github.com/rjeczalik/notify/watcher_fen_cgo.go
  vendor/github.com/rjeczalik/notify/watcher_fsevents.go
  vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go
  vendor/github.com/rjeczalik/notify/watcher_inotify.go
  vendor/github.com/rjeczalik/notify/watcher_kqueue.go
  vendor/github.com/rjeczalik/notify/watcher_notimplemented.go
  vendor/github.com/rjeczalik/notify/watcher_readdcw.go
  vendor/github.com/rjeczalik/notify/watcher_stub.go
  vendor/github.com/rjeczalik/notify/watcher_trigger.go
  vendor/github.com/rjeczalik/notify/watchpoint.go
  vendor/github.com/rjeczalik/notify/watchpoint_other.go
  vendor/github.com/rjeczalik/notify/watchpoint_readdcw.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5129 Add a hidden 'publish' command to CRI-O
  cmd/crio/main.go
  cmd/crio/publish.go
  completions/bash/crio
  completions/zsh/_crio
  internal/criocli/criocli.go
Labels: kind/feature, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#5161 Unit Test For Defunct Processes Metric
  internal/process/defunct_processes.go
  internal/process/defunct_processes_suite_test.go
  internal/process/defunct_processes_test.go
  internal/process/testing/proc_fail
  internal/process/testing/proc_success_1/1/cgroup
  internal/process/testing/proc_success_1/1/stat
  internal/process/testing/proc_success_1/1/statm
  internal/process/testing/proc_success_1/10/cgroup
  internal/process/testing/proc_success_1/10/stat
  internal/process/testing/proc_success_1/10/statm
  internal/process/testing/proc_success_1/102/cgroup
  internal/process/testing/proc_success_1/102/stat
  internal/process/testing/proc_success_1/102/statm
  internal/process/testing/proc_success_1/1037/cgroup
  internal/process/testing/proc_success_1/1037/stat
  internal/process/testing/proc_success_1/1037/statm
  internal/process/testing/proc_success_1/2096/cgroup
  internal/process/testing/proc_success_1/2096/stat
  internal/process/testing/proc_success_1/2096/statm
  internal/process/testing/proc_success_1/215/cgroup
  internal/process/testing/proc_success_1/215/stat
  internal/process/testing/proc_success_1/215/statm
  internal/process/testing/proc_success_1/3/cgroup
  internal/process/testing/proc_success_1/3/stat
  internal/process/testing/proc_success_1/3/statm
  internal/process/testing/proc_success_1/4010/cgroup
  internal/process/testing/proc_success_1/4010/stat
  internal/process/testing/proc_success_1/4010/statm
  internal/process/testing/proc_success_1/423/cgroup
  internal/process/testing/proc_success_1/423/stat
  internal/process/testing/proc_success_1/423/statm
  internal/process/testing/proc_success_1/809/cgroup
  internal/process/testing/proc_success_1/809/stat
  internal/process/testing/proc_success_1/809/statm
  internal/process/testing/proc_success_1/cgroups
  internal/process/testing/proc_success_1/sys/dev
  internal/process/testing/proc_success_2/1/cgroup
  internal/process/testing/proc_success_2/1/stat
  internal/process/testing/proc_success_2/1/statm
  internal/process/testing/proc_success_2/cgroups
  internal/process/testing/proc_success_2/sys/dev
  internal/process/testing/proc_success_3/cgroups
  internal/process/testing/proc_success_3/sys/dev
  internal/process/testing/proc_success_4/cgroups
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#5167 Add a script for crio installation for node e2e
  scripts/node_e2e_installer
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes, kind/ci

#5182 Bump required golang version for cri-o.spec
  contrib/test/ci/cri-o.spec
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes

#4620 cri: Devices ownership from SecurityContext
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  pkg/config/config.go
  pkg/config/template.go
  pkg/container/container.go
  pkg/container/device.go
  pkg/container/device_test.go
  server/container_create_linux.go
Labels: lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#4958 [1.11] set inactive-or-failed collectmode if appropriate
  cmd/crio/main.go
  contrib/test/integration/build/cri-tools.yml
  contrib/test/integration/critest.yml
  contrib/test/integration/golang.yml
  lib/node/node.go
  lib/node/systemd.go
  server/container_create.go
  server/sandbox_run.go
  test/ctr_seccomp.bats
  vendor.conf
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#4981 1.11 conmon: kill process group if timed out
  conmon/conmon.c
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#5196 Fix kubeadm.md typo
  tutorials/kubeadm.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#5205 [1.21] scripts: pin cri-tools version
  scripts/github-actions-setup
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#5201 [1.20] Bump c/storage to latest release-1.24
  go.mod
  go.sum
  vendor/github.com/containers/storage/layers.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5134 Log structured container/sandbox ID and PID on start
  internal/log/log.go
  server/container_start.go
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#5209 docs: remove outdated field
  docs/crio.conf.5.md
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#4759 config: use deep equal to compare workloads and runtimes
  pkg/config/template.go
  pkg/config/template_test.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#4830 Support Intel RDT
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  go.mod
  go.sum
  internal/config/rdt/rdt.go
  internal/config/rdt/rdt_test.go
  internal/config/rdt/suite_test.go
  internal/criocli/criocli.go
  pkg/annotations/annotations.go
  pkg/config/config.go
  pkg/config/reload.go
  pkg/config/template.go
  server/container_create_linux.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/gofuzz/.travis.yml
  vendor/github.com/google/gofuzz/CONTRIBUTING.md
  vendor/github.com/google/gofuzz/README.md
  vendor/github.com/google/gofuzz/bytesource/bytesource.go
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/github.com/hashicorp/errwrap/errwrap.go
  vendor/github.com/intel/goresctrl/LICENSE
  vendor/github.com/intel/goresctrl/pkg/kubernetes/annotations.go
  vendor/github.com/intel/goresctrl/pkg/log/log.go
  vendor/github.com/intel/goresctrl/pkg/rdt/bitmask.go
  vendor/github.com/intel/goresctrl/pkg/rdt/config.go
  vendor/github.com/intel/goresctrl/pkg/rdt/info.go
  vendor/github.com/intel/goresctrl/pkg/rdt/kubernetes.go
  vendor/github.com/intel/goresctrl/pkg/rdt/prometheus.go
  vendor/github.com/intel/goresctrl/pkg/rdt/rdt.go
  vendor/github.com/intel/goresctrl/pkg/utils/json.go
  vendor/github.com/intel/goresctrl/pkg/utils/sort.go
  vendor/golang.org/x/oauth2/internal/client_appengine.go
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#5214 [1.20] oci: fix panic on double close
  internal/oci/runtime_oci.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5213 [1.21] oci: fix panic on double close
  internal/oci/runtime_oci.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5215 [1.19] oci: fix panic on double close
  internal/oci/runtime_oci.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5135 List build tags and seccomp/apparmor status on `version` subcommand
  internal/version/buildtag_apparmor.go
  internal/version/buildtag_devicemapper.go
  internal/version/buildtag_openpgp.go
  internal/version/buildtag_ostree.go
  internal/version/buildtag_seccomp.go
  internal/version/buildtag_selinux.go
  internal/version/version.go
  test/version.bats
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#5212 oci: fix panic on double close
  internal/oci/runtime_oci.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5199 Allow expanded DNS configuration
  pkg/sandbox/fixtures/expanded_resolv.conf
  pkg/sandbox/infra.go
  pkg/sandbox/infra_test.go
Labels: kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#5194 Bump runc to 1.0.1
  dependencies.yaml
  scripts/versions
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/dependency-change

#5183 node: log if we are using cgroupv2
  internal/config/node/node.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5226 Bump node e2e test commit to use runc v1.0.1
  scripts/node_e2e_installer
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#5191 server: return a better error when container requests pod pid ns, but…
  server/container_create_linux.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#5175 dirnotifier: optimize accesses to Map
  internal/dirnotifier/dirnotifier.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#5155 server: do not check storage for image name on inspect
  server/inspect.go
  server/inspect_ginkgo_test.go
  server/inspect_test.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#5173 drop crio.shutdown support
  Makefile
  contrib/systemd/crio-shutdown.service
  contrib/test/ci/cri-o.spec
  server/sandbox_stop.go
  server/server.go
Labels: kind/design, lgtm, approved, release-note, dco-signoff: yes

#5179 service file: add alias for cri-o
  Makefile
  contrib/systemd/crio.service
  contrib/test/ci/cri-o.spec
  contrib/test/ci/crio-metrics.sysconfig
  contrib/test/ci/crio-network.sysconfig
  contrib/test/ci/crio-storage.sysconfig
  contrib/test/ci/crio.service
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/other

#5239 Switch to build tag for linkmode
  internal/version/linkmode_dynamic.go
  internal/version/linkmode_static.go
  internal/version/version.go
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#5229 [1.20] introduce clean shutdown handling
  cmd/crio/main.go
  cmd/crio/wipe.go
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  pkg/config/config.go
  pkg/config/config_unix.go
  pkg/config/template.go
  server/server.go
  server/server_test.go
  server/suite_test.go
  test/crio-wipe.bats
  test/helpers.bash
  utils/utils.go
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#5235 [1.19] introduce clean shutdown handling
  cmd/crio/main.go
  cmd/crio/wipe.go
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  pkg/config/config.go
  pkg/config/config_unix.go
  pkg/config/template.go
  server/server.go
  server/server_test.go
  server/suite_test.go
  test/crio-wipe.bats
  test/helpers.bash
  utils/utils.go
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#5238 fix checking in openpgp_tag.sh
  .github/workflows/verify.yml
  hack/openpgp_tag.sh
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#5218 config: set internal_wipe to true by default, and deprecate the option
  completions/fish/crio.fish
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  pkg/config/config.go
  test/crio-wipe.bats
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/deprecation

#4873 Support for cgroups blockio
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  go.mod
  go.sum
  internal/config/blockio/blockio.go
  internal/config/blockio/blockio_test.go
  internal/config/blockio/suite_test.go
  internal/criocli/criocli.go
  pkg/config/config.go
  pkg/config/reload.go
  pkg/config/template.go
  server/container_create_linux.go
  vendor/github.com/intel/goresctrl/pkg/blockio/blockio.go
  vendor/github.com/intel/goresctrl/pkg/blockio/config.go
  vendor/github.com/intel/goresctrl/pkg/blockio/kubernetes.go
  vendor/github.com/intel/goresctrl/pkg/blockio/oci.go
  vendor/github.com/intel/goresctrl/pkg/cgroups/cgroupblkio.go
  vendor/github.com/intel/goresctrl/pkg/cgroups/cgroupcontrol.go
  vendor/github.com/intel/goresctrl/pkg/cgroups/cgroupid.go
  vendor/github.com/intel/goresctrl/pkg/cgroups/cgrouppath.go
  vendor/github.com/intel/goresctrl/pkg/cgroups/fsi.go
  vendor/github.com/intel/goresctrl/pkg/cgroups/fsimock.go
  vendor/github.com/intel/goresctrl/pkg/cgroups/fsios.go
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#5245 oci: use conmon for exec again
  internal/dirnotifier/dirnotifier.go
  internal/dirnotifier/dirnotifier_test.go
  internal/dirnotifier/suite_test.go
  internal/oci/oci.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5262 [1.21] oci: use conmon for exec again
  internal/dirnotifier/dirnotifier.go
  internal/dirnotifier/dirnotifier_test.go
  internal/dirnotifier/suite_test.go
  internal/oci/oci.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
Labels: lgtm, approved, release-note, dco-signoff: yes
