Repository cri-o/cri-o, pull requests merged in 2021-01, with the labels that each got.

#4446 Add Digital Science to adopters
  ADOPTERS.md
Labels: approved, dco-signoff: yes, kind/other, lgtm, ok-to-test, release-note-none

#4453 [1.18] set inactive-or-failed CollectMode if appropriate
  internal/config/node/node.go
  internal/config/node/systemd.go
  pkg/config/config.go
  server/container_create_linux.go
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4450 contrib/test/integration: parallel build process in CentOS
  contrib/test/integration/build/parallel.yml
Labels: approved, dco-signoff: yes, kind/ci, lgtm, ok-to-test, release-note-none

#4467 Rollback gocapability vendor bump
  go.mod
  go.sum
  vendor/github.com/syndtr/gocapability/capability/enum.go
  vendor/github.com/syndtr/gocapability/capability/enum_gen.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test, release-note-none

#4459 Provide functionality to start infra containers on the specified set of CPUs
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  internal/oci/oci.go
  pkg/config/config.go
  pkg/config/template.go
  server/sandbox_run_linux.go
  test/infra_ctr_cpuset.bats
Labels: approved, dco-signoff: yes, kind/feature, lgtm, ok-to-test, release-note

#4449 Add initial Kata Containers support to contrib/test/integration playbook
  contrib/test/integration/build/cri-o.yml
  contrib/test/integration/build/kata.yml
  contrib/test/integration/main.yml
  contrib/test/integration/test.yml
  contrib/test/integration/vars.yml
Labels: approved, dco-signoff: yes, kind/ci, lgtm, ok-to-test, release-note-none

#4473 Return runtime API version based on protocol
  server/cri/v1/rpc_version.go
  server/cri/v1alpha2/rpc_version.go
  server/version.go
  server/version_test.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#4469 [1.20] Provide functionality to start infra containers on the specified set of CPUs
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  internal/oci/oci.go
  pkg/config/config.go
  pkg/config/template.go
  server/sandbox_run_linux.go
  test/infra_ctr_cpuset.bats
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#4477 add `regitries` deprecation notice
  docs/crio.conf.5.md
  pkg/config/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note

#4348 Make Ingress/Egress Burst upper limit slightly under 4GB
  server/utils.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test, release-note

#4406 server: use IsAlive() more
  internal/lib/container_server.go
  server/container_attach.go
  server/container_exec.go
  server/container_reopen_log.go
  server/container_update_resources.go
  server/container_update_resources_test.go
  server/sandbox_remove.go
  server/sandbox_stop_linux.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4425 release-notes: fix flags
  scripts/release-notes/release_notes.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4439 Refactor managed namespace handling
  Makefile
  internal/config/nsmgr/nsmgr.go
  internal/config/nsmgr/types.go
  internal/lib/sandbox/namespaces.go
  internal/lib/sandbox/namespaces_linux.go
  internal/lib/sandbox/namespaces_test.go
  internal/lib/sandbox/sandbox.go
  internal/lib/sandbox/suite_test.go
  pkg/config/config.go
  server/sandbox_run_linux.go
  test/mocks/sandbox/sandbox.go
Labels: approved, dco-signoff: yes, kind/design, lgtm, release-note-none

#4440 docs: update kubeadm tutorial
  install.md
  tutorials/kubeadm.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none

#4492 Do not log file path on ioutil.ReadFile
  internal/config/seccomp/seccomp.go
  internal/oci/runtime_oci.go
  server/server.go
  server/utils.go
  test/docs-validation/main.go
  utils/utils.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#4441 handle irqbalance service
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  internal/runtimehandlerhooks/high_performance_hooks.go
  internal/runtimehandlerhooks/high_performance_hooks_test.go
  internal/runtimehandlerhooks/runtime_handler_hooks.go
  internal/runtimehandlerhooks/utils.go
  pkg/config/config.go
  pkg/config/template.go
  server/container_start.go
  server/container_stop.go
  server/sandbox_stop_linux.go
  server/server.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note

#4480 Fix `make lint`
  Makefile
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4468 runtime_vm: set finished time when containers stop
  internal/oci/runtime_vm.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4487 Close the stdin/tty on server start to avoid shortname prompts
  server/server.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#4500 Make rootless namespace unit test execution work
  internal/lib/sandbox/namespaces_test.go
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#4501 Make config tests work rootless
  pkg/config/config_test.go
  pkg/config/suite_test.go
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#4471 Update compatibility matrix to mention v1.20
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none

#4043 [1.18] stats: return information on container level, not pod
  internal/oci/oci.go
  internal/oci/oci_linux.go
  server/container_create.go
  server/container_create_linux.go
  server/sandbox_run_linux.go
  test/stats.bats
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4482 [1.19] image pull: close progress chan
  server/image_pull.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note

#4503 Move docs and completions validation to GitHub actions
  .circleci/config.yml
  .github/workflows/test.yml
  Makefile
  scripts/github-actions-packages
Labels: approved, dco-signoff: yes, kind/ci, lgtm, release-note-none

#4395 Update nix pin with `make nixpkgs`
  Makefile
  nix/default.nix
  nix/nixpkgs.json
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note

#4490 fixes version_test.go
  internal/version/suite_test.go
  internal/version/version_test.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, ok-to-test, release-note-none

#4495 update pinns to support pinning host level namespaces
  internal/config/nsmgr/nsmgr.go
  internal/config/nsmgr/types.go
  pinns/src/pinns.c
  server/sandbox_run_linux.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#4514 Support pprof profile over unix socket
  cmd/crio/main.go
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  internal/criocli/criocli.go
  server/inspect.go
  server/inspect_ginkgo_test.go
  test/profile.bats
Labels: approved, dco-signoff: yes, kind/feature, lgtm, needs-backport, release-note

#4512 Lookup echo command for unit tests
  server/suite_test.go
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#4510 Move static build to GitHub actions
  .circleci/config.yml
  .github/workflows/test.yml
  contrib/bundle/Makefile
  contrib/bundle/build
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#4520 [1.20] Support pprof profile over unix socket
  cmd/crio/main.go
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  internal/criocli/criocli.go
  server/inspect.go
  server/inspect_ginkgo_test.go
  test/profile.bats
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#4504 Remove implicit GitHub action `name` fields
  .github/workflows/verify.yml
Labels: approved, dco-signoff: yes, kind/ci, lgtm, release-note-none
