Repository cri-o/cri-o, pull requests merged in 2021-09, with the labels that each got.

#5271 [1.20] Fix CI issues
  contrib/test/integration/main.yml
  scripts/github-actions-setup
  scripts/versions
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#5272 [1.19] test: Pin gomega and ginkgo versions
  contrib/test/integration/golang.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#5274 [1.19] Use conmon for exec
  internal/dirnotifier/dirnotifier.go
  internal/dirnotifier/dirnotifier_test.go
  internal/dirnotifier/suite_test.go
  internal/lib/container_server.go
  internal/lib/container_server_test.go
  internal/lib/suite_test.go
  internal/oci/oci.go
  internal/oci/oci_test.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  test/ctr.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5283 oci: call wait on conmon if cgroup move fails
  internal/oci/runtime_oci.go
  internal/storage/image.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5263 server: remove ineffective `updateLock`.
  server/container_create.go
  server/sandbox_run_linux.go
  server/server.go
Labels: lgtm, approved, kind/cleanup, release-note-none, ok-to-test, dco-signoff: yes

#5286 Fix cluster.yaml for kubectl create
  contrib/metrics-exporter/cluster.yaml
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5291 version: bump to v1.19.4
  internal/version/version.go
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#5290 version: bump to v1.20.5
  internal/version/version.go
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#5289 version: bump to v1.21.3
  internal/version/version.go
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#5293 Do not log on startup if Intel RDT is not supported
  internal/config/rdt/rdt.go
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#5280 Remove bashism in sh script
  contrib/bundle/install
  scripts/get
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#5306 server: do not wait forever on conmon cgroup move fail
  internal/oci/runtime_oci.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5313 server: set spec when dropping infra
  internal/lib/container_server.go
  server/sandbox_status.go
  test/drop_infra.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5312 Update 'master' branch links to 'main'
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/integration.yml
  .github/workflows/test.yml
  .github/workflows/verify.yml
  README.md
  cri.md
  install.md
  internal/hostport/README.md
  scripts/node_e2e_installer
  test/README.md
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes, kind/other

#5268 Add `--profile-cpu` and `--profile-mem` options
  cmd/crio/main.go
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  internal/criocli/criocli.go
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#5310 updates pause image to 3.6
  docs/crio.8.md
  docs/crio.conf.5.md
  pkg/config/config.go
  test/helpers.bash
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/dependency-change

#5316 fix shfmt
  test/drop_infra.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#5328 Add unit test for the `server/sandbox_remove`.
  server/sandbox_remove_test.go
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes, kind/other

#5337 node e2e: keep infra container
  scripts/node_e2e_installer
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes

#5334 test: fix journald test for new conmon
  test/ctr.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#5331 Remove one of the explanations for `bind_mount_prefix` because it is duplicated.
  docs/crio.conf.5.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#4696 test/testdata/sandbox_config.json: fix the dns_config
  test/testdata/sandbox_config.json
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/other

#5307 [1.19] gh actions: fix workflow
  .github/workflows/test.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#5342 Fix typo in install.md
  install.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#5347 bump crio commit for node e2e installer
  scripts/node_e2e_installer
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes, kind/other

#5354 fix node e2e
  scripts/node_e2e_installer
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#5244 server: fix some hostNet handling in container creation
  server/container_create.go
  server/container_create_linux.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5359 use a more appropriate console with code block
  README.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#5158 fix debian 10 build doc
  install.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes
