Repository cri-o/cri-o, pull requests merged in 2021-10, with the labels that each got.

#5362 Fix install.md links
  install.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#5369 Remove usge of deprecated apt-key in Ubuntu install
  install.md
  tutorials/install-distro.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#5378 test: skip certificate check for downloading parallel
  contrib/test/integration/build/parallel.yml
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes

#5364 [1.20] oci: finish reverting exec changes
  internal/oci/oci.go
  internal/oci/runtime_oci.go
  test/ctr.bats
Labels: lgtm, approved, release-note, dco-signoff: yes
