Repository cri-o/cri-o, pull requests merged in 2022-03, with the labels that each got.

#5688 test/crio-wipe.bats: fix test case teardown ordering.
  test/crio-wipe.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#5686 [1.21] server: filter sysctls passed through CRI if host namespace
  pkg/config/sysctl.go
  server/sandbox_run_linux.go
  test/pod.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5691 test: allow state of failing tests to be kept intact.
  test/helpers.bash
  test/test_runner.sh
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/other

#5700 Pin nixos/nix version
  Makefile
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#5701 Bump nixpkgs
  nix/nixpkgs.json
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#5695 [1.19] Add container out of memory metrics
  hack/build-rpms.sh
  internal/oci/runtime_oci.go
  internal/oci/runtime_vm.go
  server/metrics/metrics.go
  test/ctr.bats
  test/helpers.bash
  test/metrics.bats
  tutorials/metrics.md
Labels: lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#5692 Add dedicated security information
  SECURITY.md
  SECURITY_CONTACTS
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#5705 bump to 1.21.5
  internal/version/version.go
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#5332 [1.19] server: handle processes better
  internal/oci/runtime_oci.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5710 bump to v1.19.5
  internal/version/version.go
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#5707 Switch to `main` for `get` script
  scripts/get
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes, kind/ci

#5711 Automatically `chcon` and `restorecon` on get script
  contrib/bundle/install
  scripts/get
  scripts/node_e2e_installer
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#5717 test: update to new runc behavior
  test/drop_infra.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#5726 README: Update EOL & Version Skew links
  README.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#5727 Fix shell format
  test/pod.bats
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes, kind/ci

#5587 Enable `--seccomp-use-default-when-empty` by default
  completions/fish/crio.fish
  contrib/test/integration/critest.yml
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/config/seccomp/seccomp.go
  internal/criocli/criocli.go
  pkg/config/config.go
  test/critest.bats
  test/ctr_seccomp.bats
Labels: kind/feature, lgtm, approved, release-note, kind/api-change, dco-signoff: yes

#5708 Pin `github.com/u-root/u-root`
  .github/workflows/verify.yml
  go.mod
  go.sum
  vendor/github.com/vishvananda/netlink/README.md
  vendor/github.com/vishvananda/netlink/class_linux.go
  vendor/github.com/vishvananda/netlink/conntrack_linux.go
  vendor/github.com/vishvananda/netlink/devlink_linux.go
  vendor/github.com/vishvananda/netlink/filter_linux.go
  vendor/github.com/vishvananda/netlink/handle_linux.go
  vendor/github.com/vishvananda/netlink/handle_unspecified.go
  vendor/github.com/vishvananda/netlink/ipset_linux.go
  vendor/github.com/vishvananda/netlink/link.go
  vendor/github.com/vishvananda/netlink/link_linux.go
  vendor/github.com/vishvananda/netlink/neigh.go
  vendor/github.com/vishvananda/netlink/neigh_linux.go
  vendor/github.com/vishvananda/netlink/netlink_unspecified.go
  vendor/github.com/vishvananda/netlink/netns_linux.go
  vendor/github.com/vishvananda/netlink/nl/conntrack_linux.go
  vendor/github.com/vishvananda/netlink/nl/devlink_linux.go
  vendor/github.com/vishvananda/netlink/nl/link_linux.go
  vendor/github.com/vishvananda/netlink/nl/rdma_link_linux.go
  vendor/github.com/vishvananda/netlink/nl/seg6_linux.go
  vendor/github.com/vishvananda/netlink/nl/syscall.go
  vendor/github.com/vishvananda/netlink/nl/tc_linux.go
  vendor/github.com/vishvananda/netlink/rdma_link_linux.go
  vendor/github.com/vishvananda/netlink/route.go
  vendor/github.com/vishvananda/netlink/route_linux.go
  vendor/github.com/vishvananda/netlink/rule.go
  vendor/github.com/vishvananda/netlink/xfrm_state_linux.go
  vendor/golang.org/x/mod/modfile/read.go
  vendor/golang.org/x/mod/modfile/rule.go
  vendor/golang.org/x/mod/module/module.go
  vendor/golang.org/x/mod/module/pseudo.go
  vendor/golang.org/x/mod/semver/semver.go
  vendor/golang.org/x/net/http2/hpack/huffman.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/cpu/cpu_gc_x86.go
  vendor/golang.org/x/sys/windows/mksyscall.go
  vendor/golang.org/x/sys/windows/setupapi_windows.go
  vendor/golang.org/x/sys/windows/setupapierrors_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/term.go
  vendor/modules.txt
  vendor/mvdan.cc/sh/v3/cmd/shfmt/Dockerfile
  vendor/mvdan.cc/sh/v3/cmd/shfmt/main.go
  vendor/mvdan.cc/sh/v3/fileutil/file.go
  vendor/mvdan.cc/sh/v3/syntax/fuzz
  vendor/mvdan.cc/sh/v3/syntax/fuzz.go
  vendor/mvdan.cc/sh/v3/syntax/lexer.go
  vendor/mvdan.cc/sh/v3/syntax/parser.go
  vendor/mvdan.cc/sh/v3/syntax/quote.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#5728 pinns: Pass sysctls as repeated '-s' arguments
  internal/config/nsmgr/nsmgr.go
  pinns/src/pinns.c
  pinns/src/sysctl.c
  pinns/src/sysctl.h
Labels: lgtm, approved, kind/cleanup, release-note-none, ok-to-test, dco-signoff: yes

#5749 Add bats test for zombie conmon cleanup
  test/pod.bats
  test/workloads.bats
Labels: lgtm, approved, kind/cleanup, release-note-none, ok-to-test, dco-signoff: yes

#5694 factory: take capabilities setup
  internal/factory/container/container.go
  internal/factory/container/container_test.go
  internal/factory/sandbox/infra.go
  server/container_create.go
  server/container_create_linux.go
  server/sandbox_run_linux.go
  server/utils.go
Labels: kind/design, lgtm, approved, release-note-none, dco-signoff: yes

#5748 Update golangci-lint and config
  .github/workflows/verify.yml
  .golangci.yml
  Makefile
  dependencies.yaml
  internal/client/client.go
  internal/config/cnimgr/cnimgr.go
  internal/hostport/fake_iptables.go
  internal/hostport/meta_hostport_manager.go
  internal/lib/stats/stats_server.go
  internal/log/klog.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  internal/process/defunct_processes_test.go
  internal/resourcestore/resourcestore.go
  pkg/config/config.go
  server/image_pull.go
  server/inspect_ginkgo_test.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#5758 Add bats test for infra_ctr_cpuset taskset
  test/infra_ctr_cpuset.bats
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes, kind/ci

#5766 Bump ocicni to v0.3.0
  contrib/test/integration/build/plugins.yml
  dependencies.yaml
  go.mod
  go.sum
  scripts/versions
  vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/types_unix.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/types_windows.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/util_linux.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/util_unsupported.go
  vendor/github.com/onsi/gomega/.travis.yml
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/Dockerfile
  vendor/github.com/onsi/gomega/Makefile
  vendor/github.com/onsi/gomega/RELEASING.md
  vendor/github.com/onsi/gomega/docker-compose.yaml
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/internal/gutil/post_ioutil.go
  vendor/github.com/onsi/gomega/internal/gutil/using_ioutil.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/github.com/onsi/gomega/matchers/contain_element_matcher.go
  vendor/github.com/onsi/gomega/matchers/have_each_matcher.go
  vendor/github.com/onsi/gomega/matchers/have_field.go
  vendor/github.com/onsi/gomega/matchers/have_http_body_matcher.go
  vendor/github.com/onsi/gomega/matchers/have_http_status_matcher.go
  vendor/github.com/onsi/gomega/matchers/have_value.go
  vendor/github.com/onsi/gomega/tools
  vendor/golang.org/x/net/http2/go118.go
  vendor/golang.org/x/net/http2/not_go118.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/writesched.go
  vendor/golang.org/x/net/http2/writesched_random.go
  vendor/golang.org/x/net/idna/go118.go
  vendor/golang.org/x/net/idna/idna10.0.0.go
  vendor/golang.org/x/net/idna/idna9.0.0.go
  vendor/golang.org/x/net/idna/pre_go118.go
  vendor/golang.org/x/net/idna/punycode.go
  vendor/golang.org/x/sys/plan9/syscall_plan9.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_aix.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_netbsd.go
  vendor/golang.org/x/sys/unix/syscall_openbsd.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/exec_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/term/codereview.cfg
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes
