Repository cri-o/cri-o, pull requests merged in 2022-07, with the labels that each got.

#6021 remove Vagrantfile
  Vagrantfile
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#6019 Retry release notes push if failed
  scripts/release-notes/release_notes.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#5505 scripts: install runc if not found in get script
  contrib/bundle/build
  contrib/bundle/install
  scripts/get
Labels: lifecycle/stale, lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#5672 server: reduce object creation in List{Containers,PodSandboxes}
  internal/lib/sandbox/sandbox.go
  internal/oci/container.go
  server/container_list.go
  server/sandbox_list.go
Labels: kind/bug, lifecycle/stale, lgtm, approved, release-note-none, dco-signoff: yes

#6022 do not wipe images by default
  docs/crio.conf.5.md
  internal/version/version.go
  internal/version/version_test.go
  pkg/config/config.go
  pkg/config/config_unix.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#6027 Fix release notes pull behavior
  scripts/release-notes/release_notes.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#5740 Refactor Stop and Remove methods in ContainerServer and Server
  internal/lib/container_server.go
  internal/lib/remove.go
  internal/lib/remove_test.go
  internal/lib/stop.go
  internal/oci/runtime_oci.go
  server/container_remove.go
  server/container_remove_test.go
  server/container_stop.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#5927 Add annotations to allow power management configuration
  internal/runtimehandlerhooks/high_performance_hooks.go
  internal/runtimehandlerhooks/high_performance_hooks_test.go
  internal/runtimehandlerhooks/runtime_handler_hooks.go
  pkg/annotations/annotations.go
Labels: kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#6049 remove succinct option to fix jenkins
  contrib/test/integration/e2e-features.yml
  contrib/test/integration/e2e.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#6025 server: Fix Unmasked ProcMountType
  server/container_create_linux.go
Labels: kind/bug, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#5706 [1.20] Add container out of memory metrics
  internal/oci/runtime_oci.go
  internal/oci/runtime_vm.go
  server/metrics/metrics.go
  test/ctr.bats
  test/helpers.bash
  test/metrics.bats
  tutorials/metrics.md
Labels: kind/feature, lifecycle/stale, lgtm, approved, release-note, dco-signoff: yes

#5971 Add test for "Canonize selinux label"
  test/selinux.bats
Labels: lifecycle/stale, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes, kind/other

#6030 Retry dependency report push if failed
  scripts/dependencies/dependencies.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#6072 Add Lyft to adopters
  ADOPTERS.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#6065 Remove etcd dependency replacement
  go.mod
  go.sum
  vendor/go.etcd.io/etcd/v3/.gitignore
  vendor/go.etcd.io/etcd/v3/.travis.yml
  vendor/go.etcd.io/etcd/v3/.words
  vendor/go.etcd.io/etcd/v3/ADOPTERS.md
  vendor/go.etcd.io/etcd/v3/Dockerfile-release.amd64
  vendor/go.etcd.io/etcd/v3/Dockerfile-release.arm64
  vendor/go.etcd.io/etcd/v3/Dockerfile-release.ppc64le
  vendor/go.etcd.io/etcd/v3/Dockerfile-release.s390x
  vendor/go.etcd.io/etcd/v3/MAINTAINERS
  vendor/go.etcd.io/etcd/v3/Makefile
  vendor/go.etcd.io/etcd/v3/README.md
  vendor/go.etcd.io/etcd/v3/RELEASE.md
  vendor/go.etcd.io/etcd/v3/bill-of-materials.json
  vendor/go.etcd.io/etcd/v3/build
  vendor/go.etcd.io/etcd/v3/build.bat
  vendor/go.etcd.io/etcd/v3/build.ps1
  vendor/go.etcd.io/etcd/v3/build.sh
  vendor/go.etcd.io/etcd/v3/etcd.conf.yml.sample
  vendor/go.etcd.io/etcd/v3/test
  vendor/go.etcd.io/etcd/v3/test.sh
  vendor/modules.txt
Labels: lgtm, approved, dco-signoff: yes

#6078 Bump crun: 1.4.5 -> 1.5
  dependencies.yaml
  scripts/versions
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/dependency-change

#6079 changes the cri-o clone step to a copy
  contrib/test/ci/build/cri-o.yml
  contrib/test/ci/golang.yml
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#5914 [1.21] utils/RunUnderSystemdScope: fix wrt channel deadlock
  utils/utils.go
Labels: lifecycle/stale, lgtm, approved, release-note, dco-signoff: yes

#6089 version: bump to v1.24.2
  internal/version/version.go
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#5974 Enter mount namespace if set in $KUBENSMNT environment
  cmd/crio/main.go
  docs/crio.8.md
  go.mod
  go.sum
  internal/criocli/documentation.go
  test/helpers.bash
  test/namespaces.bats
  test/restore.bats
  vendor/github.com/containers/kubensmnt/LICENSE
  vendor/github.com/containers/kubensmnt/Makefile
  vendor/github.com/containers/kubensmnt/README.md
  vendor/github.com/containers/kubensmnt/kubensmnt.c
  vendor/github.com/containers/kubensmnt/kubensmnt.go
  vendor/github.com/containers/kubensmnt/kubensmnt.h
  vendor/github.com/containers/kubensmnt/kubensmnt_linux.go
  vendor/github.com/containers/kubensmnt/kubensmnt_nonlinux.go
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#6091 add vagrantfile to test CI and fixes
  Vagrantfile
  contrib/test/ci/build/cri-o.yml
  contrib/test/ci/build/parallel.yml
  contrib/test/ci/integration-main.yml
  contrib/test/ci/requirements.yml
  contrib/test/ci/setup.yml
  contrib/test/ci/system.yml
  contrib/test/ci/test.yml
  contrib/test/integration/build/cri-o.yml
  contrib/test/integration/build/parallel.yml
  contrib/test/integration/system.yml
  test/helpers.bash
Labels: approved, do-not-merge/release-note-label-needed, dco-signoff: yes

#6098 Fix nginx based integration tests
  test/image.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#6096 add GCP vagrant environment and mirror critest images
  Vagrantfile
  contrib/test/ci/critest.yml
  contrib/test/ci/critest_images.yml
  contrib/test/ci/sync_images.sh
  contrib/test/ci/vars.yml
  contrib/test/integration/critest.yml
  contrib/test/integration/vars.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/other

#6106 migrate image_list to quay.io
  contrib/test/ci/critest_images.yml
  contrib/test/ci/sync_images.sh
  test/image.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes
