Repository cri-o/cri-o, pull requests merged in 2022-12, with the labels that each got.

#6391 Update security process
  README.md
  SECURITY.md
Labels: approved, kind/documentation, release-note-none, dco-signoff: yes

#6389 [1.24] Bump c/storage to v1.37.3 (OCPBUGS-4470)
  go.mod
  go.sum
  vendor/github.com/containers/storage/drivers/quota/projectquota.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#6273 fix: give loopback a name
  contrib/cni/99-loopback.conf
Labels: kind/bug, lifecycle/stale, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#6390 [1.23] Bump c/storage to v1.37.3 (OCPBUGS-4471)
  go.mod
  go.sum
  vendor/github.com/containers/storage/drivers/quota/projectquota.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#6442 OWNERS: move vrothberg to emeritus approvers
  OWNERS
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/other

#6423 [1.22] Bump c/storage to v1.34.2 (OCPBUGS-4472)
  go.mod
  go.sum
  vendor/github.com/containers/storage/drivers/quota/projectquota.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#6445 ci: update system-packages.yml to install gpgme-devel on fedora
  contrib/test/ci/system-packages.yml
Labels: approved, release-note-none, dco-signoff: yes, kind/ci

#6398 contrib/test/ci: fix SELinux permission issue on RHEL9
  contrib/test/ci/system-packages.yml
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes

#6408 systemd: use on-failure as restart policy
  contrib/systemd/crio.service
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#6447 Merge log and metrics interceptor
  cmd/crio/main.go
  internal/criocli/criocli.go
  pkg/config/config.go
  server/container_attach.go
  server/container_exec.go
  server/container_portforward.go
  server/metrics/metrics.go
  server/otel-collector/collectors/collectors.go
  server/otel-collector/collectors/collectors_test.go
  server/otel-collector/interceptors.go
Labels: lgtm, approved, kind/cleanup, release-note-none, ok-to-test, dco-signoff: yes

#6296 docs: general updates
  tutorials/kubernetes.md
Labels: lifecycle/stale, lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#6379 Support checkpointing infra less containers
  internal/lib/restore.go
  internal/lib/restore_test.go
  internal/oci/oci.go
  internal/oci/oci_test.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_pod.go
  internal/oci/runtime_vm.go
  internal/oci/suite_test.go
  server/container_create.go
  server/container_restore.go
  server/container_restore_test.go
  test/checkpoint.bats
  test/mocks/oci/oci.go
Labels: kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#6403 ResourceStore: cleanup created entries
  internal/resourcestore/resourcestore.go
  server/container_create.go
  server/sandbox_run_linux.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#6450 server: fail if HOME variable has a newline
  server/container_create.go
  test/ctr.bats
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/deprecation

#6425 Remove `cri` wrapper package
  cmd/crio/main.go
  server/container_checkpoint.go
  server/container_checkpoint_test.go
  server/container_events.go
  server/container_remove.go
  server/container_remove_test.go
  server/container_reopen_log.go
  server/container_reopen_log_test.go
  server/container_start.go
  server/container_start_test.go
  server/container_stop.go
  server/container_stop_test.go
  server/container_update_resources.go
  server/container_update_resources_test.go
  server/cri/v1/api.go
  server/cri/v1/rpc_attach.go
  server/cri/v1/rpc_checkpoint_container.go
  server/cri/v1/rpc_container_events.go
  server/cri/v1/rpc_container_stats.go
  server/cri/v1/rpc_container_status.go
  server/cri/v1/rpc_create_container.go
  server/cri/v1/rpc_exec.go
  server/cri/v1/rpc_exec_sync.go
  server/cri/v1/rpc_image_fs_info.go
  server/cri/v1/rpc_image_status.go
  server/cri/v1/rpc_list_container_stats.go
  server/cri/v1/rpc_list_containers.go
  server/cri/v1/rpc_list_images.go
  server/cri/v1/rpc_list_pod_sandbox.go
  server/cri/v1/rpc_list_pod_sandbox_stats.go
  server/cri/v1/rpc_pod_sandbox_stats.go
  server/cri/v1/rpc_pod_sandbox_status.go
  server/cri/v1/rpc_port_forward.go
  server/cri/v1/rpc_pull_image.go
  server/cri/v1/rpc_remove_container.go
  server/cri/v1/rpc_remove_image.go
  server/cri/v1/rpc_remove_pod_sandbox.go
  server/cri/v1/rpc_reopen_container_log.go
  server/cri/v1/rpc_run_pod_sandbox.go
  server/cri/v1/rpc_start_container.go
  server/cri/v1/rpc_status.go
  server/cri/v1/rpc_stop_container.go
  server/cri/v1/rpc_stop_pod_sandbox.go
  server/cri/v1/rpc_update_container_resources.go
  server/cri/v1/rpc_update_runtime_config.go
  server/cri/v1/rpc_version.go
  server/image_fs_info.go
  server/image_fs_info_test.go
  server/image_remove.go
  server/image_remove_test.go
  server/sandbox_remove.go
  server/sandbox_remove_test.go
  server/sandbox_stop.go
  server/sandbox_stop_test.go
  server/update_runtime_config.go
  server/version.go
  server/version_test.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#6456 server/metrics: Update seccomp notifier metrics to reduce cardinality
  server/metrics/metrics.go
  server/server.go
  test/seccomp_notifier.bats
  tutorials/metrics.md
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#6416 Fix conmonrs cgroup when infra container is dropped
  internal/oci/oci_linux.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_pod.go
  test/cgroups.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#6289 Fix-6080: Update the CNI version to 1.0.0
  contrib/bundle/build
  contrib/bundle/install
  contrib/cni/10-crio-bridge.conf
  contrib/cni/10-crio-bridge.conflist
  contrib/cni/11-crio-ipv4-bridge.conf
  contrib/cni/11-crio-ipv4-bridge.conflist
  contrib/cni/99-loopback.conf
  contrib/cni/99-loopback.conflist
  contrib/cni/README.md
  contrib/test/ci/build/cri-o.yml
  contrib/test/ci/cri-o.spec
  contrib/test/integration/build/cri-o.yml
  scripts/get
  tutorials/kubeadm.md
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#6404 Support for Evented PLEG
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  go.mod
  go.sum
  internal/criocli/criocli.go
  pkg/config/config.go
  pkg/config/template.go
  server/container_create.go
  server/container_events.go
  server/container_remove.go
  server/container_start.go
  server/container_stop.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/sandbox_status.go
  server/sandbox_stop_linux.go
  server/server.go
  test/config.bats
  test/ctr.bats
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.pb.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#6468 get script: fix conflist path
  contrib/bundle/build
  contrib/bundle/install
  scripts/get
Labels: approved, release-note-none, dco-signoff: yes, kind/ci

#6470 bump to v1.26.0
  contrib/cni/11-crio-ipv4-bridge.conflist
  internal/version/version.go
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes
