Repository cri-o/cri-o, pull requests merged in 2022-01, with the labels that each got.

#5528 version: bump to 1.18.5
  internal/version/version.go
Labels: lgtm, approved, do-not-merge/release-note-label-needed, ok-to-test, dco-signoff: yes, kind/other

#5265 [release-1.20] BZ#2010831 Fix missing quantile in `latency_microseconds_total` metrics
  server/metrics/metrics.go
Labels: lgtm, approved, release-note, dco-signoff: yes

#5535 Use timeout for conmon cgroup move
  utils/utils.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#5533 [metrics] Fixed a problem where metricImagePullsBytesTotal was raising an error
  server/metrics/metrics.go
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#5537 Bump to v1.18.6
  internal/version/version.go
Labels: approved, release-note, kind/cleanup, dco-signoff: yes

#5514 prepend commands with taskset if InfraCtrCPUSet is configured
  Makefile
  internal/config/conmonmgr/conmonmgr.go
  internal/config/conmonmgr/conmonmgr_test.go
  internal/config/node/systemd.go
  internal/config/nsmgr/nsmgr.go
  internal/dbusmgr/user.go
  internal/oci/runtime_oci.go
  internal/runtimehandlerhooks/high_performance_hooks.go
  internal/runtimehandlerhooks/utils.go
  pkg/config/config.go
  test/mocks/cmdrunner/cmdrunner.go
  utils/cmdrunner/cmdrunner.go
  utils/cmdrunner/cmdrunner_test.go
  utils/cmdrunner/cmdrunner_test_inject.go
  utils/cmdrunner/suite_test.go
  utils/utils.go
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#5543 bump crio commit for upstream k8s CI
  scripts/node_e2e_installer
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#5007 Comments default values instead of omitting them
  .github/workflows/verify.yml
  Makefile
  hack/validate-config.sh
  pkg/config/config.go
  pkg/config/template.go
  test/config.bats
Labels: lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#5548 pkg/container: fix container device GID fallback.
  pkg/container/device.go
  pkg/container/device_test.go
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#5529 namespace: drop and replace stop method
  internal/config/nsmgr/types.go
  internal/lib/sandbox/namespaces.go
  internal/lib/sandbox/namespaces_test.go
  internal/oci/container.go
  pkg/container/namespaces_test.go
  server/sandbox_stop_linux.go
  server/server.go
  test/crio-wipe.bats
  test/restore.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5547 [1.22] prepend commands with taskset if InfraCtrCPUSet is configured
  Makefile
  internal/config/conmonmgr/conmonmgr.go
  internal/config/conmonmgr/conmonmgr_test.go
  internal/config/node/systemd.go
  internal/config/nsmgr/nsmgr.go
  internal/dbusmgr/user.go
  internal/oci/runtime_oci.go
  internal/runtimehandlerhooks/high_performance_hooks.go
  internal/runtimehandlerhooks/utils.go
  pkg/config/config.go
  test/mocks/cmdrunner/cmdrunner.go
  utils/cmdrunner/cmdrunner.go
  utils/cmdrunner/cmdrunner_test.go
  utils/cmdrunner/cmdrunner_test_inject.go
  utils/cmdrunner/suite_test.go
  utils/utils.go
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#5554 Add Nestybox to the CRI-O adopters list.
  ADOPTERS.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#5556 [1.21] Use timeout for conmon cgroup move
  utils/utils.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#5551 config: add allowed_devices field
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/config/device/device.go
  internal/config/device/device_test.go
  internal/criocli/criocli.go
  pkg/config/config.go
  pkg/config/sysctl.go
  pkg/config/template.go
  server/container_create_linux.go
  server/utils.go
  test/devices.bats
  test/workloads.bats
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#5561 [1.23] config: add allowed_devices field
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/config/device/device.go
  internal/config/device/device_test.go
  internal/criocli/criocli.go
  pkg/config/config.go
  pkg/config/sysctl.go
  pkg/config/template.go
  server/container_create_linux.go
  server/utils.go
  test/devices.bats
  test/workloads.bats
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#5568 Documentation: expand on CNI CIDRs in the kubeadm tutorial (RE: #5549)
  tutorials/kubeadm.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#5555 Bug 2043254: pass the main image mount point to fix crypto profiles binding
  server/container_create_linux.go
Labels: kind/bug, do-not-merge/hold, lgtm, approved, release-note, dco-signoff: yes

#5579 server: fix a potential NULL-pointer dereference.
  server/container_create.go
  server/container_create_test.go
Labels: kind/bug, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#5583 openshift e2e: bump ci image
  contrib/test/integration/build/runc.yml
  images/os/Dockerfile
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci
