Repository cri-o/cri-o, pull requests merged in 2022-06, with the labels that each got.

#5926 test: set cri stats more idiomatically
  contrib/test/integration/build/kubernetes.yml
  contrib/test/integration/main.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#5906 Bump cri-tools to v1.24.2
  contrib/test/integration/main.yml
  dependencies.yaml
  scripts/versions
  test/ctr.bats
  test/helpers.bash
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/dependency-change

#5935 [1.24] oci: add support for capping memory and disk usage from exec sync output
  internal/config/conmonmgr/conmonmgr.go
  internal/config/conmonmgr/conmonmgr_test.go
  internal/oci/oci.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  internal/oci/runtime_vm.go
  internal/version/version.go
  pkg/config/config.go
  test/ctr.bats
  vendor/k8s.io/kubernetes/pkg/kubelet/util/ioutils/ioutils.go
  vendor/modules.txt
Labels: kind/bug, approved, release-note, dco-signoff: yes

#5936 [1.22] oci: add support for capping memory and disk usage from exec sync output
  internal/config/conmonmgr/conmonmgr.go
  internal/config/conmonmgr/conmonmgr_test.go
  internal/oci/oci.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  internal/oci/runtime_vm.go
  internal/version/version.go
  pkg/config/config.go
  test/ctr.bats
  vendor/k8s.io/kubernetes/pkg/kubelet/util/ioutils/ioutils.go
  vendor/modules.txt
Labels: kind/bug, approved, release-note, dco-signoff: yes

#5937 [1.23] oci: add support for capping memory and disk usage from exec sync output
  internal/config/conmonmgr/conmonmgr.go
  internal/config/conmonmgr/conmonmgr_test.go
  internal/oci/oci.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  internal/oci/runtime_vm.go
  internal/version/version.go
  pkg/config/config.go
  test/ctr.bats
  vendor/k8s.io/kubernetes/pkg/kubelet/util/ioutils/ioutils.go
  vendor/modules.txt
Labels: kind/bug, approved, release-note, dco-signoff: yes

#5941 Fix unit tests
  internal/config/conmonmgr/conmonmgr_test.go
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes

#5939 drop use of deprecated package io/ioutil
  .golangci.yml
  contrib/metrics-exporter/main.go
  internal/client/client.go
  internal/config/blockio/blockio.go
  internal/config/blockio/blockio_test.go
  internal/config/cgmgr/cgmgr.go
  internal/config/cgmgr/stats_test.go
  internal/config/node/sysctl.go
  internal/config/rdt/rdt.go
  internal/config/rdt/rdt_test.go
  internal/config/seccomp/seccomp.go
  internal/config/seccomp/seccomp_test.go
  internal/factory/container/device_test.go
  internal/factory/sandbox/infra_test.go
  internal/lib/container_server_test.go
  internal/lib/suite_test.go
  internal/log/hook_filter.go
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_vm.go
  internal/process/defunct_processes.go
  internal/runtimehandlerhooks/high_performance_hooks.go
  internal/runtimehandlerhooks/high_performance_hooks_test.go
  internal/runtimehandlerhooks/utils.go
  internal/storage/image.go
  internal/version/version.go
  internal/version/version_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/reload_test.go
  scripts/dependencies/dependencies.go
  scripts/release-notes/release_notes.go
  server/container_portforward.go
  server/metrics/metrics.go
  server/rootless.go
  server/sandbox_run_linux.go
  server/server.go
  server/suite_test.go
  server/utils.go
  server/utils_test.go
  test/docs-validation/main.go
  test/framework/framework.go
  utils/utils.go
  utils/utils_test.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#5949 bump ocicni to v0.4.0
  go.mod
  go.sum
  vendor/github.com/containernetworking/cni/pkg/invoke/exec.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/util_linux.go
  vendor/modules.txt
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/dependency-change

#5922 utils/RunUnderSystemdScope: fix wrt channel deadlock
  utils/utils.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5962 [1.11] oci: add support for capping memory and disk usage from exec sync output
  conmon/conmon.c
  oci/oci.go
Labels: kind/bug, lgtm, release-note, dco-signoff: yes

#5943 [1.24] oci: kill children of container if it is in the host pid namespace
  internal/oci/container.go
  internal/oci/runtime_oci.go
  test/ctr.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5950 [1.21] oci: add support for capping memory and disk usage from exec sync output
  internal/config/conmonmgr/conmonmgr.go
  internal/config/conmonmgr/conmonmgr_test.go
  internal/oci/oci.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  internal/oci/runtime_vm.go
  internal/version/version.go
  pkg/config/config.go
  test/ctr.bats
  vendor/k8s.io/kubernetes/pkg/kubelet/util/ioutils/ioutils.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5951 [1.20] oci: add support for capping memory and disk usage from exec sync output
  internal/config/conmonmgr/conmonmgr.go
  internal/config/conmonmgr/conmonmgr_test.go
  internal/oci/oci.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  internal/oci/runtime_vm.go
  internal/version/version.go
  pkg/config/config.go
  test/ctr.bats
  vendor/k8s.io/kubernetes/pkg/kubelet/util/ioutils/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/util/ioutils/ioutils.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5960 [1.24] bump ocicni to 0.4.0
  go.mod
  go.sum
  vendor/github.com/containernetworking/cni/pkg/invoke/exec.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/util_linux.go
  vendor/modules.txt
Labels: lgtm, approved, release-note, dco-signoff: yes

#5952 [1.19] oci: add support for capping memory and disk usage from exec sync output
  internal/config/conmonmgr/conmonmgr.go
  internal/config/conmonmgr/conmonmgr_test.go
  internal/oci/oci.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  internal/oci/runtime_vm.go
  internal/version/version.go
  pkg/config/config.go
  test/ctr.bats
  vendor/k8s.io/kubernetes/pkg/kubelet/util/ioutils/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/util/ioutils/ioutils.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5977 [1.23] oci: kill children of container if it is in the host pid namespace
  internal/oci/container.go
  internal/oci/runtime_oci.go
  test/ctr.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5978 Update conmon
  contrib/test/integration/build/conmon.yml
  contrib/test/integration/main.yml
  dependencies.yaml
  scripts/versions
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#5981 Fix container status for HostToContainer propagation
  internal/oci/container.go
  server/container_create_linux.go
  server/container_status.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#5979 server: cleanup cleanup funcs
  internal/resourcestore/resourcecleaner.go
  server/container_create.go
  server/sandbox_run_linux.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#5972 Bump runc to v1.1.3
  contrib/test/integration/build/runc.yml
  dependencies.yaml
  internal/config/cgmgr/cgroupfs.go
  scripts/versions
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/manager/new.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/dependency-change

#5975 Sign static binary bundle via cosign
  .github/workflows/integration.yml
  .github/workflows/test.yml
  .github/workflows/verify.yml
  Makefile
  scripts/get
  scripts/github-actions-setup
  scripts/sign-artifacts
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#5986 [1.22] oci: kill children of container if it is in the host pid namespace
  internal/oci/container.go
  internal/oci/runtime_oci.go
  test/ctr.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5770 [1.23] capabilities: drop inheritable
  server/container_create.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5997 Add stale bot workflow
  .github/workflows/stale.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#6002 Run more stale operations
  .github/workflows/stale.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#6007 Pin upstream node e2e test to latest `main`
  scripts/node_e2e_installer
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#6001 chore: Set permissions for GitHub actions
  .github/workflows/integration.yml
  .github/workflows/test.yml
  .github/workflows/verify.yml
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#6006 Use default token for stale bot
  .github/workflows/stale.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#5566 [1.23] config: uncomment cni_default_network
  pkg/config/template.go
Labels: kind/bug, lifecycle/stale, lgtm, approved, release-note, dco-signoff: yes

#5992 Verify SBOM for static binary bundle
  .github/workflows/verify.yml
  Makefile
  README.md
  contrib/bundle/build
  go.mod
  go.sum
  scripts/get
  scripts/release-notes/release_notes.go
  vendor/github.com/google/go-containerregistry/pkg/crane/options.go
  vendor/github.com/google/go-containerregistry/pkg/v1/google/keychain.go
  vendor/github.com/google/go-containerregistry/pkg/v1/partial/with.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/check.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/mount.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/write.go
  vendor/golang.org/x/term/term.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
  vendor/sigs.k8s.io/bom/cmd/bom/cmd/document.go
  vendor/sigs.k8s.io/bom/cmd/bom/cmd/generate.go
  vendor/sigs.k8s.io/bom/cmd/bom/cmd/query.go
  vendor/sigs.k8s.io/bom/cmd/bom/cmd/validate.go
  vendor/sigs.k8s.io/bom/pkg/license/catalog.go
  vendor/sigs.k8s.io/bom/pkg/license/download.go
  vendor/sigs.k8s.io/bom/pkg/license/implementation.go
  vendor/sigs.k8s.io/bom/pkg/license/license.go
  vendor/sigs.k8s.io/bom/pkg/osinfo/container_scanner.go
  vendor/sigs.k8s.io/bom/pkg/osinfo/layer_scanner.go
  vendor/sigs.k8s.io/bom/pkg/provenance/predicate.go
  vendor/sigs.k8s.io/bom/pkg/provenance/provenance.go
  vendor/sigs.k8s.io/bom/pkg/provenance/statement.go
  vendor/sigs.k8s.io/bom/pkg/query/engine.go
  vendor/sigs.k8s.io/bom/pkg/query/expression.go
  vendor/sigs.k8s.io/bom/pkg/query/filter.go
  vendor/sigs.k8s.io/bom/pkg/serialize/serialize.go
  vendor/sigs.k8s.io/bom/pkg/spdx/builder.go
  vendor/sigs.k8s.io/bom/pkg/spdx/document.go
  vendor/sigs.k8s.io/bom/pkg/spdx/file.go
  vendor/sigs.k8s.io/bom/pkg/spdx/format.go
  vendor/sigs.k8s.io/bom/pkg/spdx/gomod.go
  vendor/sigs.k8s.io/bom/pkg/spdx/imageanalyzer.go
  vendor/sigs.k8s.io/bom/pkg/spdx/imageanalyzer_distroless.go
  vendor/sigs.k8s.io/bom/pkg/spdx/imageanalyzer_gorunner.go
  vendor/sigs.k8s.io/bom/pkg/spdx/implementation.go
  vendor/sigs.k8s.io/bom/pkg/spdx/json/v2.2.2/types.go
  vendor/sigs.k8s.io/bom/pkg/spdx/object.go
  vendor/sigs.k8s.io/bom/pkg/spdx/package.go
  vendor/sigs.k8s.io/bom/pkg/spdx/parser.go
  vendor/sigs.k8s.io/bom/pkg/spdx/relationship.go
  vendor/sigs.k8s.io/bom/pkg/spdx/spdx.go
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#6008 update ubuntu releases
  install.md
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#6012 Fix unit test coverage
  .github/workflows/test.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#6013 Upload release notes for each tag
  .github/workflows/test.yml
  scripts/upload-artifacts
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#6011 Fix release-notes tag determination
  scripts/release-notes/release_notes.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#6020 Fix a link in install.md building section about dependencies
  install.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#6018 [release-1.24] Fix unit test coverage
  .github/workflows/test.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci
