Repository cri-o/cri-o, pull requests merged in 2022-05, with the labels that each got.

#5783 server: no longer use hardcoded timeouts
  server/sandbox_network.go
  server/utils.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5788 seccomp: drop unshare syscall from default profile
  internal/config/seccomp/seccomp.go
  internal/config/seccomp/seccomp_test.go
  test/ctr_seccomp.bats
Labels: lgtm, approved, release-note, kind/api-change, dco-signoff: yes

#5823 config: move conmon specific fields in to runtime handler
  completions/fish/crio.fish
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  internal/oci/oci_linux.go
  internal/oci/runtime_oci.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/template.go
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/deprecation

#5844 Add sha256sum bundle files to uploaded artifacts
  .github/workflows/test.yml
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#5840 Move WillRunSystemd call after iterating the mounts
  server/container_create_linux.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#5836 main(): do not treat reexec.Init() == true as an error
  cmd/crio/main.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#5843 crio:fix a bug about log container
  server/container_status.go
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#5852 Reenable pod runtime in package spec
  contrib/test/ci/cri-o.spec
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#5837 Exec cgroup
  dependencies.yaml
  internal/config/cgmgr/cgmgr.go
  internal/oci/runtime_oci.go
  pkg/config/config.go
  pkg/config/template.go
  scripts/versions
Labels: kind/bug, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#5855 Run critest with conmonrs
  .github/workflows/integration.yml
  scripts/github-actions-setup
  test/critest.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#5856 Bump third party dependencies
  contrib/test/integration/build/bats.yml
  dependencies.yaml
  scripts/versions
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/dependency-change

#5847 [release-1.22] Move WillRunSystemd call after iterating the mounts
  server/container_create_linux.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#5750 Use go 1.18 buildinfo for version output
  Makefile
  cmd/crio-status/main.go
  cmd/crio/main.go
  cmd/crio/version.go
  completions/fish/crio.fish
  docs/crio.8.md
  internal/version/buildtag_apparmor.go
  internal/version/buildtag_devicemapper.go
  internal/version/buildtag_openpgp.go
  internal/version/buildtag_ostree.go
  internal/version/buildtag_seccomp.go
  internal/version/buildtag_selinux.go
  internal/version/version.go
  pkg/config/config.go
  server/useragent/useragent.go
  server/useragent/useragent_test.go
  server/version.go
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#5859 [1.21] vendor: bump json-iterator to prevent segfault
  go.mod
  go.sum
  vendor/github.com/json-iterator/go/README.md
  vendor/github.com/json-iterator/go/go.mod
  vendor/github.com/json-iterator/go/go.sum
  vendor/github.com/modern-go/reflect2/.travis.yml
  vendor/github.com/modern-go/reflect2/Gopkg.lock
  vendor/github.com/modern-go/reflect2/Gopkg.toml
  vendor/github.com/modern-go/reflect2/go.mod
  vendor/github.com/modern-go/reflect2/go_above_118.go
  vendor/github.com/modern-go/reflect2/go_above_17.go
  vendor/github.com/modern-go/reflect2/go_above_19.go
  vendor/github.com/modern-go/reflect2/go_below_118.go
  vendor/github.com/modern-go/reflect2/go_below_17.go
  vendor/github.com/modern-go/reflect2/go_below_19.go
  vendor/github.com/modern-go/reflect2/reflect2.go
  vendor/github.com/modern-go/reflect2/test.sh
  vendor/github.com/modern-go/reflect2/type_map.go
  vendor/github.com/modern-go/reflect2/unsafe_link.go
  vendor/github.com/modern-go/reflect2/unsafe_map.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/dependency-change

#5865 Typo fix
  internal/hostport/README.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#5864 Add CodeQL Github actions
  .github/workflows/test.yml
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes, kind/ci

#5869 typo fix
  cmd/crio/main.go
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#5870 [1.20] vendor: bump json-iterator to prevent segfault
  go.mod
  go.sum
  vendor/github.com/json-iterator/go/README.md
  vendor/github.com/json-iterator/go/go.mod
  vendor/github.com/json-iterator/go/go.sum
  vendor/github.com/json-iterator/go/iter_float.go
  vendor/github.com/json-iterator/go/iter_int.go
  vendor/github.com/json-iterator/go/reflect.go
  vendor/github.com/json-iterator/go/reflect_json_raw_message.go
  vendor/github.com/json-iterator/go/reflect_struct_decoder.go
  vendor/github.com/modern-go/reflect2/.travis.yml
  vendor/github.com/modern-go/reflect2/Gopkg.lock
  vendor/github.com/modern-go/reflect2/Gopkg.toml
  vendor/github.com/modern-go/reflect2/go.mod
  vendor/github.com/modern-go/reflect2/go_above_118.go
  vendor/github.com/modern-go/reflect2/go_above_17.go
  vendor/github.com/modern-go/reflect2/go_above_19.go
  vendor/github.com/modern-go/reflect2/go_below_118.go
  vendor/github.com/modern-go/reflect2/go_below_17.go
  vendor/github.com/modern-go/reflect2/go_below_19.go
  vendor/github.com/modern-go/reflect2/reflect2.go
  vendor/github.com/modern-go/reflect2/test.sh
  vendor/github.com/modern-go/reflect2/type_map.go
  vendor/github.com/modern-go/reflect2/unsafe_link.go
  vendor/github.com/modern-go/reflect2/unsafe_map.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/dependency-change

#5875 chore: Included githubactions in the dependabot config
  .github/dependabot.yml
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#5871 Fix some uses of Atoi
  internal/oci/runtime_oci.go
  server/sandbox_run_linux.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#5887 version: bump to 1.22.4
  internal/version/version.go
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#5888 version: bump to 1.21.7
  internal/version/version.go
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#5886 vendor: bump crypto package
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ed25519/ed25519.go
  vendor/golang.org/x/crypto/ed25519/ed25519_go113.go
  vendor/golang.org/x/crypto/ed25519/internal/edwards25519/const.go
  vendor/golang.org/x/crypto/ed25519/internal/edwards25519/edwards25519.go
  vendor/golang.org/x/crypto/ssh/agent/client.go
  vendor/golang.org/x/crypto/ssh/agent/keyring.go
  vendor/golang.org/x/crypto/ssh/certs.go
  vendor/golang.org/x/crypto/ssh/cipher.go
  vendor/golang.org/x/crypto/ssh/client.go
  vendor/golang.org/x/crypto/ssh/client_auth.go
  vendor/golang.org/x/crypto/ssh/common.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/kex.go
  vendor/golang.org/x/crypto/ssh/keys.go
  vendor/golang.org/x/crypto/ssh/messages.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/session.go
  vendor/golang.org/x/crypto/ssh/transport.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/dependency-change

#5893 OWNERS: remove fgiudici
  OWNERS
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#5901 docs: move 1.23 to 1.24 in README
  README.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#5902 changes in README
  README.md
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#5904 Use a default umask of `0o022`
  server/server.go
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#5895 oci: kill children of container if it is in the host pid namespace
  internal/oci/container.go
  internal/oci/runtime_oci.go
  test/ctr.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#5894 docs: update for CNI package change
  install.md
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#5876 feature:Try to force delete ctr when in paused state
  internal/lib/container_server.go
  internal/lib/remove.go
  internal/lib/stop.go
  server/container_list.go
  server/container_status.go
  test/ctr_pause_unpause.bats
Labels: kind/feature, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#5907 docs: Add pause/unpause description to readme
  README.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#5918 [1.21] ci/gha: fixup golangci-lint job
  .github/workflows/verify.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci
