Repository cri-o/cri-o, pull requests merged in 2022-09, with the labels that each got.

#6196 cgmgr: use NewSystemd from createSandboxCgroup
  internal/config/cgmgr/cgmgr.go
Labels: kind/bug, lgtm, approved, kind/flake, release-note-none, dco-signoff: yes

#6200 metrics: close listener on shutdown
  server/metrics/metrics.go
Labels: kind/bug, approved, release-note-none, dco-signoff: yes

#6193 Adds rhel9 variant-specific changes to CI
  contrib/test/ci/build/crun.yml
  contrib/test/ci/system-packages.yml
Labels: approved, release-note-none, dco-signoff: yes, kind/ci

#6206 Fix integration CI runs
  .github/workflows/integration.yml
  scripts/github-actions-setup
Labels: approved, release-note-none, kind/failing-test, dco-signoff: yes

#6179 [OCPNODE-1208] Add scripts to run node e2e tests using custom cri-o builds
  contrib/custom-node-e2e/README.md
  contrib/custom-node-e2e/create-ignition-config.sh
  contrib/custom-node-e2e/upload-artifacts.sh
  scripts/get
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes, kind/other

#6174 Update build instructions for RHEL 8 distribution
  install.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#6123 server: return already created ID for duplicated requests
  server/container_create.go
  server/sandbox_run_linux.go
  test/timeout.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#6225 Add conmon-rs e2e to ansible playbook
  contrib/test/ci/build/conmon-rs.yml
  contrib/test/ci/build/cri-o.yml
  contrib/test/ci/setup.yml
  contrib/test/ci/vars.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#5683 resource store: save stage of resource creation and report to callers
  internal/resourcestore/resourcestore.go
  internal/resourcestore/resourcestore_test.go
  server/container_create.go
  server/container_create_linux.go
  server/sandbox_run_linux.go
  server/utils.go
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#6240 [1.24] Revert "capabilities: drop inheritable"
  internal/factory/container/container.go
  internal/factory/container/container_test.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#6237 use cri-tools version from dependencies.yaml
  contrib/test/ci/critest-main.yml
  contrib/test/ci/golang.yml
  contrib/test/ci/integration-main.yml
  contrib/test/ci/main.yml
  contrib/test/ci/setup.yml
  contrib/test/ci/vars.yml
  contrib/test/integration/golang.yml
  contrib/test/integration/main.yml
  contrib/test/integration/vars.yml
  dependencies.yaml
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#6056 Allow runtimes to be added and default runtime to be modified on config reload
  docs/crio.conf.5.md
  pkg/config/config.go
  pkg/config/reload.go
  pkg/config/reload_test.go
  test/reload_config.bats
Labels: kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#6245 contrib/test: drop userns integration tests
  contrib/test/ci/test.yml
  contrib/test/integration/test.yml
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes, kind/ci

#6236 add "add_inheritable_capabilities" option
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  internal/factory/container/container.go
  internal/factory/container/container_test.go
  internal/factory/sandbox/infra.go
  pkg/config/config.go
  pkg/config/template.go
  server/container_create_linux.go
  test/ctr.bats
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#6251 Update conmon-rs
  go.mod
  go.sum
  internal/oci/runtime_pod.go
  vendor/github.com/containers/conmon-rs/internal/proto/conmon.capnp.go
  vendor/github.com/containers/conmon-rs/pkg/client/attach.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#6154 [1.24] migrate image_list to quay.io
  test/image.bats
Labels: lifecycle/stale, lgtm, approved, release-note-none, dco-signoff: yes

#6257 config: do not remove runc if different default runtime
  pkg/config/config.go
  pkg/config/template.go
  test/config.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes
