Repository cri-o/cri-o, pull requests merged in 2023-11, with the labels that each got.

#7457 [release-1.27] NO-ISSUE: server: allow Bidirectional mounts that contain storage root
  server/container_create_linux.go
  server/container_create_linux_test.go
  test/ctr.bats
Labels: lgtm, approved, release-note, dco-signoff: yes, jira/valid-reference

#7428 [release-1.28] Bump to v1.28.2
  internal/version/version.go
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#7430 version: bump to 1.27.2
  internal/version/version.go
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#7484 contrib/test: update RHEL 9.2 dependencies
  contrib/test/ci/build/crun.yml
  contrib/test/ci/system-packages.yml
  contrib/test/integration/build/crun.yml
Labels: lgtm, kind/cleanup, release-note-none, dco-signoff: yes, kind/ci

#7507 contrib/test/ci: update ansible syntax to include_tasks
  contrib/test/ci/critest-main.yml
  contrib/test/ci/critest.yml
  contrib/test/ci/e2e-base.yml
  contrib/test/ci/e2e-features.yml
  contrib/test/ci/e2e-main.yml
  contrib/test/ci/e2e.yml
  contrib/test/ci/integration-main.yml
  contrib/test/ci/setup-main.yml
  contrib/test/ci/setup.yml
Labels: kind/cleanup, release-note-none, dco-signoff: yes, kind/ci

#7508 contrib/test/ci: use embedded yajl for crun installation
  contrib/test/ci/build/crun.yml
Labels: kind/cleanup, release-note-none, dco-signoff: yes, kind/ci

#7506 [1.25] version: bump to 1.25.2
  internal/version/version.go
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#7515 tests(ansible): fix tasks environment
  contrib/test/ci/e2e-main.yml
Labels: lgtm, do-not-merge/release-note-label-needed, dco-signoff: yes

#7463 contrib/ci: remove duplicate directory
  contrib/test/integration/README.md
  contrib/test/integration/ansible.cfg
  contrib/test/integration/build/bats.yml
  contrib/test/integration/build/cri-o.yml
  contrib/test/integration/build/cri-tools.yml
  contrib/test/integration/build/crun.yml
  contrib/test/integration/build/jq.yml
  contrib/test/integration/build/kata.yml
  contrib/test/integration/build/kubernetes.yml
  contrib/test/integration/build/kubetest.yml
  contrib/test/integration/build/parallel.yml
  contrib/test/integration/build/plugins.yml
  contrib/test/integration/build/runc.yml
  contrib/test/integration/critest.yml
  contrib/test/integration/e2e-base.yml
  contrib/test/integration/e2e-features.yml
  contrib/test/integration/e2e.yml
  contrib/test/integration/golang.yml
  contrib/test/integration/main.yml
  contrib/test/integration/python3.yml
  contrib/test/integration/results.yml
  contrib/test/integration/system-packages.yml
  contrib/test/integration/system.yml
  contrib/test/integration/test.yml
  contrib/test/integration/vars.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#7517 dependencies: fix the CI test path
  dependencies.yaml
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#7460 Fix inconsistency in restore image name resolution
  internal/lib/restore.go
  internal/lib/restore_test.go
  internal/oci/container.go
  internal/oci/container_test.go
  server/container_create.go
  server/container_restore.go
  server/container_restore_test.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#7461 Prepare image pulling for per-namespace signature enforcement
  internal/storage/image.go
  internal/storage/image_test.go
  internal/storage/runtime.go
  internal/storage/runtime_test.go
  server/image_pull.go
  server/image_pull_test.go
  test/mocks/criostorage/criostorage.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#7467 contrib/test: Use the main branch of runc
  contrib/test/ci/vars.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#7353 Validate pod uid
  internal/factory/container/container.go
  internal/factory/sandbox/sandbox.go
  internal/factory/sandbox/sandbox_setnameandid_test.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#7525 Add kwilczynski to CRI-O reviewers
  OWNERS_ALIASES
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#7522 config: allow the devices annotation in the default runtime class
  pkg/config/config.go
Labels: lgtm, approved, release-note, dco-signoff: yes
