Repository cri-o/cri-o, pull requests merged in 2023-09, with the labels that each got.

#6668 Configure systemd install path based on OS
  contrib/bundle/install-paths
  scripts/get
Labels: kind/bug, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#7281 Mention Roadmap GitHub Project in README.md
  README.md
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#4868 move shm setup for sandbox to internal/factory/sandbox
  internal/factory/sandbox/infra.go
  internal/factory/sandbox/infra_test.go
  server/sandbox_run_linux.go
Labels: lifecycle/stale, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#7228 Policy: Allow backport of independent features
  README.md
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#7283 Add new adopter
  ADOPTERS.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#7232 Add Kubernetes package test for static binary bundle
  .github/workflows/test.yml
  Makefile
  contrib/bundle/Vagrantfile
  contrib/bundle/build
  contrib/bundle/install
  contrib/bundle/registries.conf
  dependencies.yaml
  scripts/get
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/ci

#7208 cgmgr: reorder setting of sched_load_balance for pod cgroup
  internal/config/cgmgr/cgmgr_linux.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#6977 Pause container during checkpointing
  internal/lib/checkpoint.go
  internal/lib/checkpoint_test.go
  server/container_checkpoint_test.go
Labels: kind/bug, lifecycle/stale, lgtm, approved, release-note-none, dco-signoff: yes

#7295 Remove golang-go from debian installation
  install.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#7292 contrib/test: fix golang version extraction for CI
  contrib/test/ci/golang.yml
  contrib/test/integration/golang.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#7289 config/server: add functions to check IDMap support in runtime
  go.mod
  go.sum
  internal/oci/oci.go
  pkg/config/config.go
  server/container_create_linux.go
  server/container_create_linux_test.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/features/features.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#7297 [1.28] config/server: add functions to check IDMap support in runtime
  go.mod
  go.sum
  internal/oci/oci.go
  pkg/config/config.go
  server/container_create_linux.go
  server/container_create_linux_test.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/features/features.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#7298 version: bump to v1.28.1
  internal/version/version.go
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#7299 internal/storage: address unpredictable behavior of image names
  internal/storage/image.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#7303 contrib/test/ci: remove the redundant golang setup file
  contrib/test/ci/build/golang.yml
  contrib/test/ci/golang.yml
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#7284 Add conmon-rs binary to bundle
  .github/workflows/test.yml
  contrib/bundle/build
  contrib/bundle/install
  contrib/bundle/test-e2e
  dependencies.yaml
  scripts/get
  scripts/versions
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#7305 docs: Update the containers/image branch name
  install.md
  tutorials/kubeadm.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#6254 blockio: add blockio_reload option
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/config/blockio/blockio.go
  internal/criocli/criocli.go
  pkg/config/config.go
  pkg/config/reload.go
  pkg/config/template.go
  server/container_create_linux.go
Labels: kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#7309 Simplify, and optimize, ImageServer.ResolveNames
  internal/storage/image.go
  internal/storage/image_test.go
  server/container_create_linux.go
  server/image_remove.go
  server/image_remove_test.go
  server/image_status.go
  server/image_status_test.go
Labels: lgtm, approved, kind/cleanup, release-note-none, ok-to-test, dco-signoff: yes

#7311 docs: fix CI failure
  docs/crio.8.md
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#7306 Bump version to 1.29.0
  internal/version/version.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#7312 [1.28] Add registries.conf to CRI-O bundle
  contrib/bundle/build
  contrib/bundle/install
  contrib/bundle/registries.conf
  contrib/bundle/test
  contrib/bundle/test-e2e
  scripts/get
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#7314 Fix release notes job
  scripts/release-notes/release_notes.go
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes

#7318 Fix nix `dirty` build
  nix/derivation.nix
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#7323 Disambiguate image identification in container creation
  internal/storage/runtime.go
  internal/storage/runtime_test.go
  server/sandbox_run_linux.go
  server/sandbox_run_test.go
  test/mocks/criostorage/criostorage.go
Labels: lgtm, approved, kind/cleanup, release-note-none, ok-to-test, dco-signoff: yes

#7325 RFC: Use RuntimeContainerMetadata for passing container data
  internal/storage/runtime.go
Labels: lgtm, approved, kind/cleanup, release-note-none, ok-to-test, dco-signoff: yes

#7322 update containers storage to 1.50.2
  go.mod
  go.sum
  vendor/github.com/Microsoft/go-winio/tools/mkwinsyscall/doc.go
  vendor/github.com/Microsoft/go-winio/tools/mkwinsyscall/mkwinsyscall.go
  vendor/github.com/Microsoft/hcsshim/.gitignore
  vendor/github.com/Microsoft/hcsshim/.golangci.yml
  vendor/github.com/Microsoft/hcsshim/Protobuild.toml
  vendor/github.com/Microsoft/hcsshim/computestorage/helpers.go
  vendor/github.com/Microsoft/hcsshim/computestorage/storage.go
  vendor/github.com/Microsoft/hcsshim/computestorage/zsyscall_windows.go
  vendor/github.com/Microsoft/hcsshim/internal/hcs/schema2/cim_mount.go
  vendor/github.com/Microsoft/hcsshim/internal/hcs/schema2/isolation_settings.go
  vendor/github.com/Microsoft/hcsshim/internal/hcs/schema2/properties.go
  vendor/github.com/Microsoft/hcsshim/internal/jobobject/jobobject.go
  vendor/github.com/Microsoft/hcsshim/internal/log/format.go
  vendor/github.com/Microsoft/hcsshim/internal/log/scrub.go
  vendor/github.com/Microsoft/hcsshim/internal/safefile/safeopen.go
  vendor/github.com/Microsoft/hcsshim/internal/wclayer/baselayerreader.go
  vendor/github.com/Microsoft/hcsshim/internal/wclayer/converttobaselayer.go
  vendor/github.com/Microsoft/hcsshim/internal/wclayer/legacy.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/cimfs.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/offlinereg.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/ofreg.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/utils.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/zsyscall_windows.go
  vendor/github.com/Microsoft/hcsshim/osversion/osversion_windows.go
  vendor/github.com/Microsoft/hcsshim/tools.go
  vendor/github.com/containerd/cgroups/v3/LICENSE
  vendor/github.com/containerd/cgroups/v3/cgroup1/stats/doc.go
  vendor/github.com/containerd/cgroups/v3/cgroup1/stats/metrics.pb.go
  vendor/github.com/containerd/cgroups/v3/cgroup1/stats/metrics.pb.txt
  vendor/github.com/containerd/cgroups/v3/cgroup1/stats/metrics.proto
  vendor/github.com/containers/storage/OWNERS
  vendor/github.com/containers/storage/VERSION
  vendor/modules.txt
Labels: lgtm, approved, release-note, ok-to-test, dco-signoff: yes, kind/dependency-change

#7317 Make the release branch fast forward a cronjob
  .github/workflows/cron.yml
  .github/workflows/test.yml
  dependencies.yaml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#7343 contrib/test: pin the latest release of runc
  contrib/test/ci/build/runc.yml
  contrib/test/ci/vars.yml
  contrib/test/integration/build/runc.yml
  contrib/test/integration/vars.yml
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes, kind/ci
