Repository cri-o/cri-o, pull requests merged in 2023-03, with the labels that each got.

#6681 [CI] Fix validate-completion
  completions/fish/crio.fish
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#6684 Pin nix version to fix static builds
  .github/workflows/test.yml
  dependencies.yaml
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes

#6697 Bump crun to v1.8.1
  dependencies.yaml
  scripts/versions
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#6682 go.mod: update github.com/containerd/nri to 0.3.0.
  go.mod
  go.sum
  vendor/github.com/containerd/nri/pkg/api/mount.go
  vendor/github.com/containerd/nri/pkg/runtime-tools/generate/generate.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes, kind/dependency-change

#6702 [release-1.26] cherry-pick related fixes, update NRI deps to 0.3.0.
  .github/workflows/test.yml
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  dependencies.yaml
  docs/crio.8.md
  docs/crio.conf.5.md
  go.mod
  go.sum
  internal/config/nri/nri.go
  internal/config/nri/nri_test.go
  internal/config/nri/suite_test.go
  internal/criocli/criocli.go
  internal/nri/nri.go
  internal/oci/container.go
  pkg/config/template.go
  server/container_update_resources.go
  server/container_update_resources_test.go
  test/docs-validation/main.go
  test/nri.bats
  vendor/github.com/containerd/nri/pkg/adaptation/adaptation.go
  vendor/github.com/containerd/nri/pkg/adaptation/config.go
  vendor/github.com/containerd/nri/pkg/adaptation/plugin.go
  vendor/github.com/containerd/nri/pkg/adaptation/plugin_linux.go
  vendor/github.com/containerd/nri/pkg/adaptation/plugin_other.go
  vendor/github.com/containerd/nri/pkg/adaptation/result.go
  vendor/github.com/containerd/nri/pkg/api/mount.go
  vendor/github.com/containerd/nri/pkg/api/plugin.go
  vendor/github.com/containerd/nri/pkg/net/socketpair_unix.go
  vendor/github.com/containerd/nri/pkg/net/socketpair_windows.go
  vendor/github.com/containerd/nri/pkg/runtime-tools/generate/generate.go
  vendor/github.com/containerd/nri/pkg/runtime-tools/generate/helpers_linux.go
  vendor/github.com/containerd/nri/pkg/runtime-tools/generate/helpers_other.go
  vendor/github.com/containerd/nri/pkg/stub/stub.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-action-required, dco-signoff: yes, kind/other

#6705 test: add irqbalance dependency
  contrib/test/integration/system-packages.yml
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes

#6638 [1.25] Fix cgroup leak for systemd cgroup driver
  internal/config/cgmgr/cgmgr.go
  internal/config/cgmgr/cgroupfs.go
  internal/config/cgmgr/systemd.go
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#6711 go.mod: update CDI dependency to 0.5.4.
  go.mod
  go.sum
  internal/factory/container/device_test.go
  test/cdi.bats
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/annotations.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/cache.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/container-edits.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/container-edits_unix.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/device.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/doc.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/qualified-device.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/spec.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/spec_linux.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/version.go
  vendor/modules.txt
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/dependency-change

#6444 Take MaskedPaths and ReadonlyPaths from checkpointed container
  server/container_restore.go
  server/container_restore_test.go
Labels: kind/bug, lifecycle/stale, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#6717 Add spdx signature and cert to release notes
  scripts/release-notes/release_notes.go
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#6754 test: add irqbalance dependency to CI
  contrib/test/ci/system-packages.yml
  contrib/test/integration/system-packages.yml
Labels: release-note-none, kind/failing-test, dco-signoff: yes

#6750 server: wire support for userns volumes
  go.mod
  go.sum
  server/container_create_linux.go
  vendor/github.com/golang/protobuf/jsonpb/decode.go
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/escape.go
  vendor/golang.org/x/net/html/render.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/text/encoding/internal/internal.go
  vendor/golang.org/x/text/unicode/norm/forminfo.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.pb.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#6764 Update zeitgeist to v0.4.1
  Makefile
  dependencies.yaml
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#6748 log errors on metric server and gracefully terminate metrics endpoint
  server/metrics/metrics.go
Labels: lgtm, approved, release-note, dco-signoff: yes

#6636 [1.24] Fix cgroup leak for systemd cgroup driver
  internal/config/cgmgr/cgmgr.go
  internal/config/cgmgr/cgroupfs.go
  internal/config/cgmgr/systemd.go
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#6736 Remove `scripts/node_e2e_installer`
  scripts/node_e2e_installer
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#6765 OCPBUGS-10970: Fix the interrupt mask width when encoding
  internal/runtimehandlerhooks/utils.go
  internal/runtimehandlerhooks/utils_test.go
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference
