Repository cri-o/cri-o, pull requests merged in 2023-05, with the labels that each got.

#6858 contrib/test/ci: fix the bin folder location for cri-tools
  contrib/test/ci/build/cri-tools.yml
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes, kind/ci

#6718 Extend cpu-c-states.crio.io annotation to add max latency
  internal/runtimehandlerhooks/high_performance_hooks.go
  internal/runtimehandlerhooks/high_performance_hooks_test.go
Labels: kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#6844 #6833 user ns: Fix segfault while constructing id mappings
  server/container_create_linux.go
Labels: lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#6863 .github/workflows: remove auto-approve workflow
  .github/workflows/test.yml
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#6864 OWNERS: allow cri-o reviewers to approve dependabot PRs
  GOVERNANCE.md
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/other

#6856 cgmgr: create cgroups for systemd cgroup driver for dropped infra pods
  internal/config/cgmgr/cgmgr.go
  internal/config/cgmgr/cgroupfs.go
  internal/config/cgmgr/systemd.go
  server/sandbox_remove.go
  test/cgroups.bats
  test/pod.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#6633 Fix events generated by Evented PLEG
  server/container_stop.go
  server/sandbox_stop_linux.go
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#6726 Use ImageRef instead of ImageName for restore
  internal/lib/checkpoint.go
  server/container_restore.go
  server/container_restore_test.go
Labels: kind/bug, kind/feature, lgtm, approved, release-note-none, dco-signoff: yes

#6455 Added documentation to force the Go garbage collector for CRI-O
  tutorials/debugging.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#6742 Migrate image registry to `registry.k8s.io`
  cri.md
  internal/config/migrate/from_1_17.go
  test/testdata/config/config-v1.17.0.toml
Labels: lgtm, approved, release-note, ok-to-test, dco-signoff: yes, kind/deprecation

#6889 OWNERS: add sohankunkerkar to cri-o-reviewers
  OWNERS_ALIASES
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/other

#6891 configurable namespace for crio metrics exporter
  contrib/metrics-exporter/.gitignore
  contrib/metrics-exporter/README.md
  contrib/metrics-exporter/cluster.yaml
  contrib/metrics-exporter/go.mod
  contrib/metrics-exporter/go.sum
  contrib/metrics-exporter/main.go
Labels: kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#6737 tests: use crictl binary directly when checking its capabilities
  test/timeout.bats
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes

#6823 Support to build binaries for `ppc64le` architecture.
  .github/workflows/test.yml
  Makefile
  README.md
  contrib/bundle/build
  install.md
  nix/default-ppc64le.nix
  scripts/get
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes, kind/ci

#6907 fix kubectl version in bug report template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: needs-ok-to-test, lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#6895 [1.26] Update c/common to fix umask bug
  go.mod
  go.sum
  vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go
  vendor/github.com/containers/common/pkg/umask/umask.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#6893 .github/worflows: add go vulnerability management check for cri-o
  .github/workflows/test.yml
  Makefile
  dependencies.yaml
  hack/govulncheck.sh
  server/server.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#6903 internal/storage: add sandbox/pause image to the list of pinned_images
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/storage/image.go
  internal/storage/image_test.go
  pkg/config/config.go
  test/helpers.bash
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#6557 FEAT: Convert status cli as a subcommand of crio
  cmd/crio-status/main.go
  cmd/crio/main.go
  completions/bash/crio
  completions/fish/crio-status.fish
  completions/fish/crio.fish
  completions/zsh/_crio
  completions/zsh/_crio-status
  docs/crio-status.8.md
  docs/crio.8.md
  internal/criocli/config.go
  internal/criocli/publish.go
  internal/criocli/status.go
  internal/criocli/version.go
  internal/criocli/wipe.go
  test/config.bats
  test/helpers.bash
  test/status.bats
Labels: kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#6912 Update CNI plugins to v1.3.0
  contrib/test/ci/build/plugins.yml
  contrib/test/integration/build/plugins.yml
  dependencies.yaml
  scripts/versions
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/dependency-change

#6919 Fix GitHub action `bundles` test
  contrib/bundle/build
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes

#6900 [1.25] Update c/common to fix umask bug
  go.mod
  go.sum
  vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go
  vendor/github.com/containers/common/pkg/umask/umask.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#6927 *: switch to go-chi/chi mux for inspect
  go.mod
  go.sum
  server/inspect.go
  server/inspect_ginkgo_test.go
  vendor/github.com/go-chi/chi/v5/.gitignore
  vendor/github.com/go-chi/chi/v5/CHANGELOG.md
  vendor/github.com/go-chi/chi/v5/CONTRIBUTING.md
  vendor/github.com/go-chi/chi/v5/LICENSE
  vendor/github.com/go-chi/chi/v5/Makefile
  vendor/github.com/go-chi/chi/v5/README.md
  vendor/github.com/go-chi/chi/v5/chain.go
  vendor/github.com/go-chi/chi/v5/chi.go
  vendor/github.com/go-chi/chi/v5/context.go
  vendor/github.com/go-chi/chi/v5/mux.go
  vendor/github.com/go-chi/chi/v5/tree.go
  vendor/github.com/go-zoo/bone/.gitignore
  vendor/github.com/go-zoo/bone/.travis.yml
  vendor/github.com/go-zoo/bone/CHANGELOG.md
  vendor/github.com/go-zoo/bone/CODE_OF_CONDUCT.md
  vendor/github.com/go-zoo/bone/CONTRIBUTING.md
  vendor/github.com/go-zoo/bone/LICENSE
  vendor/github.com/go-zoo/bone/README.md
  vendor/github.com/go-zoo/bone/bone.go
  vendor/github.com/go-zoo/bone/helper.go
  vendor/github.com/go-zoo/bone/helper_15.go
  vendor/github.com/go-zoo/bone/helper_17.go
  vendor/github.com/go-zoo/bone/mux.go
  vendor/github.com/go-zoo/bone/route.go
  vendor/github.com/go-zoo/bone/validator.go
  vendor/modules.txt
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#6918 Support image policy verification error
  server/image_pull.go
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#6931 contrib/test: re-enable block volmod tests
  contrib/test/ci/e2e.yml
  contrib/test/integration/e2e.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#6934 contrib/test: reenable Statefulset Basic tests
  contrib/test/ci/e2e.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#6917 OCPBUGS-13542: high perf hooks: disable CPU quota with libcontainer as a pre start hook
  internal/runtimehandlerhooks/high_performance_hooks.go
  server/container_create_linux.go
  test/cgroups.bats
  test/helpers.bash
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#6928 Check and fix typos in CI
  .github/workflows/verify.yml
  .typos.toml
  GOVERNANCE.md
  cmd/crio/daemon_unsupported.go
  contrib/bundle/build
  contrib/cni/README.md
  contrib/kube-local/README.md
  contrib/kube-local/kube-local
  contrib/test/ci/e2e-features.yml
  contrib/test/integration/e2e-features.yml
  docs/crio.conf.5.md
  hack/lib/build/rpm.sh
  hack/lib/log/system.sh
  internal/criocli/criocli.go
  internal/criocli/criocli_test.go
  internal/factory/container/container.go
  internal/factory/container/container_setnameandid_test.go
  internal/lib/container_server_unsupported.go
  internal/lib/sandbox/sandbox_test.go
  internal/oci/container_test.go
  internal/oci/oci.go
  internal/oci/runtime_vm.go
  pinns/src/pinns.c
  pkg/config/template.go
  server/container_attach_test.go
  server/container_exec_test.go
  server/container_portforward_test.go
  server/container_restore.go
  server/image_list_test.go
  server/sandbox_run_linux.go
  server/server.go
  test/ctr.bats
  test/docs-validation/main.go
  test/inspecti.bats
  test/irqbalance.bats
  test/selinux.bats
  test/testdata/config/config-v1.17.0.toml
  tutorials/install-distro.md
  tutorials/kubernetes.md
  tutorials/metrics.md
  utils/utils.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#6838 Clients connected to container event stream now receive the same data
  Makefile
  server/container_events.go
  server/container_events_test.go
  server/server.go
  server/suite_test.go
  test/mocks/containereventserver/containereventserver.go
Labels: kind/feature, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#6938 [1.26] OCPBUGS-13853: high perf hooks: disable CPU quota with libcontainer as a pre start hook
  internal/runtimehandlerhooks/high_performance_hooks.go
  server/container_create_linux.go
  test/cgroups.bats
  test/helpers.bash
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes, jira/invalid-bug, jira/valid-reference

#6930 [1.25] cgmgr: create cgroups for systemd cgroup driver for dropped infra pods
  internal/config/cgmgr/cgmgr.go
  internal/config/cgmgr/cgroupfs.go
  internal/config/cgmgr/systemd.go
  server/sandbox_remove.go
  test/cgroups.bats
  test/pod.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#6948 deps: bump runc to 1.1.7
  dependencies.yaml
  go.mod
  scripts/versions
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/dependency-change

#6901 [1.24] Update c/common to fix umask bug
  go.mod
  go.sum
  vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go
  vendor/github.com/containers/common/pkg/umask/umask.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#6955 OCPNODE-1286: Add a CI job to run cri-o e2e tests by enabling the evented pleg feature
  contrib/test/ci/build/cri-o.yml
  contrib/test/ci/e2e-base.yml
  contrib/test/ci/vars.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci, jira/valid-reference

#6902 OCPBUGS-13283: [1.23] Update c/common to fix umask bug
  go.mod
  go.sum
  vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go
  vendor/github.com/containers/common/pkg/umask/umask.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes, jira/severity-moderate, jira/invalid-bug, jira/valid-reference

#6913 sandbox: Handle PodLinuxOverhead and PodLinuxResources CRI fields
  internal/factory/container/container_test.go
  internal/lib/container_server.go
  internal/lib/container_server_test.go
  internal/lib/sandbox/history_test.go
  internal/lib/sandbox/sandbox.go
  internal/lib/sandbox/sandbox_test.go
  internal/lib/sandbox/suite_test.go
  internal/lib/suite_test.go
  pkg/annotations/annotations.go
  server/nri-api.go
  server/sandbox_run_linux.go
  server/suite_test.go
Labels: kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#6946 Wrap CRI errors on image pull
  go.mod
  go.sum
  internal/runtimehandlerhooks/high_performance_hooks.go
  internal/runtimehandlerhooks/utils.go
  pkg/config/config.go
  pkg/config/workloads.go
  server/image_pull.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/registry/api/v2/descriptors.go
  vendor/github.com/docker/distribution/registry/api/v2/errors.go
  vendor/k8s.io/apimachinery/pkg/api/errors/OWNERS
  vendor/k8s.io/apimachinery/pkg/api/resource/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go
  vendor/k8s.io/apimachinery/pkg/util/managedfields/internal/fieldmanager.go
  vendor/k8s.io/apimachinery/pkg/util/managedfields/internal/skipnonapplied.go
  vendor/k8s.io/apimachinery/pkg/util/managedfields/internal/versioncheck.go
  vendor/k8s.io/apimachinery/pkg/util/net/util.go
  vendor/k8s.io/apimachinery/pkg/util/version/version.go
  vendor/k8s.io/apimachinery/pkg/util/wait/poll.go
  vendor/k8s.io/client-go/openapi/typeconverter.go
  vendor/k8s.io/client-go/tools/metrics/metrics.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/k8s.io/client-go/util/cert/cert.go
  vendor/k8s.io/component-base/version/dynamic.go
  vendor/k8s.io/component-base/version/version.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.pb.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto
  vendor/k8s.io/kube-openapi/pkg/cached/cache.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/utils/cpuset/OWNERS
  vendor/k8s.io/utils/cpuset/cpuset.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#5660 [1.22] ci: use kubernetes 1.22 and cri-tools 1.22
  contrib/test/integration/main.yml
  dependencies.yaml
  scripts/versions
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#6421 Remove remnants of CONTAINER_MANAGE_NS_LIFECYCLE
  test/cgroups.bats
  test/drop_infra.bats
  test/network.bats
  test/restore.bats
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#6952 [1.23] Vendor c/storage PR #1612
  go.mod
  go.sum
  vendor/github.com/containers/storage/layers.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#6942 docs: update cri-o podman doc and remove stale information
  transfer.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#6971 ci/gha: fix double caching
  .github/workflows/integration.yml
  .github/workflows/test.yml
  .github/workflows/verify.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#6949 [1.24] cgmgr: create cgroups for systemd cgroup driver for dropped infra pods
  internal/config/cgmgr/cgmgr.go
  internal/config/cgmgr/cgroupfs.go
  internal/config/cgmgr/systemd.go
  server/sandbox_remove.go
  test/cgroups.bats
  test/pod.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#6974 test/cgroup: fix for cgroupfs
  test/helpers.bash
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#6975 test: limit number of parallel jobs
  test/test_runner.sh
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/other

#6987 [1.27] *: update sandbox/pause image to 3.9
  docs/crio.8.md
  docs/crio.conf.5.md
  pkg/config/config.go
  test/helpers.bash
Labels: lgtm, approved, release-note, dco-signoff: yes

#6880 go.{mod,sum}, vendor: update NRI.
  go.mod
  go.sum
  vendor/github.com/containerd/nri/pkg/api/resources.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes
