Repository cri-o/cri-o, pull requests merged in 2023-04, with the labels that each got.

#6777 test: run irqbalance tests serially to avoid race condition
  test/irqbalance.bats
  test/test_runner.sh
Labels: lgtm, approved, kind/flake, release-note-none, dco-signoff: yes, kind/ci

#6790 [1.24] version: bump to 1.24.5
  internal/version/version.go
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#6579 [FEAT]Add new parameter hostnetwork-disable-selinux
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  internal/criocli/criocli_test.go
  pkg/config/config.go
  pkg/config/template.go
  server/container_create_linux.go
Labels: lgtm, approved, release-note, ok-to-test, dco-signoff: yes, kind/other

#6791 Update bom and use binary directly
  Makefile
  dependencies.yaml
  go.mod
  internal/tools/tools.go
  vendor/modules.txt
  vendor/sigs.k8s.io/bom/cmd/bom/cmd/document.go
  vendor/sigs.k8s.io/bom/cmd/bom/cmd/generate.go
  vendor/sigs.k8s.io/bom/cmd/bom/cmd/query.go
  vendor/sigs.k8s.io/bom/cmd/bom/cmd/root.go
  vendor/sigs.k8s.io/bom/cmd/bom/cmd/validate.go
  vendor/sigs.k8s.io/bom/cmd/bom/main.go
  vendor/sigs.k8s.io/bom/pkg/query/engine.go
  vendor/sigs.k8s.io/bom/pkg/query/expression.go
  vendor/sigs.k8s.io/bom/pkg/query/filter.go
  vendor/sigs.k8s.io/bom/pkg/serialize/serialize.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#6782 Generate proper signature check
  scripts/get
  scripts/release-notes/release_notes.go
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes, kind/ci

#6797 Update nixpkgs
  nix/derivation.nix
  nix/nixpkgs.json
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/dependency-change

#6799 contrib/test: don't cache the cri-o content
  contrib/test/ci/critest.yml
  contrib/test/ci/e2e-base.yml
  contrib/test/ci/integration-main.yml
  contrib/test/ci/setup.yml
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#6399 Set umask for crio container
  docs/crio.conf.5.md
  pkg/annotations/annotations.go
  server/container_create_linux.go
  test/umask_annotation.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#6730 runtimeVM: fix Exec(sync) overwriting the initial spec args
  internal/oci/runtime_vm.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#6463 oci: Enable checkpointing of file locks
  internal/oci/runtime_oci.go
Labels: kind/bug, lifecycle/stale, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#6803 [1.26] version: bump to 1.26.3
  internal/version/version.go
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#6798 Don't print `Dependencies` if `crio version` it not verbose
  internal/version/version.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#6796 Update golangci-lint and config
  .github/workflows/verify.yml
  .golangci.yml
  Makefile
  dependencies.yaml
  internal/hostport/fake_iptables.go
  internal/log/klog.go
  internal/oci/runtime_vm.go
  scripts/release-notes/release_notes.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#6744 OCPBUGS-11396,OCPNODE-1536: high performance hooks: update to a cgroup approach for load balance disabling
  internal/runtimehandlerhooks/high_performance_hooks.go
  internal/runtimehandlerhooks/high_performance_hooks_test.go
  server/container_create_linux.go
  test/cpu_load_balancing.bats
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes, jira/severity-critical, jira/invalid-bug, jira/valid-reference

#6812 OCPBUGS-11777,OCPNODE-1536: [1.26] high performance hooks: update to a cgroup approach for load balance disabling
  internal/runtimehandlerhooks/high_performance_hooks.go
  internal/runtimehandlerhooks/high_performance_hooks_test.go
  server/container_create_linux.go
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes, jira/severity-critical, jira/invalid-bug, jira/valid-reference

#6570 Update container resources in ContainerStatusResponse
  internal/oci/container.go
  internal/oci/container_test.go
  server/container_status.go
Labels: lifecycle/stale, lgtm, approved, release-note, ok-to-test, dco-signoff: yes, kind/other

#6813 contrib/test/ci: cache runc and crun setup unconditionally
  contrib/test/ci/setup.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#6809 Bump runc to v1.1.6
  dependencies.yaml
  scripts/versions
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/dependency-change

#6807 config: mark seccomp-use-default-when-empty as deprecated
  completions/fish/crio.fish
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  pkg/config/config.go
  pkg/config/template.go
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/deprecation

#6815 Bump crun to v1.8.4
  dependencies.yaml
  scripts/versions
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/dependency-change

#6817 Add basic crictl info config with sandboxImage
  server/runtime_status.go
  server/runtime_status_test.go
Labels: kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#6772 stop using KUBE-MARK-MASQ for hostport chains
  internal/hostport/hostport.go
  internal/hostport/hostport_manager.go
  internal/hostport/hostport_manager_test.go
  internal/hostport/hostport_test.go
  internal/hostport/meta_hostport_manager.go
  internal/hostport/meta_hostport_manager_test.go
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#6822 version: bump version (and cri-tools) to 1.27.0
  contrib/test/ci/vars.yml
  contrib/test/integration/vars.yml
  dependencies.yaml
  internal/version/version.go
  scripts/versions
  server/container_restore_test.go
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes, kind/dependency-change

#6828 contrib/test/ci: fix failing tests
  server/container_restore_test.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#6768 consolidate images used for integration tests
  contrib/test/ci/system-packages.yml
  test/crio-wipe.bats
  test/ctr.bats
  test/helpers.bash
  test/image.bats
  test/image_remove.bats
  test/image_volume.bats
  test/inspect.bats
  test/inspecti.bats
  test/metrics.bats
  test/network.bats
  test/nri/runtime.go
  test/pod.bats
  test/seccomp_notifier.bats
  test/testdata/Dockerfile
  test/testdata/container_config.json
  test/testdata/container_config_ping.json
  test/testdata/container_redis.json
  test/testdata/container_sleep.json
  test/testdata/docker-entrypoint.sh
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes, kind/ci

#6837 .github/workflows: auto approve dependabot PRs
  .github/workflows/test.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/other

#6793 Allow restoring of containers with different names
  server/container_restore.go
  server/container_restore_test.go
  test/checkpoint.bats
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#6834 user ns: fix segfault when host id mapping is empty
  server/container_create_linux.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#6494 Add debug to identify when a relabel was not requested
  server/container_create_linux.go
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#6849 contrib/test/ci/build: use `force:yes` while linking crictl/critest
  contrib/test/ci/build/cri-tools.yml
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#6843 Update c/common to v0.53.0
  go.mod
  go.sum
  vendor/github.com/containers/common/pkg/config/containers.conf
  vendor/github.com/containers/common/pkg/config/containers.conf-freebsd
  vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go
  vendor/github.com/containers/common/pkg/sysinfo/numcpu.go
  vendor/github.com/containers/common/pkg/sysinfo/numcpu_linux.go
  vendor/github.com/containers/common/pkg/sysinfo/numcpu_other.go
  vendor/github.com/containers/common/pkg/sysinfo/numcpu_windows.go
  vendor/github.com/containers/common/pkg/umask/umask.go
  vendor/github.com/containers/common/version/version.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes
