Repository cri-o/cri-o, pull requests merged in 2023-08, with the labels that each got.

#7076 Set mount type HostToContainer for mounts that include container storage root
  server/container_create_linux.go
  server/container_create_linux_test.go
Labels: kind/bug, lifecycle/stale, lgtm, approved, release-note, dco-signoff: yes

#7191 [1.27] Revert "Fix filemode for device"
  internal/factory/container/device.go
Labels: lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#7192 Revert "devices: fill the FileMode field in spec"
  internal/factory/container/device.go
Labels: lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#7180 *: add platform_runtime_paths to RuntimeHandler
  docs/crio.conf.5.md
  internal/factory/container/container.go
  internal/factory/container/container_test.go
  internal/lib/container_server.go
  internal/oci/container.go
  internal/oci/oci.go
  internal/oci/runtime_oci.go
  pkg/annotations/annotations.go
  pkg/config/config.go
  pkg/config/template.go
  server/container_create_linux.go
  test/common.sh
  test/image.bats
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#7189 build-static: misc fixes needed for 1.25.4 generation
  Makefile
  nix/nixpkgs.nix
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#7197 [1.27] add platform_runtime_paths to RuntimeHandler
  docs/crio.conf.5.md
  internal/factory/container/container.go
  internal/factory/container/container_test.go
  internal/lib/container_server.go
  internal/oci/container.go
  internal/oci/oci.go
  internal/oci/runtime_oci.go
  pkg/annotations/annotations.go
  pkg/config/config.go
  pkg/config/template.go
  server/container_create_linux.go
  test/helpers.bash
  test/image.bats
Labels: lgtm, approved, release-note, dco-signoff: yes

#7201 Update runc to v1.1.9
  dependencies.yaml
  scripts/versions
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/dependency-change

#7207 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#7212 Fix indentation in installation instructions
  install.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#7202 Vendor Kubernetes v1.28.0-rc.1
  go.mod
  go.sum
  vendor/golang.org/x/net/html/render.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/k8s.io/api/admissionregistration/v1beta1/generated.pb.go
  vendor/k8s.io/api/admissionregistration/v1beta1/generated.proto
  vendor/k8s.io/api/admissionregistration/v1beta1/register.go
  vendor/k8s.io/api/admissionregistration/v1beta1/types.go
  vendor/k8s.io/api/admissionregistration/v1beta1/types_swagger_doc_generated.go
  vendor/k8s.io/api/admissionregistration/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/api/admissionregistration/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/apidiscovery/v2beta1/generated.proto
  vendor/k8s.io/api/apidiscovery/v2beta1/types.go
  vendor/k8s.io/api/core/v1/generated.pb.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/client-go/applyconfigurations/admissionregistration/v1beta1/auditannotation.go
  vendor/k8s.io/client-go/applyconfigurations/admissionregistration/v1beta1/expressionwarning.go
  vendor/k8s.io/client-go/applyconfigurations/admissionregistration/v1beta1/matchresources.go
  vendor/k8s.io/client-go/applyconfigurations/admissionregistration/v1beta1/namedrulewithoperations.go
  vendor/k8s.io/client-go/applyconfigurations/admissionregistration/v1beta1/paramkind.go
  vendor/k8s.io/client-go/applyconfigurations/admissionregistration/v1beta1/paramref.go
  vendor/k8s.io/client-go/applyconfigurations/admissionregistration/v1beta1/typechecking.go
  vendor/k8s.io/client-go/applyconfigurations/admissionregistration/v1beta1/validatingadmissionpolicy.go
  vendor/k8s.io/client-go/applyconfigurations/admissionregistration/v1beta1/validatingadmissionpolicybinding.go
  vendor/k8s.io/client-go/applyconfigurations/admissionregistration/v1beta1/validatingadmissionpolicybindingspec.go
  vendor/k8s.io/client-go/applyconfigurations/admissionregistration/v1beta1/validatingadmissionpolicyspec.go
  vendor/k8s.io/client-go/applyconfigurations/admissionregistration/v1beta1/validatingadmissionpolicystatus.go
  vendor/k8s.io/client-go/applyconfigurations/admissionregistration/v1beta1/validation.go
  vendor/k8s.io/client-go/applyconfigurations/admissionregistration/v1beta1/variable.go
  vendor/k8s.io/client-go/applyconfigurations/core/v1/loadbalanceringress.go
  vendor/k8s.io/client-go/applyconfigurations/core/v1/persistentvolumestatus.go
  vendor/k8s.io/client-go/applyconfigurations/internal/internal.go
  vendor/k8s.io/client-go/discovery/aggregated_discovery.go
  vendor/k8s.io/client-go/kubernetes/typed/admissionregistration/v1beta1/admissionregistration_client.go
  vendor/k8s.io/client-go/kubernetes/typed/admissionregistration/v1beta1/generated_expansion.go
  vendor/k8s.io/client-go/kubernetes/typed/admissionregistration/v1beta1/validatingadmissionpolicy.go
  vendor/k8s.io/client-go/kubernetes/typed/admissionregistration/v1beta1/validatingadmissionpolicybinding.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/zz_generated.deepcopy.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/dependency-change

#7211 Update cri-tools to v1.28.0
  contrib/test/ci/vars.yml
  contrib/test/integration/vars.yml
  dependencies.yaml
  scripts/github-actions-setup
  scripts/versions
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#7209 OCPBUGS-17429: [1.25] oci: simplify stopping code
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/container_test_inject.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  internal/oci/runtime_vm.go
  server/container_execsync.go
  server/container_remove.go
  server/container_remove_test.go
  server/container_stop.go
  server/container_stop_test.go
  server/sandbox_stop_linux.go
Labels: lgtm, approved, release-note, dco-signoff: yes, jira/severity-critical, jira/invalid-bug, jira/valid-reference

#7223 Vendor Kubernetes v1.28.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#7226 doc(installation): Update install.md
  install.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#7220 [1.25] factory: use non deprecated LastCap
  internal/factory/container/container.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#7215 Update nixpkgs and use overlay
  nix/default-amd64.nix
  nix/default-arm64.nix
  nix/default-ppc64le.nix
  nix/default.nix
  nix/nixpkgs.json
  nix/overlay.nix
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#7210 Add containers_events_dropped_total metric
  docs/crio.8.md
  docs/crio.conf.5.md
  server/metrics/metrics.go
  server/otel-collector/collectors/collectors.go
  server/otel-collector/collectors/collectors_test.go
  server/server.go
  tutorials/metrics.md
Labels: kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#6944 internal/factory/container: take dedicated CRI ContainerConfig.CDIDevices field into use.
  internal/factory/container/device.go
  internal/factory/container/device_test.go
  test/cdi.bats
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/other

#7229 Add `conmon` to `ppc64le` static bundle
  contrib/bundle/build
  dependencies.yaml
  scripts/versions
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/dependency-change

#7190 feat: check for clean shutdown on reboot
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  internal/criocli/wipe.go
  internal/lib/container_server.go
  pkg/config/config.go
  pkg/config/template.go
  test/crio-wipe.bats
Labels: kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#7236 add info about pulling image before doing the tutorial
  tutorials/crictl.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#7242 Add `ppc64le` binaries to release notes
  scripts/release-notes/release_notes.go
Labels: lgtm, approved, release-note, kind/documentation, dco-signoff: yes

#7252 server: remove deprecated functionality
  go.mod
  server/container_create_linux.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#7255 Bump conmon and crun dependencies
  dependencies.yaml
  scripts/versions
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/dependency-change

#7264 Add dependabot group for OTEL deps
  .github/dependabot.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#7265 Switch to go 1.21
  .github/workflows/integration.yml
  .github/workflows/test.yml
  .github/workflows/verify.yml
  contrib/test/ci/vars.yml
  contrib/test/integration/vars.yml
  dependencies.yaml
  go.mod
  go.sum
  nix/derivation.nix
  nix/nixpkgs.json
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/dependency-change

#5466 [1.20] Add support to drop ALL and add back few capabilities
  server/container_create.go
  server/container_create_linux.go
  server/sandbox_run_linux.go
Labels: lgtm, approved, dco-signoff: yes
