Repository cri-o/cri-o, pull requests merged in 2023-02, with the labels that each got.

#6596 contrib/test/ci: adds time information to tasks
  contrib/test/ci/ansible.cfg
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#6591 go.mod: update github.com/containerd/nri.
  go.mod
  go.sum
  vendor/github.com/containerd/nri/pkg/adaptation/adaptation.go
  vendor/github.com/containerd/nri/pkg/adaptation/plugin.go
  vendor/github.com/containerd/nri/pkg/adaptation/plugin_linux.go
  vendor/github.com/containerd/nri/pkg/adaptation/plugin_other.go
  vendor/github.com/containerd/nri/pkg/net/socketpair_unix.go
  vendor/github.com/containerd/nri/pkg/net/socketpair_windows.go
  vendor/github.com/containerd/nri/pkg/runtime-tools/generate/helpers_linux.go
  vendor/github.com/containerd/nri/pkg/runtime-tools/generate/helpers_other.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#6600 contrib/test/ci/*: refactor CI to build a cache image
  contrib/test/ci/README.md
  contrib/test/ci/build/conmon-rs.yml
  contrib/test/ci/build/cri-o.yml
  contrib/test/ci/build/crun.yml
  contrib/test/ci/build/golang.yml
  contrib/test/ci/build/kubernetes.yml
  contrib/test/ci/build/parallel.yml
  contrib/test/ci/critest-main.yml
  contrib/test/ci/critest.yml
  contrib/test/ci/critest_images.yml
  contrib/test/ci/e2e-base.yml
  contrib/test/ci/e2e-main.yml
  contrib/test/ci/integration-main.yml
  contrib/test/ci/integration.yml
  contrib/test/ci/python3.yml
  contrib/test/ci/requirements.yml
  contrib/test/ci/results.yml
  contrib/test/ci/setup-main.yml
  contrib/test/ci/setup.yml
  contrib/test/ci/sync_images.sh
  contrib/test/ci/system-packages.yml
  contrib/test/ci/system.yml
  contrib/test/ci/vars.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#6509 [release-1.24] do not wipe images by default
  internal/version/version.go
  internal/version/version_test.go
Labels: lgtm, approved, release-note, dco-signoff: yes

#6565 [1.24] Make storage unmount less strict
  internal/storage/runtime.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#6150 [1.24] server: allow for kubelet to specify -1 for swap
  server/container_create_linux.go
  test/cgroups.bats
Labels: kind/bug, lifecycle/stale, lgtm, approved, release-note, dco-signoff: yes

#6606 bundle: bump to conmon 2.1.6
  dependencies.yaml
  scripts/versions
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#6582 Update runtime-tools to mount '/dev' without the 'noexec' flag.
  go.mod
  go.sum
  vendor/github.com/opencontainers/runtime-tools/generate/generate.go
  vendor/modules.txt
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/dependency-change

#6304 [1.24] server: move StartContainer calls to clarify stage
  server/container_create_linux.go
  server/sandbox_run_linux.go
Labels: kind/bug, lifecycle/stale, lgtm, approved, release-note-none, dco-signoff: yes

#6618 [1.26] Update opencontainers/runtime-tools to a6a073817ab0
  go.mod
  go.sum
  vendor/github.com/opencontainers/runtime-tools/generate/generate.go
  vendor/github.com/opencontainers/runtime-tools/validate/capabilities/validate_unsupported.go
  vendor/modules.txt
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/dependency-change

#6603 Fix issues with PLEG events for kata
  internal/oci/oci.go
  internal/oci/runtime_vm.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#6576 Add documentation about how to use tracing
  README.md
  tutorials/tracing.md
  tutorials/tracing.png
Labels: lgtm, approved, release-note, kind/documentation, dco-signoff: yes

#6629 Bump the CRI-O commit used for node testing to the tip of main
  scripts/node_e2e_installer
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes, kind/ci

#6630 main: shutdown server only once
  cmd/crio/main.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#6518 [1.23] Make storage unmount less strict
  internal/storage/runtime.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#6644 Fix roadmap links
  roadmap.md
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#6646 [1.25] Bump runtime-tools to v0.9.1-0.20230110161035-a6a073817ab0
  go.mod
  go.sum
  vendor/github.com/opencontainers/runtime-tools/generate/generate.go
  vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default.go
  vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default_linux.go
  vendor/github.com/opencontainers/runtime-tools/validate/capabilities/validate.go
  vendor/github.com/opencontainers/runtime-tools/validate/capabilities/validate_linux.go
  vendor/github.com/opencontainers/runtime-tools/validate/capabilities/validate_unsupported.go
  vendor/github.com/opencontainers/runtime-tools/validate/validate.go
  vendor/github.com/opencontainers/runtime-tools/validate/validate_linux.go
  vendor/modules.txt
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/dependency-change

#6643 test: use container_sleep for idempotent test
  test/pod.bats
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes

#6650 Drop `ENABLE_POD_EVENTS` var from e2e installer script
  scripts/node_e2e_installer
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#6651 Revert "main: shutdown server only once"
  cmd/crio/main.go
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes

#6652 server: fix the permission issue for `/etc`
  server/container_create_linux.go
  test/helpers.bash
  test/pod.bats
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#6648 Update NRI dependencies, NRI-related configuration options.
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  go.mod
  go.sum
  internal/config/nri/nri.go
  internal/config/nri/nri_test.go
  internal/config/nri/suite_test.go
  internal/criocli/criocli.go
  internal/nri/nri.go
  internal/oci/container.go
  pkg/config/template.go
  test/docs-validation/main.go
  test/nri.bats
  vendor/github.com/containerd/nri/pkg/adaptation/adaptation.go
  vendor/github.com/containerd/nri/pkg/adaptation/config.go
  vendor/github.com/containerd/nri/pkg/adaptation/plugin.go
  vendor/github.com/containerd/nri/pkg/adaptation/result.go
  vendor/github.com/containerd/nri/pkg/api/plugin.go
  vendor/github.com/containerd/nri/pkg/stub/stub.go
  vendor/modules.txt
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/dependency-change

#6664 Update to c/image 5.24.2
  go.mod
  go.sum
  vendor/github.com/containers/image/v5/docker/body_reader.go
  vendor/github.com/containers/image/v5/version/version.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes, kind/dependency-change

#6641 Fix cgroup leak for systemd cgroup driver
  internal/config/cgmgr/cgmgr.go
  internal/config/cgmgr/cgroupfs.go
  internal/config/cgmgr/systemd.go
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#6388 improve the irqbalance restore flow
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  internal/runtimehandlerhooks/high_performance_hooks.go
  internal/runtimehandlerhooks/high_performance_hooks_test.go
  pkg/config/config.go
  pkg/config/template.go
  server/server.go
  test/irqbalance.bats
Labels: kind/feature, lgtm, approved, release-note, kind/cleanup, ok-to-test, dco-signoff: yes

#6645 nri: add protection against nil dereference
  server/container_update_resources.go
  server/container_update_resources_test.go
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes
