Repository cri-o/cri-o, pull requests merged in 2023-06, with the labels that each got.

#6994 tests/timeout: skip for conmon-rs
  test/timeout.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#7005 Update `README.md` version table
  README.md
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#6950 Fix/improve bats tests for modern bats
  Makefile
  contrib/kube-local/kube-local
  contrib/test/integration/build/bats.yml
  dependencies.yaml
  scripts/versions
  test/README.md
  test/apparmor.bats
  test/cdi.bats
  test/cgroups.bats
  test/command.bats
  test/common.sh
  test/config.bats
  test/config_migrate.bats
  test/copyimg/copyimg.go
  test/crio-wipe.bats
  test/ctr.bats
  test/ctr_pause_unpause.bats
  test/ctr_seccomp.bats
  test/devices.bats
  test/helpers.bash
  test/image_volume.bats
  test/inspect.bats
  test/network.bats
  test/nri.bats
  test/pod.bats
  test/reload_system.bats
  test/restore.bats
  test/seccomp_notifier.bats
  test/shm_size.bats
  test/status.bats
  test/test_runner.sh
  test/timeout.bats
  test/userns_annotation.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#7000 OCPBUGS-13980,OCPBUGS-14018: Fix bugs with high performance hooks
  internal/config/cgmgr/cgmgr.go
  internal/config/cgmgr/cgroupfs.go
  internal/config/cgmgr/systemd.go
  internal/runtimehandlerhooks/default_cpu_load_balance_hooks.go
  internal/runtimehandlerhooks/high_performance_hooks.go
  internal/runtimehandlerhooks/runtime_handler_hooks.go
  server/container_remove.go
  server/container_stop.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
  test/cpu_load_balancing.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes, jira/severity-critical, jira/invalid-bug, jira/valid-reference

#6996 test/helpers: simplify setup_crio()
  test/helpers.bash
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/ci

#6923 metrics: add metric for resource stalled at stage
  docs/crio.8.md
  server/metrics/metrics.go
  server/otel-collector/collectors/collectors.go
  server/otel-collector/collectors/collectors_test.go
  server/utils.go
  test/timeout.bats
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#7001 crio: remove DefaultsPath
  Makefile
  internal/criocli/criocli.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#7022 [release-1.26] update NRI.
  go.mod
  go.sum
  vendor/github.com/containerd/nri/pkg/api/resources.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#6886 crio: deprecate config migrate support
  completions/fish/crio.fish
  docs/crio.8.md
  internal/criocli/config.go
Labels: lgtm, approved, release-note, kind/cleanup, ok-to-test, dco-signoff: yes

#6890 Cleanup some documentation, markdown formatting and broken links
  .github/workflows/verify.yml
  ADOPTERS.md
  CONTRIBUTING.md
  GOVERNANCE.md
  MAINTAINERS.md
  README.md
  awesome.md
  code-of-conduct.md
  contrib/bundle/README.md
  contrib/cni/README.md
  contrib/custom-node-e2e/README.md
  contrib/kube-local/README.md
  contrib/metrics-exporter/README.md
  contrib/test/ci/README.md
  contrib/test/integration/README.md
  cri.md
  install.md
  internal/hostport/README.md
  releases/README.md
  roadmap.md
  test/README.md
  test/testdata/README.md
  transfer.md
  tutorial.md
  tutorials/crictl.md
  tutorials/debugging.md
  tutorials/decryption.md
  tutorials/install-distro.md
  tutorials/kubeadm.md
  tutorials/kubernetes.md
  tutorials/metrics.md
  tutorials/tracing.md
  tutorials/userns.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#7028 docs: fix eol test
  tutorials/kubernetes.md
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#7030 Add OSFF scorecard action
  .github/workflows/osff.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#7032 OCPBUGS-14750: Pod termination must succeed when a hook fails
  server/container_stop.go
Labels: kind/bug, lgtm, approved, release-note, ok-to-test, dco-signoff: yes, jira/valid-bug, jira/severity-critical, jira/valid-reference

#7009 [1.23] cgmgr: create cgroups for systemd cgroup driver for dropped infra pods
  internal/config/cgmgr/cgmgr.go
  internal/config/cgmgr/cgroupfs.go
  internal/config/cgmgr/systemd.go
  server/sandbox_remove.go
  test/cgroups.bats
  test/pod.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#7019 test: fix timeout metric test
  test/timeout.bats
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes

#6990 Add support for linking pod logs
  internal/linklogs/link_logs.go
  pkg/annotations/annotations.go
  pkg/config/config.go
  server/container_create_linux.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
  test/ctr.bats
  test/helpers.bash
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#7043 [1.27] Add support for linking pod logs
  internal/linklogs/link_logs.go
  pkg/annotations/annotations.go
  pkg/config/config.go
  server/container_create_linux.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
  test/ctr.bats
  test/helpers.bash
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#7045 [1.26] Add support for linking pod logs
  internal/linklogs/link_logs.go
  internal/runtimehandlerhooks/high_performance_hooks.go
  pkg/annotations/annotations.go
  pkg/config/config.go
  server/container_create_linux.go
  server/sandbox_run_linux.go
  server/sandbox_stop_linux.go
  test/ctr.bats
  test/helpers.bash
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#7048 [1.24] version: bump to v1.24.6
  internal/version/version.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#7051 fix function name in comment
  internal/oci/oci.go
  utils/cmdrunner/cmdrunner.go
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#7052 utils: make this package build on non-linux platforms
  utils/utils.go
  utils/utils_linux.go
  utils/utils_unix.go
Labels: lgtm, approved, kind/cleanup, release-note-none, ok-to-test, dco-signoff: yes

#7054 Update golangci-lint and config
  .github/workflows/verify.yml
  .golangci.yml
  Makefile
  dependencies.yaml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#7055 Move reload watcher into `Server`
  pkg/config/reload.go
  server/server.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#7006 Drop support for path based seccomp profiles
  contrib/test/ci/vars.yml
  contrib/test/integration/vars.yml
  dependencies.yaml
  internal/config/seccomp/seccomp.go
  internal/config/seccomp/seccomp_test.go
  internal/factory/container/container.go
  internal/factory/container/container_test.go
  scripts/github-actions-setup
  server/container_create_linux.go
  server/sandbox_run_linux.go
  test/ctr_seccomp.bats
  test/seccomp_notifier.bats
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#7020 main: Added a call to GarbageCollect
  cmd/crio/main.go
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#7074 governance: tweak voting behavior
  GOVERNANCE.md
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#7081 Update supported version and variable guide for adding repository
  install.md
Labels: needs-ok-to-test, lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#7058 OCPBUGS-13980: runtime handler hooks: run default hooks on graceful container exit
  server/server.go
  test/cpu_load_balancing.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes, jira/valid-bug, jira/valid-reference

#7082 [1.27] Add support for namespaced signature policies
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  contrib/test/ci/build/cri-o.yml
  contrib/test/integration/build/cri-o.yml
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  internal/storage/image.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/template.go
  scripts/github-actions-setup
  server/image_pull.go
  server/server.go
  test/default.yaml
  test/helpers.bash
  test/policy-signature.json
  test/policy.bats
  test/policy.json
  test/testdata/policies/restrictive.json
  test/testdata/policies/unrestrictive.json
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#7087 Try to find `CONTAINER_CNI_PLUGIN_DIR` by binary lookup
  test/common.sh
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci
