Repository cri-o/cri-o, pull requests merged in 2024-02, with the labels that each got.

#7472 Implement pod sandbox for FreeBSD
  internal/config/node/node_freebsd.go
  internal/config/node/node_unsupported.go
  internal/config/nsmgr/nsmgr_freebsd.go
  internal/config/nsmgr/nsmgr_unsupported.go
  internal/config/nsmgr/types_freebsd.go
  internal/factory/container/container.go
  internal/factory/sandbox/infra.go
  internal/factory/sandbox/infra_linux.go
  internal/lib/container_server.go
  internal/lib/container_server_freebsd.go
  internal/lib/container_server_linux.go
  internal/lib/sandbox/sandbox.go
  internal/lib/sandbox/sandbox_freebsd.go
  internal/lib/sandbox/sandbox_linux.go
  internal/lib/sandbox/sandbox_unsupported.go
  internal/oci/container_freebsd.go
  internal/oci/container_freebsd_nocgo.go
  internal/oci/container_unsupported.go
  pkg/config/config.go
  pkg/config/config_freebsd.go
  pkg/config/config_linux.go
  server/sandbox_run_freebsd.go
  server/sandbox_run_unsupported.go
  server/sandbox_stop_freebsd.go
  server/sandbox_stop_unsupported.go
  server/server.go
  server/server_freebsd.go
  server/server_linux.go
Labels: kind/feature, lgtm, approved, release-note-none, dco-signoff: yes

#7714 Move metrics endpoint listener to use 127.0.0.1 as default
  completions/fish/crio.fish
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  pkg/config/config.go
  pkg/config/template.go
  server/metrics/metrics.go
  test/common.sh
  test/helpers.bash
  test/metrics.bats
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#7724 Update runc to 1.1.12
  dependencies.yaml
  scripts/versions
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#7734 [release-1.29] docs: fix crio.8.md.
  docs/crio.8.md
Labels: lgtm, approved, kind/failing-test, dco-signoff: yes

#7735 oci: handle early exited container faster in stop loop
  internal/oci/container.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#7728 nri: enable otel tracing
  go.mod
  go.sum
  internal/config/nri/nri.go
  server/server.go
  vendor/github.com/containerd/nri/pkg/adaptation/adaptation.go
  vendor/github.com/containerd/nri/pkg/adaptation/plugin.go
  vendor/github.com/containerd/nri/pkg/net/socketpair.go
  vendor/github.com/containerd/nri/pkg/net/socketpair_cloexec_linux.go
  vendor/github.com/containerd/nri/pkg/net/socketpair_cloexec_unix.go
  vendor/github.com/containerd/nri/pkg/net/socketpair_cloexec_windows.go
  vendor/github.com/containerd/nri/pkg/net/socketpair_unix.go
  vendor/github.com/containerd/nri/pkg/net/socketpair_windows.go
  vendor/github.com/containerd/nri/pkg/stub/stub.go
  vendor/github.com/containerd/otelttrpc/.gitignore
  vendor/github.com/containerd/otelttrpc/LICENSE
  vendor/github.com/containerd/otelttrpc/Makefile
  vendor/github.com/containerd/otelttrpc/README.md
  vendor/github.com/containerd/otelttrpc/config.go
  vendor/github.com/containerd/otelttrpc/doc.go
  vendor/github.com/containerd/otelttrpc/interceptor.go
  vendor/github.com/containerd/otelttrpc/internal/parse.go
  vendor/github.com/containerd/otelttrpc/internal/test.pb.go
  vendor/github.com/containerd/otelttrpc/internal/test.proto
  vendor/github.com/containerd/otelttrpc/metadata_supplier.go
  vendor/github.com/containerd/otelttrpc/semconv.go
  vendor/github.com/containerd/otelttrpc/version.go
  vendor/github.com/containerd/ttrpc/client.go
  vendor/github.com/containerd/ttrpc/config.go
  vendor/github.com/containerd/ttrpc/services.go
  vendor/modules.txt
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/other

#7747 [release-1.28] OCPNODE-2023: add metrics_host to config
  .github/workflows/verify.yml
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio-status.8.md
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  internal/criocli/documentation.go
  pkg/config/config.go
  pkg/config/template.go
  server/metrics/metrics.go
Labels: lgtm, approved, release-note, dco-signoff: yes, jira/valid-reference

#7726 When crio restarts, restore the infraContainers
  internal/lib/container_server.go
  internal/lib/container_server_test.go
Labels: kind/bug, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#7719 Add support for OCI artifact seccomp profiles
  Makefile
  contrib/test/ci/integration.yml
  contrib/test/ci/vars.yml
  docs/crio.conf.5.md
  internal/config/ociartifact/ociartifact.go
  internal/config/seccomp/seccomp.go
  internal/config/seccomp/seccomp_test.go
  internal/config/seccomp/seccompociartifact/seccompociartifact.go
  internal/config/seccomp/seccompociartifact/seccompociartifact_test.go
  internal/config/seccomp/seccompociartifact/seccompociartifact_test_inject.go
  internal/config/seccomp/seccompociartifact/suite_test.go
  pkg/annotations/annotations.go
  pkg/config/config.go
  pkg/config/template.go
  pkg/config/workloads.go
  server/container_create_linux.go
  server/sandbox_run_linux.go
  test/mocks/ociartifact/ociartifact.go
  test/seccomp_oci_artifacts.bats
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#7742 Fix ctr log max test on arm64
  test/ctr.bats
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes

#7757 release-notes: fix startTag calculation
  scripts/release-notes/release_notes.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#7761 Update openSUSE's OBS URL in install-distro.md file
  tutorials/install-distro.md
Labels: needs-ok-to-test, lgtm, approved, release-note-none, dco-signoff: yes

#7589 *: add support for specifying timezone for pod/container
  .golangci.yml
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  go.mod
  go.sum
  internal/criocli/criocli.go
  internal/oci/oci.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/template.go
  server/container_create_linux.go
  test/image.bats
  vendor/github.com/containers/common/pkg/timezone/timezone_linux.go
  vendor/github.com/containers/common/version/version.go
  vendor/github.com/containers/image/v5/docker/daemon/client.go
  vendor/github.com/containers/image/v5/docker/docker_image.go
  vendor/github.com/containers/image/v5/docker/docker_image_dest.go
  vendor/github.com/containers/image/v5/docker/docker_image_src.go
  vendor/github.com/containers/image/v5/docker/docker_transport.go
  vendor/github.com/containers/image/v5/version/version.go
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#7764 CRI: An empty DNSConfig != unspecified
  internal/factory/sandbox/infra.go
Labels: lgtm, approved, release-note, ok-to-test, dco-signoff: yes, kind/other

#7770 [relese-1.28] [manual] OCPBUGS-28589: highperfhooks: add precreate hook for injecting envs
  internal/runtimehandlerhooks/default_cpu_load_balance_hooks.go
  internal/runtimehandlerhooks/high_performance_hooks.go
  internal/runtimehandlerhooks/high_performance_hooks_test.go
  internal/runtimehandlerhooks/runtime_handler_hooks.go
  server/container_create_linux.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes, jira/invalid-bug, jira/valid-reference

#7772 Don't use CRLF when generating CRI-O documentation
  docs/crio.8.md
  internal/criocli/documentation.go
Labels: lgtm, approved, kind/documentation, kind/cleanup, release-note-none, dco-signoff: yes

#7773 [release-1.25] When crio restarts, restore the infraContainer
  internal/lib/container_server.go
  internal/lib/container_server_test.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#7730 [release-1.29] nri: enable otel tracing
  go.mod
  go.sum
  internal/config/nri/nri.go
  server/server.go
  vendor/github.com/containerd/nri/pkg/adaptation/adaptation.go
  vendor/github.com/containerd/nri/pkg/adaptation/plugin.go
  vendor/github.com/containerd/nri/pkg/net/socketpair.go
  vendor/github.com/containerd/nri/pkg/net/socketpair_cloexec_linux.go
  vendor/github.com/containerd/nri/pkg/net/socketpair_cloexec_unix.go
  vendor/github.com/containerd/nri/pkg/net/socketpair_cloexec_windows.go
  vendor/github.com/containerd/nri/pkg/net/socketpair_unix.go
  vendor/github.com/containerd/nri/pkg/net/socketpair_windows.go
  vendor/github.com/containerd/nri/pkg/stub/stub.go
  vendor/github.com/containerd/otelttrpc/.gitignore
  vendor/github.com/containerd/otelttrpc/LICENSE
  vendor/github.com/containerd/otelttrpc/Makefile
  vendor/github.com/containerd/otelttrpc/README.md
  vendor/github.com/containerd/otelttrpc/config.go
  vendor/github.com/containerd/otelttrpc/doc.go
  vendor/github.com/containerd/otelttrpc/interceptor.go
  vendor/github.com/containerd/otelttrpc/internal/parse.go
  vendor/github.com/containerd/otelttrpc/internal/test.pb.go
  vendor/github.com/containerd/otelttrpc/internal/test.proto
  vendor/github.com/containerd/otelttrpc/metadata_supplier.go
  vendor/github.com/containerd/otelttrpc/semconv.go
  vendor/github.com/containerd/otelttrpc/version.go
  vendor/github.com/containerd/ttrpc/client.go
  vendor/github.com/containerd/ttrpc/config.go
  vendor/github.com/containerd/ttrpc/services.go
  vendor/modules.txt
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/other

#7780 GitHub actions: Don't fail-fast matrix
  .github/workflows/integration.yml
  .github/workflows/test.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#7774 OCPBUGS-29251: [release-1.25] Fix wrong umask by updating c/common
  go.mod
  go.sum
  vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go
  vendor/github.com/containers/common/pkg/umask/umask.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes, jira/severity-moderate, jira/invalid-bug, jira/valid-reference

#7775 OCPBUGS-29398: [release-1.26] Fix wrong umask by updating c/common
  go.mod
  go.sum
  vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go
  vendor/github.com/containers/common/pkg/umask/umask.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes, jira/severity-moderate, jira/invalid-bug, jira/valid-reference

#7776 Filter image annotations before used
  contrib/test/ci/vars.yml
  server/container_create_linux.go
  test/seccomp_oci_artifacts.bats
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#7786 Reduce amount of parallel jobs in integration tests
  .github/workflows/integration.yml
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes

#7787 Run integration tests with JOBS=2
  .github/workflows/integration.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#7782 Remove deprecated metrics
  docs/crio.8.md
  docs/crio.conf.5.md
  server/image_pull.go
  server/metrics/metrics.go
  server/otel-collector/collectors/collectors.go
  server/otel-collector/collectors/collectors_test.go
  test/metrics.bats
  tutorials/metrics.md
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#7791 Group all dependabot updates
  .github/dependabot.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#7763 [release-1.28] Revert "Fix ImageRef field for containers to default to an image ID"
  server/container_create_linux.go
  test/helpers.bash
  test/image.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#7798 Add all update types to dependabot groups
  .github/dependabot.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#7762 Revert "Fix ImageRef field for containers to default to an image ID"
  internal/config/nsmgr/test/utils.go
  internal/lib/container_server.go
  internal/lib/container_server_test.go
  internal/lib/restore_test.go
  internal/lib/sandbox/sandbox_test.go
  internal/lib/suite_test.go
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/suite_test.go
  internal/runtimehandlerhooks/high_performance_hooks_test.go
  server/container_create_linux.go
  server/container_status.go
  server/inspect.go
  server/inspect_test.go
  server/sandbox_run_freebsd.go
  server/sandbox_run_linux.go
  server/suite_test.go
  test/helpers.bash
  test/image.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#7803 [release-1.29] Revert "Fix ImageRef field for containers to default to an image ID"
  .golangci.yml
  internal/config/nsmgr/test/utils.go
  internal/lib/container_server.go
  internal/lib/container_server_test.go
  internal/lib/restore_test.go
  internal/lib/sandbox/sandbox_test.go
  internal/lib/suite_test.go
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/suite_test.go
  internal/runtimehandlerhooks/high_performance_hooks_test.go
  server/container_create_linux.go
  server/container_status.go
  server/inspect.go
  server/inspect_test.go
  server/sandbox_run_linux.go
  server/suite_test.go
  test/helpers.bash
  test/image.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#7801 Allow plain annotation `seccomp-profile.kubernetes.cri-o.io` for images
  contrib/test/ci/vars.yml
  docs/crio.conf.5.md
  internal/config/seccomp/seccompociartifact/seccompociartifact.go
  pkg/annotations/annotations.go
  pkg/config/config.go
  pkg/config/template.go
  test/seccomp_oci_artifacts.bats
Labels: kind/feature, lgtm, approved, release-note-none, dco-signoff: yes

#7807 Update release-notes to v0.16.5
  Makefile
  dependencies.yaml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#7812 version: bump to 1.27.4
  internal/version/version.go
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#7811 version: bump to 1.28.4
  internal/version/version.go
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#7810 version: bump to 1.29.2
  internal/version/version.go
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#7806 Remove `crun` from `dependencies.yaml`
  dependencies.yaml
  scripts/versions
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#7814 In-memory OCI artifact pull
  contrib/test/ci/vars.yml
  internal/config/ociartifact/ociartifact.go
  internal/config/seccomp/seccompociartifact/seccompociartifact.go
  internal/config/seccomp/seccompociartifact/seccompociartifact_test.go
  test/mocks/ociartifact/ociartifact.go
  test/seccomp_oci_artifacts.bats
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#7821 Add s390x architecture support
  .github/workflows/test.yml
  README.md
  install.md
  nix/default-s390x.nix
  nix/nixpkgs.json
  scripts/release-notes/release_notes.go
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#7823 [release-1.29] Add s390x architecture support
  .github/workflows/test.yml
  README.md
  install.md
  nix/default-s390x.nix
  nix/nixpkgs.json
  scripts/release-notes/release_notes.go
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/ci

#7824 [release-1.28] Add s390x architecture support
  .github/workflows/test.yml
  README.md
  install.md
  nix/default-s390x.nix
  nix/nixpkgs.json
  scripts/release-notes/release_notes.go
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/ci

#7820 Keep versions file simple to source only
  scripts/versions
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#7828 Disable Recursive Read-only (RRO) mounts feature
  server/runtime_status.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes
