Repository cri-o/cri-o, pull requests merged in 2024-03, with the labels that each got.

#7829 fix a minor typo in the comment of pullImageImplementation
  internal/storage/image.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#7830 Remove `--seccomp-use-default-when-empty`/`seccomp_use_default_when_empty` option
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  contrib/test/ci/critest.yml
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/config/seccomp/seccomp.go
  internal/config/seccomp/seccomp_unsupported.go
  internal/criocli/criocli.go
  pkg/config/config.go
  pkg/config/template.go
  test/critest.bats
  test/ctr_seccomp.bats
  test/seccomp_oci_artifacts.bats
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/deprecation

#7827 Do not overwrite stored latency/governor on container restart
  internal/runtimehandlerhooks/high_performance_hooks_linux.go
  internal/runtimehandlerhooks/high_performance_hooks_test.go
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#7836 Change process metrics collector log levels
  internal/process/defunct_processes.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes, kind/other

#7838 Sync changes of PR#7719
  internal/config/seccomp/seccomp_unsupported.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/other

#7843 OCPBUGS-30203: deps: update otelttrpc to get rid of 'custom import path checks'
  go.mod
  go.sum
  vendor/github.com/containerd/otelttrpc/config.go
  vendor/github.com/containerd/otelttrpc/interceptor.go
  vendor/github.com/containerd/otelttrpc/internal/parse.go
  vendor/github.com/containerd/otelttrpc/metadata_supplier.go
  vendor/github.com/containerd/otelttrpc/semconv.go
  vendor/github.com/containerd/otelttrpc/version.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/dependency-change, jira/valid-bug, jira/severity-critical, jira/valid-reference

#7844 [release-1.29] OCPBUGS-30240: deps: update otelttrpc to get rid of 'custom import path checks'
  go.mod
  go.sum
  vendor/github.com/containerd/otelttrpc/config.go
  vendor/github.com/containerd/otelttrpc/interceptor.go
  vendor/github.com/containerd/otelttrpc/internal/parse.go
  vendor/github.com/containerd/otelttrpc/metadata_supplier.go
  vendor/github.com/containerd/otelttrpc/semconv.go
  vendor/github.com/containerd/otelttrpc/version.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/dependency-change, jira/severity-critical, jira/invalid-bug, jira/valid-reference

#7837 Add OCI artifact layer cache
  internal/config/ociartifact/impl.go
  internal/config/ociartifact/ociartifact.go
  internal/config/ociartifact/ociartifact_test.go
  internal/config/seccomp/seccompociartifact/seccompociartifact.go
  test/mocks/ociartifact/ociartifact.go
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#7862 Update test/README CNI plugins installation instructions
  test/README.md
Labels: needs-ok-to-test, lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#7868 Remove Podman `errorhandling` package dependency
  server/container_restore.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#7864 OCPBUGS-30758: Update google.golang.org/protobuf package to version v1.33.0
  go.mod
  go.sum
  vendor/google.golang.org/protobuf/encoding/protojson/decode.go
  vendor/google.golang.org/protobuf/encoding/protojson/doc.go
  vendor/google.golang.org/protobuf/encoding/protojson/encode.go
  vendor/google.golang.org/protobuf/encoding/protojson/well_known_types.go
  vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  vendor/google.golang.org/protobuf/encoding/prototext/encode.go
  vendor/google.golang.org/protobuf/encoding/protowire/wire.go
  vendor/google.golang.org/protobuf/internal/descfmt/stringer.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_gen.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_message.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go120.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go121.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/decode.go
  vendor/google.golang.org/protobuf/proto/doc.go
  vendor/google.golang.org/protobuf/proto/encode.go
  vendor/google.golang.org/protobuf/proto/extension.go
  vendor/google.golang.org/protobuf/proto/merge.go
  vendor/google.golang.org/protobuf/proto/proto.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions_defaults.binpb
  vendor/google.golang.org/protobuf/reflect/protodesc/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/type.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_equal.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_union.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go120.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go121.go
  vendor/google.golang.org/protobuf/reflect/protoregistry/registry.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/dependency-change, jira/invalid-bug, jira/valid-reference

#7870 Deflake `pod annotations capability for chained cni plugins` test
  test/helpers.bash
  test/pod_annotations_capability.bats
Labels: lgtm, approved, kind/flake, release-note-none, dco-signoff: yes

#7869 Use contextual logs in `server/container_restore.go`
  server/container_restore.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#7842 Update zeitgeist to v0.4.4
  Makefile
  dependencies.yaml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#7882 Use upcoming version as release notes `endRev`
  scripts/release-notes/release_notes.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#7867 Remove Podman `annotations` package dependency
  internal/factory/container/container.go
  internal/factory/container/container_test.go
  internal/lib/checkpoint.go
  internal/lib/container_server.go
  internal/lib/container_server_freebsd.go
  internal/lib/container_server_test.go
  internal/lib/restore.go
  internal/oci/runtime_vm.go
  pkg/annotations/internal.go
  server/container_restore.go
  server/nri-api.go
  server/sandbox_run_freebsd.go
  server/sandbox_run_linux.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#7890 Change duplicated string values into constants
  internal/runtimehandlerhooks/high_performance_hooks_test.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#7892 Cleanup release notes index
  README.md
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#7893 Remove Podman `lookup` dependency
  utils/utils.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#7898 [release-1.27] Change duplicated string values into constants
  internal/runtimehandlerhooks/high_performance_hooks_test.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#7900 Use CRIU version check go-criu; not from Podman
  go.mod
  go.sum
  internal/lib/checkpoint_test.go
  internal/lib/restore_test.go
  internal/oci/oci_test.go
  internal/oci/runtime_oci.go
  server/container_checkpoint_test.go
  server/container_restore_test.go
  test/checkcriu/checkcriu.go
  vendor/github.com/checkpoint-restore/go-criu/v7/README.md
  vendor/github.com/checkpoint-restore/go-criu/v7/codecov.yml
  vendor/github.com/checkpoint-restore/go-criu/v7/features.go
  vendor/github.com/checkpoint-restore/go-criu/v7/main.go
  vendor/github.com/checkpoint-restore/go-criu/v7/utils/criu.go
  vendor/github.com/checkpoint-restore/go-criu/v7/utils/criu_linux.go
  vendor/github.com/checkpoint-restore/go-criu/v7/utils/criu_unsupported.go
  vendor/github.com/containers/podman/v4/pkg/criu/criu_unsupported.go
  vendor/github.com/containers/podman/v4/pkg/lookup/lookup.go
  vendor/golang.org/x/sys/unix/aliases.go
  vendor/golang.org/x/sys/unix/syscall_darwin_libSystem.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/modules.txt
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#7871 Update cni-plugins to v1.4.1
  contrib/test/ci/build/plugins.yml
  dependencies.yaml
  scripts/versions
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#7873 [release-1.28] OCPBUGS-30764: Update google.golang.org/protobuf package to version v1.33.0
  go.mod
  go.sum
  vendor/google.golang.org/protobuf/encoding/protojson/decode.go
  vendor/google.golang.org/protobuf/encoding/protojson/doc.go
  vendor/google.golang.org/protobuf/encoding/protojson/encode.go
  vendor/google.golang.org/protobuf/encoding/protojson/well_known_types.go
  vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  vendor/google.golang.org/protobuf/encoding/prototext/encode.go
  vendor/google.golang.org/protobuf/encoding/protowire/wire.go
  vendor/google.golang.org/protobuf/internal/descfmt/stringer.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/defaults.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/encoding/json/decode.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_init.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/genid/struct_gen.go
  vendor/google.golang.org/protobuf/internal/genid/type_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_extension.go
  vendor/google.golang.org/protobuf/internal/impl/codec_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_tables.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_message.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect_field.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/strs/strings.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go120.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go121.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/decode.go
  vendor/google.golang.org/protobuf/proto/doc.go
  vendor/google.golang.org/protobuf/proto/encode.go
  vendor/google.golang.org/protobuf/proto/extension.go
  vendor/google.golang.org/protobuf/proto/merge.go
  vendor/google.golang.org/protobuf/proto/proto.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_resolve.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_validate.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/reflect/protodesc/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/type.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_equal.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_union.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go120.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go121.go
  vendor/google.golang.org/protobuf/reflect/protoregistry/registry.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.proto
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/dependency-change, jira/invalid-bug, jira/valid-reference

#7884 [release-1.26] OCPBUGS-30896: Cherry-pick changes from containers/common/pull#1437
  go.mod
  go.sum
  vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes, jira/severity-critical, jira/invalid-bug, jira/valid-reference

#7883 [release-1.25] OCPBUGS-30883: Cherry-pick changes from containers/common/pull#1437
  go.mod
  go.sum
  vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes, jira/severity-critical, jira/invalid-bug, jira/valid-reference

#7874 [release-1.27] OCPBUGS-30765: Update google.golang.org/protobuf package to version v1.33.0
  go.mod
  go.sum
  vendor/google.golang.org/protobuf/encoding/protojson/decode.go
  vendor/google.golang.org/protobuf/encoding/protojson/doc.go
  vendor/google.golang.org/protobuf/encoding/protojson/encode.go
  vendor/google.golang.org/protobuf/encoding/protojson/well_known_types.go
  vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  vendor/google.golang.org/protobuf/encoding/prototext/encode.go
  vendor/google.golang.org/protobuf/encoding/protowire/wire.go
  vendor/google.golang.org/protobuf/internal/descfmt/stringer.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/defaults.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/encoding/json/decode.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_init.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/genid/struct_gen.go
  vendor/google.golang.org/protobuf/internal/genid/type_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_extension.go
  vendor/google.golang.org/protobuf/internal/impl/codec_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_tables.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_message.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect_field.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/strs/strings.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go120.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go121.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/decode.go
  vendor/google.golang.org/protobuf/proto/doc.go
  vendor/google.golang.org/protobuf/proto/encode.go
  vendor/google.golang.org/protobuf/proto/extension.go
  vendor/google.golang.org/protobuf/proto/merge.go
  vendor/google.golang.org/protobuf/proto/proto.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_resolve.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_validate.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/reflect/protodesc/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/type.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_equal.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_union.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go120.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go121.go
  vendor/google.golang.org/protobuf/reflect/protoregistry/registry.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.proto
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/dependency-change, jira/invalid-bug, jira/valid-reference

#7875 [release-1.26] OCPBUGS-30766: Update google.golang.org/protobuf package to version v1.33.0
  go.mod
  go.sum
  vendor/google.golang.org/protobuf/encoding/protojson/decode.go
  vendor/google.golang.org/protobuf/encoding/protojson/doc.go
  vendor/google.golang.org/protobuf/encoding/protojson/encode.go
  vendor/google.golang.org/protobuf/encoding/protojson/well_known_types.go
  vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  vendor/google.golang.org/protobuf/encoding/prototext/encode.go
  vendor/google.golang.org/protobuf/encoding/protowire/wire.go
  vendor/google.golang.org/protobuf/internal/descfmt/stringer.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/defaults.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/encoding/json/decode.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_init.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/genid/struct_gen.go
  vendor/google.golang.org/protobuf/internal/genid/type_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_extension.go
  vendor/google.golang.org/protobuf/internal/impl/codec_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_tables.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_message.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect_field.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/strs/strings.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go120.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go121.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/decode.go
  vendor/google.golang.org/protobuf/proto/doc.go
  vendor/google.golang.org/protobuf/proto/encode.go
  vendor/google.golang.org/protobuf/proto/extension.go
  vendor/google.golang.org/protobuf/proto/merge.go
  vendor/google.golang.org/protobuf/proto/proto.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_resolve.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_validate.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/reflect/protodesc/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/type.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_equal.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_union.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go120.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go121.go
  vendor/google.golang.org/protobuf/reflect/protoregistry/registry.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.proto
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/dependency-change, jira/invalid-bug, jira/valid-reference

#7907 [release-1.29] OCPBUGS-30653: Add exponential backoff to the container stop loop
  contrib/test/ci/vars.yml
  internal/oci/container.go
  internal/oci/container_linux.go
  internal/oci/container_test.go
  internal/oci/container_unsupported.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  test/ctr.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes, jira/severity-critical, jira/invalid-bug, jira/valid-reference

#7854 OCPBUGS-28981: Add exponential backoff to the container stop loop
  contrib/test/ci/vars.yml
  internal/oci/container.go
  internal/oci/container_freebsd.go
  internal/oci/container_freebsd_nocgo.go
  internal/oci/container_linux.go
  internal/oci/container_test.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  test/ctr.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes, jira/valid-bug, jira/severity-critical, jira/valid-reference

#7908 [release-1.28] OCPBUGS-30654: Add exponential backoff to the container stop loop
  contrib/test/ci/vars.yml
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  test/ctr.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes, jira/severity-critical, jira/invalid-bug, jira/valid-reference

#7934 Update bats to v1.11.0
  contrib/test/ci/build/bats.yml
  dependencies.yaml
  scripts/versions
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/dependency-change

#7924 add a more clear pointer to what is supported for packaging
  install-legacy.md
  install.md
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#7920 [release-1.25] OCPBUGS-31254: Update google.golang.org/protobuf package to version v1.33.0
  go.mod
  go.sum
  vendor/google.golang.org/protobuf/encoding/protojson/decode.go
  vendor/google.golang.org/protobuf/encoding/protojson/doc.go
  vendor/google.golang.org/protobuf/encoding/protojson/encode.go
  vendor/google.golang.org/protobuf/encoding/protojson/well_known_types.go
  vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  vendor/google.golang.org/protobuf/encoding/prototext/encode.go
  vendor/google.golang.org/protobuf/encoding/protowire/wire.go
  vendor/google.golang.org/protobuf/internal/descfmt/stringer.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/defaults.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/encoding/json/decode.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_init.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/genid/struct_gen.go
  vendor/google.golang.org/protobuf/internal/genid/type_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_extension.go
  vendor/google.golang.org/protobuf/internal/impl/codec_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_tables.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_message.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect_field.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/strs/strings.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go120.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go121.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/decode.go
  vendor/google.golang.org/protobuf/proto/doc.go
  vendor/google.golang.org/protobuf/proto/encode.go
  vendor/google.golang.org/protobuf/proto/extension.go
  vendor/google.golang.org/protobuf/proto/merge.go
  vendor/google.golang.org/protobuf/proto/proto.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_resolve.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_validate.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/reflect/protodesc/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/type.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_equal.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_union.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go120.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go121.go
  vendor/google.golang.org/protobuf/reflect/protoregistry/registry.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.proto
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/dependency-change, jira/invalid-bug, jira/valid-reference

#7909 [release-1.27] OCPBUGS-30655: Add exponential backoff to the container stop loop
  contrib/test/ci/vars.yml
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  test/ctr.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes, jira/severity-critical, jira/invalid-bug, jira/valid-reference

#7922 packit: Update config and sync to Fedora
  .packit.yaml
Labels: lgtm, approved, release-note, ok-to-test, dco-signoff: yes, kind/ci
