Repository cri-o/cri-o, pull requests merged in 2024-08, with the labels that each got.

#8448 Run critest in parallel
  scripts/github-actions-setup
  test/critest.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8452 Log how configuration gets loaded
  cmd/crio/main.go
  internal/criocli/criocli.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/reload.go
  pkg/config/reload_test.go
  server/server.go
  test/reload_config.bats
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#8466 Remove custom golang version for runc
  contrib/test/ci/build/runc.yml
  scripts/github-actions-setup
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8468 [release-1.30] Use custom storage check options for CRI-O internal wipe
  cmd/crio/main.go
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  contrib/test/ci/integration.yml
  contrib/test/ci/vars.yml
  docs/crio.8.md
  internal/criocli/check.go
  internal/criocli/wipe.go
  internal/lib/container_server.go
  test/crio-check.bats
  test/crio-wipe.bats
  test/helpers.bash
  utils/utils.go
  utils/utils_test.go
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#8461 ci: use crun 1.15 temporarily
  contrib/test/ci/vars.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#8417 Use custom storage check options for CRI-O internal wipe
  cmd/crio/main.go
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  contrib/test/ci/integration.yml
  contrib/test/ci/vars.yml
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/check.go
  internal/criocli/wipe.go
  internal/lib/container_server.go
  pkg/config/config.go
  test/crio-check.bats
  test/crio-wipe.bats
  test/helpers.bash
  utils/utils.go
  utils/utils_test.go
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#8434 internal/oci: improve container termination process in killContainer
  internal/oci/runtime_oci.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#8470 start hostport manager cleanup
  internal/hostport/hostport.go
  internal/hostport/hostport_manager.go
  internal/hostport/hostport_manager_test.go
  internal/hostport/hostport_test.go
  internal/hostport/meta_hostport_manager.go
  internal/hostport/meta_hostport_manager_test.go
  server/server.go
Labels: lgtm, approved, kind/cleanup, release-note-none, ok-to-test, dco-signoff: yes

#8480 Fix incorrect tab handling while converting Info to string and add unit tests
  internal/version/version.go
  internal/version/version_test.go
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#8381 Add documentation for setting up CRI-O with Flatcar
  install.md
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#8465 Add `crun` integration tests
  .github/workflows/integration.yml
  internal/config/seccomp/notifier.go
  scripts/github-actions-packages
  scripts/github-actions-setup
  test/checkpoint.bats
  test/ctr.bats
  test/helpers.bash
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8485 Switch to Go 1.23
  .github/workflows/integration.yml
  .github/workflows/patch-release.yml
  .github/workflows/release-branch-forward.yml
  .github/workflows/tag-reconciler.yml
  .github/workflows/test.yml
  .github/workflows/verify.yml
  Makefile
  contrib/test/ci/vars.yml
  dependencies.yaml
  internal/resourcestore/resourcecleaner.go
  internal/runtimehandlerhooks/high_performance_hooks_linux.go
  server/sandbox_run_linux.go
  utils/errdefs/grpc.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8382 Update pause image to 3.10
  dependencies.yaml
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/storage/image_test.go
  pkg/config/config_linux.go
  pkg/config/config_unsupported.go
  test/common.sh
Labels: lgtm, approved, release-note, ok-to-test, dco-signoff: yes, kind/dependency-change

#8487 Fixed token-permission and pinned-dependencies issue
  .github/workflows/nixpkgs.yml
  .github/workflows/patch-release.yml
  .github/workflows/release-branch-forward.yml
  .github/workflows/tag-reconciler.yml
  .github/workflows/test.yml
Labels: release-note-none, ok-to-test, dco-signoff: yes, kind/ci

#8489 Fix space at EOL in actions
  .github/workflows/nixpkgs.yml
  .github/workflows/patch-release.yml
  .github/workflows/release-branch-forward.yml
  .github/workflows/tag-reconciler.yml
  .github/workflows/test.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8492 [release-1.30] Make container and image removal/stop idempotent
  scripts/github-actions-setup
  server/container_remove.go
  server/container_remove_test.go
  server/container_stop.go
  server/container_stop_test.go
  server/image_remove.go
  server/image_remove_test.go
  test/restore.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#8493 [release-1.29] Make container and image removal/stop idempotent
  server/container_remove.go
  server/container_remove_test.go
  server/container_stop.go
  server/container_stop_test.go
  server/image_remove.go
  server/image_remove_test.go
  test/restore.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#8490 Update shfmt to v3.9.0
  Makefile
  dependencies.yaml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8491 Trigger `test` workflow after release branch fast forward
  .github/workflows/release-branch-forward.yml
  scripts/release-branch-forward/release_branch_forward.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8498 Pass around more contexts in hooks and metrics
  internal/runtimehandlerhooks/high_performance_hooks_linux.go
  server/metrics/metrics.go
  server/server.go
  server/server_linux.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#8427 Run the runtime RuntimeType validation first
  pkg/config/config.go
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes, kind/other

#8426 Avoid potential reallocs by pre-sizing some slices
  server/server.go
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#8511 Make static build a GitHub action matrix
  .github/workflows/nixpkgs.yml
  .github/workflows/test.yml
  Makefile
  dependencies.yaml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8506 Change profile endpoint to 127.0.0.1
  cmd/crio/main.go
  completions/fish/crio.fish
  docs/crio.8.md
  internal/criocli/criocli.go
Labels: lgtm, approved, release-note, ok-to-test, dco-signoff: yes, kind/other

#8495 Change default tracing endpoint to 127.0.0.1
  docs/crio.8.md
  docs/crio.conf.5.md
  pkg/config/config.go
  tutorials/tracing.md
Labels: lgtm, approved, release-note, ok-to-test, dco-signoff: yes, kind/other

#8521 Add additional bind mount to image volumes
  .github/workflows/integration.yml
  contrib/test/ci/vars.yml
  server/container_create_linux.go
  test/oci_volumes.bats
Labels: kind/feature, lgtm, approved, release-note-none, dco-signoff: yes

#8530 Make `prettier` target run in a privileged container
  Makefile
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8531 Fix Makefile `$PWD` when running using `sudo`
  Makefile
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8525 config: add /dev/net/tun to default allowed devices
  docs/crio.8.md
  pkg/config/config.go
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#8532 Add Makefile help
  Makefile
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes
