Repository cri-o/cri-o, pull requests merged in 2024-07, with the labels that each got.

#8331 changed the scorecard badge link to the standard format
  README.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#8319 Mark v1.27 as EOL
  internal/version/version.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/deprecation

#8335 test: ensure correct parsing of supplemental groups policy in JSON
  test/ctr.bats
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes, kind/ci

#8336 Sort `crio` subcommands by name
  cmd/crio/main.go
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
Labels: lgtm, approved, release-note, kind/documentation, dco-signoff: yes

#8337 Fix version output in help
  cmd/crio/main.go
Labels: lgtm, approved, release-note, kind/documentation, dco-signoff: yes

#8345 Allow setting `CRICTL_BINARY` externally
  test/common.sh
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8346 Add `kubernetes` group in dependabot
  .github/dependabot.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8290 Restore container logs from checkpoint
  internal/lib/restore.go
Labels: kind/bug, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#8360 Add automatic markdown table of contents generation
  .github/workflows/verify.yml
  CONTRIBUTING.md
  GOVERNANCE.md
  Makefile
  awesome.md
  contrib/kube-local/README.md
  dependencies.yaml
  install.md
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8365 Add table of contents to README.md
  README.md
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#8347 nri: pass around context and log failed pid for not spoofed containers
  internal/nri/domain.go
  internal/nri/nri.go
  server/nri-api.go
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#8325 [release-1.29] OCPBUGS-33350: Reload config should remove pinned images when an empty list is provided
  contrib/test/ci/integration.yml
  contrib/test/ci/vars.yml
  go.mod
  go.sum
  pkg/config/reload.go
  server/image_status.go
  test/reload_config.bats
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/modules.txt
Labels: lgtm, approved, release-note, dco-signoff: yes, jira/severity-important, jira/invalid-bug, jira/valid-reference

#8362 server: propagate the pinned status of an image when queried via crictl
  server/image_status.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#8368 Remove go-setup from jobs not using golang
  .github/workflows/verify.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8359 Cleanup install docs
  README.md
  install-legacy.md
  install.md
  tutorials/install-distro.md
Labels: lgtm, approved, release-note, kind/documentation, dco-signoff: yes

#8367 Remove config migration
  completions/fish/crio.fish
  contrib/test/ci/integration.yml
  contrib/test/ci/vars.yml
  docs/crio.8.md
  internal/config/migrate/from_1_17.go
  internal/config/migrate/migrate.go
  internal/criocli/config.go
  test/config_migrate.bats
Labels: lgtm, approved, release-note, kind/api-change, dco-signoff: yes

#8354 Sanitize CRI-O version set in the User-Agent header
  server/useragent/useragent.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#8357 Move hostport tests to use ginkgo
  .golangci.yml
  internal/hostport/fake_iptables_test.go
  internal/hostport/hostport_manager_test.go
  internal/hostport/meta_hostport_manager_test.go
  internal/hostport/noop_hostport_manager_test.go
  test/nri/nri_suite_test.go
  test/nri/nri_test.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#8384 Remove duplicate `exclude_graphdriver_devicemapper` from static builds
  nix/derivation.nix
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#8386 KEP-3619: implement RuntimeStatus.features.supplemental_groups_policy
  go.mod
  go.sum
  server/runtime_status.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.pb.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#7958 test: use kata 3.6.0 for testing
  contrib/test/ci/build/kata.yml
  contrib/test/ci/vars.yml
  test/helpers.bash
  test/kata.bats
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes, kind/ci

#8300 OCPNODE-2408: internal/oci: remove redundant ShouldBeStopped check for stopping containers
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  internal/oci/runtime_vm.go
  server/container_stop.go
  test/ctr.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes, jira/valid-reference

#8398 Disable network ping tests for actuated runners
  test/network_ping.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8387 Use `.gitignore` in nix build excludes
  nix/derivation.nix
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8317 Add OCI/Image Volume Source support
  go.mod
  internal/storage/image.go
  internal/storage/image_test.go
  server/container_create_linux.go
  server/container_create_linux_test.go
  server/image_remove.go
  server/image_remove_test.go
  test/oci_volumes.bats
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#8392 [release-1.30] internal/oci: remove redundant ShouldBeStopped check for stopping containers
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  internal/oci/runtime_vm.go
  server/container_stop.go
  test/ctr.bats
Labels: lgtm, approved, release-note, dco-signoff: yes

#8407 Use cri-tools `master` for CI tests
  contrib/test/ci/vars.yml
  dependencies.yaml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8410 oci_volumes: require crictl that can request OCI volumes
  test/oci_volumes.bats
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes

#8408 Make ImageVolume garbage collection work
  internal/oci/container.go
  server/container_create_linux.go
  server/container_status.go
  test/oci_volumes.bats
Labels: kind/feature, lgtm, approved, release-note-none, dco-signoff: yes

#8393 [release 1.29] internal/oci: remove redundant ShouldBeStopped check for stopping containers
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  internal/oci/runtime_vm.go
  server/container_stop.go
  test/ctr.bats
Labels: lgtm, approved, release-note, dco-signoff: yes

#8415 Remove error log message if mountpoint cannot be found
  internal/storage/image.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#8406 Log version only for main CRI-O command
  cmd/crio/main.go
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#6280 test: config tests should ignore default runtime environment variable
  contrib/test/ci/integration.yml
  contrib/test/ci/vars.yml
  test/config.bats
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes, kind/ci

#8394 [release 1.28] internal/oci: remove redundant ShouldBeStopped check for stopping containers
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  internal/oci/runtime_vm.go
  server/container_stop.go
  test/ctr.bats
Labels: lgtm, approved, release-note, dco-signoff: yes

#8395 [release 1.27] internal/oci: remove redundant ShouldBeStopped check for stopping containers
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  internal/oci/runtime_vm.go
  server/container_stop.go
  test/ctr.bats
Labels: lgtm, approved, release-note, dco-signoff: yes

#8421 Fix lint timeout option
  .github/workflows/verify.yml
  .golangci.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8428 Trim `crio version Version: …` prefix from `crio -v`
  cmd/crio/main.go
  internal/criocli/version.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#8431 Make container and image removal/stop idempotent
  server/container_remove.go
  server/container_remove_test.go
  server/container_stop.go
  server/container_stop_test.go
  server/image_remove.go
  server/image_remove_test.go
  test/restore.bats
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#8418 hack/build-rpms.sh: Update for new builder image
  contrib/test/ci/cri-o.spec
  hack/build-rpms.sh
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes, kind/ci

#8438 Enable and fix `gomoddirectives`, `gomodguard`, `noctx` and `wastedassign` linters
  .golangci.yml
  cmd/crio/main.go
  contrib/metrics-exporter/main.go
  internal/client/client.go
  internal/criocli/status.go
  internal/factory/container/container.go
  internal/log/hook_filename.go
  internal/oci/container.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes
