Repository cri-o/cri-o, pull requests merged in 2024-11, with the labels that each got.

#8706 Cleanups on top of #8212, second part
  internal/factory/container/container.go
  internal/factory/container/container_test.go
  internal/lib/checkpoint.go
  internal/lib/container_server.go
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/runtime_vm.go
  pkg/annotations/internal.go
  server/container_create.go
  server/container_create_linux.go
  server/container_restore.go
  server/container_restore_test.go
  server/container_status.go
  server/inspect.go
  server/sandbox_run_freebsd.go
  server/sandbox_run_linux.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#8717 Remove unused server metrics interceptor
  server/metrics/interceptors.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#8720 Use context for logging in server
  server/server.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#8718 Switch to golang native context
  go.mod
  internal/oci/container.go
  internal/oci/container_linux.go
  internal/oci/oci.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_linux.go
  internal/oci/runtime_pod.go
  internal/oci/runtime_vm.go
  internal/resourcestore/resourcecleaner_test.go
  internal/resourcestore/resourcestore_test.go
  server/container_attach.go
  server/container_checkpoint.go
  server/container_create_linux.go
  server/container_create_unsupported.go
  server/container_exec.go
  server/container_execsync.go
  server/container_portforward.go
  server/container_reopen_log.go
  server/container_restore.go
  server/container_start.go
  server/container_stats_list.go
  server/container_status.go
  server/container_stop.go
  server/container_update_resources.go
  server/image_list.go
  server/inspect.go
  server/metric_descriptors_list.go
  server/runtime_config.go
  server/runtime_status.go
  server/sandbox_list.go
  server/sandbox_metrics_list.go
  server/sandbox_remove.go
  server/sandbox_remove_test.go
  server/sandbox_run.go
  server/sandbox_run_freebsd.go
  server/sandbox_run_linux.go
  server/sandbox_status.go
  server/sandbox_stop.go
  server/sandbox_stop_freebsd.go
  server/sandbox_stop_linux.go
  utils/utils_linux.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#8731 expose Pod assigned IPs to NRI plugins
  go.mod
  go.sum
  internal/lib/sandbox/sandbox.go
  internal/nri/sandbox.go
  vendor/github.com/containerd/nri/pkg/api/api.pb.go
  vendor/github.com/containerd/nri/pkg/api/api.proto
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, release-note, kind/flake, dco-signoff: yes, kind/other

#8736 Remove dead code in HostportManager
  internal/hostport/hostport.go
  internal/hostport/hostport_manager.go
  internal/hostport/hostport_manager_test.go
  internal/hostport/hostport_test.go
  internal/hostport/noop_hostport_manager.go
  internal/hostport/noop_hostport_manager_test.go
  server/sandbox_network.go
Labels: lgtm, approved, kind/cleanup, release-note-none, ok-to-test, dco-signoff: yes

#8730 Convert `interface{}` to `any`
  internal/criocli/criocli.go
  internal/log/interceptors/interceptors.go
  internal/log/klog.go
  internal/log/log.go
  internal/mockutils/mockutils.go
  internal/oci/runtime_oci_linux.go
  internal/oci/runtime_oci_test.go
  pkg/config/template.go
  server/container_start.go
  server/runtime_status.go
  server/sandbox_status.go
  test/docs-validation/main.go
  utils/errdefs/grpc.go
  utils/utils.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#8740 Fix `typos` in CI
  .typos.toml
  cmd/crio/main.go
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes

#8397 Cleanup/refactor create sandbox container
  internal/config/node/cgroups_unsupported.go
  internal/factory/container/container.go
  internal/factory/container/container_test.go
  server/container_create_linux.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#8744 Validate stream server TLS config on startup
  pkg/config/config.go
  pkg/config/config_test.go
  server/server.go
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#8755 Remove validation for TLSCA
  pkg/config/config.go
  pkg/config/config_test.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#8757 Improve hostport unit tests
  internal/hostport/fake_iptables.go
  internal/hostport/hostport_manager_test.go
Labels: lgtm, approved, kind/cleanup, release-note-none, ok-to-test, dco-signoff: yes

#8758 vendor cni 0.4.3
  go.mod
  go.sum
  test/mocks/ocicni/types.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/types.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/dependency-change

#8623 Use a common cert-reloader for metrics and streaming endpoints
  completions/fish/crio.fish
  docs/crio.8.md
  internal/cert/cert.go
  internal/criocli/criocli.go
  pkg/config/template.go
  server/metrics/metrics.go
  server/server.go
  test/cert.bats
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#8754 RuntimeHandler inheritance
  docs/crio.conf.5.md
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/reload.go
  pkg/config/reload_test.go
  pkg/config/template.go
Labels: kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#8766 Use `slices.Equal` instead of custom implementation
  pkg/config/template.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#8763 Update golangci-lint to v1.62.0
  .github/workflows/verify.yml
  .golangci.yml
  Makefile
  dependencies.yaml
  internal/runtimehandlerhooks/runtime_handler_hooks.go
  server/container_attach.go
  server/container_exec.go
  server/container_portforward.go
  server/server.go
  server/suite_test.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#8768 RuntimeHandler inheritance bug-fix
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/reload.go
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#8750 Use google.golang.org/protobuf instead of gogo
  go.mod
  server/container_update_resources.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#8756 Update and fix nix packages
  nix/derivation.nix
  nix/nixpkgs.json
  nix/overlay.nix
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/dependency-change

#8765 Add `--pull-progress-timeout` / `pull_progress_timeout` option
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  pkg/config/config.go
  pkg/config/template.go
  server/image_pull.go
  test/image.bats
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#8782 Fix NRI CLI flags
  completions/fish/crio.fish
  docs/crio.8.md
  internal/criocli/criocli.go
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#8786 Fix container restore lint and unit tests
  server/container_restore.go
  server/container_restore_test.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8792 [release-1.31] Only restore container if all bind mounts are defined
  server/container_restore.go
  server/container_restore_test.go
  test/checkpoint.bats
Labels: lgtm, approved, release-note, dco-signoff: yes

#8793 [release-1.30] Only restore container if all bind mounts are defined
  server/container_restore.go
  server/container_restore_test.go
  test/checkpoint.bats
Labels: lgtm, approved, release-note, dco-signoff: yes

#8795 [release-1.29] Only restore container if all bind mounts are defined
  server/container_restore.go
  server/container_restore_test.go
  test/checkpoint.bats
Labels: lgtm, approved, release-note, dco-signoff: yes
