Repository cri-o/cri-o, pull requests merged in 2024-12, with the labels that each got.

#8807 [release-1.29] Fix failing test following a backport from cri-o/cri-o/pull#8795
  .github/workflows/integration.yml
  .github/workflows/test.yml
  server/container_restore_test.go
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes, kind/ci

#8808 Use `monitor_env` for calling the OCI runtime
  internal/oci/runtime_oci.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#8804 [release-1.31] Disable actuated runners
  .github/workflows/integration.yml
  .github/workflows/test.yml
  README.md
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#8785 Allow to remove pod sandbox on netns removal
  internal/config/nsmgr/types_linux.go
  server/sandbox_network.go
  test/network.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#8813 Always clear env even when `monitor_env` is unset
  cmd/crio/daemon_linux.go
  internal/oci/runtime_oci.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#8821 Update cni-plugins to v1.6.1
  contrib/test/ci/build/plugins.yml
  dependencies.yaml
  scripts/versions
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8824 Fix issues when running on Linux with seccomp disabled
  server/container_create_linux.go
  server/sandbox_run_linux.go
  server/server.go
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#8835 Update golangci-lint to v1.62.2 and config
  .github/workflows/verify.yml
  .golangci.yml
  Makefile
  dependencies.yaml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8597 Require go 1.23 for build
  dependencies.yaml
  go.mod
  hack/build-rpms.sh
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#8794 Only ctx timeout errors detected in the final stage can be ignored in createcontainer or runsandbox operation
  server/container_create.go
  server/sandbox_run_linux.go
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#8610 Moving container sanbox to lib sandbox
  internal/factory/container/container_test.go
  internal/factory/sandbox/sandbox.go
  internal/factory/sandbox/sandbox_setnameandid_test.go
  internal/factory/sandbox/sandbox_test.go
  internal/factory/sandbox/suite_test.go
  internal/lib/container_server.go
  internal/lib/sandbox/builder.go
  internal/lib/sandbox/fixtures/expanded_resolv.conf
  internal/lib/sandbox/fixtures/resolv.conf
  internal/lib/sandbox/infra.go
  internal/lib/sandbox/infra_linux.go
  internal/lib/sandbox/infra_test.go
  internal/lib/sandbox/sandbox.go
  internal/lib/sandbox/sandbox_builder_test.go
  internal/lib/sandbox/sandbox_test.go
  internal/lib/sandbox/suite_test.go
  internal/lib/suite_test.go
  internal/memorystore/history_test.go
  internal/memorystore/suite_test.go
  internal/runtimehandlerhooks/high_performance_hooks_test.go
  server/sandbox_run_freebsd.go
  server/sandbox_run_linux.go
  server/suite_test.go
Labels: lgtm, approved, release-note, kind/cleanup, ok-to-test, dco-signoff: yes

#8829 config: add default_annotations
  contrib/test/ci/vars.yml
  docs/crio.conf.5.md
  internal/oci/oci.go
  pkg/config/config.go
  pkg/config/template.go
  server/sandbox_run_linux.go
  test/pod.bats
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#8863 Refactor man page variables in Makefile.
  Makefile
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#8857 maintainers: promote Sohan and Krzysztof to approvers
  MAINTAINERS.md
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/other
