Repository cri-o/cri-o, pull requests merged in 2024-04, with the labels that each got.

#7887 Add dynamic image pull timeout
  internal/storage/image.go
  internal/storage/image_test.go
  internal/storage/runtime.go
  internal/storage/runtime_test.go
  server/image_pull.go
  server/image_pull_test.go
  test/mocks/criostorage/criostorage.go
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#7822 Add support for setting CPU limits for workloads
  internal/config/cgmgr/cgroupfs_linux.go
  internal/config/cgmgr/systemd_linux.go
  pkg/config/template.go
  pkg/config/workloads.go
  pkg/config/workloads_test.go
Labels: kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#7945 oci: AttachContainer: always read attach socket
  internal/oci/runtime_oci.go
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#7910 [release-1.26] OCPBUGS-30656: Add exponential backoff to the container stop loop
  contrib/test/ci/vars.yml
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  test/ctr.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes, jira/severity-critical, jira/invalid-bug, jira/valid-reference

#7921 [release-1.25] OCPBUGS-31253: Add exponential backoff to the container stop loop
  contrib/test/ci/vars.yml
  internal/oci/container.go
  internal/oci/container_test.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_oci_test.go
  test/ctr.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes, jira/severity-critical, jira/invalid-bug, jira/valid-reference

#7933 Deflake seccomp notifier bats tests
  test/seccomp_notifier.bats
Labels: kind/bug, lgtm, approved, release-note-none, kind/failing-test, ok-to-test, dco-signoff: yes, kind/ci

#7946 Change `progressGoRoutine` to `consumeImagePullProgress`
  server/image_pull.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#7951 use wasmedge and drop crun-wasm
  contrib/test/ci/build/crun.yml
  contrib/test/ci/system-packages.yml
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#7953 add x to set for traceability
  test/test_runner.sh
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#7952 test: remove references to crioctl
  test/common.sh
  test/helpers.bash
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#7948 Run seccomp notifier tests on arm
  scripts/github-actions-setup
  test/seccomp_notifier.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#7956 use golang 1.21 until runc works with 1.22
  contrib/test/ci/build/runc.yml
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#7846 Change CRIU support from default off to default on
  docs/crio.conf.5.md
  pkg/config/config.go
  server/container_restore.go
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#7790 config, docs, completions: enable NRI by default.
  completions/fish/crio.fish
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/config/nri/nri.go
  test/helpers.bash
  test/nri.bats
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/other

#7967 create go1.21.9 directory
  contrib/test/ci/build/crun.yml
  contrib/test/ci/build/runc.yml
  contrib/test/ci/system-packages.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#7970 test: fix potential flake in timezone tests.
  test/image.bats
Labels: lgtm, approved, kind/flake, release-note-none, dco-signoff: yes

#7975 Do not abort startup if CRIU binary not found
  pkg/config/config.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#7988 skip crun-wasm test in image bats
  test/image.bats
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes

#7993 Disable cron jobs forks
  .github/workflows/cron.yml
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes, kind/ci

#7999 contrib/test/ci: use the main branch for building crun
  contrib/test/ci/build/crun.yml
  contrib/test/ci/vars.yml
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes, kind/ci

#8003 Remove pinned conmon-rs version
  dependencies.yaml
  scripts/versions
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8004 Fix Actuated badge in README.md
  README.md
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#8005 Add docs about the prow CI images
  README.md
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#7982 [release-1.29] OCPBUGS-29439: Cherry-pick changes from containers/image/pull#2363
  go.mod
  go.sum
  vendor/github.com/containers/image/v5/docker/docker_client.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes, jira/severity-important, jira/invalid-bug, jira/valid-reference

#7990 Use unshare instead of rootless
  internal/config/cgmgr/cgroupfs_linux.go
  internal/config/cgmgr/systemd_linux.go
  internal/storage/image.go
  internal/storage/image_linux.go
  pkg/config/config.go
  server/container_create_linux.go
  server/sandbox_run_linux.go
  test/copyimg/copyimg.go
  utils/utils_test.go
  vendor/github.com/containers/podman/v4/pkg/errorhandling/errorhandling.go
  vendor/github.com/containers/podman/v4/pkg/rootless/rootless.go
  vendor/github.com/containers/podman/v4/pkg/rootless/rootless_freebsd.c
  vendor/github.com/containers/podman/v4/pkg/rootless/rootless_freebsd.go
  vendor/github.com/containers/podman/v4/pkg/rootless/rootless_linux.c
  vendor/github.com/containers/podman/v4/pkg/rootless/rootless_linux.go
  vendor/github.com/containers/podman/v4/pkg/rootless/rootless_unsupported.go
  vendor/modules.txt
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#8006 contrib/test/ci: use force_clone for crun to avoid outdated codebase
  contrib/test/ci/build/cri-tools.yml
  contrib/test/ci/build/crun.yml
  contrib/test/ci/setup.yml
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes, kind/ci

#8000 add powertools repo for gpgme-devel
  install.md
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#7981 Cherry-pick changes from containers/image/pull#2363
  go.mod
  go.sum
  vendor/github.com/containers/image/v5/docker/docker_client.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#7983 [release-1.28] OCPBUGS-31925: Cherry-pick changes from containers/image/pull#2363
  go.mod
  go.sum
  vendor/github.com/containers/image/v5/docker/docker_client.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes, jira/severity-important, jira/invalid-bug, jira/valid-reference

#7832 Add configurable container minimum memory limit
  completions/fish/crio.fish
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/config/cgmgr/cgmgr_linux.go
  internal/config/cgmgr/cgmgr_test.go
  internal/config/cgmgr/cgmgr_unsupported.go
  internal/config/cgmgr/cgroupfs_linux.go
  internal/config/cgmgr/systemd_linux.go
  internal/criocli/criocli.go
  internal/oci/oci.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/template.go
  server/container_create_linux.go
  server/nri-api.go
  server/sandbox_run_linux.go
  test/image.bats
Labels: kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#8014 Print runtime version info on CRI-O startup
  pkg/config/config.go
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#8015 Enable and fix errorlint
  .golangci.yml
  cmd/crio/main.go
  internal/factory/container/device_linux.go
  internal/factory/sandbox/infra_linux.go
  internal/iptables/iptables.go
  internal/iptables/iptables_linux.go
  internal/lib/container.go
  internal/lib/sandbox/namespaces.go
  internal/nri/nri.go
  internal/oci/runtime_oci.go
  internal/storage/image.go
  pkg/config/config.go
  server/container_create.go
  server/container_create_linux.go
  server/container_remove.go
  server/container_restore.go
  server/container_start.go
  server/container_stop.go
  server/image_pull.go
  server/inspect.go
  server/inspect_test.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/sandbox_stop.go
  server/sandbox_stop_linux.go
  server/server.go
  server/utils.go
  test/nri/nri_test.go
  test/nri/runtime.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#7965 add release versions for manual workflow run
  scripts/patch-release/patch-release.go
  scripts/patch-release/patch-release_test.go
Labels: kind/feature, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#7962 OCPNODE-2213: Add support for Recursive Read-only (RRO) mounts
  contrib/test/ci/vars.yml
  internal/oci/container.go
  internal/oci/oci.go
  pkg/config/config.go
  pkg/config/config_freebsd.go
  pkg/config/config_linux.go
  pkg/config/config_test.go
  pkg/config/config_unsupported.go
  pkg/config/config_windows.go
  server/container_create_linux.go
  server/container_create_linux_test.go
  server/container_restore.go
  server/container_status.go
  server/runtime_status.go
  test/ctr.bats
  test/helpers.bash
  test/selinux.bats
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes, jira/valid-reference

#7998 update runtime spec to 1.2
  go.mod
  go.sum
  vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/features/features.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8024 [release-1.29] OCPNODE-2247: Implement configurable container minimum memory limit per OCI runtime.
  completions/fish/crio.fish
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/config/cgmgr/cgmgr_linux.go
  internal/config/cgmgr/cgmgr_test.go
  internal/config/cgmgr/cgmgr_unsupported.go
  internal/config/cgmgr/cgroupfs_linux.go
  internal/config/cgmgr/systemd_linux.go
  internal/criocli/criocli.go
  internal/oci/oci.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/template.go
  server/container_create_linux.go
  server/nri-api.go
  server/sandbox_run_linux.go
  test/image.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes, jira/valid-reference

#7971 deps,config,factory: update CDI deps, use updated CDI interface.
  go.mod
  go.sum
  internal/factory/container/device_linux.go
  internal/factory/container/device_test.go
  pkg/config/config.go
  pkg/config/reload.go
  vendor/modules.txt
  vendor/tags.cncf.io/container-device-interface/internal/multierror/multierror.go
  vendor/tags.cncf.io/container-device-interface/internal/validation/k8s/objectmeta.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/cache.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/container-edits.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/default-cache.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/doc.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/registry.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/spec-dirs.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/spec.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/version.go
  vendor/tags.cncf.io/container-device-interface/specs-go/config.go
  vendor/tags.cncf.io/container-device-interface/specs-go/oci.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/other

#8027 Update golangci-lint to v1.57.2 and config
  .github/workflows/verify.yml
  .golangci.yml
  Makefile
  dependencies.yaml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8037 Update `release-notes` to v0.16.8
  Makefile
  dependencies.yaml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/dependency-change

#8026 Fix patch release workflow restriction
  .github/workflows/patch-release.yml
  dependencies.yaml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8038 Add missing kernel version check to the RRO mounts integration tests
  test/ctr.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8043 patch-release: configure the default git user and fix file update
  scripts/patch-release/patch-release.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#7984 [release-1.27] OCPBUGS-31926: Cherry-pick changes from containers/image/pull#2363
  go.mod
  go.sum
  vendor/github.com/containers/image/v5/docker/docker_client.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes, jira/severity-important, jira/invalid-bug, jira/valid-reference

#8048 Use release-note block instead of label
  scripts/patch-release/patch-release.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8047 Bump version to 1.27.5
  internal/version/version.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#8046 Bump version to 1.28.5
  internal/version/version.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#8045 Bump version to 1.29.3
  internal/version/version.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#8036 Update cri-tools to v1.30.0
  contrib/test/ci/vars.yml
  dependencies.yaml
  scripts/versions
  test/ctr.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8051 drop hooks from kata integration tests
  contrib/test/ci/vars.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8055 Rename `cron` workflow to `release-branch-forward`
  .github/workflows/release-branch-forward.yml
  dependencies.yaml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8059 Remove duplicate comment in crio.conf
  pkg/config/template.go
Labels: lgtm, approved, kind/cleanup, release-note-none, ok-to-test, dco-signoff: yes

#8060 Distinguish conmon version parse from execution error
  internal/config/conmonmgr/conmonmgr.go
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#8061 Run patch release and nixpkgs jobs only on cri-o/cri-o
  .github/workflows/nixpkgs.yml
  .github/workflows/patch-release.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8062 Bump ocicrypt to v1.1.10
  go.mod
  go.sum
  vendor/github.com/containers/ocicrypt/keywrap/jwe/keywrapper_jwe.go
  vendor/github.com/containers/ocicrypt/utils/testing.go
  vendor/modules.txt
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/dependency-change

#8063 [release-1.29] Bump ocicrypt to v1.1.10
  .golangci.yml
  go.mod
  go.sum
  vendor/github.com/containers/ocicrypt/keywrap/jwe/keywrapper_jwe.go
  vendor/github.com/containers/ocicrypt/utils/testing.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/dependency-change

#8057 Stop using BytesSize when merging the config
  contrib/test/ci/vars.yml
  internal/criocli/criocli.go
  test/image.bats
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#7937 oci: keep track of exec PIDs and stop them on container stop
  internal/oci/container.go
  internal/oci/oci_unix.go
  internal/oci/runtime_oci.go
  test/ctr.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#7840 server: do not chmod bind mounts with user namespaces
  internal/factory/sandbox/infra.go
  internal/factory/sandbox/sandbox.go
  server/container_create_linux.go
  server/sandbox_run_freebsd.go
  server/sandbox_run_linux.go
  vendor/github.com/containers/common/pkg/util/util.go
  vendor/github.com/containers/common/pkg/util/util_supported.go
  vendor/github.com/containers/common/pkg/util/util_windows.go
  vendor/modules.txt
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#7976 Reload config update pinned_images
  contrib/test/ci/integration.yml
  contrib/test/ci/vars.yml
  internal/storage/image.go
  pkg/config/reload.go
  server/server.go
  test/mocks/criostorage/criostorage.go
  test/reload_config.bats
Labels: kind/bug, kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#8070 Build s390x binaries using musl libc
  nix/default-s390x.nix
  nix/derivation.nix
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#8075 Pin GitHub actions commits
  .github/workflows/integration.yml
  .github/workflows/nixpkgs.yml
  .github/workflows/osff.yml
  .github/workflows/patch-release.yml
  .github/workflows/release-branch-forward.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .github/workflows/verify.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8073 [release-1.29] Reload config update pinned_images
  contrib/test/ci/integration.yml
  contrib/test/ci/vars.yml
  internal/storage/image.go
  pkg/config/reload.go
  server/server.go
  test/mocks/criostorage/criostorage.go
  test/reload_config.bats
Labels: lgtm, approved, release-note, dco-signoff: yes

#8056 Replace patch-release.go with release.go
  .github/workflows/patch-release.yml
  Makefile
  scripts/patch-release/patch-release.go
  scripts/release/release.go
  scripts/release/release_test.go
  scripts/release/suite_test.go
Labels: lgtm, approved, kind/cleanup, release-note-none, ok-to-test, dco-signoff: yes

#8064 [release-1.28] Bump ocicrypy to v1.1.10
  go.mod
  go.sum
  vendor/github.com/containers/ocicrypt/Makefile
  vendor/github.com/containers/ocicrypt/keywrap/jwe/keywrapper_jwe.go
  vendor/github.com/containers/ocicrypt/keywrap/pkcs11/keywrapper_pkcs11.go
  vendor/github.com/containers/ocicrypt/spec/spec.go
  vendor/github.com/containers/ocicrypt/utils/testing.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#8078 Fix verify.yml for GitHub actions
  .github/workflows/verify.yml
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes

#8065 [release-1.27] Bump ocicrypt to v1.1.10
  go.mod
  go.sum
  vendor/github.com/containers/ocicrypt/Makefile
  vendor/github.com/containers/ocicrypt/keywrap/jwe/keywrapper_jwe.go
  vendor/github.com/containers/ocicrypt/keywrap/pkcs11/keywrapper_pkcs11.go
  vendor/github.com/containers/ocicrypt/spec/spec.go
  vendor/github.com/containers/ocicrypt/utils/testing.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/dependency-change

#8011 server: allow containers within a cluster to opt out of FIPS mode
  .golangci.yml
  contrib/test/ci/vars.yml
  dependencies.yaml
  docs/crio.conf.5.md
  pkg/annotations/annotations.go
  pkg/config/config.go
  pkg/config/template.go
  scripts/github-actions-setup
  scripts/versions
  server/container_create_linux.go
  test/pod.bats
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#8082 Pin golangci-lint action
  .github/workflows/verify.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8086 version: bump to 1.28.6
  internal/version/version.go
  pkg/annotations/annotations.go
  test/workloads.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#8087 version: bump to 1.27.6
  internal/version/version.go
  pkg/annotations/annotations.go
  test/workloads.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#8085 version: bump to 1.29.4
  internal/version/version.go
  pkg/annotations/annotations.go
  test/workloads.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#8088 fix typo and lints of CVE-2024-3154 fix
  pkg/annotations/annotations.go
  test/workloads.bats
Labels: lgtm, approved, release-note, dco-signoff: yes

#7715 OCPBUGS-28586: higeperfhooks: mixedcpus: set only exclusive cpus in child cgroup
  internal/runtimehandlerhooks/high_performance_hooks_linux.go
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes, jira/valid-bug, jira/valid-reference

#8077 Install `cri-tools` from `master`
  dependencies.yaml
  scripts/github-actions-setup
  scripts/versions
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8089 [1.26] annotations: add OCI runtime specific annotations to the AllowedAnnotions
  pkg/annotations/annotations.go
  test/workloads.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#8090 [1.25] annotations: add OCI runtime specific annotations to the AllowedAnnotions
  pkg/annotations/annotations.go
  test/workloads.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes
