Repository cri-o/cri-o, pull requests merged in 2025-05, with the labels that each got.

#9171 Refactor addOCIBindMounts
  server/container_create.go
  server/container_create_freebsd.go
  server/container_create_linux.go
  server/container_create_linux_test.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#9186 Fix GitHub actions CI test setup
  scripts/github-actions-setup
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes

#8684 Port hostport code from iptables to nftables
  contrib/test/ci/system-packages.yml
  go.mod
  go.sum
  install.md
  internal/hostport/fake_iptables.go
  internal/hostport/hostport.go
  internal/hostport/hostport_iptables.go
  internal/hostport/hostport_iptables_test.go
  internal/hostport/hostport_manager.go
  internal/hostport/hostport_manager_test.go
  internal/hostport/hostport_nftables.go
  internal/hostport/hostport_nftables_test.go
  internal/hostport/hostport_test.go
  internal/hostport/meta_hostport_manager.go
  internal/hostport/meta_hostport_manager_test.go
  internal/hostport/noop_hostport_manager.go
  internal/hostport/noop_hostport_manager_test.go
  server/sandbox_network.go
  server/server.go
  server/suite_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/knftables/.gitignore
  vendor/sigs.k8s.io/knftables/CHANGELOG.md
  vendor/sigs.k8s.io/knftables/CONTRIBUTING.md
  vendor/sigs.k8s.io/knftables/LICENSE
  vendor/sigs.k8s.io/knftables/Makefile
  vendor/sigs.k8s.io/knftables/OWNERS
  vendor/sigs.k8s.io/knftables/README.md
  vendor/sigs.k8s.io/knftables/SECURITY_CONTACTS
  vendor/sigs.k8s.io/knftables/code-of-conduct.md
  vendor/sigs.k8s.io/knftables/error.go
  vendor/sigs.k8s.io/knftables/exec.go
  vendor/sigs.k8s.io/knftables/fake.go
  vendor/sigs.k8s.io/knftables/nftables.go
  vendor/sigs.k8s.io/knftables/objects.go
  vendor/sigs.k8s.io/knftables/transaction.go
  vendor/sigs.k8s.io/knftables/types.go
  vendor/sigs.k8s.io/knftables/util.go
Labels: lgtm, approved, release-note-action-required, kind/cleanup, ok-to-test, dco-signoff: yes, kind/other

#9198 Improve timeout integration tests
  test/timeout.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#9016 New UpdatePodSandboxResources CRI API handler
  go.mod
  go.sum
  internal/nri/nri.go
  server/nri-api.go
  server/sandbox_update_resources.go
  server/sandbox_update_resources_test.go
  test/nri/plugin.go
  test/nri/runtime.go
  vendor/github.com/containerd/nri/pkg/adaptation/adaptation.go
  vendor/github.com/containerd/nri/pkg/adaptation/api.go
  vendor/github.com/containerd/nri/pkg/adaptation/plugin.go
  vendor/github.com/containerd/nri/pkg/adaptation/plugin_type.go
  vendor/github.com/containerd/nri/pkg/api/api.pb.go
  vendor/github.com/containerd/nri/pkg/api/api.proto
  vendor/github.com/containerd/nri/pkg/api/api_host.pb.go
  vendor/github.com/containerd/nri/pkg/api/api_plugin.pb.go
  vendor/github.com/containerd/nri/pkg/api/api_service.pb.go
  vendor/github.com/containerd/nri/pkg/api/api_ttrpc.pb.go
  vendor/github.com/containerd/nri/pkg/api/api_vtproto.pb.go
  vendor/github.com/containerd/nri/pkg/api/event.go
  vendor/github.com/containerd/nri/pkg/api/resources.go
  vendor/github.com/containerd/nri/pkg/stub/stub.go
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#9196 Add v1.33 to supported versions
  dependencies.yaml
  internal/version/version.go
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#9197 Update CNI plugins to v1.7.1
  contrib/test/ci/build/plugins.yml
  dependencies.yaml
  scripts/versions
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#9201 Decrement the `Version`
  dependencies.yaml
  internal/version/version.go
Labels: lgtm, approved, priority/critical-urgent, release-note-none, dco-signoff: yes, kind/ci

#9190 Add option to allow seccomp profiles for privileged containers
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  pkg/config/config.go
  pkg/config/reload.go
  pkg/config/template.go
  server/container_create.go
  server/sandbox_run_linux.go
  test/ctr_seccomp.bats
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#9194 Support multi arch artifact
  internal/ociartifact/impl.go
  internal/ociartifact/store.go
  internal/ociartifact/store_test.go
  internal/storage/image.go
  test/mocks/ociartifact/ociartifact.go
  test/oci_artifacts.bats
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#9208 Fix build-rpm.sh exited 141
  hack/build-rpms.sh
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes

#9206 Switch to v1.34.0 as development version of `main`
  dependencies.yaml
  internal/version/version.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#9200 Add coverage report from integration tests
  .github/workflows/integration.yml
  .github/workflows/test.yml
  Makefile
  test/test_runner.sh
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#9202 Extend checkpoint/restore test for container logs
  test/checkpoint.bats
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes, kind/ci

#9213 Pass down apparmor errors
  internal/config/apparmor/apparmor_linux.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#9226 internal/hostport: fix linter warning
  internal/hostport/hostport_iptables.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#9222 Fix HostPort manager when one backend is unavailable
  internal/hostport/meta_hostport_manager.go
  internal/hostport/meta_hostport_manager_test.go
  internal/iptables/iptables.go
Labels: kind/bug, lgtm, approved, release-note, kind/cleanup, ok-to-test, dco-signoff: yes
