Repository cri-o/cri-o, pull requests merged in 2025-03, with the labels that each got.

#9034 Drop image status log message
  server/image_status.go
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#9040 Update the release-notes tool to v0.18.0
  Makefile
  dependencies.yaml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#9039 Update conmon to v2.1.13
  dependencies.yaml
  scripts/versions
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#9045 Improve artifact error logs
  server/image_remove.go
  server/image_status.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#9048 [1.32] vendor: bump c/storage to 1.57.2 to get idmapped mount fix
  go.mod
  go.sum
  vendor/github.com/containers/storage/Makefile
  vendor/github.com/containers/storage/VERSION
  vendor/github.com/containers/storage/pkg/idmap/idmapped_utils.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/dependency-change

#9055 Update debug flag
  Makefile
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/other

#9051 Require go 1.24 for build
  dependencies.yaml
  go.mod
  server/container_create_linux_test.go
  server/inspect_test.go
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#9056 Fix release notes download location
  Makefile
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes

#9064 Add lint-fix target
  Makefile
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/other

#9065 Use go version requirements from go.mod
  .github/workflows/integration.yml
  .github/workflows/patch-release.yml
  .github/workflows/release-branch-forward.yml
  .github/workflows/tag-reconciler.yml
  .github/workflows/test.yml
  .github/workflows/verify.yml
  dependencies.yaml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#9050 Add image volume subpath support
  go.mod
  go.sum
  nix/nixpkgs.json
  server/container_create.go
  server/container_create_freebsd.go
  server/container_create_linux.go
  server/container_create_linux_test.go
  server/safemount_freebsd.go
  server/safemount_linux.go
  test/oci_volumes.bats
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.pb.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto
  vendor/k8s.io/cri-api/pkg/apis/services.go
  vendor/k8s.io/cri-api/pkg/errors/doc.go
  vendor/k8s.io/cri-api/pkg/errors/errors.go
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes

#9059 OCPBUGS-44780: crio wipe should remove storage only once per reboot
  internal/criocli/wipe.go
  test/crio-wipe.bats
Labels: kind/bug, lgtm, approved, release-note, ok-to-test, dco-signoff: yes, jira/valid-bug, jira/valid-reference

#9061 Cleanup: ensure image volume path
  server/container_create_linux.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#9072 OCPBUGS-53431: [release-1.31] Backport c/image `3161ab1`
  go.mod
  go.sum
  vendor/github.com/containers/image/v5/storage/storage_dest.go
  vendor/modules.txt
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes, jira/invalid-bug, jira/valid-reference

#9069 Set default masked paths
  server/container_create.go
  server/masked_paths.go
  test/ctr.bats
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#9067 Fix comment location about error message
  server/container_create_linux.go
  server/safemount_linux.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#9078 Use `strings.SplitSeq` instead of `strings.Split`
  server/masked_paths.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#9080 Switch to golangci-lint v2
  .github/workflows/verify.yml
  .golangci.yml
  Makefile
  cmd/crio/main.go
  dependencies.yaml
  internal/config/cgmgr/cgroupfs_linux.go
  internal/factory/container/container.go
  internal/hostport/fake_iptables.go
  internal/hostport/hostport_manager.go
  internal/lib/container_server.go
  internal/oci/oci.go
  internal/oci/runtime_vm.go
  internal/ociartifact/store.go
  internal/runtimehandlerhooks/high_performance_hooks_linux.go
  internal/watchdog/watchdog_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  server/container_attach.go
  server/container_checkpoint.go
  server/container_create.go
  server/container_exec.go
  server/container_execsync.go
  server/container_list.go
  server/container_portforward.go
  server/container_remove.go
  server/container_reopen_log.go
  server/container_restore.go
  server/container_start.go
  server/container_stats.go
  server/container_stats_list.go
  server/container_status.go
  server/container_stop.go
  server/container_update_resources.go
  server/inspect.go
  server/inspect_test.go
  server/metric_descriptors_list.go
  server/naming.go
  server/nri-api.go
  server/runtime_status.go
  server/sandbox_list.go
  server/sandbox_metrics_list.go
  server/sandbox_remove.go
  server/sandbox_run_linux.go
  server/sandbox_stats.go
  server/sandbox_stats_list.go
  server/server.go
  server/server_linux.go
  server/server_test.go
  test/nri/nri_suite_test.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#9076 Remove Krzysztof Wilczyński as maintainer
  MAINTAINERS.md
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes, kind/other

#9081 Fix artifact status handling
  internal/ociartifact/artifact.go
  internal/ociartifact/impl.go
  internal/ociartifact/store.go
  test/mocks/ociartifact/ociartifact.go
  test/oci_artifacts.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#9085 [release-1.31] OCPBUGS-53284: Update c/storage
  go.mod
  go.sum
  vendor/github.com/containers/storage/drivers/quota/projectquota_supported.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes
