Repository cri-o/cri-o, pull requests merged in 2025-08, with the labels that each got.

#9372 server: ensure CNI teardown prevents IP leaks with missing netns
  server/sandbox_network.go
  test/network.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#9398 Update nix and gpgme build config
  nix/nixpkgs.json
  nix/overlay.nix
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#9385 server: add real-time memory validation for limit updates
  internal/config/cgmgr/cgmgr_linux.go
  internal/config/cgmgr/systemd_linux.go
  server/container_update_resources.go
  server/container_update_resources_linux.go
  server/container_update_resources_unsupported.go
  test/ctr.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#9420 Cleanup container user log message and trivial code
  server/container_create.go
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#9425 Remove thermal_throttle masked paths.
  server/masked_paths.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes
