Repository cri-o/cri-o, pull requests merged in 2025-01, with the labels that each got.

#8874 [Docs] Fetch latest containernetworking/plugins tag instead of v1.1.1
  contrib/cni/README.md
Labels: lgtm, approved, kind/documentation, release-note-none, ok-to-test, dco-signoff: yes

#8870 Makefile: fixes wrt crio.conf
  Makefile
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#8865 Update CRI-O version and add checks
  dependencies.yaml
  internal/version/version.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#8797 [release-1.28] OCPBUGS-45907: Only restore container if all bind mounts are defined
  server/container_restore.go
  server/container_restore_test.go
  test/checkpoint.bats
Labels: release-note, dco-signoff: yes, jira/severity-moderate, jira/invalid-bug, jira/valid-reference

#8912 Makefile: introduce GO_TEST for more flexible configuration
  Makefile
Labels: lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#8898 Remove Fedora 39 content from .packit.yaml
  .packit.yaml
Labels: lgtm, approved, release-note, kind/cleanup, ok-to-test, dco-signoff: yes

#8918 Fix klog-shim to close the bracket properly
  internal/log/klog.go
  internal/log/klog_test.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#8883 Switch to our log module for logging in iptables module
  internal/hostport/hostport_manager.go
  internal/iptables/iptables.go
  server/server.go
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#8926 Add `release-1.33` to active prerelease version
  internal/version/version.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8903 [release-1.32] OCPBUGS-48198: Cherry-pick changes from containers/storage project
  contrib/test/ci/build/plugins.yml
  dependencies.yaml
  go.mod
  go.sum
  scripts/versions
  vendor/github.com/containers/storage/layers.go
  vendor/github.com/containers/storage/pkg/chunked/compression_linux.go
  vendor/github.com/containers/storage/pkg/chunked/storage_linux.go
  vendor/github.com/go-task/slim-sprig/v3/.gitattributes
  vendor/github.com/tetratelabs/wazero/.gitattributes
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes, jira/severity-important, jira/invalid-bug, jira/valid-reference

#8911 [OCPBUGS-48334] watchdog: Decouple CNI plugin initialization from CRI-O health checks
  internal/watchdog/watchdog.go
  server/health.go
  server/sandbox_network.go
  server/sandbox_run_freebsd.go
  server/sandbox_run_linux.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#8930 [release-1.29] Fix build errors on go >= 1.23
  internal/resourcestore/resourcecleaner.go
  internal/runtimehandlerhooks/high_performance_hooks_linux.go
  server/sandbox_run_linux.go
  utils/errdefs/grpc.go
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/ci

#8936 Enable linters and auto-fix
  .golangci.yml
  internal/config/nsmgr/nsmgr_linux.go
  internal/config/nsmgr/types_linux.go
  internal/iptables/iptables.go
  internal/lib/sandbox/sandbox_linux.go
  internal/oci/oci_unix.go
  server/utils_test.go
  test/checkseccomp/checkseccomp.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#8789 [release-1.31] OCPBUGS-43968: Cherry-pick changes from containers/storage project
  go.mod
  go.sum
  vendor/github.com/containers/storage/layers.go
  vendor/github.com/containers/storage/pkg/chunked/cache_linux.go
  vendor/github.com/containers/storage/pkg/chunked/compression_linux.go
  vendor/github.com/containers/storage/pkg/chunked/storage_linux.go
  vendor/github.com/containers/storage/storage.conf
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes, jira/severity-important, jira/invalid-bug, jira/valid-reference

#8902 [release-1.32] Cherry-pick changes from containers/image project
  go.mod
  go.sum
  vendor/github.com/containers/image/v5/storage/storage_dest.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#8937 Log error when failing to update container status from exit file
  internal/oci/runtime_oci.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/other

#8871 Use iterators in a for-range loop
  internal/config/seccomp/notifier.go
  internal/memorystore/memory_store.go
  server/container_events.go
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#8942 Integrate native GitHub arm64 runners
  .github/workflows/integration.yml
  .github/workflows/test.yml
  scripts/github-actions-setup
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8843 [release-1.31] Cherry-pick changes from containers/image project
  go.mod
  go.sum
  vendor/github.com/containers/image/v5/storage/storage_dest.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#8962 Remove `LimitNOFILE` from systemd service file
  contrib/systemd/crio.service
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/deprecation

#8944 Add warning log for a process having an uninterruptible child.
  internal/oci/runtime_oci.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/other
