Repository cri-o/cri-o, pull requests merged in 2025-02, with the labels that each got.

#8968 CVE: Fix path traversal in CRI-O log handling
  internal/linklogs/link_logs.go
  test/ctr.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/other, cve

#8965 [release-1.32] Bump containers/storage
  go.mod
  go.sum
  vendor/github.com/containers/storage/pkg/chrootarchive/archive.go
  vendor/github.com/vbatts/tar-split/archive/tar/format.go
  vendor/github.com/vbatts/tar-split/archive/tar/reader.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#8977 [release-1.31] CVE: Fix path traversal in CRI-O log handling
  internal/linklogs/link_logs.go
  test/ctr.bats
Labels: lgtm, approved, release-note, dco-signoff: yes

#8978 [release-1.30] CVE: Fix path traversal in CRI-O log handling
  internal/linklogs/link_logs.go
  test/ctr.bats
Labels: lgtm, approved, release-note, dco-signoff: yes

#8976 [release-1.32] CVE: Fix path traversal in CRI-O log handling
  internal/linklogs/link_logs.go
  test/ctr.bats
Labels: lgtm, approved, release-note, dco-signoff: yes

#8975 Switch to golang native error joining and errgroup
  go.mod
  internal/hostport/hostport_manager.go
  internal/iptables/iptables_linux.go
  server/sandbox_stop_freebsd.go
  server/sandbox_stop_linux.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#8985 Change nixpkgs update to monthly
  .github/workflows/nixpkgs.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8987 Mark v1.29 as EOL
  dependencies.yaml
  internal/version/version.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#8828 [release-1.30] OCPBUGS-46026: Cherry-pick changes from containers/storage project
  go.mod
  go.sum
  vendor/github.com/containers/storage/pkg/chrootarchive/archive.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes, jira/severity-important, jira/invalid-bug, jira/valid-reference

#8993 [release-1.30] OCPBUGS-46026: Revert "Cherry-pick changes from containers/storage project"
  go.mod
  go.sum
  vendor/github.com/containers/storage/pkg/chrootarchive/archive.go
  vendor/modules.txt
Labels: kind/bug, needs-ok-to-test, lgtm, approved, release-note-none, dco-signoff: yes, jira/severity-important, jira/invalid-bug, jira/valid-reference

#8986 Fix typo in `version_update_mask` regex
  .packit.yaml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#8880 [release-1.30] Cherry-pick changes from containers/image project
  go.mod
  go.sum
  vendor/github.com/containers/image/v5/storage/storage_dest.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, release-note-none, dco-signoff: yes

#8888 Fix: If cgroup manager is cgroupfs then allow conmon_cgroup to be empty
  pkg/config/config.go
  pkg/config/config_test.go
Labels: kind/bug, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#8994 Remove `exclude_graphdriver_devicemapper` build tag
  .golangci.yml
  Makefile
  contrib/test/ci/cri-o.spec
  hack/govulncheck.sh
  hack/libdm_installed.sh
  hack/libdm_no_deferred_remove_tag.sh
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#8949 [release-1.30] Avoid using UpdateContainerStatus for ReopenContainerLog and add logs tests
  internal/oci/container.go
  internal/oci/oci.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_pod.go
  internal/oci/runtime_vm.go
  server/container_reopen_log.go
  test/logs.bats
  test/mocks/oci/oci.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#8998 Fix context cancellation when image pull progress timeout is `0`
  server/image_pull.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#8950 [release-1.29] Avoid using UpdateContainerStatus for ReopenContainerLog and add logs tests
  internal/oci/container.go
  internal/oci/oci.go
  internal/oci/runtime_oci.go
  internal/oci/runtime_pod.go
  internal/oci/runtime_vm.go
  server/container_reopen_log.go
  test/mocks/oci/oci.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#9002 [release-1.27] Fix build github actions
  .github/workflows/test.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#9003 [release-1.28] Fix build github actions
  .github/workflows/osff.yml
  .github/workflows/test.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#9012 [release-1.30] OCPBUGS-50854: backport pull_progress_timeout into v.1.30
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  pkg/config/config.go
  pkg/config/template.go
  server/image_pull.go
  test/image.bats
Labels: kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes, jira/severity-critical, jira/invalid-bug, jira/valid-reference

#9000 Updating install docs
  install.md
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#9014 server: fix races in GetContainerEvents
  server/container_events.go
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#9017 Update golangci-lint config and fix reports
  .github/workflows/verify.yml
  .golangci.yml
  Makefile
  dependencies.yaml
  internal/log/interceptors/interceptors.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#9018 [release-1.29] OCPBUGS-33075: Add `--pull-progress-timeout` / `pull_progress_timeout` option
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  internal/storage/image.go
  internal/storage/image_test.go
  internal/storage/runtime.go
  internal/storage/runtime_test.go
  pkg/config/config.go
  pkg/config/template.go
  server/image_pull.go
  server/image_pull_test.go
  test/image.bats
  test/mocks/criostorage/criostorage.go
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes, jira/severity-important, jira/valid-reference

#9008 Validate before creating Sandbox
  internal/factory/container/container_test.go
  internal/lib/container_server.go
  internal/lib/sandbox/builder.go
  internal/lib/sandbox/sandbox_builder_test.go
  internal/lib/sandbox/sandbox_test.go
  internal/lib/sandbox/suite_test.go
  internal/lib/suite_test.go
  internal/memorystore/history_test.go
  internal/memorystore/suite_test.go
  internal/runtimehandlerhooks/high_performance_hooks_test.go
  server/suite_test.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#9021 [1.32] vendor: bump go-jose to 4.0.5
  go.mod
  go.sum
  vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/v4/README.md
  vendor/github.com/go-jose/go-jose/v4/jwe.go
  vendor/github.com/go-jose/go-jose/v4/jwk.go
  vendor/github.com/go-jose/go-jose/v4/jws.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#9022 Fix nix build
  Makefile
Labels: kind/bug, lgtm, approved, release-note-none, ok-to-test, dco-signoff: yes

#9025 [release-1.32] Bump CDI deps to v0.8.1.
  go.mod
  go.sum
  vendor/modules.txt
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/cache.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/dependency-change

#9023 Switch to go 1.24
  .github/workflows/integration.yml
  .github/workflows/patch-release.yml
  .github/workflows/release-branch-forward.yml
  .github/workflows/tag-reconciler.yml
  .github/workflows/test.yml
  .github/workflows/verify.yml
  dependencies.yaml
  nix/derivation.nix
  nix/nixpkgs.json
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci
