Repository cri-o/cri-o, pull requests merged in 2025-10, with the labels that each got.

#9479 Re-add the `--enable-fixed-path` removal for gpgme
  nix/overlay.nix
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#9445 Update dependencies.yaml if required on release cut
  scripts/release/release.go
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#9494 Remove unused code from Makefile
  Makefile
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#9489 Switch to go 1.25
  .github/workflows/integration.yml
  dependencies.yaml
  go.mod
  nix/derivation.nix
Labels: lgtm, approved, release-note, dco-signoff: yes, kind/ci

#9501 Update log formatting in interceptors to use %+v
  internal/log/interceptors/interceptors.go
  test/ctr.bats
  test/logs.bats
Labels: lgtm, approved, release-note, kind/cleanup, dco-signoff: yes

#9490 Actions: cancel parallel runs for a single PR
  .github/workflows/integration.yml
  .github/workflows/test.yml
  .github/workflows/verify.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci
