Repository cri-o/cri-o, pull requests merged in 2025-06, with the labels that each got.

#9235 install: drop outdated flatcar installation instructions
  install.md
Labels: lgtm, approved, kind/documentation, release-note-none, dco-signoff: yes

#9211 Retry failed bats tests
  test/test_runner.sh
Labels: lgtm, approved, release-note-none, kind/failing-test, dco-signoff: yes

#9255 [revert] internal/oci: fix terminal resize race condition
  internal/oci/runtime_oci.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#9224 OCPBUGS-54938: [1.32] sandbox: use created/stopped instead of infra container for readiness
  internal/lib/container_server.go
  internal/lib/sandbox/sandbox.go
  internal/lib/sandbox/sandbox_test.go
  server/container_portforward.go
  server/sandbox_list_test.go
  server/sandbox_status.go
  server/server.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes, jira/severity-critical, jira/invalid-bug, jira/valid-reference

#9253 fix verify command
  scripts/release-notes/release_notes.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#9267 temporarily enable debug symbols
  Makefile
Labels: lgtm, approved, release-note-none, dco-signoff: yes

#9273 Mark v1.30 as EOL
  dependencies.yaml
  internal/version/version.go
  roadmap.md
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#9271 test/ctr.bats: fix wrt new CPU units to weight conversion
  test/ctr.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#9256 OCPBUGS-55485: Fix deadlock when stopping uninterruptible container
  internal/oci/container.go
  internal/oci/runtime_oci.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes, jira/valid-bug, jira/valid-reference

#9209 Fix error handling of mountArtifact
  server/container_create_linux.go
Labels: lgtm, approved, kind/cleanup, release-note-none, dco-signoff: yes

#9290 Update runtime-tools
  go.mod
  go.sum
  internal/factory/container/container.go
  internal/factory/container/container_test.go
  vendor/github.com/opencontainers/runtime-tools/generate/generate.go
  vendor/github.com/opencontainers/runtime-tools/validate/capabilities/lastcap.go
  vendor/github.com/opencontainers/runtime-tools/validate/capabilities/validate.go
  vendor/github.com/opencontainers/runtime-tools/validate/capabilities/validate_linux.go
  vendor/github.com/opencontainers/runtime-tools/validate/capabilities/validate_unsupported.go
  vendor/github.com/syndtr/gocapability/LICENSE
  vendor/github.com/syndtr/gocapability/capability/capability.go
  vendor/github.com/syndtr/gocapability/capability/capability_linux.go
  vendor/github.com/syndtr/gocapability/capability/capability_noop.go
  vendor/github.com/syndtr/gocapability/capability/enum.go
  vendor/github.com/syndtr/gocapability/capability/enum_gen.go
  vendor/github.com/syndtr/gocapability/capability/syscall_linux.go
  vendor/modules.txt
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/dependency-change

#9292 server,factory/container: delay CDI device injection later.
  internal/factory/container/container.go
  internal/factory/container/device_freebsd.go
  internal/factory/container/device_linux.go
  internal/factory/container/device_test.go
  internal/factory/container/device_unsupported.go
  server/container_create.go
  test/cdi.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes
