Repository cri-o/cri-o, pull requests merged in 2025-09, with the labels that each got.

#9451 [release-1.32] Backport kata logrotate fix
  internal/oci/runtime_vm.go
  test/logs.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#9452 [release-1.33] Backport kata logrotate fix
  internal/oci/runtime_vm.go
  test/logs.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#9450 [release-1.31] Backport kata logrotate fix
  internal/oci/runtime_vm.go
  test/logs.bats
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#9454 Warn when CONTAINER_INCLUDED_POD_METRCIS (typo) is used.
  cmd/crio/main.go
Labels: lgtm, approved, kind/cleanup, dco-signoff: yes

#9424 Add runtime handler seccomp profile
  internal/config/seccomp/seccomp.go
  internal/config/seccomp/seccomp_test.go
  internal/oci/oci.go
  internal/oci/oci_test.go
  pkg/config/config.go
  pkg/config/reload.go
  pkg/config/template.go
  server/container_create.go
  server/sandbox_run_linux.go
  test/helpers.bash
  test/reload_config.bats
  test/seccomp_runtime_handler.bats
Labels: kind/feature, lgtm, approved, release-note, ok-to-test, dco-signoff: yes

#9401 image pull: enforce shortnames
  completions/bash/crio
  completions/fish/crio.fish
  completions/zsh/_crio
  docs/crio.8.md
  docs/crio.conf.5.md
  internal/criocli/criocli.go
  internal/ociartifact/impl.go
  internal/storage/image.go
  pkg/config/config.go
  pkg/config/template.go
  test/image.bats
Labels: lgtm, approved, release-note, dco-signoff: yes

#9465 Fix periodic setup job
  contrib/test/ci/ansible.cfg
  contrib/test/ci/build/parallel.yml
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci

#9473 Update third party dependencies
  .github/workflows/nixpkgs.yml
  .github/workflows/test.yml
  .github/workflows/verify.yml
  .golangci.yml
  Makefile
  contrib/test/ci/build/bats.yml
  contrib/test/ci/build/plugins.yml
  dependencies.yaml
  hack/govulncheck.sh
  internal/criocli/documentation.go
  internal/lib/stats/cpu_metrics.go
  internal/runtimehandlerhooks/high_performance_hooks_linux.go
  internal/runtimehandlerhooks/utils_linux.go
  scripts/versions
  server/metrics/metrics.go
  test/apparmor.bats
  test/irqbalance.bats
Labels: lgtm, approved, release-note-none, dco-signoff: yes, kind/ci
